objects/Assessment__c.object
<CustomObject><fields>
        <fullName>Module__c</fullName>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Assessment</label><nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Assessments</pluralLabel><sharingModel>ControlledByParent</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/Module__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Instances of Modules</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module</label><nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Modules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme_Module__c.object
<CustomObject><fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To find correct Module type first the few character of Module title then click magnifying glass for available options</inlineHelpText>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Assigned Programmes</relationshipLabel>
        <relationshipName>Programme_Modules</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Many to many object, to allow one Module (instance) to be a member of multiple Programmes (instances)</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Programme Module</label><nameField>
        <displayFormat>PMI-{00000000}</displayFormat>
        <label>Programme Module</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Programme Modules</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Session__c.object
<CustomObject><fields>
        <fullName>Module__c</fullName>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Study or learning entity associated with a Module (instance)</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Session</label><nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Sessions</pluralLabel><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Student_Absence__c.object
<CustomObject><fields>
        <fullName>Module__c</fullName>
        <formula>Student_Module__r.Programme_Module__r.Module__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Module</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Session__c</fullName>
        <label>Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipName>Student_Attendances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Student_Module__c</fullName>
        <label>Student Module</label>
        <referenceTo>Student_Module__c</referenceTo>
        <relationshipName>Student_Attendances</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Student Applicant, Full Student, Student Pre-Reg</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Student_Attendances</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Student Absence</label><nameField>
        <displayFormat>SAR-{00000000}</displayFormat>
        <label>Attendance Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Student Absences</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Student_Assessment__c.object
<CustomObject><fields>
        <fullName>Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Student Assessments</relationshipLabel>
        <relationshipName>Student_Assessments</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Module__c</fullName>
        <formula>Assessment__r.Module__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Module</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Student_Module__c</fullName>
        <label>Student Module</label>
        <referenceTo>Student_Module__c</referenceTo>
        <relationshipLabel>Student Assessments</relationshipLabel>
        <relationshipName>Student_Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Student Applicant, Full Student, Student Pre-Reg</value>
            </filterItems>
            <infoMessage>Contact record needs to have record type of Applicant or Student</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Assessments</relationshipLabel>
        <relationshipName>Student_Assessments</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Student Assessment</label><nameField>
        <label>Student Assessment Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Assessments</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Student_Module__c.object
<CustomObject><fields>
        <fullName>Assessments_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Assessments Created</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Attendances_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attendances Created</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Module__c</fullName>
        <formula>HYPERLINK ( Programme_Module__r.Module__r.Id, Programme_Module__r.Module__r.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Module</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme_Module__c</fullName>
        <label>Programme Module</label>
        <referenceTo>Programme_Module__c</referenceTo>
        <relationshipLabel>Student Modules</relationshipLabel>
        <relationshipName>Student_Modules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Student_Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to (new) Student Programme object</description>
        <label>Student Programme</label>
        <referenceTo>Student_Programme__c</referenceTo>
        <relationshipLabel>Student Modules</relationshipLabel>
        <relationshipName>Student_Modules</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Student Applicant, Full Student, Student Pre-Reg</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Modules</relationshipLabel>
        <relationshipName>Student_Modules</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Join table between Student (contact) and Program Module join table, with link up to Student Programme</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Student Module</label><nameField>
        <label>Student Module Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Modules</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reverted from Master:Detail as per LSTM requirement</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Programmes</relationshipLabel>
        <relationshipName>Student_Programmes1</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/StudentProgrammeUtilities.cls
/*
*@auther :Simon Edwards
* 2014-08-04 : CSL : This class will hold methods called from Student Programme buttons & pages
*<summary>
@Auther: Manu KM
*Date:17-Sep-2015
*Support task:- Renamed all the studentAttandance object to studentAbsences
*Line number, 23,
*</summary>
*/

global class StudentProgrammeUtilities {

    //2014-08-04 : CSL : This method will be called from a button on the Student Programme
    //and will create the necessary Student Assessment records and Student Attendance records
    //against the provided Student Programme
    webservice static void createAssessmentsAndAttendance(String spID){
        Student_Programme__c sp;
        Map<Id, Assessment__c> assessmentMap = new Map<Id, Assessment__c>();
        Map<Id, Session__c> sessionMap = new Map<Id, Session__c>();
        List<Student_Assessment__c> studentAssessments = new List<Student_Assessment__c>();        
        List<Student_Absence__c> studentAbsences = new List<Student_Absence__c>();
        Map<Id, Student_Module__c> savedStudentModules = new Map<Id, Student_Module__c>();        
        System.Debug('spID'+spID);
        //We need to get hold of the Student Programme and relevant records
        sp = [Select s.Id, s.Student__c, s.Student__r.LastName, (Select Id, Programme_Module__c,Assessments_Created__c,Attendances_Created__c, Programme_Module__r.Module__r.Id, Programme_Module__r.Module__r.Name From Student_Modules__r) From Student_Programme__c s where s.Id =:spID LIMIT 1];
        //sp = [Select s.Id, s.Student__c, s.Student__r.LastName, (Select Id, Programme_Module__c,Programme_Module__r.Module__r.Id, Programme_Module__r.Module__r.Name From Student_Modules__r) From Student_Programme__c s where s.Id =:spID LIMIT 1];
        System.debug('sp'+sp);
        if (sp == null){
            return;
        }
        
        
        Set<Id> moduleIdSet = new Set<Id>();
        
        for (Student_Module__c sm : sp.Student_Modules__r){
            moduleIdSet.add(sm.Programme_Module__r.Module__r.Id);
        }
        System.Debug('moduleIdSet'+moduleIdSet);
        //Process Assessments
        for (Assessment__c a : [Select a.Module__c, a.Id From Assessment__c a where a.Module__c in :moduleIdSet]){
            assessmentMap.put(a.Module__c, a);
        }
        System.Debug('assessmentMap'+assessmentMap);
        //Process Sessions
        for (Session__c s : [Select s.Module__c, s.Id From Session__c s where s.Module__c in :moduleIdSet]){
            sessionMap.put(s.Module__c, s);
        }
        System.Debug('sessionMap'+sessionMap);
        for (Student_Module__c sm : sp.Student_Modules__r){
            //Create the Student Assessments
          //  System.debug('sm.Assessments_Created__c = ' + sm.Assessments_Created__c);
            if (!sm.Assessments_Created__c){
                Student_Assessment__c sa = new Student_Assessment__c();
                Assessment__c getAssessment = assessmentMap.get(sm.Programme_Module__r.Module__r.Id);
                if (getAssessment != null){
                    sa.Name = sp.Student__r.LastName + sm.Programme_Module__r.Module__r.Name;
                    sa.Assessment__c = getAssessment.Id;
                    sa.Student_Module__c = sm.Id;
                    sa.Student__c = sp.Student__c;
                    studentAssessments.add(sa);
                    //Once we have created an Assessment, we can update the Student Module
                    sm.Assessments_Created__c = true;
                    if (!savedStudentModules.containsKey(sm.Id)){
                        savedStudentModules.put(sm.Id, sm);
                    }
                }
            }
            
            if (!sm.Attendances_Created__c){
                //Create the Student Attendances
                Session__c getSession = sessionMap.get(sm.Programme_Module__r.Module__r.Id);
                if (getSession != null){
                   
                    Student_Absence__c satt = new Student_Absence__c();
                    satt.Session__c = getSession.Id;
                    satt.Student_Module__c = sm.Id;
                    satt.Student__c = sp.Student__c; 
                   
                    studentAbsences.add(satt);
                    //Once we have created an Attendance record, we can update the Student Module
                    sm.Attendances_Created__c = true;
                    if (!savedStudentModules.containsKey(sm.Id)){
                        savedStudentModules.put(sm.Id, sm);
                    }
                }
            }
            
        }
        //System.Debug('studentAbsences '+studentAbsences);
        System.Debug('studentAssessments'+studentAssessments);
        //Insert the records
        if (studentAssessments.size() > 0){
            insert studentAssessments;
        }
      
        if (studentAbsences.size() > 0){         
            insert studentAbsences;
        } 
        
        //Update the Student Module records to say we've created the Assessment and Session records per Student Module
        if (savedStudentModules.size() > 0){
            update savedStudentModules.values();
        }
        
    }

}