objects/Assessment_Specification__c.object
<CustomObject><fields>
        <fullName>Anonymous_Marking__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Anonymous Marking</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Duration__c</fullName>
        <inlineHelpText>Either time (in hours) or size (eg word length)</inlineHelpText>
        <label>Duration</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Exam_Type__c</fullName>
        <label>Exam Type</label>
        <picklist>
            <picklistValues>
                <fullName>Seen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unseen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Book</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Final_Assessment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Final Assessment</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Module_Version__c</fullName>
        <label>Module Version</label>
        <referenceTo>Module_Version__c</referenceTo>
        <relationshipLabel>Assessment Specifications</relationshipLabel>
        <relationshipName>Assessment_Specifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Re_sit_Re_submission__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Re-sit or re-submission opportunity</inlineHelpText>
        <label>Re-submission</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Record_No__c</fullName>
        <description>Set by Workflow</description>
        <inlineHelpText>Leave blank on record creation if automatic numbering is required (set by Workflow)</inlineHelpText>
        <label>No.</label>
        <length>5</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Semester__c</fullName>
        <label>Semester</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Timing__c</fullName>
        <label>Timing</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Examination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poster</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Practical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dissertation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>of_Final_Module_Mark__c</fullName>
        <label>% of Final Module Mark</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Assessment Specification</label><nameField>
        <displayFormat>MAS-{000000}</displayFormat>
        <label>Assessment Spec Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Assessment Specifications</pluralLabel><sharingModel>ControlledByParent</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/Learning_Outcome__c.object
<CustomObject><fields>
        <fullName>Learning_Outcome__c</fullName>
        <label>Learning Outcome</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <label>Programme Version</label>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Learning Outcomes</relationshipLabel>
        <relationshipName>Specification_Outcomes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Record_No__c</fullName>
        <description>Set by workflow</description>
        <inlineHelpText>Leave blank on record creation if automatic numbering is required (set by Workflow)</inlineHelpText>
        <label>No.</label>
        <length>5</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Type__c</fullName>
        <description>Hidden, populated by workflow and for RSF to Programme Version, for Outcome No workflow</description>
        <label>Type</label>
        <length>5</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Learning Outcome</label><nameField>
        <displayFormat>LO-{000000}</displayFormat>
        <label>Outcome Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Learning Outcomes</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Module_Aim__c.object
<CustomObject><fields>
        <fullName>Module_Version__c</fullName>
        <label>Module Version</label>
        <referenceTo>Module_Version__c</referenceTo>
        <relationshipLabel>Module Aims</relationshipLabel>
        <relationshipName>Module_Aims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields><fields>
        <fullName>Record_No__c</fullName>
        <description>Set by Workflow</description>
        <inlineHelpText>Leave blank on record creation if automatic numbering is required (set by Workflow)</inlineHelpText>
        <label>No.</label>
        <length>5</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Specific_Aim__c</fullName>
        <label>Specific Aim</label>
        <type>TextArea</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Module Aim</label><nameField>
        <displayFormat>MA-{000000}</displayFormat>
        <label>Module Aim Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Module Aims</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Module_Learning_Outcome__c.object
<CustomObject><fields>
        <fullName>Learning_Outcome__c</fullName>
        <label>Learning Outcome</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Method_of_Teaching__c</fullName>
        <label>Method of Teaching</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Mode_of_Assessment__c</fullName>
        <label>Mode of Assessment</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Module_Version__c</fullName>
        <label>Module Version</label>
        <referenceTo>Module_Version__c</referenceTo>
        <relationshipLabel>Module Learning Outcomes</relationshipLabel>
        <relationshipName>Module_Learning_Outcomes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Record_No__c</fullName>
        <description>Set by Workflow</description>
        <inlineHelpText>Leave blank on record creation if automatic numbering is required (set by Workflow)</inlineHelpText>
        <label>No.</label>
        <length>5</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Module Learning Outcome</label><nameField>
        <displayFormat>MLO-{000000}</displayFormat>
        <label>Module Learning Outcome Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Module Learning Outcomes</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Module_Skill_Attribute__c.object
<CustomObject><fields>
        <fullName>How_Developed__c</fullName>
        <inlineHelpText>How or where this is developed</inlineHelpText>
        <label>How Developed</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Method_of_Teaching__c</fullName>
        <label>Method of Teaching</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Module_Version__c</fullName>
        <label>Module Version</label>
        <referenceTo>Module_Version__c</referenceTo>
        <relationshipLabel>Module Skill &amp; Attributes</relationshipLabel>
        <relationshipName>Module_Skill_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Record_No__c</fullName>
        <description>Set by Workflow</description>
        <inlineHelpText>Leave blank on record creation if automatic numbering is required (set by Workflow)</inlineHelpText>
        <label>No.</label>
        <length>5</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Module Skill &amp; Attribute</label><nameField>
        <displayFormat>MSA-{000000}</displayFormat>
        <label>Module Skill &amp; Attribute Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Module Skill &amp; Attributes</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Module_Version__c.object
<CustomObject><fields>
        <fullName>Module_Reference__c</fullName>
        <description>LSTM internal reference</description>
        <label>Module Reference</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Semester__c</fullName>
        <label>Semester</label>
        <length>50</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module Version</label><nameField>
        <label>Module Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Module Versions</pluralLabel><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/MV_Modification__c.object
<CustomObject><fields>
        <fullName>Module_Version__c</fullName>
        <label>Module Version</label>
        <referenceTo>Module_Version__c</referenceTo>
        <relationshipLabel>Module Version Modifications</relationshipLabel>
        <relationshipName>MV_Modifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Module Version Modification</label><nameField>
        <displayFormat>Mod-{0000}</displayFormat>
        <label>Mod Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Module Version Modifications</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Programme_Module_Version__c.object
<CustomObject><fields>
        <fullName>Member_Type__c</fullName>
        <label>Member Type</label>
        <picklist>
            <picklistValues>
                <fullName>Required</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Optional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specials</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Mod_Ver_Name__c</fullName>
        <description>For data loading</description>
        <formula>Module_Version__r.Master_Link__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mod Ver Name</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Module_Reference__c</fullName>
        <description>for dataloading</description>
        <formula>Module_Version__r.Module_Reference__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Module Reference</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Module_Version__c</fullName>
        <inlineHelpText>To find correct Module Version type the first few character of Module Version title then click magnifying glass for available options</inlineHelpText>
        <label>Module Version</label>
        <referenceTo>Module_Version__c</referenceTo>
        <relationshipLabel>Programme Module Versions</relationshipLabel>
        <relationshipName>Instance_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Prog_Ver_Name__c</fullName>
        <description>For dataloading, to be hidden. Returns Master Version name, ie without suffix</description>
        <formula>Programme_Version__r.Master_Link__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>For dataloading, to be hidden. Returns Master Version name, ie without suffix</inlineHelpText>
        <label>Prog Ver Name</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme_Version_Suffix__c</fullName>
        <formula>If (  Programme_Version__r.RecordType.Name = "Master Version", 
    "Master", 
    Programme_Version__r.Version_Suffix__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Programme Version Suffix</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <label>Programme Version</label>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Programme Module Versions</relationshipLabel>
        <relationshipName>Instance_Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Many-to-many object to allow one Module version to be a member of multiple Programme version</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Programme Module Version</label><nameField>
        <displayFormat>PMV-{00000000}</displayFormat>
        <label>Programme Module Version</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Programme Module Versions</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Programme_Version__c.object
<CustomObject><fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <length>50</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme Version</label><nameField>
        <label>Programme Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programme Versions</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel><recordTypes>
        <fullName>Specification</fullName>
        <active>true</active>
        <label>Specification</label>
    </recordTypes></CustomObject>

classes/CloneModuleVersionController.cls
public class CloneModuleVersionController {
    public final String MODULE_ID_PARAM = 'moduleId';

    public List<Module_Version__c> originalModuleList {get; set;}
    public Module_Version__c originalModule {get; set;}
    public Module_Version__c cloneModule {get; set;}
    public List<Assessment_Specification__c> assessmentSpecs {get; set;}
    public List<Module_Aim__c> moduleAims {get; set;}
    public List<Module_Learning_Outcome__c> moduleLearningOutcomes {get; set;}
    public List<Module_Skill_Attribute__c> moduleSkillsAttributes {get; set;}
    public List<MV_Modification__c> moduleMVmodifications {get; set;}
    
    public CloneModuleVersionController(ApexPages.StandardController std) {
        String moduleId = ApexPages.currentPage().getParameters().get(MODULE_ID_PARAM);
        cloneModule = new Module_Version__c();
        originalModuleList = new List<Module_Version__c>();

        String dbQuery = 'SELECT ';
        for(Schema.FieldSetMember f : SObjectType.Module_Version__c.FieldSets.Clone_Fields.getFields()) {
            dbQuery += f.getFieldPath() + ', ';
        }

        //dbQuery += '(Select Name, Member_Type__c, Module_Reference__c, Module_Version__c, Mod_Ver_Name__c, Programme_Version__c, Programme_Version_Suffix__c, Prog_Ver_Name__c From Instance_Members__r) ';
        //Include the Related List records for the Module Version
        //Assessment Specification
        dbQuery += '(SELECT of_Final_Module_Mark__c, Anonymous_Marking__c, Duration__c, Exam_Type__c, Final_Assessment__c, Module_Version__c, Record_No__c, Notes__c, Re_sit_Re_submission__c, Timing__c, Type__c,Semester__c  from Assessment_Specifications__r), ';
        //Module Aims
        dbQuery += '(SELECT Module_Version__c, Record_No__c, Specific_Aim__c from Module_Aims__r), ';
        //Module Learning Outcomes
        dbQuery += '(SELECT Learning_Outcome__c, Method_of_Teaching__c, Mode_of_Assessment__c, Module_Version__c, Record_No__c from Module_Learning_Outcomes__r), ';
        //Module Skills & Attributes
        dbQuery += '(SELECT How_Developed__c, Method_of_Teaching__c, Module_Version__c, Record_No__c, Skill_or_Attribute__c from Module_Skill_Attributes__r), ';
        //Module Skills & Attributes
        dbQuery += '(SELECT Cohort_Affected__c, Date_Approved_by_QMC__c, Modification_Description__c, Modification_Type__c, Module_Version__c from MV_Modifications__r) ';


        dbQuery += ' FROM Module_Version__c where Id = \'' + moduleId + '\'';

        system.debug('*** -- dbQuery -- ***');
        system.debug(dbQuery);
        
        originalModuleList = Database.query(dbQuery);   

        if (originalModuleList.size() > 0){
            originalModule = originalModuleList[0];
        }

        cloneModule = originalModule.clone(false, true, false, false);
        cloneModule.Active__c = true;

    }

    //This is the method that will clone the programme and all modules
    public PageReference cloneModule(){
        PageReference pageRef;
        
        //Insert the new Module
        insert cloneModule;
        
        //2015-02-10 : SM : Also clone any corresponding Related List records
        assessmentSpecs = new List<Assessment_Specification__c>();
        moduleAims = new List<Module_Aim__c>();
        moduleLearningOutcomes = new List<Module_Learning_Outcome__c>();
        moduleSkillsAttributes = new List<Module_Skill_Attribute__c>();
        moduleMVmodifications = new List<MV_Modification__c>();

        for (Assessment_Specification__c aspec : originalModule.Assessment_Specifications__r){
            Assessment_Specification__c newAS = aspec.Clone(false, true, false, false);
            newAS.Module_Version__c = cloneModule.Id;
            assessmentSpecs.add(newAS);
        }

        for (Module_Aim__c ma : originalModule.Module_Aims__r){
            Module_Aim__c newMA = ma.Clone(false, true, false, false);
            newMA.Module_Version__c = cloneModule.Id;
            moduleAims.add(newMA);
        }

        for (Module_Learning_Outcome__c mlc : originalModule.Module_Learning_Outcomes__r){
            Module_Learning_Outcome__c newMLC = mlc.Clone(false, true, false, false);
            newMLC.Module_Version__c = cloneModule.Id;
            moduleLearningOutcomes.add(newMLC);
        }

        for (Module_Skill_Attribute__c msa : originalModule.Module_Skill_Attributes__r){
            Module_Skill_Attribute__c newMSA = msa.Clone(false, true, false, false);
            newMSA.Module_Version__c = cloneModule.Id;
            moduleSkillsAttributes.add(newMSA);
        }
        
        for (MV_Modification__c mvm : originalModule.MV_Modifications__r){
            MV_Modification__c newMVM = mvm.Clone(false, true, false, false);
            newMVM.Module_Version__c = cloneModule.Id;
            moduleMVmodifications.add(newMVM);
        }

        insert assessmentSpecs;
        insert moduleAims;
        insert moduleLearningOutcomes;
        insert moduleSkillsAttributes;
        insert moduleMVmodifications;
        
        pageRef = new PageReference('/' + cloneModule.Id);
        pageRef.setRedirect(true);
                
        return pageRef;
    }
}