objects/Assessment_Specification__c.object
<CustomObject><fields>
        <fullName>Module_Version__c</fullName>
        <label>Module Version</label>
        <referenceTo>Module_Version__c</referenceTo>
        <relationshipLabel>Assessment Specifications</relationshipLabel>
        <relationshipName>Assessment_Specifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Assessment Specification</label><nameField>
        <displayFormat>MAS-{000000}</displayFormat>
        <label>Assessment Spec Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Assessment Specifications</pluralLabel><sharingModel>ControlledByParent</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/Module_Aim__c.object
<CustomObject><fields>
        <fullName>Module_Version__c</fullName>
        <label>Module Version</label>
        <referenceTo>Module_Version__c</referenceTo>
        <relationshipLabel>Module Aims</relationshipLabel>
        <relationshipName>Module_Aims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Module Aim</label><nameField>
        <displayFormat>MA-{000000}</displayFormat>
        <label>Module Aim Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Module Aims</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Module_Learning_Outcome__c.object
<CustomObject><fields>
        <fullName>Module_Version__c</fullName>
        <label>Module Version</label>
        <referenceTo>Module_Version__c</referenceTo>
        <relationshipLabel>Module Learning Outcomes</relationshipLabel>
        <relationshipName>Module_Learning_Outcomes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Module Learning Outcome</label><nameField>
        <displayFormat>MLO-{000000}</displayFormat>
        <label>Module Learning Outcome Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Module Learning Outcomes</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Module_Skill_Attribute__c.object
<CustomObject><fields>
        <fullName>Module_Version__c</fullName>
        <label>Module Version</label>
        <referenceTo>Module_Version__c</referenceTo>
        <relationshipLabel>Module Skill &amp; Attributes</relationshipLabel>
        <relationshipName>Module_Skill_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Module Skill &amp; Attribute</label><nameField>
        <displayFormat>MSA-{000000}</displayFormat>
        <label>Module Skill &amp; Attribute Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Module Skill &amp; Attributes</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Module_Version__c.object
<CustomObject><fields>
        <fullName>Master_Link__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Link</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Record must be a master</errorMessage>
            <filterItems>
                <field>Module_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Master Version</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Module_Version__c</referenceTo>
        <relationshipLabel>Child Module Versions</relationshipLabel>
        <relationshipName>Child_Module_Versions</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module Version</label><nameField>
        <label>Module Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Module Versions</pluralLabel><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><recordTypes>
        <fullName>Master_Version</fullName>
        <active>true</active>
        <label>Master Version</label>
    </recordTypes><recordTypes>
        <fullName>Versions</fullName>
        <active>true</active>
        <label>Versions</label>
    </recordTypes></CustomObject>

objects/MV_Modification__c.object
<CustomObject><fields>
        <fullName>Module_Version__c</fullName>
        <label>Module Version</label>
        <referenceTo>Module_Version__c</referenceTo>
        <relationshipLabel>Module Version Modifications</relationshipLabel>
        <relationshipName>MV_Modifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Module Version Modification</label><nameField>
        <displayFormat>Mod-{0000}</displayFormat>
        <label>Mod Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Module Version Modifications</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/TestCloneModuleVersionController.cls
/**
 * 2014-05-22 : Test class for CloneProgrammeController
 */
@isTest
private class TestCloneModuleVersionController {
    final static String MODULE_MASTER_NAME = 'Master_Version';
    final static String MODULE_VERSION_NAME = 'Versions';

    static testMethod void testController() {
        //Set up test data
        
        Map<String, RecordType> moduleRTMap = new Map<String, RecordType>();
        
        for (RecordType r : [select r.Id, r.DeveloperName from RecordType r where r.SObjectType = 'Module_Version__c' and r.IsActive = true]){
            moduleRTMap.put(r.DeveloperName, r);
        }
        
        Map<String, Module_Version__c> modMap = new Map<String, Module_Version__c>();
        for (integer i = 0 ; i < 4 ; i++){
            Module_Version__c m = new Module_Version__c();
            m.Name = 'Test Module Version Master ' + i;
            //m.Instance_Date__c = date.today();
            m.RecordTypeId = moduleRTMap.get(MODULE_MASTER_NAME).Id;
            modMap.put(m.Name, m);
        }
        
        insert modMap.values();
        
        Map<String, Module_Version__c> modMapVersions = new Map<String, Module_Version__c>();
        for (integer i = 0 ; i < 4 ; i++){
            Module_Version__c m = new Module_Version__c();
            m.Name = 'Test Module Version ' + i;
            //m.Instance_Date__c = date.today();
            m.RecordTypeId = moduleRTMap.get(MODULE_VERSION_NAME).Id;
            m.Master_Link__c = modMap.get('Test Module Version Master ' + i).Id;
            modMapVersions.put(m.Name, m);
        }

        insert modMapVersions.values();

        //Related List records
        List<Assessment_Specification__c> assessmentSpecs = new List<Assessment_Specification__c>();
        List<Module_Aim__c> moduleAims = new List<Module_Aim__c>();
        List<Module_Learning_Outcome__c> moduleLearningOutcomes = new List<Module_Learning_Outcome__c>();
        List<Module_Skill_Attribute__c> moduleSkillsAttributes = new List<Module_Skill_Attribute__c>();
        List<MV_Modification__c> moduleMVmodifications= new List<MV_Modification__c>();

        for (Module_Version__c mv : modMapVersions.values()){
            Assessment_Specification__c aSpec = new Assessment_Specification__c();
            aSpec.Module_Version__c = mv.Id;
            assessmentSpecs.add(aSpec);

            Module_Aim__c ma = new Module_Aim__c();
            ma.Module_Version__c = mv.Id;
            moduleAims.add(ma);

            Module_Learning_Outcome__c mlc = new Module_Learning_Outcome__c();
            mlc.Module_Version__c = mv.Id;
            moduleLearningOutcomes.add(mlc);

            Module_Skill_Attribute__c msa = new Module_Skill_Attribute__c();
            msa.Module_Version__c = mv.Id;
            moduleSkillsAttributes.add(msa);
            
            MV_Modification__c mvm = new MV_Modification__c();
            mvm.Module_Version__c = mv.Id;
            moduleMVmodifications.add(mvm);
        }

        insert assessmentSpecs;
        insert moduleAims;
        insert moduleLearningOutcomes;
        insert moduleSkillsAttributes;
        insert moduleMVmodifications;
        
        PageReference pageRef = Page.CloneModuleVersion;
        pageRef.getParameters().put('moduleId',modMapVersions.get('Test Module Version 0').Id);
        test.setCurrentPage(pageRef);
        
        ApexPages.StandardController std = new ApexPages.StandardController(modMapVersions.get('Test Module Version 0'));
        
        test.startTest();
        
        CloneModuleVersionController cpc = new CloneModuleVersionController(std);
        
        PageReference returnRef = cpc.cloneModule();
               
        test.stopTest();
    }
    
}