objects/Assessment__c.object
<CustomObject><fields>
        <fullName>Module_Reference__c</fullName>
        <formula>Module__r.Module_Reference__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Module Reference</label>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Assessment</label><nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Assessments</pluralLabel><sharingModel>ControlledByParent</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/Learning_Outcome__c.object
<CustomObject><fields>
        <fullName>Learning_Outcome__c</fullName>
        <label>Learning Outcome</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>Mode_of_Assessing__c</fullName>
        <inlineHelpText>Mode of Assessing Achievement of skill or other attribute</inlineHelpText>
        <label>Mode of Assessing</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Modules_Included__c</fullName>
        <inlineHelpText>Modules in which this will be delivered</inlineHelpText>
        <label>Modules Included</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Outcome_Type__c</fullName>
        <label>Outcome Type</label>
        <picklist>
            <picklistValues>
                <fullName>A (Knowledge &amp; Understanding)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B (Cognitive Skills)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C (Practical/Professional Skills)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <label>Programme Version</label>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Learning Outcomes</relationshipLabel>
        <relationshipName>Specification_Outcomes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Record_No__c</fullName>
        <description>Set by workflow</description>
        <inlineHelpText>Leave blank on record creation if automatic numbering is required (set by Workflow)</inlineHelpText>
        <label>No.</label>
        <length>5</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Type__c</fullName>
        <description>Hidden, populated by workflow and for RSF to Programme Version, for Outcome No workflow</description>
        <label>Type</label>
        <length>5</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Learning Outcome</label><nameField>
        <displayFormat>LO-{000000}</displayFormat>
        <label>Outcome Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Learning Outcomes</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Module__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Module_Reference__c</fullName>
        <description>LSTM reference for each course</description>
        <inlineHelpText>LSTM reference for each course</inlineHelpText>
        <label>Module Reference</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Module_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Filter prevents attaching Master record for Module Versions to Module Instance</description>
        <label>Module Version</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Module_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Versions</value>
            </filterItems>
            <filterItems>
                <field>Module_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Pre-Approved</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Module_Version__c</referenceTo>
        <relationshipLabel>Module Instances</relationshipLabel>
        <relationshipName>Modules_Instances</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Instances of Modules</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module</label><nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Modules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Module_Version__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Module_Reference__c</fullName>
        <description>LSTM internal reference</description>
        <label>Module Reference</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Version_Suffix__c</fullName>
        <label>Version Suffix</label>
        <length>20</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module Version</label><nameField>
        <label>Module Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Module Versions</pluralLabel><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme_Aim__c.object
<CustomObject><fields>
        <fullName>Programme_Version__c</fullName>
        <label>Programme Version</label>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Aims</relationshipLabel>
        <relationshipName>Programme_Aims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Record_No__c</fullName>
        <description>Text and not number to be consistent with Outcome Record No which needs letter prefix; set by workflow</description>
        <inlineHelpText>Leave blank on record creation if automatic numbering is required (set by Workflow)</inlineHelpText>
        <label>No.</label>
        <length>5</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Specific_Aim__c</fullName>
        <label>Specific Aim</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Programme Aim</label><nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Aim Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Programme Aims</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Programme_Module_Version__c.object
<CustomObject><fields>
        <fullName>Member_Type__c</fullName>
        <label>Member Type</label>
        <picklist>
            <picklistValues>
                <fullName>Required</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Optional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specials</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Mod_Ver_Name__c</fullName>
        <description>For data loading</description>
        <formula>Module_Version__r.Master_Link__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mod Ver Name</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Module_Reference__c</fullName>
        <description>for dataloading</description>
        <formula>Module_Version__r.Module_Reference__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Module Reference</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Module_Version__c</fullName>
        <inlineHelpText>To find correct Module Version type the first few character of Module Version title then click magnifying glass for available options</inlineHelpText>
        <label>Module Version</label>
        <referenceTo>Module_Version__c</referenceTo>
        <relationshipLabel>Programme Module Versions</relationshipLabel>
        <relationshipName>Instance_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Prog_Ver_Name__c</fullName>
        <description>For dataloading, to be hidden. Returns Master Version name, ie without suffix</description>
        <formula>Programme_Version__r.Master_Link__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>For dataloading, to be hidden. Returns Master Version name, ie without suffix</inlineHelpText>
        <label>Prog Ver Name</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme_Version_Suffix__c</fullName>
        <formula>If (  Programme_Version__r.RecordType.Name = "Master Version", 
    "Master", 
    Programme_Version__r.Version_Suffix__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Programme Version Suffix</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <label>Programme Version</label>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Programme Module Versions</relationshipLabel>
        <relationshipName>Instance_Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Many-to-many object to allow one Module version to be a member of multiple Programme version</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Programme Module Version</label><nameField>
        <displayFormat>PMV-{00000000}</displayFormat>
        <label>Programme Module Version</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Programme Module Versions</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Programme_Version__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Modules_Included__c</fullName>
        <inlineHelpText>This is Table 1 in paper specification</inlineHelpText>
        <label>Modules Included</label>
        <length>32768</length>
        <type>Html</type>
    </fields><fields>
        <fullName>Programme_Type__c</fullName>
        <label>Programme Type</label>
        <picklist>
            <picklistValues>
                <fullName>MSc Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Diploma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Masters Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG Cert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Course</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Version_Suffix__c</fullName>
        <description>To differentiate between Programme Versions, added to Master name</description>
        <label>Version Suffix</label>
        <length>20</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme Version</label><nameField>
        <label>Programme Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programme Versions</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Skills_Attributes__c.object
<CustomObject><fields>
        <fullName>Mode_of_Assessing__c</fullName>
        <inlineHelpText>Mode of Assessing Achievement of skill or other attribute</inlineHelpText>
        <label>Mode of Assessing</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Modules_Included__c</fullName>
        <inlineHelpText>Modules in which this will be delivered</inlineHelpText>
        <label>Modules Included</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <label>Programme Version</label>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Skills &amp; Attributes</relationshipLabel>
        <relationshipName>Skills_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Record_No__c</fullName>
        <description>Text and not number to be consistent with Outcome Record No which needs letter prefix; set by workflow</description>
        <inlineHelpText>Leave blank on record creation if automatic numbering is required (set by Workflow)</inlineHelpText>
        <label>No.</label>
        <length>5</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Skill_Attribute__c</fullName>
        <label>Skill or Attribute</label>
        <type>TextArea</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Skill &amp; Attribute</label><nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Skill Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Skills &amp; Attributes</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/CloneProgrammeVersionController.cls
public class CloneProgrammeVersionController {
	public final String PROG_ID_PARAM = 'progId';
	public final String MSC_TYPE = 'Masters Module';
	public List<Programme_Version__c> originalProgList {get; set;}
	public Programme_Version__c originalProg {get; set;}
	public Programme_Version__c cloneProg {get; set;}
	public List<Programme_Module_Version__c> originalProgModuleList {get; set;}
	public List<ModuleWrapper> moduleWrapperList {get; set;}
	public integer numberOfSessions {get; set;}
	public Map<Id, Programme_Module_Version__c> originalProgModuleMap {get; set;}
	public boolean isShortCourse {get; set;}
	public String filterName {get; set;}
	public String filterType {get; set;}
	public boolean noResults {get; set;}
	//Related list objects against Programme Version
	public List<Programme_Aim__c> programmeAims {get; set;}
	public List<Skills_Attributes__c> skillsAttributes {get; set;}
	public List<Learning_Outcome__c> learningOutcomes {get; set;}
	

	public CloneProgrammeVersionController(ApexPages.standardController std){
		isShortCourse = false;
		String progId = ApexPages.currentPage().getParameters().get(PROG_ID_PARAM);
		cloneProg = new Programme_Version__c();
		originalProgList = new List<Programme_Version__c>();

		String dbQuery = 'SELECT Id, ';
		for(Schema.FieldSetMember f : SObjectType.Programme_Version__c.FieldSets.AllFields.getFields()) {
            dbQuery += f.getFieldPath() + ', ';
        }

	    dbQuery += '(Select Name, Member_Type__c, Module_Reference__c, Module_Version__c, Mod_Ver_Name__c, Programme_Version__c, Programme_Version_Suffix__c, Prog_Ver_Name__c From Instance_Members__r), ';
	    //Programme Aims
	    dbQuery += '(Select Record_No__c, Specific_Aim__c from Programme_Aims__r), ';
	    //Skills & Attributes
	    dbQuery += '(Select Mode_of_Assessing__c, Modules_Included__c, Record_No__c, Skill_Attribute__c from Skills_Attributes__r), ';
	    //Learning Outcomes
	    dbQuery += '(Select Learning_Outcome__c, Mode_of_Assessing__c, Modules_Included__c, Record_No__c, Outcome_Type__c, Type__c from Specification_Outcomes__r)';

        dbQuery += 'FROM Programme_Version__c where Id = \'' + progId + '\'';

        system.debug('*** -- dbQuery -- ***');
        system.debug(dbQuery);
		
		originalProgList = Database.query(dbQuery);

		if (originalProgList.size() > 0){
			originalProg = originalProgList[0];
			originalProgModuleList = originalProgList[0].Instance_Members__r;
		}
		
		if (MSC_TYPE.equalsIgnoreCase(originalProg.Programme_Type__c)){
			isShortCourse = true;
		}
		
		system.debug('*** -- isShortCourse = ' + isShortCourse + ' -- ***');

		originalProgModuleMap = new Map<Id, Programme_Module_Version__c>();
		for (Programme_Module_Version__c pm : originalProgModuleList){
			originalProgModuleMap.put(pm.Module_Version__c, pm);
		}		
		
		cloneProg = originalProg.clone(false, true, false, false);
		cloneProg.Active__c = true;
		
		if (!isShortCourse){		
			Set<Id> moduleIds = new Set<Id>();
			for (Programme_Module_Version__c pm : originalProgModuleList){
				moduleIds.add(pm.Module_Version__c);
			}
			
			List<Module_Version__c> originalModuleList = new List<Module_Version__c>();
			List<Module_Version__c> clonedModuleList = new List<Module_Version__c>();
			Map<Id, Module_Version__c> originalModuleMap = new Map<Id, Module_Version__c>();

			String dbModuleQuery = 'SELECT ';

			for(Schema.FieldSetMember f : SObjectType.Module_Version__c.FieldSets.AllFields.getFields()) {
	            dbModuleQuery += f.getFieldPath() + ', ';
	        }

		    //dbModuleQuery += '(Select Name, RecordTypeId, Session_Type__c, Room_Name__c, Module__c From Sessions__r), ';
		    //dbModuleQuery += '(Select Name, Module__c, Assessment_Type__c, Description__c, Weighting_Variable__c, Weighting_percent__c, Short_Name__c, Module_Reference__c, Pass_Critical__c, Criticality_Score__c From Assessments__r)';

	        dbModuleQuery += 'Id From Module_Version__c m where m.Id in :moduleIds';

					
			originalModuleList = Database.query(dbModuleQuery);

			moduleWrapperList = new List<ModuleWrapper>();
			for (Module_Version__c m : originalModuleList){
				moduleWrapperList.add(new ModuleWrapper(m));
			}
		} 	
	}

	//This method will return a list of Modules with the matching searched for criteria
	public PageReference filterModules(){
		String dbQuery = 'SELECT ';

		for(Schema.FieldSetMember f : SObjectType.Module_Version__c.FieldSets.AllFields.getFields()) {
            dbQuery += f.getFieldPath() + ', ';
        }

	    //dbQuery += '(Select Name, RecordTypeId, Session_Type__c, Room_Name__c, Module__c From Sessions__r), ';
	    //dbQuery += '(Select Name, Module__c, Assessment_Type__c, Description__c, Weighting_Variable__c, Weighting_percent__c, Short_Name__c, Module_Reference__c, Pass_Critical__c, Criticality_Score__c From Assessments__r)';

        dbQuery += 'Id From Module_Version__c m where m.Name LIKE \'' + filterName + '%\' ORDER BY m.Name DESC';

		system.debug('*** -- dbQuery = ' + dbQuery + ' -- ***');
		
		List<Module_Version__c> originalModuleList = new List<Module_Version__c>();
		originalModuleList = Database.Query(dbQuery);
		if (originalModuleList.size() == 0){
			noResults = true;
		}else {
			noResults = false;
		}
		
		List<Module_Version__c> clonedModuleList = new List<Module_Version__c>();
		Map<Id, Module_Version__c> originalModuleMap = new Map<Id, Module_Version__c>();
		
		if (!noResults){
			moduleWrapperList = new List<ModuleWrapper>();
			for (Module_Version__c m : originalModuleList){
				moduleWrapperList.add(new ModuleWrapper(m));
			}
		}
		
		return null;
	}

	//This is the method that will clone the programme and all modules
	public PageReference cloneProgramme(){
		Map<Id, Module_Version__c> cloneModulesMap = new Map<Id, Module_Version__c>();
		List<Programme_Module_Version__c> cloneProgModules = new List<Programme_Module_Version__c>();
		List<Assessment__c> cloneAssessments = new List<Assessment__c>();
		List<Session__c> cloneSessions = new List<Session__c>();
		PageReference pageRef;
		
		//First we need to insert the new Programme
		insert cloneProg;
		
		//2014-07-15 : CSL : We need to only create Modules if this isn't the special type (At the moment set to Short Course, but TBD)
		if (!isShortCourse){
			//Then we need to loop through all the selected Modules and clone them
			for (ModuleWrapper mw : moduleWrapperList){
				if (mw.isSelected){
					Module_Version__c cloneMod = mw.theModule.clone(false, true, false, false);
					cloneMod.Version_Suffix__c = cloneProg.Version_Suffix__c;
					cloneModulesMap.put(mw.theModule.Id, cloneMod);
				}
			}
			
			insert cloneModulesMap.values();
					
			//Now we need to make sure we have the Programme_Modules__c cloned
			for (ModuleWrapper mw : moduleWrapperList){
				if (mw.isSelected){
					Programme_Module_Version__c originalPM = originalProgModuleMap.get(mw.theModule.Id);
					if (originalPM != null){
						Module_Version__c cloneModule = cloneModulesMap.get(mw.theModule.Id);
						Programme_Module_Version__c clonePM = originalPM.clone(false, true, false, false);
						clonePM.Module_Version__c = cloneModule.Id;
						clonePM.Programme_Version__c = cloneProg.Id;
						cloneProgModules.add(clonePM);
					}	
				}
			}
			
			insert cloneProgModules;
			
		}else {
			//2014-07-15 : CSL : This is new code for the specialist 'forked clone' functionality
			for (ModuleWrapper mw : moduleWrapperList){
				if (mw.isSelected){
					Programme_Module_Version__c clonePM = new Programme_Module_Version__c();
					clonePM.Module_Version__c = mw.theModule.Id;
					clonePM.Programme_Version__c = cloneProg.Id;
					cloneProgModules.add(clonePM);
				}
			}
			
			insert cloneProgModules;
			
		}

		//Clone any related list objects
		programmeAims = new List<Programme_Aim__c>();
		skillsAttributes = new List<Skills_Attributes__c>();
		learningOutcomes = new List<Learning_Outcome__c>();
		for (Programme_Aim__c pa : originalProgList[0].Programme_Aims__r){
			Programme_Aim__c newPA = pa.Clone(false, true, false, false);
			newPA.Programme_Version__c = cloneProg.Id;
			programmeAims.add(newPA);
		}

		for (Skills_Attributes__c sa : originalProgList[0].Skills_Attributes__r){
			Skills_Attributes__c newSA = sa.Clone(false, true, false, false);
			newSA.Programme_Version__c = cloneProg.Id;
			skillsAttributes.add(newSA);
		}

		for (Learning_Outcome__c lc : originalProgList[0].Specification_Outcomes__r){
			Learning_Outcome__c newLC = lc.Clone(false, true, false, false);
			newLC.Programme_Version__c = cloneProg.Id;
			learningOutcomes.add(newLC);
		}

		if (programmeAims.size() > 0) insert programmeAims;

		if (skillsAttributes.size() > 0) insert skillsAttributes;

		if (learningOutcomes.size() > 0) insert learningOutcomes;
		
		pageRef = new PageReference('/' + cloneProg.Id);
		pageRef.setRedirect(true);
				
		return pageRef;
	}

	public class ModuleWrapper {
		public Module_Version__c theModule {get; set;}
		public integer numberOfSessions {get; set;}
		public integer numberOfAssessments {get; set;}
		public boolean isSelected {get; set;}
		
		public ModuleWrapper(Module_Version__c inMod) {
			theModule = inMod;
			//numberOfSessions = inMod.Sessions__r.size();
			//numberOfAssessments = inMod.Assessments__r.size();
			isSelected = false;
		}
		
	}

}