objects/Case.object
<CustomObject><fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme_Version_Name__c</fullName>
        <label>Programme Version Name</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme Version</label>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Enquiries</relationshipLabel>
        <relationshipName>Enquiries</relationshipName>
        <type>Lookup</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><sharingModel>ReadWriteTransfer</sharingModel></CustomObject>

objects/Programme_Version__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme Version</label><nameField>
        <label>Programme Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programme Versions</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

classes/testTgrUpdateWebtoCase.cls
/* testtgrUpdateWebtoCase Test class Created by Manu KM on 10-sep-2015*/
/// <summary>
// This is Unit test for tgrUpdateWebtoCase
/// </summary>
@isTest
public class testTgrUpdateWebtoCase{
    public static testMethod void testCaseCreation(){
        //creating test cases 
        case testCase = new case();
        testCase.Programme_Version_Name__c = 'testPgmname'; 
        testCase.origin= 'Web';
        testCase.Last_Name__c= 'test';
        //inserting test case this will invoke TgrUpdateWebtoCase with bad case
        insert testCase;
        //creating test programme data
        Programme_Version__c testpgmversion = new Programme_Version__c();
        testpgmversion.Name = 'test';
        insert testpgmversion;
        //inserting test case record with true value
        case testCase2 = new case();
        testCase2.Programme_Version_Name__c = '-'; 
        testCase2.origin= 'Web';
        testCase2.Last_Name__c= 'test';
        //this will invoke trigger with true values
        insert testCase2;
        case resultset=[Select id from case where id=:testCase2.Id];
        //Asserting the result
        System.assertEquals(true,resultset != null);
    }
}