objects/Contact.object
<CustomObject><fields>
        <fullName>EU_Citizen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>X EU Citizen</label>
        <type>Checkbox</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Programme__c.object
<CustomObject><fields>
        <fullName>End_Date__c</fullName>
        <description>Last Date module is valid</description>
        <label>End Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Home_EU_Fee__c</fullName>
        <inlineHelpText>Fee for UK and rest of EU students; if 'Fee TBC' is checked this amount is an estimate for reporting</inlineHelpText>
        <label>Home EU Fee</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Overseas_Fee__c</fullName>
        <inlineHelpText>Fees for students outside of EU; if 'Fee TBC' is checked this amount is an estimate for reporting</inlineHelpText>
        <label>Overseas Fee</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme Version</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Programme_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Versions, Versions, Specification, Versions - Pre Approved, Specification Edit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Programme Instances</relationshipLabel>
        <relationshipName>Programmes_Instances</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme_Version__c.object
<CustomObject><fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Home_EU_Fee__c</fullName>
        <label>Home EU Fee</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Overseas_Fee__c</fullName>
        <label>Overseas Fee</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Date of first Intake</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme Version</label><nameField>
        <label>Programme Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programme Versions</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

classes/TestChooseProgrammeCont.cls
/**
 * @author Valentyn Bilenkyy
 * @date 17/06/2014
 * @description Test class for ChooseProgrammeCont.cls
 */
 /* Support task :commented the lines for removing additioanl x fields 95 and 102*/
@isTest
private class TestChooseProgrammeCont {

    private static final Integer NUMBER_OF_PROGRAMS_TO_CREATE = 3 * ChooseProgrammeCont.SEARCH_RESULTS_PER_PAGE;
    private static final String PROGRAMME_TYPE = 'Test';
    private static final String PROGRAMME_NAME = 'Test Programme';

    @isTest static void testConstructorIsNotNull() {
        Test.startTest();
            ChooseProgrammeCont ctrl = new ChooseProgrammeCont();
        Test.stopTest();
        System.assertNotEquals(null, ctrl);
    }

    @isTest static void testSearch() {
        createTestData();
        Test.startTest();
            ChooseProgrammeCont ctrl = new ChooseProgrammeCont();
            ctrl.searchTerm = PROGRAMME_NAME;
            ctrl.searchProgrammeType = PROGRAMME_TYPE;
            ctrl.search();
            System.assert(ctrl.getFoundProgrammes().size()>0);            
        Test.stopTest();
    }

    @isTest static void testPaginationMethodsAndProperties() {
        createTestData();
        Test.startTest();
            ChooseProgrammeCont ctrl = new ChooseProgrammeCont();
            System.assertEquals(1, ctrl.pageNumber);
            System.assertEquals(false, ctrl.hasPrevious);
            System.assertEquals(true, ctrl.hasNext);
            ctrl.next();
            System.assertEquals(2, ctrl.pageNumber);
            ctrl.first();
            System.assertEquals(1, ctrl.pageNumber);
            ctrl.last();
            System.assertEquals(3, ctrl.pageNumber);
            ctrl.previous();
            System.assertEquals(2, ctrl.pageNumber);                       
        Test.stopTest();
    }

    @isTest static void testGetProgrammeTypes() {
        Test.startTest();
            ChooseProgrammeCont ctrl = new ChooseProgrammeCont();
            List<SelectOption> programmeTypes = ctrl.getProgrammeTypes();                       
            ctrl.resetSearch();
            ctrl.getProgrammeTypesExternal();
            ApexPages.currentPage().getParameters().put('programmeid', 'a0311000003b1hF');
            ChooseProgrammeCont ctrl2 = new ChooseProgrammeCont();
        Test.stopTest();
        System.assert(programmeTypes.size()>0);
    }
    
    @isTest static void testProcessApply(){
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        User commUser;
        System.runAs(thisUser) {
           
            commUser = ApplyTestingUtils.createCommunityUser('Patterson', 'd1@test.com', ApplyTestingUtils.CUSTOMER_COMMUNITY_PROFILE_NAME);
        }
        Test.startTest();
        System.runAs(commUser) {
             createTestData();
            ChooseProgrammeCont ctrl = new ChooseProgrammeCont();
            PageReference result1 = ctrl.processApply();
            System.assertEquals(null, result1);
            Id progId = ctrl.getFoundProgrammes()[0].programme.Id;
            ctrl.programmeId = progId;
            PageReference result2 = ctrl.processApply();
            System.assert(result2.getUrl().toLowerCase().startsWith('/apex/applywizard'));
        }
        Test.stopTest();
    }

    @isTest static void testProgrammeWrapper() {
        Test.startTest();
            Programme__c p = new Programme__c();
            p.Home_EU_Fee__c = 1000;
            p.Overseas_Fee__c = 1500;
            ProgrammeWrapper pw;
            pw = new ProgrammeWrapper(p);
            System.assertEquals('', pw.combinedDates);

            User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
            User commUser;
            System.runAs(thisUser) {
                commUser = ApplyTestingUtils.createCommunityUser('Fox Maulder', 'maulder@fbi.com', ApplyTestingUtils.CUSTOMER_COMMUNITY_PROFILE_NAME);
            }
             Contact c = [SELECT Id FROM Contact WHERE Id = : commUser.ContactId];
            c.EU_Citizen__c = false;
            update c;
            System.runAs(commUser) {
                System.assertEquals(1500, pw.fee);
            }
            c.EU_Citizen__c = true;
            update c; 
            ProgrammeWrapper.usr = null;
            System.runAs(commUser) {
                System.assertEquals(1000, pw.fee);
            }

            p.Start_Date__c = Date.newInstance(2014, 5, 15);
            pw = new ProgrammeWrapper(p);
            System.assertEquals('From 15 May 2014', pw.combinedDates);
            p.Start_Date__c = null;
            p.End_Date__c = Date.newInstance(2014, 5, 15);
            pw = new ProgrammeWrapper(p);
            System.assertEquals('Till 15 May 2014', pw.combinedDates);
            p.Start_Date__c = Date.newInstance(2014, 5, 15);
            pw = new ProgrammeWrapper(p);
            System.assertEquals('15 May 2014', pw.combinedDates);
            p.Start_Date__c = Date.newInstance(2014, 5, 14);
            pw = new ProgrammeWrapper(p);
            System.assertEquals('14 - 15 May 2014', pw.combinedDates);
            p.Start_Date__c = Date.newInstance(2014, 4, 15);
            pw = new ProgrammeWrapper(p);
            System.assertEquals('15 April - 15 May 2014', pw.combinedDates);
            p.Start_Date__c = Date.newInstance(2013, 5, 15);
            pw = new ProgrammeWrapper(p);
            System.assertEquals('15 May 2013 - 15 May 2014', pw.combinedDates);
        Test.stopTest();
    }
    
    private static void createTestData() {
        //Programme Version
        Id mvrtId = CommonUtils.findRecordTypeIdByDev(ApplyTestingUtils.PROGRAMME_VERSION, ApplyServices.RT_MASTER_PV_DEVNAME);
        Programme_Version__c mv = ApplyTestingUtils.createProgrammeVersion(PROGRAMME_NAME, mvrtId, PROGRAMME_TYPE, true);
        Id rtId = CommonUtils.findRecordTypeIdByDev(ApplyTestingUtils.PROGRAMME_VERSION, ApplyServices.RT_VERSION_PV_DEVNAME);
        Programme_Version__c pv = ApplyTestingUtils.createProgrammeVersion(PROGRAMME_NAME, rtId, PROGRAMME_TYPE, mv.Id, true);
        //Programme
        List<Programme__c> programmesList = ApplyTestingUtils.createProgramme(PROGRAMME_NAME, pv.Id, NUMBER_OF_PROGRAMS_TO_CREATE, true);
        System.debug('### Initial programmesList: ' + programmesList);
    }
}