objects/Contact.object
<CustomObject><fields>
        <fullName>LSTM_Email__c</fullName>
        <description>For LSTM email address, which is LSTM No with domain suffix</description>
        <label>LSTM Email</label>
        <type>Email</type>
    </fields><fields>
        <fullName>Middle_Name_Other_Names__c</fullName>
        <label>Middle Name/Other Names</label>
        <length>80</length>
        <type>Text</type>
    </fields><fields>
        <fullName>VLE_ID__c</fullName>
        <description>UserId for desire2learn API</description>
        <label>VLE_ID</label>
        <length>32</length>
        <type>Text</type>
    </fields><fields>
        <fullName>VLE_Visibility__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VLE_Visibility</label>
        <type>Checkbox</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Module__c.object
<CustomObject><fields>
        <fullName>VLE_ID__c</fullName>
        <description>Course offering ID at VLE side</description>
        <label>VLE ID</label>
        <length>32</length>
        <type>Text</type>
    </fields><fields>
        <fullName>VLE_Visibility__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To prevent some records triggering actions in VLE</description>
        <inlineHelpText>To prevent some records triggering actions in VLE</inlineHelpText>
        <label>VLE Visibility</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Instances of Modules</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module</label><nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Modules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Module_Role__c.object
<CustomObject><fields>
        <fullName>Module_Role__c</fullName>
        <description>Defines role for Module Spec, and against Module Instance for VLE integration</description>
        <label>Module Role</label>
        <picklist>
            <picklistValues>
                <fullName>Module Convenor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Module Moderator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Examiner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Teacher</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Staff with Roles</relationshipLabel>
        <relationshipName>Module_Roles</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Staff__c</fullName>
        <label>Staff</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Staff</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Module Roles</relationshipLabel>
        <relationshipName>Module_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Join object between Staff (Contacts) and Modules (both Instances and Version objects). Will allow definition of staff role on a module and be used in VLE integration to define extent of staff enrolment.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Module Role</label><nameField>
        <displayFormat>MR-{00000000}</displayFormat>
        <label>Module Role Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Module Roles</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Programme__c.object
<CustomObject><fields>
        <fullName>Homepage_VLE_ID__c</fullName>
        <formula>Programme_Version__r.Homepage_VLE_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Homepage VLE ID</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Type__c</fullName>
        <formula>Text ( Programme_Version__r.Programme_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Taken from Version level</inlineHelpText>
        <label>Type</label>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>LSTM_Email__c</fullName>
        <description>Taken from Contact object</description>
        <label>LSTM Email</label>
        <type>Email</type>
    </fields><fields>
        <fullName>Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Programme must be active (i.e. most recent)</errorMessage>
            <filterItems>
                <field>Programme__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Student Programmes</relationshipLabel>
        <relationshipName>Students_on_Programme1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reverted from Master:Detail as per LSTM requirement</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Programmes</relationshipLabel>
        <relationshipName>Student_Programmes1</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/VLE_Action__c.object
<CustomObject><fields>
        <fullName>Action__c</fullName>
        <description>Type of action to VLE API</description>
        <label>Action</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>Next_Try__c</fullName>
        <description>Time when delayed action should try sync again</description>
        <label>Next Try</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Note__c</fullName>
        <description>Some notes about this action. Show error message if error occurs in the perform() method.</description>
        <label>Note</label>
        <length>64</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <description>Status value means: New - for future, Delayed - wait for became Batch, Canceled - not actual in some reasons</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Batch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delayed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Object for perform complex action to VLE API</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>VLE Action</label><nameField>
        <label>VLE Action Name</label>
        <type>Text</type>
    </nameField><pluralLabel>VLE Actions</pluralLabel><sharingModel>Private</sharingModel></CustomObject>

classes/VleDaoServices.cls
/**
 * Common DAO service for SOQL and DML operations
 * Note: Use 'without sharing' to perform all operation in system mode 
 */
public without sharing class VleDaoServices {

    /**
     * Get list of last modified action records
     * @param num List size
     * @return List of actions
     */
    public static List<Vle_Action__c> getLastSyncActions(Integer num) {
        return [
            SELECT Action__c, LastModifiedDate, Name, Next_Try__c, Note__c, Status__c
            FROM VLE_Action__c
            ORDER BY LastModifiedDate DESC
            LIMIT :num
        ];
    }
    
    /**
     * Retrieve Student programme records with related data like Contact and Programme__c
     * @param studentProgramId ID of Student_Programme__c record
     * @return Student_Programme__c or null
     */
    public static Student_Programme__c findStudentProgrammeInfo(Id studentProgramId) {
        System.debug('Person query');
        List<Student_Programme__c> spList = [
            SELECT Student__c, Student__r.Email,Student__r.RecordType.Name,Student__r.LSTM_Email__c, Student__r.FirstName, Student__r.LastName,
                Student__r.Name, Student__r.Middle_Name_Other_Names__c, Student__r.VLE_ID__c,
                Programme__r.Type__c, Programme__r.Homepage_VLE_ID__c
            FROM Student_Programme__c
            WHERE Id = :studentProgramId
        ];
        System.debug('spList ='+spList);
        return ( spList.isEmpty() ) ? null : spList[0];
    }
    
    /**
     * Retrieve contacts with related module roles
     * @param cList List of contacts
     * @return List of contacts
     */
    public static List<Contact> findStaffWithModuleRoles(List<Contact> cList) {
        System.debug('Suyati VleDaoServices findStaffWithModuleRoles');
        return [
            SELECT Email,LSTM_Email__c,RecordType.Name, FirstName, LastName, Name, Middle_Name_Other_Names__c, VLE_ID__c, VLE_Visibility__c,
                ( SELECT Module__c, Module_Role__c, Module__r.VLE_ID__c, Module__r.VLE_Visibility__c, Staff__c FROM Module_Roles__r )
            FROM Contact
            WHERE Id IN :cList
        ];
    }
    
    /**
     * Retrieve Contact with related module roles
     * @param studentId ID of student
     * @return Contact with related data
     */
    public static Contact findStaffModuleRoles(Id studentId) {
        List<Contact> cList = findStaffWithModuleRoles(new List<Contact>{ new Contact(Id = studentId) });
        return ( cList.isEmpty() ) ? null : cList[0];
    }
    
    /**
     * Retrieve modules by IDs
     * @param moduleIds Set of ID
     * @return List of modules
     */
    public static List<Module__c> findProgrammeModules(Set<Id> moduleIds) {
        return [SELECT VLE_ID__c FROM Module__c WHERE Id IN :moduleIds];
    }
    
    /**
     * Retrieve list of contacts with VLE fields
     * @param cList List of contacts
     * @return List of contacts with VLE fields
     */
    public static List<Contact> findContacts(List<Contact> cList) {
        System.debug('Suyati VleDaoServices findContacts');
        return [SELECT VLE_ID__c, VLE_Visibility__c FROM Contact WHERE Id IN :cList];
    }
    
    /**
     * Retrieve contact by ID with VLE fields
     * @param contactID ID of contact
     * @return Contact or null
     */
    public static Contact findContact(Id contactId) {
        List<Contact> cList = findContacts(new List<Contact>{ new Contact(Id = contactId) });
        return ( cList.isEmpty() ) ? null : cList[0];
    }
    
    /**
     * Retrieve related to list of Module_Role__c data
     * @param mrList List of Module_Role__c records
     * @return List of Module_Role__c with related data
     */
    public static List<Module_Role__c> findModuleRolesData(List<Module_Role__c> mrList) {
        return [
            SELECT Module__c, Module_Role__c, Module__r.VLE_ID__c, Module__r.VLE_Visibility__c,
                Staff__c, Staff__r.VLE_ID__c, Staff__r.VLE_Visibility__c
            FROM Module_Role__c
            WHERE Id IN :mrList
        ];
    }
    
    /**
     * Retrieve related to Module_Role__c data
     * @param mrId ID of Module_Role__c record
     * @return Module_Role__c or null
     */
    public static Module_Role__c findModuleRoleData(Id mrId) {
        List<Module_Role__c> mrList = findModuleRolesData(new List<Module_Role__c>{ new Module_Role__c(Id = mrId) });
        return ( mrList.isEmpty() ) ? null : mrList[0];
    }
    
    /**
     * Detect empty or not empty VLE_ID__c field value
     * @param objName Name of sObject e.g. Contact or Student_Programme__c
     * @param recordId ID of record
     * @return True if VLE_ID__c has a value (not null) 
     */
    public static Boolean hasNotEmptyVleId(String objName, Id recordId) {
        String s = 'SELECT Id FROM ' + objName + ' WHERE Id = :recordId AND VLE_ID__c != NULL';
        System.debug('query >>>> ' + s);
        List<sObject> sObjList = Database.query(s);
        return !sObjList.isEmpty();
    }
    
    /**
     * Do update DML in system mode
     * @param sObjList List of sObject for update
     */
    public static void makeUpdate(List<sObject> sObjList) {
        update sObjList;
    }

    /**
     * Retrieve Module__c data by specified Ids
     * @param moduleIds Set of Module__c record Ids
     * @return List of Module__c records
     */
    public static List<Module__c> findModuleData(Set<Id> moduleIds) {
        return [
            SELECT Id, Vle_Id__c
            FROM Module__c
            WHERE Id IN :moduleIds
        ];
    }   
    
}