objects/Contact.object
<CustomObject><fields>
        <fullName>VLE_ID__c</fullName>
        <description>UserId for desire2learn API</description>
        <label>VLE_ID</label>
        <length>32</length>
        <type>Text</type>
    </fields><fields>
        <fullName>VLE_Visibility__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VLE_Visibility</label>
        <type>Checkbox</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Module__c.object
<CustomObject><fields>
        <fullName>VLE_ID__c</fullName>
        <description>Course offering ID at VLE side</description>
        <label>VLE ID</label>
        <length>32</length>
        <type>Text</type>
    </fields><fields>
        <fullName>VLE_Visibility__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To prevent some records triggering actions in VLE</description>
        <inlineHelpText>To prevent some records triggering actions in VLE</inlineHelpText>
        <label>VLE Visibility</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Instances of Modules</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module</label><nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Modules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme__c.object
<CustomObject><fields>
        <fullName>Code__c</fullName>
        <formula>Programme_Version__r.Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Taken from Version level</inlineHelpText>
        <label>Code</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Homepage_VLE_ID__c</fullName>
        <formula>Programme_Version__r.Homepage_VLE_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Homepage VLE ID</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme Version</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Programme_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Versions, Versions, Specification, Versions - Pre Approved, Specification Edit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Programme Instances</relationshipLabel>
        <relationshipName>Programmes_Instances</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Type__c</fullName>
        <formula>Text ( Programme_Version__r.Programme_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Taken from Version level</inlineHelpText>
        <label>Type</label>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme_Module__c.object
<CustomObject><fields>
        <fullName>Member_Type__c</fullName>
        <inlineHelpText>Whether Module is Required, Optional or Alternative; Solus is used to denote where a Programme only had a single Module.</inlineHelpText>
        <label>Member Type</label>
        <picklist>
            <picklistValues>
                <fullName>Required</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Optional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specials</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To find correct Module type first the few character of Module title then click magnifying glass for available options</inlineHelpText>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Assigned Programmes</relationshipLabel>
        <relationshipName>Programme_Modules</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Programme__c</fullName>
        <description>Via Master-Detail relationship, no reparenting allowed</description>
        <label>Programme</label>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Assigned Modules</relationshipLabel>
        <relationshipName>Programme_Modules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Many to many object, to allow one Module (instance) to be a member of multiple Programmes (instances)</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Programme Module</label><nameField>
        <displayFormat>PMI-{00000000}</displayFormat>
        <label>Programme Module</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Programme Modules</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Programme_Version__c.object
<CustomObject><fields>
        <fullName>Code__c</fullName>
        <inlineHelpText>Internal LSTM programme code</inlineHelpText>
        <label>Code</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Homepage_VLE_ID__c</fullName>
        <description>Program Homepage VLE ID</description>
        <label>Homepage VLE ID</label>
        <length>10</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme Version</label><nameField>
        <label>Programme Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programme Versions</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Student_Module__c.object
<CustomObject><fields>
        <fullName>Member_Type__c</fullName>
        <formula>TEXT( Programme_Module__r.Member_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Member Type</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Module__c</fullName>
        <formula>HYPERLINK ( Programme_Module__r.Module__r.Id, Programme_Module__r.Module__r.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Module</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme_Module__c</fullName>
        <label>Programme Module</label>
        <referenceTo>Programme_Module__c</referenceTo>
        <relationshipLabel>Student Modules</relationshipLabel>
        <relationshipName>Student_Modules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Programme__c</fullName>
        <formula>HYPERLINK (  Programme_Module__r.Programme__r.Id , Programme_Module__r.Programme__r.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Programme</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Student_Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to (new) Student Programme object</description>
        <label>Student Programme</label>
        <referenceTo>Student_Programme__c</referenceTo>
        <relationshipLabel>Student Modules</relationshipLabel>
        <relationshipName>Student_Modules</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Student Applicant, Full Student, Student Pre-Reg</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Modules</relationshipLabel>
        <relationshipName>Student_Modules</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Join table between Student (contact) and Program Module join table, with link up to Student Programme</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Student Module</label><nameField>
        <label>Student Module Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Modules</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Programme must be active (i.e. most recent)</errorMessage>
            <filterItems>
                <field>Programme__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Student Programmes</relationshipLabel>
        <relationshipName>Students_on_Programme1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Stage__c</fullName>
        <description>NOTE : This field drives the Student Programme flow - DO NOT change pick list values without discussion with the I.T / Dev Team</description>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Checked</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional</fullName>
                <color>#339999</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unconditional</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
                <color>#FF99FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Expected</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Registered</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
                <color>#419249</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#666666</color>
            </picklistValues>
            <picklistValues>
                <fullName>Offered</fullName>
                <color>#DDDDDD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reverted from Master:Detail as per LSTM requirement</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Programmes</relationshipLabel>
        <relationshipName>Student_Programmes1</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><recordTypes>
        <fullName>Completed</fullName>
        <active>true</active>
        <label>Completed</label>
    </recordTypes><recordTypes>
        <fullName>Registered</fullName>
        <active>true</active>
        <label>Non-MSc Registered</label>
    </recordTypes></CustomObject>

classes/StudentProgrammeTriggerMethods.cls
/*
*
* 2014-07-31 : CSL : This class holds methods called from the StudentProgrammeTrigger
*
*/
public class StudentProgrammeTriggerMethods {
    
    public static final String TYPE_REQUIRED = 'Required';
    public static final String TYPE_OPTIONAL = 'Optional';
    
    // Student_Programme__c.Stage__c constants
    public static final String STAGE_ACCEPTED = 'Accepted';
    public static final String STAGE_PRE_REGISTERED = 'Pre-Registered';
    public static final String STAGE_COMPLETED = 'Completed';
    
    public static final String CODE_DTN = 'DTN';

    private static List<Student_Programme__c> findDTNStudentProgrammesData(List<Student_Programme__c> spList) {
        return [
            SELECT Id, Programme__c, Student__c, Student__r.VLE_ID__c, Student__r.FirstName, Student__r.LastName
            FROM Student_Programme__c
            WHERE Id IN :spList
            //AND Programme__r.Code__c = :CODE_DTN
        ];
    }

    private static List<Student_Programme__c> findStudentProgrammesDataWithPv(List<Student_Programme__c> spList) {
        List<Id> spIds = new List<Id>();
        for(Student_Programme__c sp : spList)
            spIds.add(sp.Id);
        
        return [
            SELECT Id, Programme__c, Student__c, Student__r.VLE_ID__c, Student__r.FirstName, Student__r.LastName, Programme__r.Type__c, Programme__r.Homepage_VLE_ID__c
            FROM Student_Programme__c
            WHERE Id IN :spIds
            AND Programme__r.Programme_Version__c != NULL
            //AND Programme__r.Code__c = :CODE_DTN
        ];
    }


    //return Programme id to list of modules (student module relation is used)
    private static Map<Id,List<Module__c>> findStudentModulesByProgramModuleMemberType(List<Student_Programme__c> spList, List<String> memberTypes) {
        Set<Id> progIds = new Set<Id>();
        List<Id> spIds = new List<Id>();
        for (Student_Programme__c sp: spList) {
            progIds.add(sp.Programme__c);
            spIds.add(sp.Id);
        }
        system.debug('##1'+progIds);
        system.debug('##2'+memberTypes);
        List<Student_Module__c> smList = [
            SELECT Id, Programme_Module__c, Programme_Module__r.Programme__c, Programme_Module__r.Module__r.VLE_ID__c,Student_Programme__c
            FROM Student_Module__c
            WHERE Programme_Module__r.Programme__c IN : progIds
            AND Programme_Module__r.Member_Type__c in :memberTypes
            AND Programme_Module__r.Module__c != null
            AND Programme_Module__r.Module__r.VLE_Visibility__c = true
            AND Student_Programme__c IN : spIds
        ];
        system.debug('##3'+spList );
        system.debug('##3'+smList );
     /*   Map<Id,List<Module__c>> progToModuleMap = new Map<Id,List<Module__c>>();
        for (Student_Module__c sm: smList) {
            List<Module__c> innerList = progToModuleMap.get(sm.Programme_Module__r.Programme__c); 
            if ( innerList == null ) {
                innerList = new List<Module__c>();
                progToModuleMap.put(sm.Programme_Module__r.Programme__c, innerList);
            }
            innerList.add(sm.Programme_Module__r.Module__r);
        }
        */

        Map<Id,List<Module__c>> progToModuleMap = new Map<Id,List<Module__c>>();
        for (Student_Module__c sm: smList) {
            List<Module__c> innerList = progToModuleMap.get(sm.Student_Programme__c); 
            if ( innerList == null ) {
                innerList = new List<Module__c>();
                progToModuleMap.put(sm.Student_Programme__c, innerList);
            }
            innerList.add(sm.Programme_Module__r.Module__r);
        }
        
        return progToModuleMap;
    }




    private static List<Student_Programme__c> findStudentProgrammesWithNewStage(List<Student_Programme__c> newList, Map<Id,Student_Programme__c> oldMap, String newStage) {
        List<Student_Programme__c> spList = new List<Student_Programme__c>();
        for (Student_Programme__c sp : newList) {
            if (sp.Stage__c == newStage && oldMap.get(sp.Id).Stage__c != newStage) {
                spList.add(sp);
            }
        }
        return spList;
    }

    /**
     * Single point to the all Student_Programme__c triggers
     */
    public static void onTrigger(List<Student_Programme__c> newList, List<Student_Programme__c> oldList, Map<Id,Student_Programme__c> newMap, Map<Id,Student_Programme__c> oldMap,
    Boolean isBefore, Boolean isAfter, Boolean isInsert, Boolean isUpdate, Boolean isDelete) {
        if (isAfter && isUpdate) {

            //This call creates the Mandatory Student Modules, if a Student Programme is updated as 'Accepted'
            //findAcceptedStudentProgrammesAndCreateMandatoryModules(newList);

            /* This call creates new user (save VLE ID in the Contact record) and sets user's role depending on Programme Type 
                value of related Programme Version. 
                assigns user to Course offering equals with specific role */     
            //findPreRegisteredStudentProgrammesByProgrammeType(newList, oldMap);
            
            findCompletedStudentProgrammes(newList, oldMap);
            
        }
    }

/*
    public static void findAcceptedStudentProgrammesAndCreateMandatoryModules(List<Student_Programme__c> newList) {
        List<Student_Programme__c> spList = new List<Student_Programme__c>();
        for (Student_Programme__c sp : newList) {
            if (sp.Stage__c == STAGE_ACCEPTED) {
                spList.add(sp);
            }
        }

        List<Student_Programme__c> spListToProcess = findStudentProgrammesDataWithPv(spList);

        if (! spList.isEmpty() ){
            Map<Id,List<Module__c>> progModules = findStudentModulesByProgramModuleMemberType(spList, new List<String>{TYPE_OPTIONAL});
            for (Student_Programme__c sp: spListToProcess) {
                // add action to create VLE student
                
                //ENROLE TO ORG-WIDE MODULES
                Set<Long> defaultOrgUnits = new Set<Long>( VleServices.studentOrgUnitIds );
                if ( VleServices.credentials.Enable_Programme_Homepage__c && sp.Programme__r.Homepage_VLE_ID__c != null ){
                    defaultOrgUnits.add( Long.valueOf( sp.Programme__r.Homepage_VLE_ID__c ) );  //Enroll to homepage
                }      
                System.debug( '>>> defaultOrgUnits >>> ' + defaultOrgUnits );

                VleCreateStudentWithRoleBySpAction vleAction = new VleCreateStudentWithRoleBySpAction();
                vleAction.sp = sp;
                vleAction.modules = progModules.get(sp.Programme__c);
                vleAction.defaultOrgUnits = defaultOrgUnits;
                VleSyncServices.addToQueue(vleAction, VleSyncServices.CREATE_VLE_STUDENT_WITH_ROLE_BY_SP_ACTION, sp.Student__r.Id);  
                
            }
            VleSyncServices.persistQueue(); // sync
        }
    }
*/

    @InvocableMethod
    public static List<Student_Programme__c> findPreRegisteredStudentProgrammesByProgrammeType(List<Student_Programme__c> newList) 
    {
        //List<Student_Programme__c> spList = findStudentProgrammesWithNewStage(newList, oldMap, STAGE_PRE_REGISTERED);
        List<Student_Programme__c> spListToProcess = findStudentProgrammesDataWithPv(newList);
        system.debug('##SP1'+newList );
        system.debug('##SP2'+spListToProcess);
        if (! spListToProcess.isEmpty() )
        {
            createMandatoryModules(spListToProcess);
        }

        Map<Id,List<Module__c>> progModules = findStudentModulesByProgramModuleMemberType(newList, new List<String>{TYPE_REQUIRED,TYPE_OPTIONAL});
        for (Student_Programme__c sp: spListToProcess) 
        {
            // add action to create VLE student
            
            //ENROLE TO ORG-WIDE MODULES
            Set<Long> defaultOrgUnits = new Set<Long>( VleServices.studentOrgUnitIds );
            if ( VleServices.credentials.Enable_Programme_Homepage__c != null && VleServices.credentials.Enable_Programme_Homepage__c && sp.Programme__r.Homepage_VLE_ID__c != null )
            {
                defaultOrgUnits.add( Long.valueOf( sp.Programme__r.Homepage_VLE_ID__c ) );  //Enroll to homepage
            }      
            
            System.debug( '>>> defaultOrgUnits >>> ' + defaultOrgUnits );

            VleCreateStudentWithRoleBySpAction vleAction = new VleCreateStudentWithRoleBySpAction();
            vleAction.sp = sp;
        //  vleAction.modules = progModules.get(sp.Programme__c);
            vleAction.modules = progModules.get(sp.Id);
            vleAction.defaultOrgUnits = defaultOrgUnits;
            VleSyncServices.addToQueue(vleAction, VleSyncServices.CREATE_VLE_STUDENT_WITH_ROLE_BY_SP_ACTION, sp.Student__r.Id);  
        }
        VleSyncServices.persistQueue(); // sync
        
        return spListToProcess;                
    }


    public static List<Student_Programme__c> findCompletedStudentProgrammes(List<Student_Programme__c> newList, Map<Id,Student_Programme__c> oldMap) 
    {
        List<Student_Programme__c> spList = findStudentProgrammesWithNewStage(newList, oldMap, STAGE_COMPLETED);
        List<Student_Programme__c> spListToProcess = findDTNStudentProgrammesData(spList);

        // add VLE actions
        for (Student_Programme__c sp: spListToProcess) 
        {
            VleSetStudentInactiveBySpAction vleAction = new VleSetStudentInactiveBySpAction();
            vleAction.sp = sp;
            VleSyncServices.addToQueue(vleAction, VleSyncServices.SET_STUDENT_INACTIVE_BY_SP_ACTION, sp.Student__r.Id);
        }
        VleSyncServices.persistQueue(); // sync
        
        return spListToProcess;
    }
    
    //2014-07-31 : CSL : This method will create all the necessary Student Modules for those Student Programmes that have beem 'Accepted' by the Student
    public static void createMandatoryModules(List<Student_Programme__c> inRecords)
    {
        system.debug('*** -- Into StudentProgrammeTriggerMethods.createMandatoryModules with ' + inRecords.size() + ' -- ***');
        Set<Id> progIds = new Set<Id>();
        Set<Id> studentProgIds = new Set<Id>();
        Map<String, Student_Module__c> currentModules = new Map<String, Student_Module__c>();
        List<Student_Module__c> newStudentModules = new List<Student_Module__c>();
        
        for (Student_Programme__c sp : inRecords)
        {
            progIds.add(sp.Programme__c);
            studentProgIds.add(sp.Id);
        }
        
        System.debug('>>> progIds >>>' + progIds);
        System.debug('>>> studentProgIds>>>' + studentProgIds);
        //We need to make sure we don't create Student Modules that already exist
        for (Student_Module__c sm : [Select s.Student_Programme__c, s.Programme_Module__c, s.Id From Student_Module__c s where s.Student_Programme__c in :studentProgIds])
        {
            String smKey = sm.Student_Programme__c + '~' + sm.Programme_Module__c;
            system.debug('*** -- smKey = ' + smKey + ' -- ***');
            currentModules.put(smKey, sm);
        }
        
        Map<Id, Programme__c> progMap = new Map<Id, Programme__c>([Select (Select Id, Name From Programme_Modules__r where Member_Type__c = :TYPE_REQUIRED) From Programme__c p where p.Id in :progIds]);
              
        System.debug('>>> progMap  >>>' + progMap );
        for (Student_Programme__c sp : inRecords)
        {
            Programme__c prog = progMap.get(sp.Programme__c);
            
            if (prog != null)
            {
                for (Programme_Module__c pm : prog.Programme_Modules__r)
                {
                    String smKey = sp.Id + '~' + pm.Id;
                    Student_Module__c sm = currentModules.get(smKey);                   
                    if (sm == null)
                    {
                        system.debug('*** -- Creating new Module -- ***');
                        Student_Module__c newSM = new Student_Module__c();
                        newSM.Name = pm.Name + ' Student Module';
                        newSM.Student__c = sp.Student__c;
                        newSM.Student_Programme__c = sp.Id;
                        newSM.Programme_Module__c = pm.Id;
                        newStudentModules.add(newSM);
                    }
                }
            }
        }
        
        if (newStudentModules.size() > 0)
        {
            system.debug('*** -- About to insert ' + newStudentModules.size() + ' new Student Modules -- ***');
            insert newStudentModules;
        }
    }
    
}