objects/Contact.object
<CustomObject><fields>
        <fullName>VLE_ID__c</fullName>
        <description>UserId for desire2learn API</description>
        <label>VLE_ID</label>
        <length>32</length>
        <type>Text</type>
    </fields><fields>
        <fullName>VLE_Visibility__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VLE_Visibility</label>
        <type>Checkbox</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Module__c.object
<CustomObject><fields>
        <fullName>VLE_ID__c</fullName>
        <description>Course offering ID at VLE side</description>
        <label>VLE ID</label>
        <length>32</length>
        <type>Text</type>
    </fields><fields>
        <fullName>VLE_Visibility__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To prevent some records triggering actions in VLE</description>
        <inlineHelpText>To prevent some records triggering actions in VLE</inlineHelpText>
        <label>VLE Visibility</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Instances of Modules</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module</label><nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Modules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Module_Role__c.object
<CustomObject><fields>
        <fullName>Module_Role__c</fullName>
        <description>Defines role for Module Spec, and against Module Instance for VLE integration</description>
        <label>Module Role</label>
        <picklist>
            <picklistValues>
                <fullName>Module Convenor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Module Moderator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Examiner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Teacher</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Staff with Roles</relationshipLabel>
        <relationshipName>Module_Roles</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Staff__c</fullName>
        <label>Staff</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Staff</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Module Roles</relationshipLabel>
        <relationshipName>Module_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Join object between Staff (Contacts) and Modules (both Instances and Version objects). Will allow definition of staff role on a module and be used in VLE integration to define extent of staff enrolment.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Module Role</label><nameField>
        <displayFormat>MR-{00000000}</displayFormat>
        <label>Module Role Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Module Roles</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/ModuleRoleServices.cls
public with sharing class ModuleRoleServices {

    // ModuleRole constants
    public static final String MODULE_CONVENOR_ROLE_NAME =	'Module Convenor';
    public static final String MODULE_MODERATOR_ROLE_NAME =	'Module Moderator';
    public static final String TEACHING_ROLE_NAME =			'Teaching';
    public static final String EXT_EXAMINER_ROLE_NAME =		'External Examiner';
    
    /**
     * Get list of Module_Role__c with VLE_Visibility__c equals to true
     * @param newList List of Module_Role__c
     * return List of valid records
     */
    private static List<Module_Role__c> findRolesWithVisibleContacts(List<Module_Role__c> newList) {
        return [SELECT Id FROM Module_Role__c WHERE Staff__r.VLE_Visibility__c = true AND Id IN :newList];
    }
    
    /**
     * Add sync action for certain type of Mode_Role__c modification (insert, update or delete)
     * @param mrList List of module roles
     * @param actionType Mode of action
     */
    private static void syncToVLE(List<Module_Role__c> mrList, String actionType) {
    	if ( !mrList.isEmpty() ) {
	    	// add actions
    		for (Module_Role__c mr: VleDaoServices.findModuleRolesData(mrList)) {
    			if ( !String.isBlank(mr.Module__r.VLE_ID__c) ) {
	    			VleStaffRoleAction staffRoleAction = new VleStaffRoleAction();
	    			staffRoleAction.actionType = actionType;
	    			staffRoleAction.moduleRole = mr;
	    			VleSyncServices.addToQueue(staffRoleAction, VleSyncServices.VLE_STAFF_ROLE_ACTION, mr.Id);
    			}
    		}
    		VleSyncServices.persistQueue(); // sync
    	}
    }

    /**
     * Single point to the all Module_Role__c triggers
     */
    public static void onTrigger(List<Module_Role__c> newList, List<Module_Role__c> oldList, Map<Id,Module_Role__c> newMap, Map<Id,Module_Role__c> oldMap,
    		Boolean isBefore, Boolean isAfter, Boolean isInsert, Boolean isUpdate, Boolean isDelete) {
        if (isBefore) {
            if (isDelete) {
                findDeletedRolesWithVisibleContacts(oldList);
            }
        }
        if (isAfter) {
            if (isInsert) {
                findInsertedRolesWithVisibleContacts(newList);
            }
            if (isUpdate) {
                findUpdatedRolesWithVisibleContacts(newList, oldMap);
            }
        }
    }

    public static List<Module_Role__c> findDeletedRolesWithVisibleContacts(List<Module_Role__c> oldList) {
        List<Module_Role__c> mrList = findRolesWithVisibleContacts(oldList);
        syncToVLE(mrList, VleStaffRoleAction.DELETE_ACTION_TYPE);
        return mrList;
    }

    public static List<Module_Role__c> findInsertedRolesWithVisibleContacts(List<Module_Role__c> newList) {
    	List<Module_Role__c> mrList = findRolesWithVisibleContacts(newList);
    	syncToVLE(mrList, VleStaffRoleAction.INSERT_ACTION_TYPE);
        return mrList;
    }

    public static List<Module_Role__c> findUpdatedRolesWithVisibleContacts(List<Module_Role__c> newList, Map<Id,Module_Role__c> oldMap) {
        List<Module_Role__c> mrs = new List<Module_Role__c>();
        for (Module_Role__c mr : newList) {
            if (mr.Module_Role__c != oldMap.get(mr.Id).Module_Role__c) {
                mrs.add(mr);
            }
        }
        
        List<Module_Role__c> mrList = findRolesWithVisibleContacts(mrs);
        syncToVLE(mrList, VleStaffRoleAction.UPDATE_ACTION_TYPE);
        return mrList;
    }
    
}