objects/Contact.object
<CustomObject><fields>
        <fullName>VLE_Visibility__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VLE_Visibility</label>
        <type>Checkbox</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel><recordTypes>
        <fullName>Staff</fullName>
        <active>true</active>
        <label>Staff</label>
    </recordTypes></CustomObject>

objects/Module_Role__c.object
<CustomObject><fields>
        <fullName>Module_Role__c</fullName>
        <description>Defines role for Module Spec, and against Module Instance for VLE integration</description>
        <label>Module Role</label>
        <picklist>
            <picklistValues>
                <fullName>Module Convenor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Module Moderator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Examiner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Teacher</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Staff__c</fullName>
        <label>Staff</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Staff</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Module Roles</relationshipLabel>
        <relationshipName>Module_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Join object between Staff (Contacts) and Modules (both Instances and Version objects). Will allow definition of staff role on a module and be used in VLE integration to define extent of staff enrolment.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Module Role</label><nameField>
        <displayFormat>MR-{00000000}</displayFormat>
        <label>Module Role Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Module Roles</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/VLE__c.object
<CustomObject><fields>
        <fullName>API_Host__c</fullName>
        <description>Domain name of API host</description>
        <label>API Host</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>App_ID__c</fullName>
        <description>App ID from desire2learn</description>
        <label>App ID</label>
        <length>22</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>App_Key__c</fullName>
        <description>App Key for desire2learn (secret)</description>
        <label>App Key</label>
        <length>22</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>Default_Staff_Role_VLE_ID__c</fullName>
        <description>If Module Role has no matches for VLE Role Id - this value is used as default for Staff</description>
        <inlineHelpText>If Module Role has no matches for VLE Role Id - this value is used as default for Staff</inlineHelpText>
        <label>Default Staff Role VLE ID</label>
        <length>10</length>
        <type>Text</type>
    </fields><customSettingsType>List</customSettingsType><description>Credentials for VLE external service</description><enableFeeds>false</enableFeeds><label>VLE parameters</label><visibility>Protected</visibility></CustomObject>

classes/TestContactServices.cls
@isTest
private class TestContactServices {
    
    @testSetup
    public static void setup() {
        VLE__c vle = new VLE__c();
        vle.Name = 'main';
        vle.Default_Staff_Role_VLE_ID__c = '102';
        vle.API_Host__c = '2lstmedtest.desire2learn.com';
        vle.App_ID__c = '2BqFg3qrSd26I';
        vle.App_Key__c = '2MWXZLyA2xo4I';
        insert vle;
    }
    
    
    static testMethod void testOnTriggerPositive() {
        Contact c = VleTestingUtils.createStudent(false);
        c.RecordTypeId = CommonUtils.findRecordTypeIdByDev('Contact', 'Staff');
        c.VLE_Visibility__c = false;
        
        insert c;
        Module_Role__c mr = new Module_Role__c(
            Staff__c = c.Id, Module_Role__c = 'Test role'
        );
        insert mr;
        c.VLE_Visibility__c = true;
        update c;
        List<Contact> cNewList = new List<Contact>{c};
        Contact cOld = c.clone(true, true, true, true);
        cOld.VLE_Visibility__c = false;
        List<Contact> cOldList = new List<Contact>{cOld};
        Map<Id, Contact> cOldMap = new Map <Id, Contact>(cOldList);

        Test.startTest();
            List<Module_Role__c> mrList = ContactServices.findVLEVisibleModuleRoles(cNewList,cOldMap);
        Test.stopTest();

        System.assertEquals(1, mrList.size());
    }

    static testMethod void testFindVLEVisibleModuleRolesZero() {
        Contact c = VleTestingUtils.createStudent(false);
        c.RecordTypeId = CommonUtils.findRecordTypeIdByDev('Contact', 'Staff');
        c.VLE_Visibility__c = false;
        insert c;
        Module_Role__c mr = new Module_Role__c(
            Staff__c = c.Id, Module_Role__c = 'Test role'
        );
        insert mr;
        List<Contact> cNewList = new List<Contact>{c};
        Contact cOld = c.clone(true, true, true, true);
        cOld.VLE_Visibility__c = false;
        List<Contact> cOldList = new List<Contact>{cOld};
        Map<Id, Contact> cOldMap = new Map <Id, Contact>(cOldList);

        Test.startTest();
            List<Module_Role__c> mrList = ContactServices.findVLEVisibleModuleRoles(cNewList,cOldMap);
        Test.stopTest();

        System.assertEquals(0, mrList.size());
    }

    static testMethod void testFindVLENotVisibleModuleRoles() {
        Contact c = VleTestingUtils.createStudent(false);
        c.RecordTypeId = CommonUtils.findRecordTypeIdByDev('Contact', 'Staff');
        c.VLE_Visibility__c = false;
        insert c;
        Module_Role__c mr = new Module_Role__c(
            Staff__c = c.Id, Module_Role__c = 'Test role'
        );
        insert mr;
        List<Contact> cNewList = new List<Contact>{c};
        Contact cOld = c.clone(true, true, true, true);
        cOld.VLE_Visibility__c = true;
        List<Contact> cOldList = new List<Contact>{cOld};
        Map<Id, Contact> cOldMap = new Map <Id, Contact>(cOldList);

        Test.startTest();
            List<Contact> cList = ContactServices.findVLENotVisibleContacts(cNewList,cOldMap);
        Test.stopTest();

        System.assertEquals(1, cList.size());
    }

    static testMethod void testFindVLENotVisibleModuleRolesZero() {
        Contact c = VleTestingUtils.createStudent(false);
        c.RecordTypeId = CommonUtils.findRecordTypeIdByDev('Contact', 'Staff');
        c.VLE_Visibility__c = false;
        insert c;
        Module_Role__c mr = new Module_Role__c(
            Staff__c = c.Id, Module_Role__c = 'Test role'
        );
        insert mr;
        List<Contact> cNewList = new List<Contact>{c};
        Contact cOld = c.clone(true, true, true, true);
        cOld.VLE_Visibility__c = false;
        List<Contact> cOldList = new List<Contact>{cOld};
        Map<Id, Contact> cOldMap = new Map <Id, Contact>(cOldList);

        Test.startTest();
            List<Contact> cList = ContactServices.findVLENotVisibleContacts(cNewList,cOldMap);
        Test.stopTest();

        System.assertEquals(0, cList.size());
    }


}