objects/Contact.object
<CustomObject><fields>
        <fullName>EU_Citizen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>X EU Citizen</label>
        <type>Checkbox</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Programme__c.object
<CustomObject><fields>
        <fullName>End_Date__c</fullName>
        <description>Last Date module is valid</description>
        <label>End Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Fee_TBC__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Used in applications portal search results; indicates that fees are To Be Confirmed. Use previous years fees in Home/EU and Overseas fields for internal reporting of applications pipeline value</inlineHelpText>
        <label>Fee TBC</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Home_EU_Fee__c</fullName>
        <inlineHelpText>Fee for UK and rest of EU students; if 'Fee TBC' is checked this amount is an estimate for reporting</inlineHelpText>
        <label>Home EU Fee</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Overseas_Fee__c</fullName>
        <inlineHelpText>Fees for students outside of EU; if 'Fee TBC' is checked this amount is an estimate for reporting</inlineHelpText>
        <label>Overseas Fee</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/ProgrammeWrapper.cls
/**
 * Wrapper class for Programme__c object
 */
public class ProgrammeWrapper {
    public String combinedDates {
        get {
            String dateString = '';
            String dateDay = '';
            String dateEndDay = '';
            String dateMonth = '';
            String dateEndMonth = '';
            String dateYear = '';
            String dateEndYear = '';
            Date startDate = programme.Start_Date__c;
            Date endDate = programme.End_Date__c;
            if(startDate != null) {
                dateDay = String.valueOf(startDate.day());
                dateMonth = String.valueOf(Datetime.newInstance(startDate.year(), startDate.month(), startDate.day()).format('MMMM'));
                dateYear = String.valueOf(startDate.year());
            }
            if(endDate != null) {
                dateEndDay = String.valueOf(endDate.day());
                dateEndMonth = String.valueOf(Datetime.newInstance(endDate.year(), endDate.month(), endDate.day()).format('MMMM'));
                dateEndYear = String.valueOf(endDate.year());
            }
            if(startDate != null && endDate != null) {
                if (startDate.year() == endDate.year()) {
                    if(startDate.month() == endDate.month()) {
                        if (startDate.day() != endDate.day()) 
                            dateDay = String.valueOf(startDate.day() + ' - ' + endDate.day());
                        dateString = dateDay + ' ' + dateMonth + ' ' + dateYear;
                    }
                    else {
                        dateString = dateDay + ' ' + dateMonth + ' - ' + dateEndDay + ' ' + dateEndMonth + ' ' + dateYear;
                    }
                }
                else {
                    dateString = dateDay + ' ' + dateMonth + ' ' + dateYear + ' - ' + dateEndDay + ' ' + dateEndMonth + ' ' + dateEndYear;
                }
            }
            else {
                if(startDate != null) {
                    dateString = 'From ' + dateDay + ' ' + dateMonth + ' ' + dateYear;
                }
                else if(endDate != null) {
                    dateString = 'Till ' + dateEndDay + ' ' + dateEndMonth + ' ' + dateEndYear;
                }
                else return '';
            }
            return dateString;
        }
    }
    //2014-08-13 : CSL : Client now wants to show both Home Fee and Overseas Fee, so two new methods will be added 
    //so the current 'fee' method is left untouched
    
    public Decimal displayFee {
        get {
            return programme.Home_EU_Fee__c;
        }
    }
    
    public Decimal displayOverseasFee {
        get {
            return programme.Overseas_Fee__c;
        }
    }
    
    public boolean displayTBC {
        get {
            return programme.Fee_TBC__c;
        }
    }
    
    public Decimal fee {
        get {
            if (usr.Contact != null && usr.Contact.EU_Citizen__c == true) {
                return programme.Home_EU_Fee__c;
            }
            return programme.Overseas_Fee__c;
        }
    }
    public Programme__c programme { get; private set;}
    
    @TestVisible
    private static User usr {
        get {
            if(usr == null) {
                usr = [SELECT Id, Contact.EU_Citizen__c FROM User WHERE Id = :UserInfo.getUserId()];
            }
            return usr;
        }
        set;
    }
    public ProgrammeWrapper(Programme__c programme) {
        this.programme = programme;
    }
}