objects/Contact.object
<CustomObject><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Hidden field for Test Class use, to exclude from Flows</description>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>VLE_ID__c</fullName>
        <description>UserId for desire2learn API</description>
        <label>VLE_ID</label>
        <length>32</length>
        <type>Text</type>
    </fields><fields>
        <fullName>VLE_Visibility__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VLE_Visibility</label>
        <type>Checkbox</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel><recordTypes>
        <fullName>Staff</fullName>
        <active>true</active>
        <label>Staff</label>
    </recordTypes></CustomObject>

objects/Module__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Instance_Suffix__c</fullName>
        <label>Instance Suffix</label>
        <length>20</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>VLE_ID__c</fullName>
        <description>Course offering ID at VLE side</description>
        <label>VLE ID</label>
        <length>32</length>
        <type>Text</type>
    </fields><fields>
        <fullName>VLE_Visibility__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To prevent some records triggering actions in VLE</description>
        <inlineHelpText>To prevent some records triggering actions in VLE</inlineHelpText>
        <label>VLE Visibility</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Instances of Modules</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module</label><nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Modules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Module_Role__c.object
<CustomObject><fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Staff with Roles</relationshipLabel>
        <relationshipName>Module_Roles</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Join object between Staff (Contacts) and Modules (both Instances and Version objects). Will allow definition of staff role on a module and be used in VLE integration to define extent of staff enrolment.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Module Role</label><nameField>
        <displayFormat>MR-{00000000}</displayFormat>
        <label>Module Role Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Module Roles</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Programme__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used for lookup from Student processes</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Code__c</fullName>
        <formula>Programme_Version__r.Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Taken from Version level</inlineHelpText>
        <label>Code</label>
        <type>Text</type>
    </fields><fields>
        <fullName>End_Date__c</fullName>
        <description>Last Date module is valid</description>
        <label>End Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Home_EU_Fee__c</fullName>
        <inlineHelpText>Fee for UK and rest of EU students; if 'Fee TBC' is checked this amount is an estimate for reporting</inlineHelpText>
        <label>Home EU Fee</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Instance_Suffix__c</fullName>
        <label>Instance Suffix</label>
        <length>20</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Overseas_Fee__c</fullName>
        <inlineHelpText>Fees for students outside of EU; if 'Fee TBC' is checked this amount is an estimate for reporting</inlineHelpText>
        <label>Overseas Fee</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Programme_Type__c</fullName>
        <description>DO NOT USE, to be deleted</description>
        <label>X Programme Type</label>
        <picklist>
            <picklistValues>
                <fullName>MSc Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Diploma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSc Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Course</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme Version</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Programme_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Versions, Versions, Specification, Versions - Pre Approved, Specification Edit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Programme Instances</relationshipLabel>
        <relationshipName>Programmes_Instances</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme_Version__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Code__c</fullName>
        <inlineHelpText>Internal LSTM programme code</inlineHelpText>
        <label>Code</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Home_EU_Fee__c</fullName>
        <label>Home EU Fee</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Master_Link__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To allow two levels of versions - master or senior, and child versions. Will provide external systems with a persistent ID across all Programmes and Programme Versions of same group</description>
        <label>Master Link</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Record must be a master</errorMessage>
            <filterItems>
                <field>Programme_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Master Version</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Child Programme Versions</relationshipLabel>
        <relationshipName>Programme_Versions</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Overseas_Fee__c</fullName>
        <label>Overseas Fee</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Programme_Type__c</fullName>
        <label>Programme Type</label>
        <picklist>
            <picklistValues>
                <fullName>MSc Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Diploma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Masters Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG Cert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Course</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Date of first Intake</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme Version</label><nameField>
        <label>Programme Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programme Versions</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>End_Date__c</fullName>
        <description>For PGR HESA return</description>
        <inlineHelpText>Use where Student Programme End Date is not the same as Programme End Date (eg. PGR, DipUKMP)</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Programme_Type__c</fullName>
        <formula>TEXT(  Programme__r.Programme_Version__r.Programme_Type__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Programme Type</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Programme must be active (i.e. most recent)</errorMessage>
            <filterItems>
                <field>Programme__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Student Programmes</relationshipLabel>
        <relationshipName>Students_on_Programme1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Stage__c</fullName>
        <description>NOTE : This field drives the Student Programme flow - DO NOT change pick list values without discussion with the I.T / Dev Team</description>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Checked</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional</fullName>
                <color>#339999</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unconditional</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
                <color>#FF99FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Expected</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Registered</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
                <color>#419249</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#666666</color>
            </picklistValues>
            <picklistValues>
                <fullName>Offered</fullName>
                <color>#DDDDDD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reverted from Master:Detail as per LSTM requirement</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Programmes</relationshipLabel>
        <relationshipName>Student_Programmes1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/VleTestingUtils.cls
/** 
 * Helper class for testing VLE integration
 */
public with sharing class VleTestingUtils {
    
    // Test constants
    public static final String STUDENT_LAST_NAME = 'Doe';
    public static final String PROGRAMME_VERSION_CODE = 'ABC';
    public static final String PROGRAMME_INSTANCE_SUFFIX = '1234';
    public static final Integer PROGRAMME_HOME_EU_FEE = 1000;
    public static final Integer PROGRAMME_OVERSEAS_FEE = 1250;
    public static final String STUDENT_EMAIL = 'student@mail.com';
    
    /**
     * Create Contact as Student
     * @param doInsert If true DML will be performed
     * @return Just created Contact
     */
    public static Contact createStudent(Boolean doInsert) {
        Contact st = new Contact(LastName = STUDENT_LAST_NAME, Email = STUDENT_EMAIL);
        if ( doInsert ) insert st;
        return st;
    }
    
    /**
     * Create Contact as Staff person
     * @param doInsert If true DML will be performed
     * @return Just created Contact
     */
    public static Contact createStaff(Boolean doInsert) {
        Contact st = new Contact(LastName = STUDENT_LAST_NAME, RecordTypeId = CommonUtils.findRecordTypeIdByDev('Contact', 'Staff'));
        if ( doInsert ) insert st;
        return st;
    }
    
    /**
     * This method creates a new master Programme_Version__c object
     * @param String pvName Created programme version name
     * @param Id rtId Created programme version record type id
     * @param String pvType Created programme version type
     * @param Boolean doInsert Flag indicates that results will be inserted in database immediately
     * @return Programme_Version__c programmeVersion
     */
    public static Programme_Version__c createMasterProgrammeVersion(String pvName, Id rtId, String pvType, Boolean doInsert) {
        Programme_Version__c programmeVersion = (Programme_Version__c)Programme_Version__c.sObjectType.newSobject(null, true);
        programmeVersion.Name = pvName;
        programmeVersion.Programme_Type__c = pvType;
        programmeVersion.RecordTypeId = rtId;
        programmeVersion.Code__c = PROGRAMME_VERSION_CODE;
        if(doInsert) insert programmeVersion;
        return programmeVersion;
    }
    
    /**
     * This method creates a new child Programme_Version__c object
     * @param String pvName Created programme version name
     * @param Id rtId Created programme version record type id
     * @param String pvType Created programme version type
     * @param Id masterLinkId Created programme version master link
     * @param Boolean doInsert Flag indicates that results will be inserted in database immediately
     * @return Programme_Version__c programmeVersion
     */
    public static Programme_Version__c createProgrammeVersion(String pvName, Id rtId, String pvType, Id masterLinkId, Boolean doInsert) {
        Programme_Version__c programmeVersion = (Programme_Version__c)Programme_Version__c.sObjectType.newSobject(null, true);
        programmeVersion.Name = pvName;
        programmeVersion.Programme_Type__c = pvType;
        programmeVersion.RecordTypeId = rtId;
        programmeVersion.Code__c = PROGRAMME_VERSION_CODE;
        programmeVersion.Master_Link__c = masterLinkId;
        if(doInsert) insert programmeVersion;
        return programmeVersion;
    }
    
    /**
     * This method creates a new Programme__c object
     * @param String pName Created programme name
     * @param Id versionId Created programme vresion Id
     * @param Boolean doInsert Flag indicates that programme will be inserted in database immediately
     * @return Programme__c programme
     */
    public static Programme__c createProgramme(String pName, Id versionId, Boolean doInsert) {
        Programme__c programme = (Programme__c)Programme__c.sObjectType.newSobject(null, true);
        programme.Name = pName;
        programme.Programme_Version__c = versionId;
        programme.Active__c = true;
        programme.Start_Date__c = Date.today().toStartOfMonth().addYears(1);
        programme.End_Date__c = Date.today().toStartOfMonth().addYears(3);
        programme.Home_EU_Fee__c = PROGRAMME_HOME_EU_FEE;
        programme.Overseas_Fee__c = PROGRAMME_OVERSEAS_FEE;
        programme.Instance_Suffix__c = PROGRAMME_INSTANCE_SUFFIX;
        programme.Test_Class_Record__c = True ;
        if(doInsert) insert programme;
        return programme;
    }
    
    /**
     * Create Module__c record
     * @param doInsert If true DML will be performed
     * @return Module__c
     */
    public static Module__c createModule(String name, String vleId, Boolean doInsert) {
        Boolean isVleVisible = !String.isBlank(vleId);
        Module__c m = new Module__c(Active__c = true, Name = name, VLE_ID__c = vleId, VLE_Visibility__c = isVleVisible, Test_Class_Record__c = true);
        if ( doInsert ) insert m;
        return m;
    }
    
    /**
     * Create Student Programme
     * @param rogrammeId ID of programme
     * @param studentId ID of Contact
     * @param doInsert If true DML will be performed
     * @return Just created Student programme
     */
    public static Student_Programme__c createStudentProgramme(Id programmeId, Id studentId, Boolean doInsert) {
        Student_Programme__c sp = new Student_Programme__c(
            Programme__c = programmeId, Student__c = studentId, Name = ApplyServices.DUMMY_REQUIRED_STRING,
            Stage__c = ApplyServices.COURSE_INIT_STAGE_NAME,Test_Class_Record__c = True
        );
        if ( doInsert ) {
            insert sp;
        }
        return sp;
    }
    
    /**
     * Create junction object Module_Role__c
     * @param c Staff person
     * @param m Module
     * @param roleName Value for Module_Role__c field
     * @return Record
     */
    public static Module_Role__c createModuleRole(Contact c, Module__c m, String roleName, Boolean doInsert) {
        Module_Role__c mr = new Module_Role__c(
            Staff__c = c.Id, Module__c = m.Id, Module_Role__c = roleName
        );
        if ( doInsert ) insert mr;
        return mr;
    }

}