objects/Contact.object
<CustomObject><fields>
        <fullName>VLE_ID__c</fullName>
        <description>UserId for desire2learn API</description>
        <label>VLE_ID</label>
        <length>32</length>
        <type>Text</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Module__c.object
<CustomObject><fields>
        <fullName>VLE_ID__c</fullName>
        <description>Course offering ID at VLE side</description>
        <label>VLE ID</label>
        <length>32</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Instances of Modules</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module</label><nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Modules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Module_Role__c.object
<CustomObject><fields>
        <fullName>Module_Role__c</fullName>
        <description>Defines role for Module Spec, and against Module Instance for VLE integration</description>
        <label>Module Role</label>
        <picklist>
            <picklistValues>
                <fullName>Module Convenor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Module Moderator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Examiner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Teacher</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Staff with Roles</relationshipLabel>
        <relationshipName>Module_Roles</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Staff__c</fullName>
        <label>Staff</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Staff</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Module Roles</relationshipLabel>
        <relationshipName>Module_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Join object between Staff (Contacts) and Modules (both Instances and Version objects). Will allow definition of staff role on a module and be used in VLE integration to define extent of staff enrolment.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Module Role</label><nameField>
        <displayFormat>MR-{00000000}</displayFormat>
        <label>Module Role Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Module Roles</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/VLE_Action__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Object for perform complex action to VLE API</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>VLE Action</label><nameField>
        <label>VLE Action Name</label>
        <type>Text</type>
    </nameField><pluralLabel>VLE Actions</pluralLabel><sharingModel>Private</sharingModel></CustomObject>

objects/VLE_Sync_Command__c.object
<CustomObject><fields>
        <fullName>Command__c</fullName>
        <description>Type of command</description>
        <label>Command</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>Params__c</fullName>
        <description>Additional parameters for command in the JSON format</description>
        <label>Params</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>VLE_Action__c</fullName>
        <label>VLE Action</label>
        <referenceTo>VLE_Action__c</referenceTo>
        <relationshipLabel>VLE Sync Commands</relationshipLabel>
        <relationshipName>VLE_Sync_Commands</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Simple VLE API calls to perform only single API methods</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>false</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>VLE Sync Command</label><nameField>
        <label>VLE Sync Command Name</label>
        <type>Text</type>
    </nameField><pluralLabel>VLE Sync Commands</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/VleStaffRoleAction.cls
/**
 * Complex action to modify enrollments accordingly to changes in Module_Role__c object
 */
public with sharing class VleStaffRoleAction extends VleBaseAction {
    
    // Action types
    public static final String INSERT_ACTION_TYPE = 'insert';
    public static final String UPDATE_ACTION_TYPE = 'update';
    public static final String DELETE_ACTION_TYPE = 'delete'; 

    /**
     * Module_Role__c object related to the action
     */
    public Module_Role__c moduleRole { get; set; }
    
    /**
     * Type of action
     */
    public String actionType { get; set; }
    
    /**
     * Add command of creating new enrollments to current ActionStructure
     * @param aStruct Structure of action
     */
    private void addCreateEnrollCommand(VleSyncServices.ActionStructure aStruct) {
        List<Long> roleIds = VleServices.staffRoles.get(moduleRole.Module_Role__c) != null 
            ? VleServices.staffRoles.get(moduleRole.Module_Role__c) 
            : new List<Long> { Long.valueOf( VleServices.credentials.Default_Staff_Role_VLE_ID__c ) };
            
        if ( roleIds != null ) {
            for (Long roleId: roleIds) {
                VleCommands.EnrollmentParams enrParams = new VleCommands.EnrollmentParams();
                enrParams.roleId = roleId;
                Vle_Sync_Command__c cmd = VleSyncServices.createCommand(
                    VleSyncServices.CREATE_ENROLL_COMMAND, moduleRole.Id, aStruct.getDetailCommands().size()+1,
                    VleSyncServices.OBJ_TYPE_MODULE_ROLE, JSON.serialize(enrParams)
                );
                aStruct.getDetailCommands().add(cmd);
            }
        }
    }
    
    /**
     * Add command of deleting enrollments to current ActionStructure
     * @param aStruct Structure of action
     */
    private void addDeleteEnrollCommand(VleSyncServices.ActionStructure aStruct) {
        VleCommands.EnrollmentParams enrParams = new VleCommands.EnrollmentParams();
        enrParams.userSourceId = moduleRole.Staff__c;
        Vle_Sync_Command__c cmd = VleSyncServices.createCommand(
            VleSyncServices.DELETE_ENROLL_COMMAND, moduleRole.Module__c, aStruct.getDetailCommands().size()+1,
            VleSyncServices.OBJ_TYPE_MODULE, JSON.serialize(enrParams)
        );
        aStruct.getDetailCommands().add(cmd);
    }
    
    @TestVisible
    protected override Boolean findActionData(VLE_Action__c action) {
        moduleRole = VleDaoServices.findModuleRoleData(action.Name);
        return moduleRole != null;
    }
    
    @TestVisible
    protected override VleSyncServices.ICommand findCommand(VLE_Sync_Command__c cmd) {
        VleSyncServices.ICommand cmdImpl;

        if ( cmd.Command__c == VleSyncServices.WAIT_VLE_ID_COMMAND ) {
            VleCommands.WaitForVleId waitCmd = new VleCommands.WaitForVleId();
            waitCmd.objName = VleSyncServices.OBJ_TYPE_CONTACT;
            waitCmd.recordId = cmd.Name; // ID of contact
            cmdImpl = waitCmd;
        } else if ( cmd.Command__c == VleSyncServices.CREATE_ENROLL_COMMAND && moduleRole != null ) {
            VleCommands.CreateEnrollment enrollCmd = new VleCommands.CreateEnrollment();
            enrollCmd.cont = moduleRole.Staff__r;
            enrollCmd.orgUnitId = ( String.isBlank(moduleRole.Module__r.VLE_ID__c) ) ? null : Long.valueOf(moduleRole.Module__r.VLE_ID__c);
            cmdImpl = enrollCmd;
        } else if ( cmd.Command__c == VleSyncServices.DELETE_ENROLL_COMMAND ) {
            VleCommands.DeleteEnrollment enrollCmd = new VleCommands.DeleteEnrollment();
            Module__c module = VleDaoServices.findProgrammeModules(new Set<Id>{ cmd.Name })[0];
            enrollCmd.orgUnitId = module.VLE_ID__c;
            VleCommands.EnrollmentParams enrParams = (VleCommands.EnrollmentParams) JSON.deserialize(cmd.Params__c, VleCommands.EnrollmentParams.class);
            enrollCmd.cont = VleDaoServices.findContact(enrParams.userSourceId);
            cmdImpl = enrollCmd;
        }

        return cmdImpl;
    }
    
    public VleSyncServices.ActionStructure create() {
        VleSyncServices.ActionStructure aStruct = new VleSyncServices.ActionStructure();
        aStruct.masterAction = VleSyncServices.createAction(
            VleSyncServices.VLE_STAFF_ROLE_ACTION, moduleRole.Id, VleSyncServices.ACTION_NEW_STATUS
        );
        
        // check VLE_ID__c field on Contact
        Vle_Sync_Command__c cmd = VleSyncServices.createCommand(
            VleSyncServices.WAIT_VLE_ID_COMMAND, moduleRole.Staff__c, 1,
            VleSyncServices.OBJ_TYPE_CONTACT, null
        );
        aStruct.getDetailCommands().add(cmd);
        
        // enrollments by type of action
        if ( actionType == INSERT_ACTION_TYPE ) {
            addCreateEnrollCommand(aStruct);
        } else if ( actionType == UPDATE_ACTION_TYPE ) {
            addDeleteEnrollCommand(aStruct);
            addCreateEnrollCommand(aStruct);
        } else if ( actionType == DELETE_ACTION_TYPE ) {
            addDeleteEnrollCommand(aStruct);
        }
        
        return aStruct;         
    }
    
}