objects/Contact.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel><recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <label>Other</label>
    </recordTypes></CustomObject>

objects/Module__c.object
<CustomObject><fields>
        <fullName>Credits__c</fullName>
        <label>Credits</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Module_Reference__c</fullName>
        <description>LSTM reference for each course</description>
        <inlineHelpText>LSTM reference for each course</inlineHelpText>
        <label>Module Reference</label>
        <length>50</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Instances of Modules</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module</label><nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Modules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme_Module__c.object
<CustomObject><fields>
        <fullName>Member_Type__c</fullName>
        <inlineHelpText>Whether Module is Required, Optional or Alternative; Solus is used to denote where a Programme only had a single Module.</inlineHelpText>
        <label>Member Type</label>
        <picklist>
            <picklistValues>
                <fullName>Required</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Optional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specials</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Module_Credits__c</fullName>
        <formula>Module__r.Credits__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Always taken from Module level</inlineHelpText>
        <label>Module Credits</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Module_Reference__c</fullName>
        <formula>Module__r.Module_Reference__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Module Reference</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To find correct Module type first the few character of Module title then click magnifying glass for available options</inlineHelpText>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Assigned Programmes</relationshipLabel>
        <relationshipName>Programme_Modules</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Programme__c</fullName>
        <description>Via Master-Detail relationship, no reparenting allowed</description>
        <label>Programme</label>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Assigned Modules</relationshipLabel>
        <relationshipName>Programme_Modules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Many to many object, to allow one Module (instance) to be a member of multiple Programmes (instances)</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Programme Module</label><nameField>
        <displayFormat>PMI-{00000000}</displayFormat>
        <label>Programme Module</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Programme Modules</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Student_Module__c.object
<CustomObject><fields>
        <fullName>Credits__c</fullName>
        <formula>Programme_Module__r.Module__r.Credits__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Takes credit from Module</inlineHelpText>
        <label>Credits</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Member_Type__c</fullName>
        <formula>TEXT( Programme_Module__r.Member_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Member Type</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Module_Reference__c</fullName>
        <formula>Programme_Module__r.Module__r.Module_Reference__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Module Reference</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Module__c</fullName>
        <formula>HYPERLINK ( Programme_Module__r.Module__r.Id, Programme_Module__r.Module__r.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Module</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme_Module__c</fullName>
        <label>Programme Module</label>
        <referenceTo>Programme_Module__c</referenceTo>
        <relationshipLabel>Student Modules</relationshipLabel>
        <relationshipName>Student_Modules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Programme__c</fullName>
        <formula>HYPERLINK (  Programme_Module__r.Programme__r.Id , Programme_Module__r.Programme__r.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Programme</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Student_Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to (new) Student Programme object</description>
        <label>Student Programme</label>
        <referenceTo>Student_Programme__c</referenceTo>
        <relationshipLabel>Student Modules</relationshipLabel>
        <relationshipName>Student_Modules</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Student Applicant, Full Student, Student Pre-Reg</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Modules</relationshipLabel>
        <relationshipName>Student_Modules</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Join table between Student (contact) and Program Module join table, with link up to Student Programme</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Student Module</label><nameField>
        <label>Student Module Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Modules</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>Credits__c</fullName>
        <description>Number of Academic credits calculated according to Entry Option</description>
        <formula>IF(TEXT(Exit_Option__c)="",
IF(ISPICKVAL( Entry_Option__c ,"MSc"),180,IF(ISPICKVAL( Entry_Option__c ,"PGDip"),120,IF(ISPICKVAL( Entry_Option__c ,"PGCert"),60,0))),
IF(ISPICKVAL( Exit_Option__c ,"MSc"),180,IF(ISPICKVAL( Exit_Option__c ,"PGDip"),120,IF(ISPICKVAL( Exit_Option__c ,"PGCert"),60,0))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Number of Academic credits calculated according to Entry and Exit Options</inlineHelpText>
        <label>Credits</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Programme must be active (i.e. most recent)</errorMessage>
            <filterItems>
                <field>Programme__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Student Programmes</relationshipLabel>
        <relationshipName>Students_on_Programme1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Required_Credits__c</fullName>
        <formula>Programme__r.Academic_Credits__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Takes Academic Credits value from Programme</inlineHelpText>
        <label>Required Credits</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Stage__c</fullName>
        <description>NOTE : This field drives the Student Programme flow - DO NOT change pick list values without discussion with the I.T / Dev Team</description>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Checked</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional</fullName>
                <color>#339999</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unconditional</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
                <color>#FF99FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Expected</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Registered</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
                <color>#419249</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#666666</color>
            </picklistValues>
            <picklistValues>
                <fullName>Offered</fullName>
                <color>#DDDDDD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reverted from Master:Detail as per LSTM requirement</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Programmes</relationshipLabel>
        <relationshipName>Student_Programmes1</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><recordTypes>
        <fullName>Registered</fullName>
        <active>true</active>
        <label>Non-MSc Registered</label>
    </recordTypes></CustomObject>

classes/ModuleRegistrationContExt.cls
/**
 * @author Mykola Senyk
 * @date 13/06/2014
 * @description Controller extension for Module Registration Page
 */
 /***** Modifications
 ** @author MKM
 ** done for workstream Module Registration amendments  
 */
/// <summary>Added new logic to calulate total availbale, used and required modules credits on Controller </summary>
///<param name="totalAvlCredit"> Used calculate and store total available credits</param>
///<param name="totalUsedCredits">Used calculated and store total used credits</param>
///<param name="sumOfRequiredModuled">Used to store sum of required module credits</param>
global with sharing class ModuleRegistrationContExt {

    // List of modlules to show in the page from which the user selects optional modules
    public List < Programme_Module__c > lstModules {
        get;
        set;
    }

    // List of existing modlules to show in the page from which the user selects optional modules
    public List < Programme_Module__c > lstExtModules {
        get;
        set;
    }

    // List of modlules to store user selections
    public List < Module__c > lstSelectedModuleModule {
        get;
        set;
    }

    //The application by student
    global static Student_Programme__c application {
        get;
        set;
    }
    //The application by student
    public Student_Programme__c application1 {
        get;
        set;
    }   
    // List of modlules to store user selections
    public Integer count {
        get;
        set;
    }

    // List of student modules selected by the user to insert
    public static List < Student_Module__c > lstNewStudentModule {
        get;
        set;
    }


    // List of student modules selected by the user to insert
    public static List < Student_Module__c > lstexistingStudentModule {
        get;
        set;
    }

    // boolean value which will set if the sp stage is Registerd
    public boolean lsstageRegister {
        get;
        set;
    }

    public double totalAvlCredit {
        get;
        set;
    }
    public double totalUsedCredits{
        get;
        set;
    }    
   public double sumOfRequiredModuled {get; set; }
    
    public ModuleRegistrationContExt(ApexPages.StandardController stdcontroller) {

        //populating the student programme record in page load
        List < string > fieldlist = new List < String > ();
        fieldlist.add('Programme__c');
        fieldlist.add('Student__c');
        fieldlist.add('Student__r.Name');
        fieldlist.add('Programme__r.Name');
        fieldlist.add('Stage__c');
        fieldlist.add('Name');
        fieldlist.add('Required_Credits__c'); 
        if (!Test.isRunningTest()) {
            stdcontroller.addFields(fieldlist);
        }

        application = new Student_Programme__c();
        application = (Student_Programme__c) stdController.getRecord();     
        application1 = (Student_Programme__c) stdController.getRecord(); 
          
        if (application.Stage__c == 'Registered') {
            //This parameter uses to hide and show the panel for adding modules
            lsstageRegister = true;
        } else {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING, 'This Student Programme is not yet Registered so you cannot add optional modules.'));

        }        
        //Querying all the modules assigned to the student in this application
        lstexistingStudentModule = new List < Student_Module__c > ([Select Id, Name, Programme_Module__c, Programme_Module__r.Id from Student_Module__c where Student__c = : application.Student__c and Student_Programme__c = : application.Id]);
        Set < Id > existingprogrammemoduleids = new Set < Id > ();


        for (Student_Module__c mod: lstexistingStudentModule) {
            existingprogrammemoduleids.add(mod.Programme_Module__r.Id);
        }



        //Querying and the modules to dispalay in the page load

        lstModules = new List < Programme_Module__c > ();
        lstExtModules = new List < Programme_Module__c > ();
        //Querying all the optional programme modules available
         totalAvlCredit = 0.0;
        totalUsedCredits = 0.0;
        sumOfRequiredModuled = 0.0;
        List < Programme_Module__c > lstallmodules = new List < Programme_Module__c > ([Select Id, Name,Module_Credits__c,Module__r.Module_Reference__c, Module__r.Name from Programme_Module__c where Programme__c = : application.Programme__c and Member_Type__c = 'Optional']);
        for(Student_Module__c temppm :[Select Credits__c from Student_Module__c where Student_Programme__c =:application.id and (Member_Type__c = 'required' OR Member_Type__c ='Specials') and Student__c = : application.Student__c ]){
          
           sumOfRequiredModuled = sumOfRequiredModuled + temppm.Credits__c ;
        }
        // Seperating already assigned modules and other in to seperate lists.
        for (Programme_Module__c programmeModule: lstallmodules) {
            if (existingprogrammemoduleids.contains(programmeModule.Id)) {
                System.debug('programmeModule.Module_Credits__c'+programmeModule.Module_Credits__c);
                if( programmeModule.Module_Credits__c != null){                
                  totalUsedCredits =totalUsedCredits + programmeModule.Module_Credits__c;
                }              
                lstExtModules.add(programmeModule);
            } else {                       
                lstModules.add(programmeModule);
            }              
        }            
        lstNewStudentModule = new List < Student_Module__c > ();
        count = 1;
    }


    @RemoteAction
    global static String saveOptionalModules(String selectedModlueIds, String studentProgrammeId, String unselectedModlueIds) {

        application = new Student_Programme__c();
        application = [SELECT Id, Name, Programme__c, Student__c from Student_Programme__c where Id = : studentProgrammeId];        
        // The Set od unselected Ids
        Set < String > unselectedids = new Set < String > ();
        if (unselectedModlueIds.split(',').size() > 0) {
            //finding the removed modules, forming a list and deleting the list
            unselectedids.addAll(unselectedModlueIds.split(','));
            List < Student_Module__c > lstNewStudentModuletobedeleted = new List < Student_Module__c > ([Select Id from Student_Module__c where Programme_Module__c IN: unselectedids and Student__c=:application.Student__c and Student_Programme__c = : application.Id]);
            if (lstNewStudentModuletobedeleted.size() > 0) {
                delete lstNewStudentModuletobedeleted;
            }
        }
        if (selectedModlueIds.split(',').size() > 0) {
            Set < String > ids = new Set < String > ();

            //contains the set of program module ids in existing student modules
            Set < String > existingids = new Set < String > ();
            ids.addAll(selectedModlueIds.split(','));
           
            Student_Module__c objStudentModule;
            lstexistingStudentModule = new List < Student_Module__c > ();
            lstNewStudentModule = new List < Student_Module__c > ();
            // lstexistingStudentModule=  new List<Student_Module__c>([Select id, Programme_Module__c from Student_Module__c where Programme_Module__c IN:ids ]);
            for (Student_Module__c sm: [Select id, Programme_Module__c from Student_Module__c where Programme_Module__c IN: ids and Student__c=:application.Student__c ]) {
                existingids.add(sm.Programme_Module__c);
            }
            

            for (Programme_Module__c mod: [Select ID, Name from Programme_Module__c Where Id IN: ids and Id NOT IN: existingids]) {
                System.Debug('Success: ');
                objStudentModule = new Student_Module__c();
                objStudentModule.Programme_Module__c = mod.Id;
                objStudentModule.Student__c = application.Student__c;
                objStudentModule.Student_Programme__c = application.Id;
                lstNewStudentModule.add(objStudentModule);
                System.Debug('objStudentModule  ' + objStudentModule);
            }
            
            if (lstNewStudentModule.size() > 0 && !Test.isRunningTest()) {
                insert lstNewStudentModule;
            }
        }
        // Create the assesment and Attendence records
        StudentProgrammeUtilities.createAssessmentsAndAttendance(application.Id);
        // Save the Optional modules In to the programme which is selected
        return 'Success';

    }

}