objects/Contact.object
<CustomObject><fields>
        <fullName>VLE_Visibility__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VLE_Visibility</label>
        <type>Checkbox</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel><recordTypes>
        <fullName>Staff</fullName>
        <active>true</active>
        <label>Staff</label>
    </recordTypes></CustomObject>

objects/Module__c.object
<CustomObject><fields>
        <fullName>VLE_Visibility__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To prevent some records triggering actions in VLE</description>
        <inlineHelpText>To prevent some records triggering actions in VLE</inlineHelpText>
        <label>VLE Visibility</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Instances of Modules</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module</label><nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Modules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Module_Role__c.object
<CustomObject><fields>
        <fullName>Module_Role__c</fullName>
        <description>Defines role for Module Spec, and against Module Instance for VLE integration</description>
        <label>Module Role</label>
        <picklist>
            <picklistValues>
                <fullName>Module Convenor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Module Moderator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Examiner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Teacher</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Staff with Roles</relationshipLabel>
        <relationshipName>Module_Roles</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Staff__c</fullName>
        <label>Staff</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Staff</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Module Roles</relationshipLabel>
        <relationshipName>Module_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Join object between Staff (Contacts) and Modules (both Instances and Version objects). Will allow definition of staff role on a module and be used in VLE integration to define extent of staff enrolment.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Module Role</label><nameField>
        <displayFormat>MR-{00000000}</displayFormat>
        <label>Module Role Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Module Roles</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/TestModuleRoleServices.cls
@isTest
private class TestModuleRoleServices {

    private static final String STR_CONTACT = 'Contact';
    private static final String STR_STAFF = 'Staff';

    static testMethod void testFindInsertedRolesWithVisibleContactsPositive() {
        Contact c = VleTestingUtils.createStudent(false);
        c.RecordTypeId = CommonUtils.findRecordTypeIdByDev(STR_CONTACT, STR_STAFF);
        c.Email = 'test@test.com';
        c.VLE_Visibility__c = false;
        insert c;
        
        Module__c m = VleTestingUtils.createModule('Test Module', '123', true);
        Module_Role__c mr = new Module_Role__c(
            Module__c = m.Id, Staff__c = c.Id, Module_Role__c = 'Test role'
        );
        
        try {
            insert mr;
        } catch (DMLException dmle) {
            System.debug(dmle.getMessage());
        }       
        
        Contact c1 = VleTestingUtils.createStudent(false);
        c1.RecordTypeId = CommonUtils.findRecordTypeIdByDev(STR_CONTACT, STR_STAFF);
        c1.VLE_Visibility__c = false;
        insert c1;
        Module_Role__c mr1 = new Module_Role__c(
            Staff__c = c1.Id, Module_Role__c = 'Test role'
        );
        insert mr1;
        
        Test.startTest();
            List<Module_Role__c> mrListToTest = new List<Module_Role__c>{mr,mr1};
            List<Module_Role__c> mrList = ModuleRoleServices.findInsertedRolesWithVisibleContacts(mrListToTest);
        Test.stopTest();
        System.assertEquals(0,mrList.size());
    }

    static testMethod void testFindInsertedRolesWithVisibleContactsNegative() {
        Contact c = VleTestingUtils.createStudent(false);
        c.RecordTypeId = CommonUtils.findRecordTypeIdByDev(STR_CONTACT, STR_STAFF);
        c.VLE_Visibility__c = false;
        insert c;
        Module_Role__c mr = new Module_Role__c(
            Staff__c = c.Id, Module_Role__c = 'Test role'
        );
        insert mr;
        Test.startTest();
            List<Module_Role__c> mrListToTest = new List<Module_Role__c>{mr};
            List<Module_Role__c> mrList = ModuleRoleServices.findInsertedRolesWithVisibleContacts(mrListToTest);
        Test.stopTest();
        System.assertEquals(0,mrList.size());
    }

    static testMethod void testFindDeletedRolesWithVisibleContactsPositive() {
        Contact c = VleTestingUtils.createStudent(false);
        c.RecordTypeId = CommonUtils.findRecordTypeIdByDev(STR_CONTACT, STR_STAFF);
        c.VLE_Visibility__c = true;
        insert c;
        Module_Role__c mr = new Module_Role__c(
            Staff__c = c.Id, Module_Role__c = 'Test role'
        );
        insert mr;
        Test.startTest();
            List<Module_Role__c> mrListToTest = new List<Module_Role__c>{mr};
            List<Module_Role__c> mrList = ModuleRoleServices.findDeletedRolesWithVisibleContacts(mrListToTest);
            System.assertEquals(1,mrList.size());
        Test.stopTest();
        delete mr;
        List<Module_Role__c> mrListDeleted = ModuleRoleServices.findDeletedRolesWithVisibleContacts(mrListToTest);
        System.assertEquals(0,mrListDeleted.size());
    }

    static testMethod void testFindDeletedRolesWithVisibleContactsNegative() {
        Contact c = VleTestingUtils.createStudent(false);
        c.RecordTypeId = CommonUtils.findRecordTypeIdByDev(STR_CONTACT, STR_STAFF);
        c.VLE_Visibility__c = false;
        insert c;
        Module_Role__c mr = new Module_Role__c(
            Staff__c = c.Id, Module_Role__c = 'Test role'
        );
        insert mr;
        Test.startTest();
            List<Module_Role__c> mrListToTest = new List<Module_Role__c>{mr};
            List<Module_Role__c> mrList = ModuleRoleServices.findDeletedRolesWithVisibleContacts(mrListToTest);
        Test.stopTest();
        System.assertEquals(0,mrList.size());
    }

    static testMethod void testFindUpdatedRolesWithVisibleContactsPositive() {
        Contact c = VleTestingUtils.createStudent(false);
        c.RecordTypeId = CommonUtils.findRecordTypeIdByDev(STR_CONTACT, STR_STAFF);
        c.VLE_Visibility__c = true;
        insert c;
        Module_Role__c mr = new Module_Role__c(
            Staff__c = c.Id,
            Module_Role__c = ModuleRoleServices.EXT_EXAMINER_ROLE_NAME
        );
        insert mr;
        mr.Module_Role__c = ModuleRoleServices.TEACHING_ROLE_NAME;
        update mr;
        Test.startTest();
            List<Module_Role__c> mrListNew = new List<Module_Role__c>{mr};
            Module_Role__c mrOld = mr.clone(true, true, true, true);
            mrOld.Module_Role__c = ModuleRoleServices.EXT_EXAMINER_ROLE_NAME;
            List<Module_Role__c> mrOldList = new List<Module_Role__c>{mrOld};
            Map<Id, Module_Role__c> mrOldMap = new Map <Id, Module_Role__c>(mrOldList);
            List<Module_Role__c> mrList = ModuleRoleServices.findUpdatedRolesWithVisibleContacts(mrListNew, mrOldMap);
            System.assertEquals(1,mrList.size());
        Test.stopTest();
    }

    static testMethod void testFindUpdatedRolesWithVisibleContactsNegative() {
        Contact c = VleTestingUtils.createStudent(false);
        c.RecordTypeId = CommonUtils.findRecordTypeIdByDev(STR_CONTACT, STR_STAFF);
        c.VLE_Visibility__c = true;
        insert c;
        Module_Role__c mr = new Module_Role__c(
            Staff__c = c.Id,
            Module_Role__c = ModuleRoleServices.EXT_EXAMINER_ROLE_NAME
        );
        insert mr;
        Test.startTest();
            List<Module_Role__c> mrListNew = new List<Module_Role__c>{mr};
            Module_Role__c mrOld = mr.clone(true, true, true, true);
            mrOld.Module_Role__c = ModuleRoleServices.EXT_EXAMINER_ROLE_NAME;
            List<Module_Role__c> mrOldList = new List<Module_Role__c>{mrOld};
            Map<Id, Module_Role__c> mrOldMap = new Map <Id, Module_Role__c>(mrOldList);
            List<Module_Role__c> mrList = ModuleRoleServices.findUpdatedRolesWithVisibleContacts(mrListNew, mrOldMap);
            System.assertEquals(0,mrList.size());
        Test.stopTest();
    }
    
}