objects/Contact.object
<CustomObject><fields>
        <fullName>LSTM_No__c</fullName>
        <description>As requested by KT 20th Oct</description>
        <displayFormat>{00000000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>Autonumber, unique Student identifier</inlineHelpText>
        <label>LSTM No</label>
        <type>AutoNumber</type>
    </fields><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Hidden field for Test Class use, to exclude from Flows</description>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Programme__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used for lookup from Student processes</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>External_Form__c</fullName>
        <description>eg Form Assembly</description>
        <inlineHelpText>URL of external form creation service</inlineHelpText>
        <label>External Form</label>
        <type>Url</type>
    </fields><fields>
        <fullName>Home_EU_Fee__c</fullName>
        <inlineHelpText>Fee for UK and rest of EU students; if 'Fee TBC' is checked this amount is an estimate for reporting</inlineHelpText>
        <label>Home EU Fee</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Overseas_Fee__c</fullName>
        <inlineHelpText>Fees for students outside of EU; if 'Fee TBC' is checked this amount is an estimate for reporting</inlineHelpText>
        <label>Overseas Fee</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme Version</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Programme_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Versions, Versions, Specification, Versions - Pre Approved, Specification Edit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Programme Instances</relationshipLabel>
        <relationshipName>Programmes_Instances</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme_Version__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Application_Form_Type__c</fullName>
        <inlineHelpText>Help text to set by LSTM</inlineHelpText>
        <label>Application Form Type</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Short+</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short-</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FormAssembly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Entry_Award_1__c</fullName>
        <globalPicklist>Entry_Exit_Awards</globalPicklist>
        <label>Entry Award 1</label>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Home_EU_Fee__c</fullName>
        <label>Home EU Fee</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Master_Link__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To allow two levels of versions - master or senior, and child versions. Will provide external systems with a persistent ID across all Programmes and Programme Versions of same group</description>
        <label>Master Link</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Record must be a master</errorMessage>
            <filterItems>
                <field>Programme_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Master Version</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Child Programme Versions</relationshipLabel>
        <relationshipName>Programme_Versions</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Overseas_Fee__c</fullName>
        <label>Overseas Fee</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme Version</label><nameField>
        <label>Programme Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programme Versions</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel><recordTypes>
        <fullName>Versions</fullName>
        <active>true</active>
        <description>Annual (or other) iterations per programme</description>
        <label>Versions</label>
    </recordTypes></CustomObject>

objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>Fee_Status__c</fullName>
        <description>Default is Null, to trigger workflow ref to Student EEA setting (taken from HESA table); LSTM Admin can override this manually if needed and workflow will not re-trigger (unless set back to null)</description>
        <inlineHelpText>Taken from HESA Nationality choice on Student record; can be manually changed to other value if Fee score dictates</inlineHelpText>
        <label>Fee Status</label>
        <picklist>
            <picklistValues>
                <fullName>Home/EU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overseas</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>LSTM_No__c</fullName>
        <description>Taken from Contact object</description>
        <label>LSTM No</label>
        <length>12</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Programme must be active (i.e. most recent)</errorMessage>
            <filterItems>
                <field>Programme__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Student Programmes</relationshipLabel>
        <relationshipName>Students_on_Programme1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reverted from Master:Detail as per LSTM requirement</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Programmes</relationshipLabel>
        <relationshipName>Student_Programmes1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/ExternalFormControllerTest.cls
@IsTest
public class ExternalFormControllerTest{

    public static testMethod void  testExternalFormController(){
        id recType = Schema.SObjectType.Programme_Version__c.getRecordTypeInfosByName().get('Versions - Pre Approved').getRecordTypeId();
        id recType1 = Schema.SObjectType.Programme_Version__c.getRecordTypeInfosByName().get('Master Version').getRecordTypeId();
        
        Contact student = ApplytestingUtils.createStudent(true); 
        
        Programme_Version__c pV1= new Programme_Version__c();
        pV1.Name = 'Test';
        pV1.Entry_Award_1__c = 'MSc';
        pV1.Active__c = true;
        pV1.RecordTypeid = recType1;
        pv1.Application_Form_Type__c = 'Form Assembly';
        INSERT pV1;
        
        Programme_Version__c pV= new Programme_Version__c();
        pV.Name = 'Test';
        pV.Entry_Award_1__c = 'PGDip';
        pV.Active__c = true;
        pV.RecordTypeid = recType;
        pV.Master_Link__c = pV1.id;
        INSERT pV;

        Programme__c prog = new Programme__c();
        prog.Name ='testProgramme';
        prog.Overseas_Fee__c = 1000;
        prog.Home_EU_Fee__c = 500;       
        prog.Programme_Version__c = pV.id;
        prog.Test_Class_Record__c = true;
        prog.External_Form__c = 'abc';
        INSERT prog;

        Student_Programme__c sp = new Student_Programme__c();
        sp .Name='test';
        sp.Student__c =student.Id;
        sp.LSTM_No__c= '00012345';
        sp.Fee_Status__c = 'Overseas';
        sp.Programme__c = prog.Id;
        sp.Test_Class_Record__c = true;         

        insert sp;
        
        Test.startTest();     
        Test.setMock(HttpCalloutMock.Class, new MockHttpResponseGenerator (200, 'OK', ''));   
        Test.setCurrentPageReference(new PageReference('Page.ExternalForm')); 
        System.currentPageReference().getParameters().put('SPID', sp.Id);
        System.currentPageReference().getParameters().put('LSTM_NO', student.LSTM_NO__c);        

        ExternalFormController obj = new ExternalFormController();
        Test.stopTest();        
        
    }
}