objects/Contact.object
<CustomObject><fields>
        <fullName>LSTM_No__c</fullName>
        <description>As requested by KT 20th Oct</description>
        <displayFormat>{00000000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>Autonumber, unique Student identifier</inlineHelpText>
        <label>LSTM No</label>
        <type>AutoNumber</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Programme__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used for lookup from Student processes</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Code__c</fullName>
        <formula>Programme_Version__r.Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Taken from Version level</inlineHelpText>
        <label>Code</label>
        <type>Text</type>
    </fields><fields>
        <fullName>End_Date__c</fullName>
        <description>Last Date module is valid</description>
        <label>End Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>External_Form__c</fullName>
        <description>eg Form Assembly</description>
        <inlineHelpText>URL of external form creation service</inlineHelpText>
        <label>External Form</label>
        <type>Url</type>
    </fields><fields>
        <fullName>Fee_TBC__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Used in applications portal search results; indicates that fees are To Be Confirmed. Use previous years fees in Home/EU and Overseas fields for internal reporting of applications pipeline value</inlineHelpText>
        <label>Fee TBC</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Home_EU_Fee__c</fullName>
        <inlineHelpText>Fee for UK and rest of EU students; if 'Fee TBC' is checked this amount is an estimate for reporting</inlineHelpText>
        <label>Home EU Fee</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Overseas_Fee__c</fullName>
        <inlineHelpText>Fees for students outside of EU; if 'Fee TBC' is checked this amount is an estimate for reporting</inlineHelpText>
        <label>Overseas Fee</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Programme_Type_External__c</fullName>
        <formula>TEXT(  Programme_Version__r.Master_Link__r.Programme_Type_External__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Taken from Programme Version; for display in MyLSTM Application form</inlineHelpText>
        <label>Programme Type External</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme_Type__c</fullName>
        <description>DO NOT USE, to be deleted</description>
        <label>X Programme Type</label>
        <picklist>
            <picklistValues>
                <fullName>MSc Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Diploma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSc Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Course</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme Version</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Programme_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Versions, Versions, Specification, Versions - Pre Approved, Specification Edit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Programme Instances</relationshipLabel>
        <relationshipName>Programmes_Instances</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Type__c</fullName>
        <formula>Text ( Programme_Version__r.Programme_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Taken from Version level</inlineHelpText>
        <label>Type</label>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme_Version__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Application_Form_Type__c</fullName>
        <inlineHelpText>Help text to set by LSTM</inlineHelpText>
        <label>Application Form Type</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Short+</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short-</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FormAssembly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Code__c</fullName>
        <inlineHelpText>Internal LSTM programme code</inlineHelpText>
        <label>Code</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Home_EU_Fee__c</fullName>
        <label>Home EU Fee</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Master_Link__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To allow two levels of versions - master or senior, and child versions. Will provide external systems with a persistent ID across all Programmes and Programme Versions of same group</description>
        <label>Master Link</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Record must be a master</errorMessage>
            <filterItems>
                <field>Programme_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Master Version</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Child Programme Versions</relationshipLabel>
        <relationshipName>Programme_Versions</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Overseas_Fee__c</fullName>
        <label>Overseas Fee</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Programme_Type_External__c</fullName>
        <description>Set at Master record type</description>
        <inlineHelpText>Used to combine Programme Type of Masters Module and (standalone) Short Courses, under External Type of of Short Courses; for display in MyLSTM Application form</inlineHelpText>
        <label>Programme Type External</label>
        <picklist>
            <picklistValues>
                <fullName>MSc Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Programme_Type__c</fullName>
        <label>Programme Type</label>
        <picklist>
            <picklistValues>
                <fullName>MSc Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Diploma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Masters Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG Cert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Course</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Date of first Intake</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme Version</label><nameField>
        <label>Programme Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programme Versions</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>End_Date__c</fullName>
        <description>For PGR HESA return</description>
        <inlineHelpText>Use where Student Programme End Date is not the same as Programme End Date (eg. PGR, DipUKMP)</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>LSTM_No__c</fullName>
        <description>Taken from Contact object</description>
        <label>LSTM No</label>
        <length>12</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme_Type__c</fullName>
        <formula>TEXT(  Programme__r.Programme_Version__r.Programme_Type__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Programme Type</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Programme must be active (i.e. most recent)</errorMessage>
            <filterItems>
                <field>Programme__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Student Programmes</relationshipLabel>
        <relationshipName>Students_on_Programme1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reverted from Master:Detail as per LSTM requirement</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Programmes</relationshipLabel>
        <relationshipName>Student_Programmes1</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/ChooseProgrammeCont.cls
/**
 * @author Valentyn Bilenkyy
 * @date 13/06/2014
 * @description Controller for ChooseProgramme page
 */
 /***** Modifications
/// done for  on A6 Persistent Application Links ,Display the data base on parameter received on applyWizard Page o=in student community on 14-06-2015 *****/
///Author: MKM
/// <summary> Edited the query by adding filter using programme id passed through url </summary>
/// <param name="programmeId">Used store selected programme id and send via Url</param>
public class ChooseProgrammeCont {
    
    public static final String EMPTY_STRING = '';
    public static final String LABEL_NONE = '-None-';
    public static final Integer SEARCH_RESULTS_PER_PAGE = 10;
    
    public static final String PROG_TYPE_DIPLOMA = 'Professional Diploma';
    public static final String PROG_TYPE_MSC = 'MSc Programme';
    public static final String PROG_TYPE_MASTERS = 'Masters Module';
    public static final String PROG_TYPE_SHORT_COURSE = 'Short Course';
    public static final String PROG_TYPE_PGT = 'PGT';
    public static final String PROG_TYPE_PGR = 'PGR';
    
    public static final String EXT_TYPE_SHORT_COURSE = 'Short Course';
    public static final String EXT_TYPE_MSC = 'MSc Programme';
    public static final String EXT_TYPE_PROFESSIONAL = 'Professional Programme';
    public static final String EXT_TYPE_RESEARCH = 'Research Programme';
    public static final String EXT_TYPE_CLOSED = 'Closed Course';
    
    /**
     * Constructor after initialization seaches for available programmes
     */
    public ChooseProgrammeCont() {
        search();
    }
    
    public String searchTerm {get;set;}
    public String searchProgrammeType {get;set;}
    public Boolean hasResults {get;set;}
    public Integer resultsSize {get;set;}
    public Integer resultsPageSize {get;set;}
    public Id programmeId {get;set;}

    /**
     * List controller for enabling pagination
     * @return ApexPages.StandardSetController programmesSetController
     */
    public ApexPages.StandardSetController programmesSetController {
        get{
            if(programmesSetController == null) {
                resultsPageSize = SEARCH_RESULTS_PER_PAGE;
                if(searchTerm == null) 
                    searchTerm = '';
                if(searchProgrammeType == null) 
                    searchProgrammeType = '';
                String searchString = '\'%' + String.escapeSingleQuotes(searchTerm) + '%\'';
                String queryString = 'SELECT Id, Code__c, Name, Start_Date__c, End_Date__c, Home_EU_Fee__c, Overseas_Fee__c, Programme_Type_External__c, Fee_TBC__c FROM Programme__c WHERE Name LIKE ' + searchString;
                if(String.isNotEmpty(searchProgrammeType)){
                    if (EXT_TYPE_SHORT_COURSE.equalsIgnoreCase(searchProgrammeType)){
                        queryString += ' AND Type__c IN (\'' + String.escapeSingleQuotes(PROG_TYPE_MASTERS) + '\',\'' + String.escapeSingleQuotes(PROG_TYPE_SHORT_COURSE) + '\')';
                        //queryString += ' AND Type__c LIKE \'' + String.escapeSingleQuotes(PROG_TYPE_MASTERS) + '\' OR Type__c LIKE \'' + String.escapeSingleQuotes(PROG_TYPE_SHORT_COURSE) + '\'';
                    }else if (EXT_TYPE_RESEARCH.equalsIgnoreCase(searchProgrammeType)){
                        queryString += ' AND Type__c IN (\'' + String.escapeSingleQuotes(PROG_TYPE_PGR) + '\',\'' + String.escapeSingleQuotes(PROG_TYPE_PGT) + '\')';
                        //queryString += ' AND Type__c LIKE \'' + String.escapeSingleQuotes(PROG_TYPE_PGR) + '\' OR Type__c LIKE \'' + String.escapeSingleQuotes(PROG_TYPE_PGT) + '\'';
                        
                    }else if (EXT_TYPE_PROFESSIONAL.equalsIgnoreCase(searchProgrammeType)){
                        queryString += ' AND (Type__c LIKE \'' + String.escapeSingleQuotes(PROG_TYPE_DIPLOMA) + '\' OR Type__c LIKE \'' + String.escapeSingleQuotes(EXT_TYPE_CLOSED) + '\')';
                    
                    }else {
                        queryString += ' AND Type__c LIKE \'' + String.escapeSingleQuotes(searchProgrammeType) + '\'';
                    }
                } 
                string filter =  ApexPages.currentPage().getParameters().get('programmeid');                
                system.debug('*** -- filter= ' + filter + ' -- ***');
                if(filter != null&& filter != '' ){
                    //set<id> idsOfPgmVersion = new set<id>(); 
                   // for(Programme_Version__c  pgmversioVr : [SELECT Id FROM Programme_Version__c where Master_Link__c =: filter  ]){
                        //idsOfPgmVersion.add(pgmversioVr.id);
                  //    }
                  //   system.debug('*** -- idsOfPgmVersion= ' + idsOfPgmVersion+ ' -- ***');
                    //queryString += ' AND Programme_Version__c IN :idsOfPgmVersion AND Active__c = true AND Start_Date__c > today ORDER BY Name ASC';
                    queryString += ' AND Id =: filter AND Active__c = true AND (Start_Date__c > today OR End_Date__c = null ) ORDER BY Name ASC';
                    
                } 
                else{    
                      queryString += ' AND Active__c = true AND (Start_Date__c > today OR End_Date__c = null) ORDER BY Name ASC';
                }
                system.debug('*** -- QueryString = ' + queryString + ' -- ***');
                programmesSetController = new ApexPages.StandardSetController(Database.getQueryLocator(queryString));
                programmesSetController.setPageSize(resultsPageSize);
                resultsSize = programmesSetController.getResultSize();
            }
            return programmesSetController;
        }
        set;
    }

    /**
     * Indicates whether there are more records after the current page set
     * @return Boolean
     */
    public Boolean hasNext {
        get {
            return programmesSetController.getHasNext();
        }
        set;
    }

    /**
     * Indicates whether there are more records before the current page set
     * @return Boolean
     */
    public Boolean hasPrevious {
        get {
            return programmesSetController.getHasPrevious();
        }
        set;
    }
  
    /**
     * Returns the page number of the current page set. Note that the first page returns 1
     * @return Integer
     */
    public Integer pageNumber {
        get {
            return programmesSetController.getPageNumber();
        }
        set;
    }

    /**
     * Redirects to given page reference
     * @return PageReference page
     */
    private PageReference redirect(PageReference page) {
        page.setRedirect(true);
        return page;
    }

    /**
     * Returns the first page of records
     */
    public void first() {
        programmesSetController.first();
    }
  
    /**
     * Returns the last page of records
     */
    public void last() {
        programmesSetController.last();
    }
  
    /**
     * Returns the previous page of records
     */
    public void previous() {
        programmesSetController.previous();
    }
  
    /**
     * Returns the next page of records
     */
    public void next() {
        programmesSetController.next();
    }

    /**
     * Returns available programmes list
     * @return List<ProgrammeWrapper> programmesList
     */
    public List<ProgrammeWrapper> getFoundProgrammes() {
        List<ProgrammeWrapper> programmesList = new List<ProgrammeWrapper>();
        if(programmesSetController != null) {
            for(Programme__c p : (List<Programme__c>)programmesSetController.getRecords())
                programmesList.add(new ProgrammeWrapper(p));
        }
        return programmesList;
    }

    /**
     * Populating values for dropdown filter
     * @return List<SelectOption> options
     */
    public List<SelectOption> getProgrammeTypes() {
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult fieldResult = Programme_Version__c.Programme_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        options.add(new SelectOption(EMPTY_STRING, LABEL_NONE));
        for( Schema.PicklistEntry f : ple) {
            options.add(new SelectOption(f.getValue(), f.getLabel()));
        }
        return options;
    }
    
    /**
     * Populating values for dropdown filter for external facing list
     * @return List<SelectOption> options
     */
    public List<SelectOption> getProgrammeTypesExternal() {
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult fieldResult = Programme_Version__c.Programme_Type_External__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        options.add(new SelectOption(EMPTY_STRING, LABEL_NONE));
        for( Schema.PicklistEntry f : ple) {
            options.add(new SelectOption(f.getValue(), f.getLabel()));
        }
        return options;
    }

    /**
     * Page reference for search button
     */
    public PageReference search() {
        programmesSetController = null;
        hasResults = false;
        if(getFoundProgrammes() != null) {
            programmesSetController.setPageNumber(1);
            if(resultsSize>0) hasResults = true;
        }
        return null;
    }

    /**
    * Page reference for reset search button
    */
    public PageReference resetSearch(){
        programmesSetController = null;
        searchTerm = null;
        searchProgrammeType = null;
        return null;
    }

    /**
     * Page reference for apply button/link
     */
    public PageReference processApply() {
        if(programmeId != null) {
            Student_Programme__c sp = ApplyServices.createCourseByProgrammeId(programmeId);
            system.debug('sp = ' + sp);
            if(sp == NULL){
                return NULL;
            }
            
            Contact student = [SELECT Id,LSTM_No__c FROM Contact WHERE Id =: sp.Student__c];
            Programme__c programme = [SELECT Id,External_Form__c,Programme_Version__r.Master_Link__r.Application_Form_Type__c FROM Programme__c WHERE Id =: sp.Programme__c];
            
            if(programme.Programme_Version__r.Master_Link__r.Application_Form_Type__c.equals('FormAssembly') && String.isNotBlank(programme.External_Form__c))
            {
                PageReference pg = Page.ExternalForm;
                pg.getParameters().put('SPID', sp.Id);
                pg.getParameters().put('StudentID', student.Id);
                return pg;  
            }
            else
            {
                PageReference applyWizardReference = Page.ApplyWizard;
                applyWizardReference.getParameters().put('Id', sp.Id);
                return redirect(applyWizardReference);              
            }   
        }
        return null;
    }
}