objects/Contact.object
<CustomObject><fields>
        <fullName>Registered_Supervisor__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Must be checked for Staff member to be linked to Supervision records or PAP Members</inlineHelpText>
        <label>Registered Supervisor</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Hidden field for Test Class use, to exclude from Flows</description>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel><recordTypes>
        <fullName>Staff</fullName>
        <active>true</active>
        <label>Staff</label>
    </recordTypes></CustomObject>

objects/Programme__c.object
<CustomObject><fields>
        <fullName>Code__c</fullName>
        <formula>Programme_Version__r.Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Taken from Version level</inlineHelpText>
        <label>Code</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme Version</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Programme_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Versions, Versions, Specification, Versions - Pre Approved, Specification Edit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Programme Instances</relationshipLabel>
        <relationshipName>Programmes_Instances</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme_Version__c.object
<CustomObject><fields>
        <fullName>Code__c</fullName>
        <inlineHelpText>Internal LSTM programme code</inlineHelpText>
        <label>Code</label>
        <length>10</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme Version</label><nameField>
        <label>Programme Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programme Versions</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Research_Period__c.object
<CustomObject><fields>
        <fullName>Period_Number__c</fullName>
        <label>Period Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Student_Programme__c</fullName>
        <label>Student Programme</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>You can only assign Research Periods to Student Programmes where Record Type = PGR Programme.</errorMessage>
            <filterItems>
                <field>Student_Programme__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>PGR Student</value>
            </filterItems>
            <filterItems>
                <field>Student_Programme__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>PGR Application</value>
            </filterItems>
            <infoMessage>Oops... the Student Programme you have selected is not a PGR Programme.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Student_Programme__c</referenceTo>
        <relationshipLabel>Research Periods</relationshipLabel>
        <relationshipName>Research_Periods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <formula>Student_Programme__r.Student__r.FirstName&amp;" "&amp;Student_Programme__r.Student__r.LastName&amp;" ("&amp;Student_Programme__r.Student__r.LSTM_No__c&amp;")"</formula>
        <label>Student</label>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Research Period</label><nameField>
        <label>Research Period Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Research Periods</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>Mode_of_Study__c</fullName>
        <label>Mode of Study</label>
        <picklist>
            <picklistValues>
                <fullName>Full Time</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Part Time</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Programme must be active (i.e. most recent)</errorMessage>
            <filterItems>
                <field>Programme__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Student Programmes</relationshipLabel>
        <relationshipName>Students_on_Programme1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Stage__c</fullName>
        <description>NOTE : This field drives the Student Programme flow - DO NOT change pick list values without discussion with the I.T / Dev Team</description>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Checked</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional</fullName>
                <color>#339999</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unconditional</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
                <color>#FF99FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Expected</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Registered</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
                <color>#419249</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#666666</color>
            </picklistValues>
            <picklistValues>
                <fullName>Offered</fullName>
                <color>#DDDDDD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reverted from Master:Detail as per LSTM requirement</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Programmes</relationshipLabel>
        <relationshipName>Student_Programmes1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Supervision__c.object
<CustomObject><fields>
        <fullName>Primary_Supervisor__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Tick to denote Supervisor will provide primary supervision of student</inlineHelpText>
        <label>Primary Supervisor</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Research_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Research Period</label>
        <referenceTo>Research_Period__c</referenceTo>
        <relationshipLabel>Supervisors</relationshipLabel>
        <relationshipName>Supervisions</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Student_Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Programme</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Oops... you can only associate Supervisors with Student Programmes where Record Type = PGR Programme</errorMessage>
            <filterItems>
                <field>Student_Programme__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>PGR Programme</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Student_Programme__c</referenceTo>
        <relationshipLabel>Supervisions</relationshipLabel>
        <relationshipName>Supervisors</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Supervisor_Weighting__c</fullName>
        <label>Supervisor Weighting</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The person you are trying to look up is not a registered supervisor or not a member of staff.</errorMessage>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Staff</value>
            </filterItems>
            <filterItems>
                <field>Contact.Registered_Supervisor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Find the name of the Supervisor.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Students Supervising</relationshipLabel>
        <relationshipName>Supervisions</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Join between staff and student programme for managing of PGR supervisions</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Supervision</label><nameField>
        <label>Supervision Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Supervisions</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes></CustomObject>

objects/VLE__c.object
<CustomObject><fields>
        <fullName>API_Host__c</fullName>
        <description>Domain name of API host</description>
        <label>API Host</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>App_ID__c</fullName>
        <description>App ID from desire2learn</description>
        <label>App ID</label>
        <length>22</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>App_Key__c</fullName>
        <description>App Key for desire2learn (secret)</description>
        <label>App Key</label>
        <length>22</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>External_Examiner_Role_ID__c</fullName>
        <description>ID of External Examiner role</description>
        <label>External Examiner Role ID</label>
        <length>32</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Instructor_Role_ID__c</fullName>
        <description>ID of Instructor role</description>
        <label>Instructor Role ID</label>
        <length>32</length>
        <type>Text</type>
    </fields><fields>
        <fullName>User_ID__c</fullName>
        <description>User ID for API calls</description>
        <label>User ID</label>
        <length>22</length>
        <type>Text</type>
    </fields><fields>
        <fullName>User_Key__c</fullName>
        <description>Key for API user (secret)</description>
        <label>User Key</label>
        <length>22</length>
        <type>Text</type>
    </fields><customSettingsType>List</customSettingsType><description>Credentials for VLE external service</description><enableFeeds>false</enableFeeds><label>VLE parameters</label><visibility>Protected</visibility></CustomObject>

classes/TestResearchPeriodRecord.cls
/*
* Test Class for ResearchPeriodRecord Visualforce Page to invoke from Student_Programme__c
* Created : 13/06/2017
* Suyati
* Desc : Class will create Student Programme and inserts Research Period and Supervisions
* Suyati Modified : 22/06/2017 - To cover the additional Visualforce amends
*/
@isTest
public class TestResearchPeriodRecord {
    
    /*Global data setting for PGR Programme Type */
    
    static final String PROGRAMME_NAME = 'PhD - Full Time Speculative - 17/18 Registration';  
    static final String PROGRAMME_VERSION = 'Programme_Version__c';
    static final String PROGRAMME_TYPE = ApplyServices.PT_PGR;   
    
    static testmethod void testVFData(){
        VLE__c vle = new VLE__c(
            Name = VleServices.CS_NAME, API_Host__c = 'vle-host.com', App_ID__c = 'app_id', App_Key__c = 'app_key',
            External_Examiner_Role_ID__c = '468', Instructor_Role_ID__c = String.valueOf(357), User_ID__c = 'user_id', User_Key__c = 'user_key'
        ); 
        insert vle;
        /* Insert Module Version */
        Id mvrtId = CommonUtils.findRecordTypeIdByDev(PROGRAMME_VERSION, ApplyServices.RT_MASTER_PV_DEVNAME);
        Programme_Version__c mv = VleTestingUtils.createMasterProgrammeVersion(PROGRAMME_NAME, mvrtId, PROGRAMME_TYPE, false);
        mv.Code__c = StudentProgrammeTriggerMethods.CODE_DTN;
        insert mv;
        
        /*Insert Programme Version */
        Id rtId = CommonUtils.findRecordTypeIdByDev(PROGRAMME_VERSION, ApplyServices.RT_VERSION_PV_DEVNAME);
        Programme_Version__c pv = VleTestingUtils.createProgrammeVersion(PROGRAMME_NAME, rtId, PROGRAMME_TYPE, mv.Id, false);
        pv.Code__c = StudentProgrammeTriggerMethods.CODE_DTN;
        insert pv;
        
        /* Create new Programme */
        Programme__c prog = VleTestingUtils.createProgramme(PROGRAMME_NAME, pv.Id, false);
        insert prog;
        
        /* Create a Student Contact for Creating Student Programme */
        Contact student = VleTestingUtils.CreateStudent(true);
        
        /* Get RecordType Id from Student Programme */
        Id spRecordTypeId = Schema.SObjectType.Student_Programme__c.getRecordTypeInfosByName().get('PGR Application').getRecordTypeId();
        system.debug('spRecordTypeId'+spRecordTypeId);
        
        /* Create new Student Programme */
        Student_Programme__c newSp = new Student_Programme__c();
        newSp.Name = 'TestProgramme';
        newSp.Programme__c = prog.Id;
        newSp.Student__c = student.Id;
        newSp.Test_Class_Record__c = true;
        newSp.RecordTypeId = spRecordTypeId;
        newSp.Stage__c = ApplyServices.COURSE_PRE_REGISTERED_STAGE_NAME;
        newSp.Mode_of_Study__c = 'Full Time';
        insert newSp;
        
        /* Get the Student Programme and assign Research Period and Supervisions*/
        Student_Programme__c lstPr = [select id, name,Mode_of_Study__c,Stage__c from Student_Programme__c where Id=: newSp.Id limit 1];
        lstPr.RecordTypeId = spRecordTypeId;
        update lstPr;
        system.debug('lstptrrrrrrrrrrrrrrrr'+lstPr.id);
        /* Create new Staff */
        Contact staff = VleTestingUtils.createStaff(true);
        staff.Registered_Supervisor__c = true;
        update staff;
        
        /* Create new Research period */
        Research_Period__c resPeriod = new Research_Period__c();
        resPeriod.Name = 'tstPeriod';
        resPeriod.Student_Programme__c = lstPr.Id;
        //resPeriod.Period_Number__c = 1;
        insert resPeriod;
        
        /* Create new Supervision */
       /* Supervision__c spv1 = new Supervision__c();
        spv1.Supervisor__c= staff.Id;
        spv1.Student_Programme__c = lstPr.id;
        spv1.Primary_Supervisor__c = true;
        spv1.Research_Period__c = resPeriod.id;
        spv1.Name = 'Supervisor';
        spv1.Supervisor_Weighting__c = 60;
        insert spv1;
        
        Supervision__c spv2 = new Supervision__c();
        spv2.Supervisor__c= staff.Id;
        spv2.Student_Programme__c = lstPr.id;
        spv2.Primary_Supervisor__c = false;
        spv2.Research_Period__c = resPeriod.id;
        spv2.Name = 'Supervisor';
        spv2.Supervisor_Weighting__c = 40;
        insert spv2;
        */
        /* Create Page reference and assign ID of Student Programme via constructor method */
        PageReference pageRef = Page.ResearchPeriodRecord;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('id',lstPr.Id);
        
        Student_Programme__c cinstance = new Student_Programme__c();
        ApexPages.StandardController sc = new ApexPages.standardController(cinstance);
        Test.startTest();
        ResearchPeriodRecord controller = new ResearchPeriodRecord(sc);
        controller.UpdateData();
        controller.Cancel();
        controller.SaveData();
        Test.stopTest();
    }
    
}