objects/Contact.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel><recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <label>Other</label>
    </recordTypes><recordTypes>
        <fullName>Staff</fullName>
        <active>true</active>
        <label>Staff</label>
    </recordTypes></CustomObject>

objects/Expiry_Days_For_Old_Vle_Actions__c.object
<CustomObject><fields>
        <fullName>Expiry_Days__c</fullName>
        <label>Expiry Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><customSettingsType>List</customSettingsType><enableFeeds>false</enableFeeds><label>Expiry Days For Old Vle Actions</label><visibility>Protected</visibility></CustomObject>

objects/Module__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Instances of Modules</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module</label><nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Modules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Module_Role__c.object
<CustomObject><fields>
        <fullName>Module_Role__c</fullName>
        <description>Defines role for Module Spec, and against Module Instance for VLE integration</description>
        <label>Module Role</label>
        <picklist>
            <picklistValues>
                <fullName>Module Convenor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Module Moderator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Examiner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Teacher</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Staff with Roles</relationshipLabel>
        <relationshipName>Module_Roles</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Join object between Staff (Contacts) and Modules (both Instances and Version objects). Will allow definition of staff role on a module and be used in VLE integration to define extent of staff enrolment.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Module Role</label><nameField>
        <displayFormat>MR-{00000000}</displayFormat>
        <label>Module Role Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Module Roles</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/VLE__c.object
<CustomObject><fields>
        <fullName>BatchIsRunning__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates state of batch for synchronization</description>
        <label>BatchIsRunning</label>
        <type>Checkbox</type>
    </fields><customSettingsType>List</customSettingsType><description>Credentials for VLE external service</description><enableFeeds>false</enableFeeds><label>VLE parameters</label><visibility>Protected</visibility></CustomObject>

objects/VLE_Action__c.object
<CustomObject><fields>
        <fullName>Action__c</fullName>
        <description>Type of action to VLE API</description>
        <label>Action</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>Next_Try__c</fullName>
        <description>Time when delayed action should try sync again</description>
        <label>Next Try</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Note__c</fullName>
        <description>Some notes about this action. Show error message if error occurs in the perform() method.</description>
        <label>Note</label>
        <length>64</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <description>Status value means: New - for future, Delayed - wait for became Batch, Canceled - not actual in some reasons</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Batch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delayed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Object for perform complex action to VLE API</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>VLE Action</label><nameField>
        <label>VLE Action Name</label>
        <type>Text</type>
    </nameField><pluralLabel>VLE Actions</pluralLabel><sharingModel>Private</sharingModel></CustomObject>

objects/VLE_Sync_Command__c.object
<CustomObject><fields>
        <fullName>Command__c</fullName>
        <description>Type of command</description>
        <label>Command</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>Error_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of errors</description>
        <label>Error Count</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Last_Error_Message__c</fullName>
        <description>Text of last error message</description>
        <label>Last Error Message</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Obj_Type__c</fullName>
        <description>Indicates name of related to synchronization object</description>
        <label>Obj Type</label>
        <picklist>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student_Programme__c</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Order__c</fullName>
        <description>Order by number</description>
        <label>Order</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Params__c</fullName>
        <description>Additional parameters for command in the JSON format</description>
        <label>Params</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <description>Current status of API call. New - just created, Error - some trouble and Done - for calls that have been succesfully processed.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>VLE_Action__c</fullName>
        <label>VLE Action</label>
        <referenceTo>VLE_Action__c</referenceTo>
        <relationshipLabel>VLE Sync Commands</relationshipLabel>
        <relationshipName>VLE_Sync_Commands</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Simple VLE API calls to perform only single API methods</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>false</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>VLE Sync Command</label><nameField>
        <label>VLE Sync Command Name</label>
        <type>Text</type>
    </nameField><pluralLabel>VLE Sync Commands</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/VleSyncServices.cls
/**
 * Service to deal with synchronization to VLE
 * Note: Use 'without sharing' to perform all operation in system mode
 */
public without sharing class VleSyncServices {
    
    // List of ActionStructure waiting for insert
    @TestVisible
    private static final List<ActionStructure> itemsToSync = new List<ActionStructure>();
    
    // Maximum number of delayed records that could be added to batch at one time  
    private static final Integer PREPARED_ACTIONS_SIZE_LIMIT = 500;
    
    /**
     * Indicator to try run batch job only once at execution context
     */
    @TestVisible
    private static Boolean firstTryToRunBatch = true;
    
    // Set of unique actions (action name + id)
    private static final Set<String> uniqActions = new Set<String>();

    // Action names
    public static final String DUMMY_ACTION =                               'dummy'; // note: for test only
    public static final String CREATE_VLE_STUDENT_BY_SP_ACTION =            'create student by SP';
    public static final String CREATE_VLE_STAFF_ACTION =                    'create staff';
    public static final String VLE_STAFF_ROLE_ACTION =                      'staff role';
    public static final String MAKE_VLE_USER_INACTIVE_ACTION =              'make user inactive';
    public static final String SET_STUDENT_INACTIVE_BY_SP_ACTION =          'set student inactive by SP';
    public static final String CREATE_VLE_COURSE_ACTION =                   'create course offering';
    public static final String UPDATE_VLE_COURSE_ACTION =                   'update course offering';
    public static final String CREATE_VLE_STUDENT_WITH_ROLE_BY_SP_ACTION =  'create student with role by SP';
    /*
    //TODO temp
    public static Set<Id> defaultModulesIds = new Set<Id>{
        VleServices.credentials.Programme_Page_Module_Id__c, 
        VleServices.credentials.Student_Community_Site_Module_ID__c, 
        VleServices.credentials.Study_Skills_Module_ID__c
    };  */  
    
    // Map with equivalent of action name and action implementation class name 
    public static final Map<String,String> actionMap = new Map<String,String> {
        DUMMY_ACTION => 'VleBaseAction.DummyAction',
        CREATE_VLE_STUDENT_BY_SP_ACTION => 'VleCreateStudentBySpAction',
        CREATE_VLE_STAFF_ACTION => 'VleCreateStaffAction',
        VLE_STAFF_ROLE_ACTION => 'VleStaffRoleAction',
        MAKE_VLE_USER_INACTIVE_ACTION => 'VleMakeUserInactiveAction',
        SET_STUDENT_INACTIVE_BY_SP_ACTION => 'VleSetStudentInactiveBySpAction',
        CREATE_VLE_COURSE_ACTION => 'VleCreateModuleAction',
        UPDATE_VLE_COURSE_ACTION => 'VleUpdateModuleAction',
        CREATE_VLE_STUDENT_WITH_ROLE_BY_SP_ACTION => 'VleCreateStudentWithRoleBySpAction'
    };
    
    // Command names
    public static final String DUMMY_COMMAND =              'dummy'; // note: for test only
    public static final String CREATE_USER_COMMAND =        'create user';
    public static final String CREATE_ENROLL_COMMAND =      'create enrollment';
    public static final String WAIT_VLE_ID_COMMAND =        'wait for VLE ID';
    public static final String UPDATE_ACTIVATION_COMMAND =  'update user activation';
    public static final String DELETE_ENROLL_COMMAND =      'delete enrollment';
    public static final String CREATE_MUDULE_COMMAND =      'create module/course';    
    public static final String UPDATE_MUDULE_COMMAND =      'update module/course';    
    
    // Action statuses
    public static final String ACTION_NEW_STATUS =      'New';
    public static final String ACTION_BATCH_STATUS =    'Batch';
    public static final String ACTION_DELAYED_STATUS =  'Delayed';
    public static final String ACTION_DONE_STATUS =     'Done';
    public static final String ACTION_CANCELED_STATUS = 'Canceled';
    
    // Command statuses
    public static final String COMMAND_NEW_STATUS =     'New';
    public static final String COMMAND_ERROR_STATUS =   'Error';
    public static final String COMMAND_DONE_STATUS =    'Done';
    
    // Valid Obj_Type__c constants
    public static final String OBJ_TYPE_CONTACT =           'Contact';
    public static final String OBJ_TYPE_STUDENT_PROGRAMME = 'Student_Programme__c';
    public static final String OBJ_TYPE_MODULE_ROLE =       'Module_Role__c';
    public static final String OBJ_TYPE_MODULE =            'Module__c';
    
    // Time constants
    //** Suyati Modified Start 16-02-2016
    public static final String EXPIRY_DAYS_FOR_OLD_ACTIONS = 'Expiry Days for Old Vle Action';
    //public static final Integer EXPIRY_DAYS_FOR_OLD_ACTIONS = 3;
    //** Suyati Modified End
    public static final Integer MINUTES_FOR_REPEAT_DELAYED = 30; // add this time to now() for 'delayed' actions
    
    /**
     * Structure class for holding all info about VLE action and commands   
     */
    public class ActionStructure {
        private List<VLE_Sync_Command__c> detailCommands = new List<VLE_Sync_Command__c>(); 
        public VLE_Action__c masterAction { get; set; }
        public List<VLE_Sync_Command__c> getDetailCommands() {
            return detailCommands;
        }
    }
    
    /**
     * Interface for class that implements VLE action
     */
    public interface IAction {
        /**
         * Create action and command object to persist in DB
         * @return Structure with action and commands ready to insert into DB or null
         */
        ActionStructure create();
        
        /**
         * Try to synchronize action
         * @param action Action with details (commands)
         */
        void perform(VLE_Action__c action);
    }
    
    public class ParseResult {
        public Boolean result { get; set; }
        public List<sObject> updatedRecords = new List<sObject>();
    }
    
    /**
     * Interface for class that implements VLE command
     */
    public interface ICommand {
        /**
         * Prepare command data
         * @param cmd Record of command
         */
        void init(VLE_Sync_Command__c cmd);
        
        /**
         * Perform HTTP(s) callout
         * @param userContext UserContext of API call
         * @return HttpResponse object or exception
         */
        HttpResponse makeCallout(VleServices.IUserContext userContext);
        /**
         * Try to get useful information from VleServices.RESULT_OKAY response
         * @param HttpResponse Response of API
         * @return Structure with result and list of updated records
         */
        ParseResult parseResultOk(HttpResponse resp);
    }
    
    /**
     * Indicates state of batch (true - running, false - not)
     */
    public static Boolean isBatchRunning {
        get {
            if ( isBatchRunning == null ) {
                // get from Custom Settings, true by default
                VLE__c vle = VLE__c.getInstance(VleServices.CS_NAME);
                isBatchRunning = ( vle == null ) ? true : vle.BatchIsRunning__c;
            }
            return isBatchRunning;
        }
        set {
            isBatchRunning = value;
            VLE__c vle = VLE__c.getInstance(VleServices.CS_NAME);
            if ( vle != null ) {
                update new VLE__c(Id = vle.Id, BatchIsRunning__c = value);
            }
        }
    }
    
    /**
     * Create certain action related to the object
     * @param name Action's name
     * @param recordId Id of record
     * @param status of 
     * @return Action instance
     */
    public static VLE_Action__c createAction(String name, Id recordId, String status) {
        return new VLE_Action__c(Name = recordId, Action__c = name, Status__c = status);
    }
    
    /**
     * Create command object
     * @param name Name of command
     * @param recordId Id of record related to command
     * @param orderNumber Order indicator
     * @param objType Name of related object
     * @params params JSON string with parameters
     * @return Command instance
     */
    public static VLE_Sync_Command__c createCommand(String name, String recordId, Integer orderNumber, String objType, String params) {
        return new VLE_Sync_Command__c(
            Name = recordId, Command__c = name, Obj_Type__c = objType,
            Order__c = orderNumber, Params__c = params, Status__c = COMMAND_NEW_STATUS
        );
    }
    
    /**
     * Return VLE_Action__c with related commands
     * @param actionId Id of action
     * @return Action with related commands or null 
     */
    public static VLE_Action__c findActionWithCommands(Id actionId) {
        List<VLE_Action__c> actions = [
            SELECT Action__c, Name, Next_Try__c, Note__c, Status__c,
                ( SELECT Command__c, Error_Count__c, Last_Error_Message__c, Name,
                    Obj_Type__c, Order__c, Params__c, Status__c, VLE_Action__c
                  FROM VLE_Sync_Commands__r
                   ORDER BY Order__c
                )
            FROM VLE_Action__c
            WHERE Id = :actionId
        ];
        System.debug('actions ='+actions);
        return ( actions.isEmpty() ) ? null : actions[0]; 
    }
    
    /**
     * Create a action with commands and add to queue.
     * Only unique action+id will be added
     * @param action Instance of action 
     */
    public static void addToQueue(IAction action, String actionName, Id relatedId) {
        String mapKey = actionName + relatedId;
        if ( !uniqActions.contains(mapKey) ) {
            uniqActions.add(mapKey);
            ActionStructure aStruct = action.create();
            if ( aStruct != null ) {
                itemsToSync.add(aStruct);
            }
        }
    }
    
    /**
     * Add items from queue to the database and clear queue.
     * First with new (future) status, other with 'delayed'
     * @return Queue that has been cleared 
     */
    public static List<ActionStructure> persistQueue() {
        // mark as batch over future limits
        Integer numberOfFutureCalls = Limits.getLimitFutureCalls() - Limits.getFutureCalls();
        if ( numberOfFutureCalls < itemsToSync.size() ) {
            for (Integer i = numberOfFutureCalls; i < itemsToSync.size(); i++) {
                itemsToSync[i].masterAction.Status__c = ACTION_BATCH_STATUS;
            }
        }
        System.debug('>>> here 2 >>>');
        // insert actions
        List<VLE_Action__c> actionList = new List<VLE_Action__c>();
        for (ActionStructure aStruct: itemsToSync) {
            actionList.add(aStruct.masterAction);
        }
        insert actionList;
        
        // insert commands
        List<VLE_Sync_Command__c> commandList = new List<VLE_Sync_Command__c>(); 
        for (Integer i = 0; i < actionList.size(); i++) {
            ActionStructure aStruct = itemsToSync[i];
            for (VLE_Sync_Command__c syncCommand: aStruct.getDetailCommands()) {
                syncCommand.VLE_Action__c = aStruct.masterAction.Id;
                commandList.add(syncCommand);
            }
        }
        insert commandList;
        
        System.debug('>>> actionList >>>' + actionList);
        // perform future calls
        for (VLE_Action__c actionItem: actionList) {
            if ( actionItem.Status__c == ACTION_NEW_STATUS ) {
                System.debug(LoggingLevel.ERROR, '@@@ Running future action: ' + actionItem.Action__c);
                syncActionFuture(actionItem.Id);
            }
        }
        System.debug('>>> here 3 >>>');
        // clear queue and return previous state
        List<ActionStructure> prevList = new List<ActionStructure>(itemsToSync);
        itemsToSync.clear();
        return prevList;
    }
    
    /**
     * Do action by ID as future call
     * @param vleActionId Id of action
     */
    @Future(callout=true)
    public static void syncActionFuture(Id vleActionId) {
        syncActionBatch(vleActionId);
    }
    
    /**
     * Do action by ID
     * @param vleActionId Id of action
     */
    public static void syncActionBatch(Id vleActionId) {
        VLE_Action__c action = findActionWithCommands(vleActionId);
        if ( action != null ) {
            String actionClassName = actionMap.get(action.Action__c);
            if ( actionClassName != null ) {
                // create instance of class that implements action
                Type instanceType = Type.forName(actionClassName);
                IAction actionImpl = (IAction) instanceType.newInstance();
                actionImpl.perform(action);
            }
        }
    }
    
    /**
     * Try to find actions for Batch
     * @return True if some delayed actions were found
     */
    public static Boolean prepareActionsForSync() {
        List<VLE_Action__c> delayedActions = [
            SELECT Id
            FROM VLE_Action__c
            WHERE Next_Try__c < :Datetime.now()
            AND Status__c = :ACTION_DELAYED_STATUS
            ORDER BY LastModifiedDate
            LIMIT :PREPARED_ACTIONS_SIZE_LIMIT
        ];
        
        if ( !delayedActions.isEmpty() ) {
            // ready for batch
            for (VLE_Action__c action: delayedActions) {
                action.Status__c = ACTION_BATCH_STATUS;
            }
            update delayedActions;
            return true;
        }
        
        return false;
    }
    
    /**
     * Looking for actions with status 'Batch'
     * @param True if even one action was found
     */
    public static Boolean isAnyActionsReadyForSync() {
        List<VLE_Action__c> actionList = [SELECT Id FROM VLE_Action__c WHERE Status__c = :ACTION_BATCH_STATUS LIMIT 1];
        return !actionList.isEmpty();
    }
    
    /**
     * Run Batch for synchronization if:
     * there is actions to sync and running of batch is allowed 
     * @return True of batch was added to queue
     */
    public static Boolean runSyncBatch() {
        if ( !isBatchRunning ) {
            // check for available actions
            if ( isAnyActionsReadyForSync() ) {
                isBatchRunning = true;
                Database.executeBatch(new VleSyncBatch(), 1);
                return true;
            }
        }
        return false;
    }
    
    /**
     * Delete from DB old synchronized actions.
     * @param expiryDateTime Records earlier than LastModifiedDate should be deleted
     */
    public static void removeOldSyncActions(Datetime expiryDateTime) {
        Set<String> removeStatuses = new Set<String> {ACTION_DONE_STATUS, ACTION_CANCELED_STATUS };
        List<VLE_Action__c> oldActions = [SELECT Id FROM VLE_Action__c WHERE LastModifiedDate < :expiryDateTime AND Status__c IN :removeStatuses];
        delete oldActions;
    }
    
    /**
     * This method is called only one at execution context.
     * It try to initiate all services like run batch job, find actions for batch and clean up old actions
     */
    public static void runAsyncServices() {
        if ( firstTryToRunBatch ) {
            firstTryToRunBatch = false;
            // clean up some old records
            //** Suyati Modified  Start 16-02-2016
            Expiry_Days_For_Old_Vle_Actions__c expiryDaysForOldVleAction = Expiry_Days_For_Old_Vle_Actions__c.getInstance(EXPIRY_DAYS_FOR_OLD_ACTIONS);
            if(expiryDaysForOldVleAction != null){
                integer expiryDays = (integer)expiryDaysForOldVleAction.Expiry_Days__c;
                System.debug('expiryDays ='+expiryDays);
                Datetime expDt = Date.today().addDays(-expiryDays);
                System.debug('expDt = '+expDt);          
                removeOldSyncActions(expDt);
            }
            //***Suyati Modified End
            //** Suyati Modified Start 15-02-2016
            // find delayed actions
            //prepareActionsForSync();
            // call batch job
            //runSyncBatch();
            //** Suyati Modified End
        }
    }

}