objects/Contact.object
<CustomObject><fields>
        <fullName>VLE_ID__c</fullName>
        <description>UserId for desire2learn API</description>
        <label>VLE_ID</label>
        <length>32</length>
        <type>Text</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel><recordTypes>
        <fullName>Staff</fullName>
        <active>true</active>
        <label>Staff</label>
    </recordTypes></CustomObject>

objects/VLE_Action__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Object for perform complex action to VLE API</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>VLE Action</label><nameField>
        <label>VLE Action Name</label>
        <type>Text</type>
    </nameField><pluralLabel>VLE Actions</pluralLabel><sharingModel>Private</sharingModel></CustomObject>

objects/VLE_Sync_Command__c.object
<CustomObject><fields>
        <fullName>Command__c</fullName>
        <description>Type of command</description>
        <label>Command</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>VLE_Action__c</fullName>
        <label>VLE Action</label>
        <referenceTo>VLE_Action__c</referenceTo>
        <relationshipLabel>VLE Sync Commands</relationshipLabel>
        <relationshipName>VLE_Sync_Commands</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Simple VLE API calls to perform only single API methods</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>false</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>VLE Sync Command</label><nameField>
        <label>VLE Sync Command Name</label>
        <type>Text</type>
    </nameField><pluralLabel>VLE Sync Commands</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/VleMakeUserInactiveAction.cls
/**
 * Action that makes user inactive
 */
public with sharing class VleMakeUserInactiveAction extends VleBaseAction {
	
	/**
	 * Student of Staff person
	 */
	public Contact person { get; set; }
	
	@TestVisible
	protected override Boolean findActionData(VLE_Action__c action) {
		person = VleDaoServices.findContact(action.Name);
        return person != null;
    }
    
    @TestVisible
    protected override VleSyncServices.ICommand findCommand(VLE_Sync_Command__c cmd) {
        VleSyncServices.ICommand cmdImpl;

        if ( cmd.Command__c == VleSyncServices.WAIT_VLE_ID_COMMAND ) {
        	VleCommands.WaitForVleId waitCmd = new VleCommands.WaitForVleId();
	        waitCmd.objName = VleSyncServices.OBJ_TYPE_CONTACT;
	        waitCmd.recordId = person.Id;
	        cmdImpl = waitCmd;
        } else if ( cmd.Command__c == VleSyncServices.UPDATE_ACTIVATION_COMMAND ) {
        	VleCommands.UpdateUserActivation inactiveCmd = new VleCommands.UpdateUserActivation();
        	inactiveCmd.person = person;
        	cmdImpl = inactiveCmd;
        }

        return cmdImpl;
    }
    
    public VleSyncServices.ActionStructure create() {
        VleSyncServices.ActionStructure aStruct = new VleSyncServices.ActionStructure();
        aStruct.masterAction = VleSyncServices.createAction(
            VleSyncServices.MAKE_VLE_USER_INACTIVE_ACTION, person.Id, VleSyncServices.ACTION_NEW_STATUS
        );
        
        // check VLE_ID__c field on Contact
        Vle_Sync_Command__c cmd = VleSyncServices.createCommand(
            VleSyncServices.WAIT_VLE_ID_COMMAND, person.Id, 1,
            VleSyncServices.OBJ_TYPE_CONTACT, null
        );
        aStruct.getDetailCommands().add(cmd);
        
        // add command to set user inactive
        VleStructures.UserActivationData actData = new VleStructures.UserActivationData();
        actData.IsActive = false;
        cmd = VleSyncServices.createCommand(
            VleSyncServices.UPDATE_ACTIVATION_COMMAND, person.Id, 2,
            VleSyncServices.OBJ_TYPE_CONTACT, JSON.serialize(actData)
        );
        aStruct.getDetailCommands().add(cmd);
        
        
        return aStruct;         
    }
    
}