objects/Contact.object
<CustomObject><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Hidden field for Test Class use, to exclude from Flows</description>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel><recordTypes>
        <fullName>Staff</fullName>
        <active>true</active>
        <label>Staff</label>
    </recordTypes></CustomObject>

objects/Module__c.object
<CustomObject><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Instances of Modules</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module</label><nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Modules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Module_Role__c.object
<CustomObject><fields>
        <fullName>Module_Role__c</fullName>
        <description>Defines role for Module Spec, and against Module Instance for VLE integration</description>
        <label>Module Role</label>
        <picklist>
            <picklistValues>
                <fullName>Module Convenor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Module Moderator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Examiner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Teacher</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Staff with Roles</relationshipLabel>
        <relationshipName>Module_Roles</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Join object between Staff (Contacts) and Modules (both Instances and Version objects). Will allow definition of staff role on a module and be used in VLE integration to define extent of staff enrolment.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Module Role</label><nameField>
        <displayFormat>MR-{00000000}</displayFormat>
        <label>Module Role Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Module Roles</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Programme__c.object
<CustomObject><fields>
        <fullName>Programme_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme Version</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Programme_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Versions, Versions, Specification, Versions - Pre Approved, Specification Edit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Programme Instances</relationshipLabel>
        <relationshipName>Programmes_Instances</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme_Module__c.object
<CustomObject><fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To find correct Module type first the few character of Module title then click magnifying glass for available options</inlineHelpText>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Assigned Programmes</relationshipLabel>
        <relationshipName>Programme_Modules</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Programme__c</fullName>
        <description>Via Master-Detail relationship, no reparenting allowed</description>
        <label>Programme</label>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Assigned Modules</relationshipLabel>
        <relationshipName>Programme_Modules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Many to many object, to allow one Module (instance) to be a member of multiple Programmes (instances)</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Programme Module</label><nameField>
        <displayFormat>PMI-{00000000}</displayFormat>
        <label>Programme Module</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Programme Modules</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Programme_Version__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme Version</label><nameField>
        <label>Programme Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programme Versions</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/VLE__c.object
<CustomObject><fields>
        <fullName>API_Host__c</fullName>
        <description>Domain name of API host</description>
        <label>API Host</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>App_ID__c</fullName>
        <description>App ID from desire2learn</description>
        <label>App ID</label>
        <length>22</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>App_Key__c</fullName>
        <description>App Key for desire2learn (secret)</description>
        <label>App Key</label>
        <length>22</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>Default_Staff_Role_VLE_ID__c</fullName>
        <description>If Module Role has no matches for VLE Role Id - this value is used as default for Staff</description>
        <inlineHelpText>If Module Role has no matches for VLE Role Id - this value is used as default for Staff</inlineHelpText>
        <label>Default Staff Role VLE ID</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Default_Student_Role_VLE_ID__c</fullName>
        <description>If Program Type has no matches for VLE Role Id - this value is used as default for Student</description>
        <inlineHelpText>If Program Type has no matches for VLE Role Id - this value is used as default for Student</inlineHelpText>
        <label>Default Student Role VLE ID</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields>
        <fullName>External_Examiner_Role_ID__c</fullName>
        <description>ID of External Examiner role</description>
        <label>External Examiner Role ID</label>
        <length>32</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Instructor_Role_ID__c</fullName>
        <description>ID of Instructor role</description>
        <label>Instructor Role ID</label>
        <length>32</length>
        <type>Text</type>
    </fields><fields>
        <fullName>User_ID__c</fullName>
        <description>User ID for API calls</description>
        <label>User ID</label>
        <length>22</length>
        <type>Text</type>
    </fields><fields>
        <fullName>User_Key__c</fullName>
        <description>Key for API user (secret)</description>
        <label>User Key</label>
        <length>22</length>
        <type>Text</type>
    </fields><customSettingsType>List</customSettingsType><description>Credentials for VLE external service</description><enableFeeds>false</enableFeeds><label>VLE parameters</label><visibility>Protected</visibility></CustomObject>

objects/VLE_Action__c.object
<CustomObject><fields>
        <fullName>Action__c</fullName>
        <description>Type of action to VLE API</description>
        <label>Action</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Object for perform complex action to VLE API</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>VLE Action</label><nameField>
        <label>VLE Action Name</label>
        <type>Text</type>
    </nameField><pluralLabel>VLE Actions</pluralLabel><sharingModel>Private</sharingModel></CustomObject>

objects/VLE_Sync_Command__c.object
<CustomObject><fields>
        <fullName>Command__c</fullName>
        <description>Type of command</description>
        <label>Command</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>VLE_Action__c</fullName>
        <label>VLE Action</label>
        <referenceTo>VLE_Action__c</referenceTo>
        <relationshipLabel>VLE Sync Commands</relationshipLabel>
        <relationshipName>VLE_Sync_Commands</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Simple VLE API calls to perform only single API methods</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>false</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>VLE Sync Command</label><nameField>
        <label>VLE Sync Command Name</label>
        <type>Text</type>
    </nameField><pluralLabel>VLE Sync Commands</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/TestVleStaffRoleAction.cls
/**
 * Unit test to VleStaffRoleAction class
 */
@isTest
private class TestVleStaffRoleAction {
    
    static final String PROGRAMME_VERSION = 'Programme_Version__c';
    static final String PROGRAMME_NAME = 'Diploma in Tropical Nursing';
    static final String PROGRAMME_TYPE = ApplyServices.PT_PROFESSIONAL_DIPLOMA;
    static final String TEST_MODULE_VLE_ID = '135';
    static final Long TEST_ROLE_ID = 246;
    static final Long TEST_INSTRUCTOR_ROLE_ID = 357;
    
    static Programme__c prog;
    static Contact staff;
    static Programme_Version__c mv;
    static Programme_Version__c pv;
    static Module__c m;
    static Module_Role__c mr;
    static VleStaffRoleAction actionImpl;
    
    static void setupCredentials() {
        VLE__c vle = new VLE__c(
            Name = VleServices.CS_NAME, API_Host__c = 'vle-host.com', App_ID__c = 'app_id', App_Key__c = 'app_key',
            External_Examiner_Role_ID__c = '468', Instructor_Role_ID__c = String.valueOf(357), User_ID__c = 'user_id', User_Key__c = 'user_key',
            Default_Staff_Role_VLE_ID__c = '102', Default_Student_Role_VLE_ID__c = '103'
        ); 
        insert vle;
    }
    
    static void setupTestData() {
        Id mvrtId = CommonUtils.findRecordTypeIdByDev(PROGRAMME_VERSION, ApplyServices.RT_MASTER_PV_DEVNAME);
        mv = VleTestingUtils.createMasterProgrammeVersion(PROGRAMME_NAME, mvrtId, PROGRAMME_TYPE, true);
        Id rtId = CommonUtils.findRecordTypeIdByDev(PROGRAMME_VERSION, ApplyServices.RT_VERSION_PV_DEVNAME);
        pv = VleTestingUtils.createProgrammeVersion(PROGRAMME_NAME, rtId, PROGRAMME_TYPE, mv.Id, true);
        prog = VleTestingUtils.createProgramme(PROGRAMME_NAME, pv.Id, true);
        m = VleTestingUtils.createModule('Test Module', TEST_MODULE_VLE_ID, true);
        Programme_Module__c pm = new Programme_Module__c(Programme__c = prog.Id, Module__c = m.Id);
        pm.Test_Class_Record__c = true;
        insert pm;
        staff = VleTestingUtils.CreateStaff(true);
        mr = VleTestingUtils.createModuleRole(staff, m, ModuleRoleServices.MODULE_CONVENOR_ROLE_NAME, true);
        actionImpl = new VleStaffRoleAction();
        actionImpl.moduleRole = mr; 
    }

    static testMethod void testCreate() {
        setupCredentials();
        setupTestData();
        
        // insert
        actionImpl.actionType = VleStaffRoleAction.INSERT_ACTION_TYPE;
        VleSyncServices.ActionStructure aStruct = actionImpl.create();
        System.assertEquals(VleSyncServices.VLE_STAFF_ROLE_ACTION, aStruct.masterAction.Action__c);
        System.assertEquals(2, aStruct.getDetailCommands().size());
        System.assertEquals(VleSyncServices.WAIT_VLE_ID_COMMAND, aStruct.getDetailCommands()[0].Command__c);
        System.assertEquals(VleSyncServices.CREATE_ENROLL_COMMAND, aStruct.getDetailCommands()[1].Command__c);
        
        // update
        actionImpl.actionType = VleStaffRoleAction.UPDATE_ACTION_TYPE;
        aStruct = actionImpl.create();
        System.assertEquals(VleSyncServices.VLE_STAFF_ROLE_ACTION, aStruct.masterAction.Action__c);
        System.assertEquals(3, aStruct.getDetailCommands().size());
        System.assertEquals(VleSyncServices.WAIT_VLE_ID_COMMAND, aStruct.getDetailCommands()[0].Command__c);
        System.assertEquals(VleSyncServices.DELETE_ENROLL_COMMAND, aStruct.getDetailCommands()[1].Command__c);
        System.assertEquals(VleSyncServices.CREATE_ENROLL_COMMAND, aStruct.getDetailCommands()[2].Command__c);
        
        // delete
        actionImpl.actionType = VleStaffRoleAction.DELETE_ACTION_TYPE;
        aStruct = actionImpl.create();
        System.assertEquals(VleSyncServices.VLE_STAFF_ROLE_ACTION, aStruct.masterAction.Action__c);
        System.assertEquals(2, aStruct.getDetailCommands().size());
        System.assertEquals(VleSyncServices.WAIT_VLE_ID_COMMAND, aStruct.getDetailCommands()[0].Command__c);
        System.assertEquals(VleSyncServices.DELETE_ENROLL_COMMAND, aStruct.getDetailCommands()[1].Command__c);
        
        Boolean findActionData = actionImpl.findActionData(new VLE_Action__c());
        
        VLE_Sync_Command__c sCm = new VLE_Sync_Command__c();
        sCm.Command__c = VleSyncServices.WAIT_VLE_ID_COMMAND;
        VleSyncServices.ICommand actionImplVar = actionImpl.findCommand(sCm);
        
        sCm.Command__c = VleSyncServices.CREATE_ENROLL_COMMAND;
        actionImplVar = actionImpl.findCommand(sCm);
        
        sCm.Command__c = VleSyncServices.DELETE_ENROLL_COMMAND;
        //actionImplVar = actionImpl.findCommand(sCm);
    }
    
    static testMethod void testFindCommand() {
        setupCredentials();
        setupTestData();
        actionImpl.actionType = VleStaffRoleAction.UPDATE_ACTION_TYPE;
        VleSyncServices.ActionStructure aStruct = actionImpl.create();
        
        VleSyncServices.ICommand waitCmd = actionImpl.findCommand(aStruct.getDetailCommands()[0]);
        System.assert(waitCmd instanceof VleCommands.WaitForVleId);
        VleSyncServices.ICommand delEnrollCmd = actionImpl.findCommand(aStruct.getDetailCommands()[1]);
        System.assert(delEnrollCmd instanceof VleCommands.DeleteEnrollment);
        VleSyncServices.ICommand createEnrollCmd = actionImpl.findCommand(aStruct.getDetailCommands()[2]);
        System.assert(createEnrollCmd instanceof VleCommands.CreateEnrollment);
    }
    
    static testMethod void testFindActionData() {
        setupCredentials();
        setupTestData();
        VleSyncServices.ActionStructure aStruct = actionImpl.create();
        
        Boolean res = actionImpl.findActionData(aStruct.masterAction);
        System.assert(res);
        
        delete mr;
        res = actionImpl.findActionData(aStruct.masterAction);
        System.assert(res == false);
    }
    
}