objects/Contact.object
<CustomObject><fields>
        <fullName>LSTM_No__c</fullName>
        <description>As requested by KT 20th Oct</description>
        <displayFormat>{00000000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>Autonumber, unique Student identifier</inlineHelpText>
        <label>LSTM No</label>
        <type>AutoNumber</type>
    </fields><fields>
        <fullName>Registration_Password__c</fullName>
        <description>This field stores a temporary string of characters for use in an Apex class</description>
        <label>Registration Password</label>
        <length>12</length>
        <type>Text</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Page_Copy__c.object
<CustomObject><fields>
        <fullName>Active_Date__c</fullName>
        <label>Active Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Body_Copy__c</fullName>
        <inlineHelpText>This is the main page content to be displayed on the community page</inlineHelpText>
        <label>Body Copy</label>
        <length>32768</length>
        <type>Html</type>
    </fields><fields>
        <fullName>Copy_Location__c</fullName>
        <inlineHelpText>Defines where the copy will be used</inlineHelpText>
        <label>Copy Location</label>
        <picklist>
            <picklistValues>
                <fullName>Applicant Homepage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Offer page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmation of Place page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Homepage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Welcome</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submission Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Registration Terms Conditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Registration Data Protection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New User Information</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Page_Status__c</fullName>
        <label>Page Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For Sys Admin defined content, to be used in specific Visualforce pages, such as home pages in Community portals.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Read</externalSharingModel><label>Page Copy</label><nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Page Copy Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Page Copy</pluralLabel><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>LSTM_No__c</fullName>
        <description>Taken from Contact object</description>
        <label>LSTM No</label>
        <length>12</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Registration_Password__c</fullName>
        <description>Takes value from Contact.LSTM TP, via workflow</description>
        <formula>Student__r.Registration_Password__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Registration Password</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Stage__c</fullName>
        <description>NOTE : This field drives the Student Programme flow - DO NOT change pick list values without discussion with the I.T / Dev Team</description>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Checked</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional</fullName>
                <color>#339999</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unconditional</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
                <color>#FF99FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Expected</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Registered</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
                <color>#419249</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#666666</color>
            </picklistValues>
            <picklistValues>
                <fullName>Offered</fullName>
                <color>#DDDDDD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reverted from Master:Detail as per LSTM requirement</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Programmes</relationshipLabel>
        <relationshipName>Student_Programmes1</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/NewUserPageContExt.cls
public class NewUserPageContExt {


    public final String PAGE_COPY_LOCATION = 'New User Information';
    public final String ACTIVE_STATUS = 'Active';
    public final String EMAIL_DOMAIN = '@lstmed.ac.uk';
    public final integer PASSWORD_LENGTH = 8;

    public Contact student {get; set;}
    public Student_Programme__c sp {get; set;}
    public Page_Copy__c pageCopy {get; set;}
    public boolean saveContact {get; set;}
    public boolean saveProgramme {get; set;}
    public String displayPassword {get; set;}
    public String lstmEmail {get; set;}
    
    public NewUserPageContExt(){
        saveContact = false; 
        saveProgramme = false;
        
        Id spId = ApexPages.currentPage().getParameters().get('Id');
        if (spId != null){
        //Suyati modified code for 6.1
            sp = [select s.Id, s.Stage__c, s.Student__c, s.Student__r.LSTM_No__c,
                    s.Student__r.Registration_Password__c from Student_Programme__c s where s.Id = :spId LIMIT 1];
            //old code  
            /* sp = [select s.Id, s.Stage__c, s.Student__c, s.Student__r.LSTM_No__c
                     from Student_Programme__c s where s.Id = :spId LIMIT 1]; */                 
           student = [select c.Id, c.LSTM_No__c,c.Registration_Password__c from Contact c where c.Id = :sp.Student__c LIMIT 1];
          //old code    
          //student = [select c.Id, c.LSTM_No__c from Contact c where c.Id = :sp.Student__c LIMIT 1]; 
          //Suyati modified code ends for 6.1
           if (student.Registration_Password__c == null){       
                displayPassword = getPassword(PASSWORD_LENGTH);
                //Encrypted commented by .suyati
               // student.LSTM_Temp_Password__c = displayPassword;
                //Unencrypted .changed name tp to  Registration_Password__c
               student.Registration_Password__c = displayPassword;
                saveContact = true;
            }else {
                //commented for 6.1 by suyati chhnaged name tp to Registration_Password__c 
                //displayPassword = sp.Student__r.LSTM_Temp_Password__c;
                displayPassword = student.Registration_Password__c ;
            }
            
            if (student.LSTM_No__c != null){
                integer intLSTMNo = integer.valueOf(student.LSTM_No__c);
                String strLSTMNo = intLSTMNO.format().replace(',','');
                lstmEmail = strLSTMNO + EMAIL_DOMAIN;
            }else {
                lstmEmail = 'NO LSTM NUMBER FOUND';
            }
            
        }
        
        pageCopy = [select p.Id, p.Body_Copy__c from Page_Copy__c p 
                    where p.Copy_Location__c = :PAGE_COPY_LOCATION and p.Page_Status__c = :ACTIVE_STATUS
                    ORDER BY Active_Date__c DESC LIMIT 1];
    
    }
    
    public PageReference gotoHomePage() {
        //return new PageReference('/');
        return Page.StudentLandingPage;
    }
    
    public PageReference confirmDetails(){
        if (saveContact){
            update student;
        }
        if (!ApplyServices.COURSE_PRE_REGISTERED_STAGE_NAME.equalsIgnoreCase(sp.Stage__c)){
            sp.Stage__c = ApplyServices.COURSE_PRE_REGISTERED_STAGE_NAME;    
            saveProgramme = true;
        }
            
        if (saveProgramme){
            update sp;
        }
        
        return gotoHomePage();
    }
    
    public String getPassword(Integer len)
     {
        Blob blobKey = crypto.generateAesKey(128);
        String key = EncodingUtil.convertToHex(blobKey);
        System.debug('*** -- Key from getPassword = ' + key + ' -- ***');
        return key.substring(0,len);
     }

}