objects/Contact.object
<CustomObject><fields>
        <fullName>VLE_Visibility__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VLE_Visibility</label>
        <type>Checkbox</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel><recordTypes>
        <fullName>Staff</fullName>
        <active>true</active>
        <label>Staff</label>
    </recordTypes></CustomObject>

objects/Module_Role__c.object
<CustomObject><fields>
        <fullName>Module_Role__c</fullName>
        <description>Defines role for Module Spec, and against Module Instance for VLE integration</description>
        <label>Module Role</label>
        <picklist>
            <picklistValues>
                <fullName>Module Convenor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Module Moderator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Examiner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Teacher</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Staff__c</fullName>
        <label>Staff</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Staff</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Module Roles</relationshipLabel>
        <relationshipName>Module_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Join object between Staff (Contacts) and Modules (both Instances and Version objects). Will allow definition of staff role on a module and be used in VLE integration to define extent of staff enrolment.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Module Role</label><nameField>
        <displayFormat>MR-{00000000}</displayFormat>
        <label>Module Role Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Module Roles</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/ContactServices.cls
/**
 * Service class for working with Contact (Student) records
 */
public with sharing class ContactServices {
    /**
     * Single point to the all Contact triggers
     */
    public static void onTrigger(List<Contact> newList, List<Contact> oldList, Map<Id,Contact> newMap, Map<Id,Contact> oldMap,
			Boolean isBefore, Boolean isAfter, Boolean isInsert, Boolean isUpdate, Boolean isDelete) {
    	if (isAfter) {
    		if (isUpdate) {
    			findVLEVisibleModuleRoles(newList, oldMap);
    			findVLENotVisibleContacts(newList, oldMap);
    		}
    	}
	}

    public static List<Module_Role__c> findVLEVisibleModuleRoles(List<Contact> newList, Map<Id,Contact> oldMap) {
        List<Contact> cList = new List<Contact>();
        Id staffRecTypeId = CommonUtils.findRecordTypeIdByDev('Contact', 'Staff');
        for (Contact c : newList) {
            if (staffRecTypeId == c.RecordTypeId && c.VLE_Visibility__c == true && oldMap.get(c.Id).VLE_Visibility__c == false) {
                cList.add(c);
            }
        }
       
        if ( cList.size() > 0 ) {
            // create staff actions
            List<Contact> staffList = VleDaoServices.findStaffWithModuleRoles(cList);
            for (Contact staff: staffList) {
                VleCreateStaffAction createStaffAction = new VleCreateStaffAction();
                createStaffAction.staff = staff;
                VleSyncServices.addToQueue(createStaffAction, VleSyncServices.CREATE_VLE_STAFF_ACTION, staff.Id);
            }
            VleSyncServices.persistQueue(); // sync
            return [SELECT Id FROM Module_Role__c WHERE Staff__c IN :cList];
        }
        return new List<Module_Role__c>();
    }

    public static List<Contact> findVLENotVisibleContacts(List<Contact> newList, Map<Id,Contact> oldMap) {
        List<Contact> cList = new List<Contact>();
        for (Contact c : newList) {
            if (c.VLE_Visibility__c == false && oldMap.get(c.Id).VLE_Visibility__c == true) {
                cList.add(c);
            }
        }
        if (cList.size() > 0) {
            // create actions to make user inactive
            for (Contact c: cList) {
                VleMakeUserInactiveAction inactiveAction = new VleMakeUserInactiveAction();
                inactiveAction.person = c;
                VleSyncServices.addToQueue(inactiveAction, VleSyncServices.MAKE_VLE_USER_INACTIVE_ACTION, c.Id);
            }
            VleSyncServices.persistQueue(); // sync
        }
        return cList;
    }
    
}