objects/Contact.object
<CustomObject><fields>
        <fullName>VLE_ID__c</fullName>
        <description>UserId for desire2learn API</description>
        <label>VLE_ID</label>
        <length>32</length>
        <type>Text</type>
    </fields><fields>
        <fullName>VLE_Visibility__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VLE_Visibility</label>
        <type>Checkbox</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel><recordTypes>
        <fullName>Staff</fullName>
        <active>true</active>
        <label>Staff</label>
    </recordTypes></CustomObject>

objects/Module__c.object
<CustomObject><fields>
        <fullName>VLE_ID__c</fullName>
        <description>Course offering ID at VLE side</description>
        <label>VLE ID</label>
        <length>32</length>
        <type>Text</type>
    </fields><fields>
        <fullName>VLE_Visibility__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To prevent some records triggering actions in VLE</description>
        <inlineHelpText>To prevent some records triggering actions in VLE</inlineHelpText>
        <label>VLE Visibility</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Instances of Modules</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module</label><nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Modules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Module_Role__c.object
<CustomObject><fields>
        <fullName>Module_Role__c</fullName>
        <description>Defines role for Module Spec, and against Module Instance for VLE integration</description>
        <label>Module Role</label>
        <picklist>
            <picklistValues>
                <fullName>Module Convenor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Module Moderator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Examiner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Teacher</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Staff with Roles</relationshipLabel>
        <relationshipName>Module_Roles</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Staff__c</fullName>
        <label>Staff</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Staff</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Module Roles</relationshipLabel>
        <relationshipName>Module_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Join object between Staff (Contacts) and Modules (both Instances and Version objects). Will allow definition of staff role on a module and be used in VLE integration to define extent of staff enrolment.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Module Role</label><nameField>
        <displayFormat>MR-{00000000}</displayFormat>
        <label>Module Role Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Module Roles</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/VLE_Action__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Object for perform complex action to VLE API</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>VLE Action</label><nameField>
        <label>VLE Action Name</label>
        <type>Text</type>
    </nameField><pluralLabel>VLE Actions</pluralLabel><sharingModel>Private</sharingModel></CustomObject>

objects/VLE_Sync_Command__c.object
<CustomObject><fields>
        <fullName>Command__c</fullName>
        <description>Type of command</description>
        <label>Command</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>Params__c</fullName>
        <description>Additional parameters for command in the JSON format</description>
        <label>Params</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>VLE_Action__c</fullName>
        <label>VLE Action</label>
        <referenceTo>VLE_Action__c</referenceTo>
        <relationshipLabel>VLE Sync Commands</relationshipLabel>
        <relationshipName>VLE_Sync_Commands</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Simple VLE API calls to perform only single API methods</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>false</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>VLE Sync Command</label><nameField>
        <label>VLE Sync Command Name</label>
        <type>Text</type>
    </nameField><pluralLabel>VLE Sync Commands</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/VleCreateStaffAction.cls
/**
 * Action for creating new staff VLE user.
 * Run when Contact.VLE_Visibility__c becomes true
 */
public with sharing class VleCreateStaffAction extends VleBaseAction {
    
    /**
     * Staff person for creating in VLE 
     */
    public Contact staff { get; set; }   
    

    @TestVisible
    protected override Boolean findActionData(VLE_Action__c action) {
        staff = VleDaoServices.findStaffModuleRoles(action.Name);
        return staff != null;
    }
    
    @TestVisible
    protected override VleSyncServices.ICommand findCommand(VLE_Sync_Command__c cmd) {
        VleSyncServices.ICommand cmdImpl;
        if ( cmd.Command__c == VleSyncServices.CREATE_USER_COMMAND ) {
            VleCommands.CreateUser createUserCmd = new VleCommands.CreateUser();
            createUserCmd.person = staff;
            createUserCmd.roleId = Long.valueOf(VleServices.credentials.Default_Staff_Role_VLE_ID__c);
            createUserCmd.sendEmail = VleServices.credentials.Email_To_Staff__c;
            cmdImpl = createUserCmd;
        } else if ( cmd.Command__c == VleSyncServices.CREATE_ENROLL_COMMAND ) {

            if ( cmd.Name == 'DEFAULT_MODULE' ){

                if ( cmd.Params__c != null ){
                    VleCommands.EnrollmentParams enrParams = (VleCommands.EnrollmentParams) JSON.deserialize(cmd.Params__c, VleCommands.EnrollmentParams.class);                    
                    VleCommands.CreateEnrollment enrollCmd = new VleCommands.CreateEnrollment();
                    enrollCmd.cont = staff;
                    enrollCmd.orgUnitId = enrParams.orgUnitId;
                    enrollCmd.roleId = enrParams.roleId;
                    cmdImpl = enrollCmd;
                }

            } else {
                Map<Id,Module_Role__c> moduleRoleMap = new Map<Id,Module_Role__c>(staff.Module_Roles__r); 
                Module_Role__c moduleRole = moduleRoleMap.get(cmd.Name);
                if ( moduleRole != null ) {
                    VleCommands.CreateEnrollment enrollCmd = new VleCommands.CreateEnrollment();
                    enrollCmd.cont = staff;
                    enrollCmd.orgUnitId = Long.valueOf(moduleRole.Module__r.VLE_ID__c);
                    cmdImpl = enrollCmd;
                }
            }
        }
        return cmdImpl;
    }
    

    public VleSyncServices.ActionStructure create() {
        VleSyncServices.ActionStructure aStruct = new VleSyncServices.ActionStructure();
        aStruct.masterAction = VleSyncServices.createAction(
            VleSyncServices.CREATE_VLE_STAFF_ACTION, staff.Id, VleSyncServices.ACTION_NEW_STATUS
        );
        
        if ( String.isEmpty(staff.VLE_ID__c) ) {
            // create user command
            Vle_Sync_Command__c cmd = VleSyncServices.createCommand(
                VleSyncServices.CREATE_USER_COMMAND, staff.Id, 1, VleSyncServices.OBJ_TYPE_CONTACT, null
            );
            aStruct.getDetailCommands().add(cmd);
        }
        
        // enroll all module roles
        if ( staff.Module_Roles__r != null ) {
            for (Module_Role__c mr: staff.Module_Roles__r) {
                
                List<Long> roleIds = VleServices.staffRoles.get(mr.Module_Role__c) != null 
                    ? VleServices.staffRoles.get(mr.Module_Role__c) 
                    : new List<Long> { Long.valueOf( VleServices.credentials.Default_Staff_Role_VLE_ID__c ) };

                if ( roleIds != null ) {
                    for (Long roleId: roleIds) {
                        VleCommands.EnrollmentParams enrParams = new VleCommands.EnrollmentParams();
                        enrParams.roleId = roleId;
                        Vle_Sync_Command__c cmd = VleSyncServices.createCommand(
                            VleSyncServices.CREATE_ENROLL_COMMAND, mr.Id, aStruct.getDetailCommands().size()+1,
                            VleSyncServices.OBJ_TYPE_MODULE_ROLE, JSON.serialize(enrParams)
                        );
                        aStruct.getDetailCommands().add(cmd);
                    }
                }
            }
        }

        //ENROLE TO ORG-WIDE MODULES
        if ( ! VleServices.staffOrgUnitId2RoleVleId.isEmpty() ) {
            for ( String orgUnitId : VleServices.staffOrgUnitId2RoleVleId.keySet() ) {
               
                List<Long> vleRoleIds = VleServices.staffOrgUnitId2RoleVleId.get( orgUnitId ) != null 
                    ? VleServices.staffOrgUnitId2RoleVleId.get( orgUnitId ) 
                    : new List<Long> { Long.valueOf( VleServices.credentials.Default_Staff_Role_VLE_ID__c ) };

                for ( Long roleId : vleRoleIds ){

                    VleCommands.EnrollmentParams enrParams = new VleCommands.EnrollmentParams();
                    enrParams.roleId = roleId;
                    enrParams.orgUnitId = Long.valueOf( orgUnitId );

                    Vle_Sync_Command__c cmd = VleSyncServices.createCommand(
                        VleSyncServices.CREATE_ENROLL_COMMAND, 'DEFAULT_MODULE', aStruct.getDetailCommands().size()+1,
                        VleSyncServices.OBJ_TYPE_MODULE_ROLE, JSON.serialize(enrParams)
                    );
                    aStruct.getDetailCommands().add(cmd);
                }
            }
        }    

        if ( aStruct.getDetailCommands().isEmpty() ) {
            return null;
        } else {
            return aStruct;         
        }
    }
    
}