objects/Contact.object
<CustomObject><fields>
        <fullName>VLE_ID__c</fullName>
        <description>UserId for desire2learn API</description>
        <label>VLE_ID</label>
        <length>32</length>
        <type>Text</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Module__c.object
<CustomObject><fields>
        <fullName>VLE_ID__c</fullName>
        <description>Course offering ID at VLE side</description>
        <label>VLE ID</label>
        <length>32</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Instances of Modules</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module</label><nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Modules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Programme must be active (i.e. most recent)</errorMessage>
            <filterItems>
                <field>Programme__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Student Programmes</relationshipLabel>
        <relationshipName>Students_on_Programme1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reverted from Master:Detail as per LSTM requirement</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Programmes</relationshipLabel>
        <relationshipName>Student_Programmes1</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><recordTypes>
        <fullName>Registered</fullName>
        <active>true</active>
        <label>Non-MSc Registered</label>
    </recordTypes></CustomObject>

objects/VLE_Action__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Object for perform complex action to VLE API</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>VLE Action</label><nameField>
        <label>VLE Action Name</label>
        <type>Text</type>
    </nameField><pluralLabel>VLE Actions</pluralLabel><sharingModel>Private</sharingModel></CustomObject>

objects/VLE_Sync_Command__c.object
<CustomObject><fields>
        <fullName>Command__c</fullName>
        <description>Type of command</description>
        <label>Command</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>Obj_Type__c</fullName>
        <description>Indicates name of related to synchronization object</description>
        <label>Obj Type</label>
        <picklist>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student_Programme__c</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>VLE_Action__c</fullName>
        <label>VLE Action</label>
        <referenceTo>VLE_Action__c</referenceTo>
        <relationshipLabel>VLE Sync Commands</relationshipLabel>
        <relationshipName>VLE_Sync_Commands</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Simple VLE API calls to perform only single API methods</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>false</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>VLE Sync Command</label><nameField>
        <label>VLE Sync Command Name</label>
        <type>Text</type>
    </nameField><pluralLabel>VLE Sync Commands</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/VleCreateStudentBySpAction.cls
/**
 * Implementation of Action: 'create student by SP'
 * Description:
 * When Stage of Student_Progamme__c becomes 'Pre-Registered' we will create VLE student 
 */
public with sharing class VleCreateStudentBySpAction extends VleBaseAction {
    
    /**
     * Student programme with all related data like Contact and Programme__c
     */
    public Student_Programme__c sp { get; set; }
    
    /**
     * List of modules related to Student_Programme__c
     */
    public List<Module__c> modules { get; set; }
    
    @TestVisible
    protected override Boolean findActionData(VLE_Action__c action) {
        sp = VleDaoServices.findStudentProgrammeInfo(action.Name);
        if ( sp != null ) {
        	Set<Id> moduleIds = new Set<Id>();
        	for (VLE_Sync_Command__c cmd: action.VLE_Sync_Commands__r) {
        		if ( cmd.Command__c == VleSyncServices.CREATE_ENROLL_COMMAND && cmd.Obj_Type__c == VleSyncServices.OBJ_TYPE_MODULE ) {
        			moduleIds.add(cmd.Name);
        		}
        	}
        	modules = VleDaoServices.findProgrammeModules(moduleIds);
        	return !modules.isEmpty();
        }
        return false;
    }
    
    @TestVisible
    protected override VleSyncServices.ICommand findCommand(Vle_Sync_Command__c cmd) {
        VleSyncServices.ICommand cmdImpl;
        if ( cmd.Command__c == VleSyncServices.CREATE_USER_COMMAND ) {
            VleCommands.CreateUser createUserCmd = new VleCommands.CreateUser();
            createUserCmd.person = sp.Student__r;
            createUserCmd.roleId = Long.valueOf(VleServices.credentials.Student_Role_ID__c);
            createUserCmd.sendEmail = VleServices.credentials.Email_To_Student__c;
            cmdImpl = createUserCmd;
        } else if ( cmd.Command__c == VleSyncServices.CREATE_ENROLL_COMMAND ) {
        	Map<Id,Module__c> moduleMap = new Map<Id,Module__c>(modules); 
        	Module__c module = moduleMap.get(cmd.Name);
        	if ( module != null ) {
	        	VleCommands.CreateEnrollment takeCmd = new VleCommands.CreateEnrollment();
	        	takeCmd.cont = sp.Student__r;
	        	takeCmd.orgUnitId = Long.valueOf(module.VLE_ID__c);
	        	takeCmd.roleId = Long.valueOf(VleServices.credentials.Student_Role_ID__c);
	        	cmdImpl = takeCmd;
        	}
        }
        return cmdImpl;
    }

    /**
     * Prepare action with commands to 'create student' action
     * Note: sp and modules should be populated before
     * @return Structure with action and commands ready to insert into DB
     */
    public VleSyncServices.ActionStructure create() {
        VleSyncServices.ActionStructure aStruct = new VleSyncServices.ActionStructure();
        aStruct.masterAction = VleSyncServices.createAction(
            VleSyncServices.CREATE_VLE_STUDENT_BY_SP_ACTION, sp.Id, VleSyncServices.ACTION_NEW_STATUS
        );
        
        if ( String.isEmpty(sp.Student__r.VLE_ID__c) && modules != null ) {
            // create user command
            Vle_Sync_Command__c cmd = VleSyncServices.createCommand(
                VleSyncServices.CREATE_USER_COMMAND, sp.Student__c, 1, VleSyncServices.OBJ_TYPE_CONTACT, null
            );
            aStruct.getDetailCommands().add(cmd);
            // attach user to the course offering for each module
            for (Module__c module: modules) {
	            cmd = VleSyncServices.createCommand(
	                VleSyncServices.CREATE_ENROLL_COMMAND, module.Id, aStruct.getDetailCommands().size()+1, VleSyncServices.OBJ_TYPE_MODULE, null
	            );
	            aStruct.getDetailCommands().add(cmd);
            }  
            return aStruct;
        }
        
        return null; // VLE Student already created
    }
    
}