objects/Contact.object
<CustomObject><fields>
        <fullName>Domicile__c</fullName>
        <description>To replace use of HESA Domicile in both admin screens and application forms (using FormAssembly), as easier to use that HESA Code lookup. Apex triggers update to HESA Domicile so correct HESA Code is recorded</description>
        <globalPicklist>HESA_Domicile</globalPicklist>
        <label>Domicile</label>
        <type>Picklist</type>
    </fields><fields>
        <fullName>HESA_Domicile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HESA Domicile</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>HESA_Code__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Domicile</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>HESA_Code__c</referenceTo>
        <relationshipLabel>Contacts (HESA Domicile)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>HESA_Nationality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HESA Nationality</label>
        <referenceTo>HESA_Code__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Nationality__c</fullName>
        <description>To replace use of HESA Nationality in both admin screens and application forms (using FormAssembly), as easier to use that HESA Code lookup. Apex triggers update to HESA Nationality so correct HESA Code is recorded</description>
        <globalPicklist>HESA_Nationality</globalPicklist>
        <label>Nationality</label>
        <type>Picklist</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/HESA_Code__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>HESA_Code__c</fullName>
        <label>HESA Code</label>
        <length>10</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Location of country definitions for HESA Nationality and HESA Domicile. The former is flagged to show EEA countries (for Home/UE v Overseas fee split) 

NB definitions for HESA Disabilities &amp; HESA Ethnicity</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>HESA Code</label><nameField>
        <label>HESA Friendly Name</label>
        <type>Text</type>
    </nameField><pluralLabel>HESA Codes</pluralLabel><recordTypeTrackFeedHistory>true</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>Read</sharingModel><recordTypes>
        <fullName>Domicile</fullName>
        <active>true</active>
        <label>Domicile</label>
    </recordTypes><recordTypes>
        <fullName>MSTUFEE</fullName>
        <active>true</active>
        <description>HESA codes for major source of tuition fees</description>
        <label>MSTUFEE</label>
    </recordTypes><recordTypes>
        <fullName>Nationality</fullName>
        <active>true</active>
        <label>Nationality</label>
    </recordTypes></CustomObject>

objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>MSTUFEE_FA__c</fullName>
        <label>MSTUFEE FA</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Major_source_of_tuition_fees__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Source: https://www.hesa.ac.uk/index.php?option=com_studrec&amp;task=show_file&amp;mnl=15051&amp;href=a^_^MSTUFEE.html</description>
        <inlineHelpText>HESA codes for student's major source of tuition fees</inlineHelpText>
        <label>Major source of tuition fees</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>HESA_Code__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>MSTUFEE</value>
            </filterItems>
            <filterItems>
                <field>HESA_Code__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>HESA_Code__c</referenceTo>
        <relationshipLabel>Student Programmes</relationshipLabel>
        <relationshipName>Student_Programmes</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reverted from Master:Detail as per LSTM requirement</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Programmes</relationshipLabel>
        <relationshipName>Student_Programmes1</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/FormAssemblyLookups.cls
public class FormAssemblyLookups{

    @InvocableMethod
    public static void buildLookups(List<Student_Programme__c> spList) {
        Set<Id> studentIds = new Set<Id>();
        Set<String> domicileNames = new Set<String>();
        Set<Id> spIds = new Set<Id>();
        Set<String> nationalityNames = new Set<String>();
        Set<String> feeNames = new Set<String>();        
        Map<String,Id> domicileMap = new Map<String,Id>();
        Map<String,Id> nationalityMap = new Map<String,Id>();
        Map<String,Id> feeMap = new Map<String,Id>();                        
        
        for(Student_Programme__c sp: spList){
            studentIds.add(sp.Student__c);
            feeNames.add(sp.MSTUFEE_FA__c);
            spIds.add(sp.Id);                            
        }
        
        for(Contact student: [SELECT Id,Domicile__c, HESA_Domicile__c, Nationality__c, HESA_Nationality__c FROM Contact WHERE Id IN: studentIds]){
            domicileNames.add(student.Domicile__c);
            nationalityNames.add(student.Nationality__c);
        }   
        
        for(HESA_Code__c hesaCode : [SELECT Id,Name,RecordTypeId FROM HESA_Code__c WHERE Active__c = true AND (Name IN: domicileNames OR Name IN: nationalityNames OR Name IN: feeNames) ]){
            Map<ID, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.HESA_Code__c.getRecordTypeInfosById();
            if(rtMap.get(hesaCode.RecordTypeId).getName().containsIgnoreCase('Domicile') && domicileNames.contains(hesaCode.Name))  
                domicileMap.put(hesaCode.Name,hesaCode.Id);
            if(rtMap.get(hesaCode.RecordTypeId).getName().containsIgnoreCase('Nationality') && nationalityNames.contains(hesaCode.Name))
                nationalityMap.put(hesaCode.Name,hesaCode.Id); 
            if(rtMap.get(hesaCode.RecordTypeId).getName().containsIgnoreCase('MSTUFEE') && feeNames.contains(hesaCode.Name))
                feeMap.put(hesaCode.Name,hesaCode.Id);                 
        }
        system.debug(nationalityMap);

        List<Contact> studentsToUpdate = new List<Contact>();
        for(Contact student: [SELECT Id,Domicile__c, HESA_Domicile__c, Nationality__c, HESA_Nationality__c FROM Contact WHERE Id IN: studentIds]){
            if(domicileMap.containsKey(student.Domicile__c))
                student.HESA_Domicile__c = domicileMap.get(student.Domicile__c);
            if(nationalityMap.containsKey(student.Nationality__c))
                student.HESA_Nationality__c = nationalityMap.get(student.Nationality__c); 
            
            studentsToUpdate.add(student); 
        }

        update studentsToUpdate;
        
        List<Student_Programme__c> spsToUpdate = new List<Student_Programme__c>();
        for(Student_Programme__c sp: [SELECT MSTUFEE_FA__c, Major_source_of_tuition_fees__c FROM Student_Programme__c WHERE Id IN: spIds]){
            if(feeMap.containsKey(sp.MSTUFEE_FA__c)){
                sp.Major_source_of_tuition_fees__c = feeMap.get(sp.MSTUFEE_FA__c);
                spsToUpdate.add(sp);
            }
        }        
        update spsToUpdate;
    }
}