objects/FilteredProgrammeIds__c.object
<CustomObject><customSettingsType>List</customSettingsType><description>For internal use of XML Filter controller classes (do not modify)</description><enableFeeds>false</enableFeeds><label>FilteredProgrammeIds</label><visibility>Protected</visibility></CustomObject>

objects/FilteredProgramTypes__c.object
<CustomObject><customSettingsType>List</customSettingsType><description>For internal use of XML Filter controller classes (do not modify)</description><enableFeeds>false</enableFeeds><label>FilteredProgramTypes</label><visibility>Public</visibility></CustomObject>

objects/FilteredSpecialinclusions__c.object
<CustomObject><customSettingsType>List</customSettingsType><description>For internal use of XML Filter controller classes (do not modify)</description><enableFeeds>false</enableFeeds><label>FilteredSpecialinclusions</label><visibility>Public</visibility></CustomObject>

objects/FilteredYear__c.object
<CustomObject><customSettingsType>List</customSettingsType><enableFeeds>false</enableFeeds><label>FilteredYear</label><visibility>Public</visibility></CustomObject>

objects/Programme__c.object
<CustomObject><fields>
        <fullName>Academic_Year__c</fullName>
        <description>For Instance level records</description>
        <inlineHelpText>For reporting, use academic year for this Instance, not from the Version</inlineHelpText>
        <label>Academic Year</label>
        <picklist>
            <picklistValues>
                <fullName>14/15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15/16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16/17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17/18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18/19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19/20</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Programme_Type__c</fullName>
        <description>DO NOT USE, to be deleted</description>
        <label>X Programme Type</label>
        <picklist>
            <picklistValues>
                <fullName>MSc Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Diploma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSc Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Course</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Provision__c.object
<CustomObject><fields>
        <fullName>Programme_Type__c</fullName>
        <formula>Student_Programme__r.Programme_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Programme Type</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Student_Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Programme</label>
        <referenceTo>Student_Programme__c</referenceTo>
        <relationshipLabel>Provisions</relationshipLabel>
        <relationshipName>Student_Programme</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Provision</label><nameField>
        <label>Provision Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Provisions</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/SIS_Audit__c.object
<CustomObject><fields>
        <fullName>Audit_Event__c</fullName>
        <inlineHelpText>Defines the SIS event that triggers the audit log</inlineHelpText>
        <label>Audit Event</label>
        <picklist>
            <picklistValues>
                <fullName>Active Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REF Data</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Audit_Output2__c</fullName>
        <description>Used for &lt;QualificationsAwarded&gt; HESA output, for Student Programme (HESA Instance) audit record only;</description>
        <inlineHelpText>Set by Workflow rule and field update, both called HESA QualsAwarded</inlineHelpText>
        <label>Audit Output2</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>Audit_Output__c</fullName>
        <inlineHelpText>In pseudo XML format</inlineHelpText>
        <label>Audit Output</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>Audit_Period__c</fullName>
        <label>Audit Period</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Exclude__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Exclude from Audit report, for example if in error</inlineHelpText>
        <label>Exclude</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Order__c</fullName>
        <inlineHelpText>Dictates order of report output, for testing</inlineHelpText>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Output_Section__c</fullName>
        <label>Output Section</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Special_Inclusion__c</fullName>
        <description>Used for none standard HESA audit records, such as credit bearing short course. Picklist used to allow for extensions if required.</description>
        <inlineHelpText>eg credit bearing Short Courses that need to be included in audit output</inlineHelpText>
        <label>Special Inclusion</label>
        <picklist>
            <picklistValues>
                <fullName>Credit Bearing Short Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intercalating Students</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Student_Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Programme</label>
        <referenceTo>Student_Programme__c</referenceTo>
        <relationshipLabel>SIS Audit</relationshipLabel>
        <relationshipName>SIS_Audit</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SIS Audit</relationshipLabel>
        <relationshipName>SIS_Audit</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Generic location for audit records such as for HESA</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>SIS Audit</label><nameField>
        <displayFormat>SA-{0000000}</displayFormat>
        <label>SIS Audit Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>SIS Audit</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>Academic_Year__c</fullName>
        <formula>Text (  Programme__r.Academic_Year__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Academic Year</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme_Type__c</fullName>
        <formula>TEXT(  Programme__r.Programme_Version__r.Programme_Type__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Programme Type</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Programme must be active (i.e. most recent)</errorMessage>
            <filterItems>
                <field>Programme__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Student Programmes</relationshipLabel>
        <relationshipName>Students_on_Programme1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reverted from Master:Detail as per LSTM requirement</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Programmes</relationshipLabel>
        <relationshipName>Student_Programmes1</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/XMLGenerationController.cls
/*
Created by Suyati Technologies
The class is used to genearate an XML stracture based on the SIS Audit object.

*/
public class XMLGenerationController {
    
    public List<String> FilteredprogramTypes = new List<String>();
    public List<String> Filteredprograms = new List<String>();  
    public List<String> FilteredSpecialinclusions = new List<String>();  
    public String FilteredYear;
    public String audit_period;
    
    public XMLGenerationController(){
        
        for(FilteredYear__c fy : FilteredYear__c.getAll().values())
        {
            FilteredYear = fy.name;
            System.debug('FilteredYear'+FilteredYear);
            audit_period = 'H' + fy.name.remove('/');
            System.debug('audit_period'+audit_period);
        }       
        for(FilteredProgramTypes__c pt : FilteredProgramTypes__c.getAll().values())
            FilteredprogramTypes.add(pt.Name);  
        System.debug('FilteredprogramTypes'+FilteredprogramTypes);
        
        for(FilteredProgrammeIds__c prog : FilteredProgrammeIds__c.getAll().values())
            Filteredprograms.add(prog.Name);  
        System.debug('Filteredprograms'+Filteredprograms);
        
        for(FilteredSpecialinclusions__c specialinclusions : FilteredSpecialinclusions__c.getAll().values())
            FilteredSpecialinclusions.add(specialinclusions.Name);  
        System.debug('FilteredSpecialinclusions'+FilteredSpecialinclusions);
        
    }
    
    //Return XML header
    public String getHeaderXmlOutput(){
        String headerXml = '<?xml version="1.0" encoding="utf-8" standalone="yes"?>';
        headerXml += '\n<StudentRecord';
        headerXml += ' xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"';
        headerXml += ' xsi:noNamespaceSchemaLocation=';
        headerXml += '"\\\\filestore\\Projects\\C16051_Student\\Testing\\Schema_XSD\\C16051.xsd">';
        headerXml += '<Institution><UKPRN>10003958</UKPRN><INSTAPP>0</INSTAPP><RECID>16051</RECID>';
        return headerXml.trim();
    }
    
    //Return XML footer
    public String getFooterXmlOutput(){
        return ('</Institution>'+ '\n' + '</StudentRecord>').trim();
    }
    
    //Return list of Courses
    public list<string> getCourses(){
        list<string> courseList = new list<string>();
        
        if(FilteredprogramTypes.isEmpty() && !FilteredSpecialinclusions.isEmpty())
        {
            System.debug('1'+FilteredprogramTypes.isEmpty() +!FilteredSpecialinclusions.isEmpty());
            for(SIS_Audit__c sisAuditRecordList :[SELECT Id, Audit_Output__c  FROM SIS_Audit__c 
                                                  WHERE 
                                                  Output_section__c= 'Course'  AND Exclude__c = False AND Audit_Period__c =: audit_period AND Special_Inclusion__c IN:FilteredSpecialinclusions
                                                 ]){            
                                                     courseList.add(sisAuditRecordList.Audit_Output__c.replaceAll('&','&amp;'));   
                                                     system.debug('sisAuditRecordList'+sisAuditRecordList);
                                                 }      
            
        }   
        else if(!FilteredprogramTypes.isEmpty() && !FilteredSpecialinclusions.isEmpty())
        {
            System.debug('2'+!FilteredprogramTypes.isEmpty() + !FilteredSpecialinclusions.isEmpty());
            
            for(SIS_Audit__c sisAuditRecordList :[SELECT Id, Audit_Output__c  FROM SIS_Audit__c 
                                                  WHERE 
                                                  Output_section__c= 'Course'  AND Exclude__c = False AND Audit_Period__c =: audit_period
                                                 ]){            
                                                     courseList.add(sisAuditRecordList.Audit_Output__c.replaceAll('&','&amp;'));             
                                                 }   }   
        else
        {
            System.debug('3'+!FilteredprogramTypes.isEmpty() + !FilteredSpecialinclusions.isEmpty());
            for(SIS_Audit__c sisAuditRecordList :[SELECT Id, Audit_Output__c  FROM SIS_Audit__c 
                                                  WHERE 
                                                  Output_section__c= 'Course'  AND Exclude__c = False AND Audit_Period__c =: audit_period AND Special_Inclusion__c = null
                                                 ]){            
                                                     
                                                     courseList.add(sisAuditRecordList.Audit_Output__c.replaceAll('&','&amp;'));                         
                                                 }   
        }   
        system.debug('courseList'+courseList);
        return courseList;
    }
    
    //Return list of Modules
    public list<String> getModules(){
        //To store the modules in SIS records
        list<String> moduleList = new list<String>();
        if(FilteredprogramTypes.isEmpty() && !FilteredSpecialinclusions.isEmpty())
        {
            for(SIS_Audit__c sisAuditRecordList :[SELECT Id, Audit_Output__c  FROM SIS_Audit__c 
                                                  WHERE 
                                                  Output_section__c= 'Module'  AND Exclude__c = False AND Audit_Period__c =: audit_period AND  Special_Inclusion__c IN:FilteredSpecialinclusions
                                                 ]){            
                                                     moduleList.add(sisAuditRecordList.Audit_Output__c.replaceAll('&','&amp;'));   
                                                 }
        }
        else if(!FilteredprogramTypes.isEmpty() && !FilteredSpecialinclusions.isEmpty())
        {
            for(SIS_Audit__c sisAuditRecordList :[SELECT Id, Audit_Output__c  FROM SIS_Audit__c 
                                                  WHERE 
                                                  Output_section__c= 'Module'  AND Exclude__c = False AND Audit_Period__c =: audit_period
                                                 ]){            
                                                     moduleList.add(sisAuditRecordList.Audit_Output__c.replaceAll('&','&amp;'));   
                                                 }           
        }
        else
        {
            for(SIS_Audit__c sisAuditRecordList :[SELECT Id, Audit_Output__c  FROM SIS_Audit__c 
                                                  WHERE 
                                                  Output_section__c= 'Module'  AND Exclude__c = False AND Audit_Period__c =: audit_period AND Special_Inclusion__c = null
                                                 ]){            
                                                     moduleList.add(sisAuditRecordList.Audit_Output__c.replaceAll('&','&amp;'));   
                                                 }                       
        }   
        system.debug('moduleList'+moduleList);
        return moduleList;
    }
    
        /*
    Return student details which consist of
    - Each student XML details
    - All the XML of student instances 
    - XML of student on module
    - XML of qualification on module 
    */
    
    public list<List<String>> getStudentDetails(){
        Map <Id,List<SIS_Audit__c>> studentMap = new Map <Id,List<SIS_Audit__c>>();
        Map <Id,List<SIS_Audit__c>> SPMap = new Map <Id,List<SIS_Audit__c>>();
        list<string> AuditEvent = new list<string>{'Registration','Student Module','Qualification','REF Data'};
            string Studentid, SPid;
        list<String> xmlPerStudent = new list<String>();
        list<list<String>> xmlStudent = new list<list<String>>();
        List<SIS_Audit__c> SISList = new List<SIS_Audit__c>([SELECT Id, Student__c,Output_section__c, Audit_Output__c,Audit_Output2__c,Student_Programme__c 
                                                             FROM SIS_Audit__c 
                                                             WHERE 
                                                             (Audit_Event__c IN : AuditEvent 
                                                              AND Exclude__c = False 
                                                              AND Student_Programme__r.Programme_Type__c IN:FilteredprogramTypes 
                                                              AND Student_Programme__r.Programme__c IN: Filteredprograms 
                                                              AND Student_Programme__r.Academic_Year__c =: FilteredYear 
                                                              AND Audit_Period__c =: audit_period
                                                             ) 
                                                             OR 
                                                             (Audit_Event__c IN : AuditEvent 
                                                              AND Exclude__c = False 
                                                              AND Special_Inclusion__c IN: FilteredSpecialinclusions
                                                              AND Audit_Period__c =: audit_period
                                                             ) 
                                                             ORDER BY Order__c
                                                            ]);
        system.debug('SISList'+SISList);
        for(SIS_Audit__c AudObj : SISList)
        {
            
            Studentid = AudObj.Student__c;
            if(studentMap.containsKey(Studentid)) {
                List<SIS_Audit__c> sAList = studentMap.get(Studentid);
                sAList.add(AudObj); 
                studentMap.put(Studentid,sAList);
            } else {
                studentMap.put(Studentid, new List<SIS_Audit__c> { AudObj });
            }   
            
        }
        list<String> studList = new list<String>();
        
        list<String> instanceList = new list<String>();
        list<String> temporarySOM = new list<String>();
        list<String> temporaryInstaceList = new list<String>();
        map<id, string> stdM = new map<id, string>();
        for(List<SIS_Audit__c> AudList1 : studentMap.values())
        {
            for(SIS_Audit__c AudObj1 : AudList1)
            {
                if(AudObj1.Output_section__c == 'Qualification on Entry')
                    stdM.put(AudObj1.Student__c, AudObj1.Audit_Output__c);
            }
        }
        for(List<SIS_Audit__c> AudList1 : studentMap.values())
        {
            for(SIS_Audit__c AudObj1 : AudList1)
            {
                SPid = AudObj1.Student_Programme__c;
                if(SPMap.containsKey(SPid)) {
                    List<SIS_Audit__c> sAList = SPMap.get(SPid);
                    sAList.add(AudObj1); 
                    SPMap.put(SPid,sAList);
                } else {
                    SPMap.put(SPid, new List<SIS_Audit__c> { AudObj1 });
                }
                //stdM.put(SPid, AudObj1.Audit_Output__c);  
            }
            for(List<SIS_Audit__c> AudList : SPMap.values())
            {
                for(SIS_Audit__c sisAuditObj: AudList)
                {
                    
                    if(sisAuditObj.Output_section__c == 'Student')
                        studList.add(sisAuditObj.Audit_Output__c.replaceAll('&','&amp;'));
                }
                for(SIS_Audit__c sisAuditObj: AudList)
                {
                    if(sisAuditObj.Output_section__c == 'instance'){
                        temporaryInstaceList.add(sisAuditObj.Audit_Output__c.replaceAll('&','&amp;'));
                        if(stdM.get(sisAuditObj.Student__c) != null && stdM.get(sisAuditObj.Student__c) != '')
                        {
                            temporaryInstaceList.add('<QualificationsOnEntry>');
                            temporaryInstaceList.add(stdM.get(sisAuditObj.Student__c));
                            temporaryInstaceList.add('</QualificationsOnEntry>');                   
                        }   
                        temporaryInstaceList.add('</EntryProfile>');
                    }
                    if(sisAuditObj.Audit_Output2__c != null && sisAuditObj.Audit_Output2__c != '' ){
                        temporaryInstaceList.add(sisAuditObj.Audit_Output2__c);
                    }
                    
                    
                    if(sisAuditObj.Output_section__c == 'Unit of Assessment'){
                        temporaryInstaceList.add('<REFData>');
                        temporaryInstaceList.add(sisAuditObj.Audit_Output__c.replaceAll('&','&amp;'));
                        temporaryInstaceList.add('</REFData>');
                    }
                    
                    if(sisAuditObj.Output_section__c == 'Student on Module'){
                        temporarySOM.add('<StudentOnModule>');
                        temporarySOM.add(sisAuditObj.Audit_Output__c.replaceAll('&','&amp;'));
                        temporarySOM.add('</StudentOnModule>');
                    }
                }
                
                
                if (!temporaryInstaceList.isEmpty() && !temporarySOM.isEmpty())
                {
                    instanceList.add('<Instance>');
                    instanceList.addall(temporaryInstaceList);
                    instanceList.addall(temporarySOM);  
                    instanceList.add('</Instance>');
                }
                else if (!temporaryInstaceList.isEmpty())
                {
                    instanceList.add('<Instance>');
                    instanceList.addall(temporaryInstaceList); 
                    instanceList.add('</Instance>'); 
                }
                else if (!temporarySOM.isEmpty())
                {
                    instanceList.add('<Instance>');
                    instanceList.addall(temporarySOM);  
                    instanceList.add('</Instance>');
                }
                temporarySOM.clear();
                temporaryInstaceList.clear();
                
            }
            xmlPerStudent.addAll(studList);
            xmlPerStudent.addAll(instanceList);
            xmlStudent.add(xmlPerStudent); 
            studList.clear();
            instanceList.clear();
            temporarySOM.clear();
            xmlPerStudent = new list<String>();
            SPMap = new Map <Id,List<SIS_Audit__c>>();
        }
        return xmlStudent;
    }//getStudentDetails() End          
}