objects/FilteredProgrammeIds__c.object
<CustomObject><customSettingsType>List</customSettingsType><description>For internal use of XML Filter controller classes (do not modify)</description><enableFeeds>false</enableFeeds><label>FilteredProgrammeIds</label><visibility>Protected</visibility></CustomObject>

objects/FilteredProgramTypes__c.object
<CustomObject><customSettingsType>List</customSettingsType><description>For internal use of XML Filter controller classes (do not modify)</description><enableFeeds>false</enableFeeds><label>FilteredProgramTypes</label><visibility>Public</visibility></CustomObject>

objects/FilteredSpecialinclusions__c.object
<CustomObject><customSettingsType>List</customSettingsType><description>For internal use of XML Filter controller classes (do not modify)</description><enableFeeds>false</enableFeeds><label>FilteredSpecialinclusions</label><visibility>Public</visibility></CustomObject>

objects/FilteredYear__c.object
<CustomObject><customSettingsType>List</customSettingsType><enableFeeds>false</enableFeeds><label>FilteredYear</label><visibility>Public</visibility></CustomObject>

objects/Programme__c.object
<CustomObject><fields>
        <fullName>Academic_Year__c</fullName>
        <description>For Instance level records</description>
        <inlineHelpText>For reporting, use academic year for this Instance, not from the Version</inlineHelpText>
        <label>Academic Year</label>
        <picklist>
            <picklistValues>
                <fullName>14/15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15/16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16/17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17/18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18/19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19/20</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Programme_Type__c</fullName>
        <description>DO NOT USE, to be deleted</description>
        <label>X Programme Type</label>
        <picklist>
            <picklistValues>
                <fullName>MSc Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Diploma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSc Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Course</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme Version</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Programme_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Versions, Versions, Specification, Versions - Pre Approved, Specification Edit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Programme Instances</relationshipLabel>
        <relationshipName>Programmes_Instances</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme_Version__c.object
<CustomObject><fields>
        <fullName>Academic_Year__c</fullName>
        <description>For Version level records</description>
        <label>Academic Year</label>
        <picklist>
            <picklistValues>
                <fullName>14/15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15/16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16/17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17/18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18/19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19/20</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Entry_Award_1__c</fullName>
        <globalPicklist>Entry_Exit_Awards</globalPicklist>
        <label>Entry Award 1</label>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Programme_Type__c</fullName>
        <label>Programme Type</label>
        <picklist>
            <picklistValues>
                <fullName>MSc Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Diploma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Masters Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG Cert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Course</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme Version</label><nameField>
        <label>Programme Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programme Versions</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel><recordTypes>
        <fullName>Versions</fullName>
        <active>true</active>
        <description>Annual (or other) iterations per programme</description>
        <label>Versions</label>
    </recordTypes></CustomObject>

objects/SIS_Audit__c.object
<CustomObject><fields>
        <fullName>Audit_Body__c</fullName>
        <label>Audit Body</label>
        <picklist>
            <picklistValues>
                <fullName>HESA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LSTM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANOther</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Audit_Event__c</fullName>
        <inlineHelpText>Defines the SIS event that triggers the audit log</inlineHelpText>
        <label>Audit Event</label>
        <picklist>
            <picklistValues>
                <fullName>Active Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REF Data</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Audit_Output__c</fullName>
        <inlineHelpText>In pseudo XML format</inlineHelpText>
        <label>Audit Output</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>Audit_Period__c</fullName>
        <label>Audit Period</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Output_Section__c</fullName>
        <label>Output Section</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Special_Inclusion__c</fullName>
        <description>Used for none standard HESA audit records, such as credit bearing short course. Picklist used to allow for extensions if required.</description>
        <inlineHelpText>eg credit bearing Short Courses that need to be included in audit output</inlineHelpText>
        <label>Special Inclusion</label>
        <picklist>
            <picklistValues>
                <fullName>Credit Bearing Short Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intercalating Students</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Student_Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Programme</label>
        <referenceTo>Student_Programme__c</referenceTo>
        <relationshipLabel>SIS Audit</relationshipLabel>
        <relationshipName>SIS_Audit</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SIS Audit</relationshipLabel>
        <relationshipName>SIS_Audit</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Generic location for audit records such as for HESA</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>SIS Audit</label><nameField>
        <displayFormat>SA-{0000000}</displayFormat>
        <label>SIS Audit Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>SIS Audit</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>Academic_Year__c</fullName>
        <formula>Text (  Programme__r.Academic_Year__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Academic Year</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme_Type__c</fullName>
        <formula>TEXT(  Programme__r.Programme_Version__r.Programme_Type__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Programme Type</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Programme must be active (i.e. most recent)</errorMessage>
            <filterItems>
                <field>Programme__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Student Programmes</relationshipLabel>
        <relationshipName>Students_on_Programme1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reverted from Master:Detail as per LSTM requirement</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Programmes</relationshipLabel>
        <relationshipName>Student_Programmes1</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/TestXMLGenerationController.cls
@IsTest
public class TestXMLGenerationController {

 //XMLGenerationController xml = new XMLGenerationController();
 //string header= xml.getHeaderXmlOutput();
static testMethod void TestCourseXML() {
  SIS_Audit__c sisAudit = new SIS_Audit__c();
  sisAudit.AUDIT_BODY__C = 'test';
  sisAudit.AUDIT_PERIOD__C = 'H1516';
  sisAudit.AUDIT_OUTPUT__C = '<COURSEID>MC776</COURSEID><OWNCOURSEID>MC776</OWNCOURSEID><AWARDBOD>10003958</AWARDBOD><CLSDCRS>0</CLSDCRS><COLLORG>0000</COLLORG><COURSEAIM>*** LSTM tbc ***</COURSEAIM><CTITLE>Child Nutrition - 14/15</CTITLE><MSFUND>*** LSTM tbc ***</MSFUND><REDUCEDC>00</REDUCEDC><TTCID>0</TTCID><CourseSubject><SBJCA>A000</SBJCA><SBJPCNT>100</SBJPCNT></CourseSubject>';
  sisAudit.OUTPUT_SECTION__C = 'Course';
  sisAudit.AUDIT_EVENT__C = 'Active Programme';
  sisAudit.Special_Inclusion__c = 'Credit Bearing Short Course';
  INSERT sisAudit;
  
  SIS_Audit__c sisAudit2 = new SIS_Audit__c();
  sisAudit2.AUDIT_BODY__C = 'test';
  sisAudit2.AUDIT_PERIOD__C = 'H1516';
  sisAudit2.AUDIT_OUTPUT__C = '<COURSEID>MC776</COURSEID><OWNCOURSEID>MC776</OWNCOURSEID><AWARDBOD>10003958</AWARDBOD><CLSDCRS>0</CLSDCRS><COLLORG>0000</COLLORG><COURSEAIM>*** LSTM tbc ***</COURSEAIM><CTITLE>Child Nutrition - 14/15</CTITLE><MSFUND>*** LSTM tbc ***</MSFUND><REDUCEDC>00</REDUCEDC><TTCID>0</TTCID><CourseSubject><SBJCA>A000</SBJCA><SBJPCNT>100</SBJPCNT></CourseSubject>';
  sisAudit2.OUTPUT_SECTION__C = 'Course';
  sisAudit2.AUDIT_EVENT__C = 'Active Programme';
  INSERT sisAudit2;  
  
  FilteredYear__c fy = new FilteredYear__c(Name='15/16');
  insert fy;
  
  FilteredProgramTypes__c fpt = new FilteredProgramTypes__c(Name='Professional Diploma');
  insert fpt;   
  
  XMLGenerationController xml1 = new XMLGenerationController();
  list < string > courseList1 = xml1.getCourses();
  
  FilteredSpecialinclusions__c fsi = new FilteredSpecialinclusions__c(Name='Credit Bearing Short Course');
  insert  fsi;
  
  XMLGenerationController xml2 = new XMLGenerationController();
  list < string > courseList2 = xml2.getCourses();

  delete fpt;
  
  Test.startTest();
  XMLGenerationController xml3 = new XMLGenerationController();
  list < string > courseList3 = xml3.getCourses();
  Test.stopTest();

}

static testMethod void TestStaticHeaderAndFooter() {
  string header;
  string footer;
  Test.startTest();
  XMLGenerationController xml = new XMLGenerationController();
  header = xml.getHeaderXmlOutput();
  footer = xml.getFooterXmlOutput();
  Test.stopTest();

}

static testMethod void TestModuleXML() {
  SIS_Audit__c sisAudit = new SIS_Audit__c();
  sisAudit.AUDIT_BODY__C = 'test';
  sisAudit.AUDIT_PERIOD__C = 'H1516';
  sisAudit.AUDIT_OUTPUT__C = '<MODID></MODID><CRDTPTS></CRDTPTS><CRDTSCM>1</CRDTSCM><FTE>100</FTE><LEVLPTS>6</LEVLPTS><MTITLE>Parasite Epidemiology & Control - 2014/15</MTITLE><PCOLAB>00</PCOLAB><ModuleSubject><COSTCN>*** LSTM tbc ***</COSTCN><MODSBJ>*** LSTM tbc ***</MODSBJ><MODSBJP>100</MODSBJP></ModuleSubject>';
  sisAudit.OUTPUT_SECTION__C = 'Module';
  sisAudit.Audit_Event__c = 'Active Module';
  sisAudit.Special_Inclusion__c = 'Credit Bearing Short Course';
  INSERT sisAudit;

  SIS_Audit__c sisAudit2 = new SIS_Audit__c();
  sisAudit2.AUDIT_BODY__C = 'test';
  sisAudit2.AUDIT_PERIOD__C = 'H1516';
  sisAudit2.AUDIT_OUTPUT__C = '<COURSEID>MC776</COURSEID><OWNCOURSEID>MC776</OWNCOURSEID><AWARDBOD>10003958</AWARDBOD><CLSDCRS>0</CLSDCRS><COLLORG>0000</COLLORG><COURSEAIM>*** LSTM tbc ***</COURSEAIM><CTITLE>Child Nutrition - 14/15</CTITLE><MSFUND>*** LSTM tbc ***</MSFUND><REDUCEDC>00</REDUCEDC><TTCID>0</TTCID><CourseSubject><SBJCA>A000</SBJCA><SBJPCNT>100</SBJPCNT></CourseSubject>';
  sisAudit2.OUTPUT_SECTION__C = 'Course';
  sisAudit2.AUDIT_EVENT__C = 'Active Programme';
  INSERT sisAudit2;  
  
  FilteredYear__c fy = new FilteredYear__c(Name='15/16');
  insert fy;  
  
  FilteredProgramTypes__c fpt = new FilteredProgramTypes__c(Name='Professional Diploma');
  insert fpt;   

  XMLGenerationController xml = new XMLGenerationController();
  list < string > moduleList = xml.getModules();
  
  FilteredSpecialinclusions__c fsi = new FilteredSpecialinclusions__c(Name='Credit Bearing Short Course');
  insert  fsi;  

  XMLGenerationController xml2 = new XMLGenerationController();
  list < string > moduleList2 = xml2.getModules();  
  
  delete fpt;
  
  Test.startTest();
  XMLGenerationController xml3 = new XMLGenerationController();
  list < string > moduleList3 = xml3.getModules();
  Test.stopTest();

}

static testMethod void TestStudentXML() {

  id recType = Schema.SObjectType.Programme_Version__c.getRecordTypeInfosByName().get('Versions').getRecordTypeId();

  Contact con = new Contact(LastName = 'test');
  INSERT con;
  Programme_Version__c pv = new Programme_Version__c(Name = 'testPV',Programme_Type__c = 'Professional Diploma');
  pv.Entry_Award_1__c = 'MSc';
  pv.RecordTypeId = recType;
  INSERT pv;

  Programme__c p = new Programme__c(Name = 'testProgramme',Academic_year__c = '15/16');
  p.programme_version__c = pv.Id;
  INSERT p;

  FilteredProgrammeIds__c fp = new FilteredProgrammeIds__c(Name = p.Id);
  insert fp;
  FilteredProgramTypes__c fpt = new FilteredProgramTypes__c(Name='Professional Diploma');
  insert fpt;   
  FilteredYear__c fy = new FilteredYear__c(Name='15/16');
  insert fy;  
  
  Student_Programme__c sp = new Student_Programme__c();
  sp.Name = 'testStudentProgramme';
  sp.Student__c = con.Id;
  sp.programme__C = p.Id;
  INSERT sp;

  SIS_Audit__c sisAudit = new SIS_Audit__c();
  sisAudit.AUDIT_BODY__C = 'test';
  sisAudit.AUDIT_PERIOD__C = 'H1516';
  sisAudit.AUDIT_OUTPUT__C = '<HUSID>*** LSTM tbc ***</HUSID><OWNSTU>00011727</OWNSTU><BIRTHDTE>2015-06-20</BIRTHDTE><DISABLE></DISABLE><ETHNIC></ETHNIC><FNAMES>Manu</FNAMES><NATION>AS</NATION><SEXID>1</SEXID><SURNAME>km</SURNAME><TTACCOM>*** LSTM tbc ***</TTACCOM><TTPCODE>6578393</TTPCODE><ULN>*** LSTM tbc ***</ULN>';
  sisAudit.OUTPUT_SECTION__C = 'Student';
  sisAudit.AUDIT_EVENT__C = 'Registration';
  sisAudit.Student__c = con.Id;
  sisAudit.Student_Programme__c = sp.Id;
  INSERT sisAudit;

  SIS_Audit__c sisAuditInstance = new SIS_Audit__c();
  sisAuditInstance.AUDIT_BODY__C = 'test';
  sisAuditInstance.AUDIT_PERIOD__C = 'H1516';
  sisAuditInstance.AUDIT_OUTPUT__C = '<NUMHUS>01</NUMHUS><OWNINST>00012488</OWNINST><COURSEID>Work in Progress</COURSEID><BRIDGE>0</BRIDGE><CAMPID>A</CAMPID><COMDATE>2016-01-11</COMDATE><ELQ>*** LSTM tbc ***</ELQ><ENDDATE>2016-04-08</ENDDATE><EXCHANGE>N</EXCHANGE><FEEELIG>Work in Progress</FEEELIG><FEEREGIME>*** LSTM tbc ***</FEEREGIME><FESTUMK>*** LSTM tbc ***</FESTUMK><FUNDCODE>*** LSTM tbc ***</FUNDCODE><FUNDCOMP>*** LSTM tbc ***</FUNDCOMP><FUNDLEV>20</FUNDLEV><LOCSDY>Z</LOCSDY><MODE>01</MODE><MSTUFEE>*** LSTM tbc ***</MSTUFEE><RCSTDNT>99</RCSTDNT><REDUCEDI>*** LSTM tbc ***</REDUCEDI><SPECFEE>0</SPECFEE><SPLENGTH>Work in Progress</SPLENGTH><SSN>*** LSTM tbc ***</SSN><STULOAD>Work in Progress</STULOAD><TYPEYR>Work in Progress</TYPEYR><UNITLGTH>Work in Progress</UNITLGTH><YEARPRG>Work in Progress</YEARPRG><YEARSTU>Work in Progress</YEARSTU>';
  sisAuditInstance.OUTPUT_SECTION__C = 'Instance';
  sisAuditInstance.AUDIT_EVENT__C = 'Registration';
  sisAuditInstance.Student__c = con.Id;
  sisAuditInstance.Student_Programme__c = sp.Id;
  INSERT sisAuditInstance;

  SIS_Audit__c sisAuditQOEntry = new SIS_Audit__c();
  sisAuditQOEntry.AUDIT_BODY__C = 'test';
  sisAuditQOEntry.AUDIT_PERIOD__C = 'H1516';
  sisAuditQOEntry.AUDIT_OUTPUT__C = '<QUALGRADE>Pass</QUALGRADE><QUALSBJ>C14</QUALSBJ><QUALSIT>W</QUALSIT><QUALTYPE>A</QUALTYPE><QUALYEAR>2010</QUALYEAR>';
  sisAuditQOEntry.OUTPUT_SECTION__C = 'Qualification on Entry';
  sisAuditQOEntry.AUDIT_EVENT__C = 'Registration';
  sisAuditQOEntry.Student__c = con.Id;
  INSERT sisAuditQOEntry;

  SIS_Audit__c sisAuditSOM = new SIS_Audit__c();
  sisAuditSOM.AUDIT_BODY__C = 'test';
  sisAuditSOM.AUDIT_PERIOD__C = 'H1516';
  sisAuditSOM.AUDIT_OUTPUT__C = '<MODID>DTM&H</MODID><MODOUT>6</MODOUT><MODSTAT>2</MODSTAT>';
  sisAuditSOM.OUTPUT_SECTION__C = 'Student On Module';
  sisAuditSOM.AUDIT_EVENT__C = 'Student Module';
  sisAuditSOM.Student__c = con.Id;
  sisAuditSOM.Student_Programme__c = sp.Id;
  INSERT sisAuditSOM;
  Test.startTest();
  XMLGenerationController xml = new XMLGenerationController();
  list < list < string >> studList = xml.getStudentDetails();
  Test.stopTest();
 }

static testMethod void TestStudentXMLWithInstanceOnly() {
  id recType = Schema.SObjectType.Programme_Version__c.getRecordTypeInfosByName().get('Versions').getRecordTypeId();

  Contact con = new Contact(LastName = 'test');
  INSERT con;
  Programme_Version__c pv = new Programme_Version__c(Name = 'testPV',Programme_Type__c = 'Professional Diploma');
  pv.Entry_Award_1__c = 'MSc';
  pv.RecordTypeId = recType;
  INSERT pv;

  Programme__c p = new Programme__c(Name = 'testProgramme',Academic_year__c = '15/16');
  p.programme_version__c = pv.Id;
  INSERT p;

  FilteredProgrammeIds__c fp = new FilteredProgrammeIds__c(Name = p.Id);
  insert fp;
  FilteredProgramTypes__c fpt = new FilteredProgramTypes__c(Name='Professional Diploma');
  insert fpt;   
  FilteredYear__c fy = new FilteredYear__c(Name='15/16');
  insert fy;  

  Student_Programme__c sp = new Student_Programme__c();
  sp.Name = 'testStudentProgramme';
  sp.Student__c = con.Id;
  sp.programme__C = p.Id;
  INSERT sp;

  SIS_Audit__c sisAudit = new SIS_Audit__c();
  sisAudit.AUDIT_BODY__C = 'test';
  sisAudit.AUDIT_PERIOD__C = 'H1516';
  sisAudit.AUDIT_OUTPUT__C = '<HUSID>*** LSTM tbc ***</HUSID><OWNSTU>00011727</OWNSTU><BIRTHDTE>2015-06-20</BIRTHDTE><DISABLE></DISABLE><ETHNIC></ETHNIC><FNAMES>Manu</FNAMES><NATION>AS</NATION><SEXID>1</SEXID><SURNAME>km</SURNAME><TTACCOM>*** LSTM tbc ***</TTACCOM><TTPCODE>6578393</TTPCODE><ULN>*** LSTM tbc ***</ULN>';
  sisAudit.OUTPUT_SECTION__C = 'Student';
  sisAudit.AUDIT_EVENT__C = 'Registration';
  sisAudit.Student__c = con.Id;
  sisAudit.Student_Programme__c = sp.Id;
  INSERT sisAudit;

  SIS_Audit__c sisAuditQOEntry = new SIS_Audit__c();
  sisAuditQOEntry.AUDIT_BODY__C = 'test';
  sisAuditQOEntry.AUDIT_PERIOD__C = 'H1516';
  sisAuditQOEntry.AUDIT_OUTPUT__C = '<QUALGRADE>Pass</QUALGRADE><QUALSBJ>C14</QUALSBJ><QUALSIT>W</QUALSIT><QUALTYPE>A</QUALTYPE><QUALYEAR>2010</QUALYEAR>';
  sisAuditQOEntry.OUTPUT_SECTION__C = 'Qualification on Entry';
  sisAuditQOEntry.AUDIT_EVENT__C = 'Registration';
  sisAuditQOEntry.Student__c = con.Id;
  INSERT sisAuditQOEntry;

  SIS_Audit__c sisAuditInstance = new SIS_Audit__c();
  sisAuditInstance.AUDIT_BODY__C = 'test';
  sisAuditInstance.AUDIT_PERIOD__C = 'H1516';
  sisAuditInstance.AUDIT_OUTPUT__C = '<NUMHUS>01</NUMHUS><OWNINST>00012488</OWNINST><COURSEID>Work in Progress</COURSEID><BRIDGE>0</BRIDGE><CAMPID>A</CAMPID><COMDATE>2016-01-11</COMDATE><ELQ>*** LSTM tbc ***</ELQ><ENDDATE>2016-04-08</ENDDATE><EXCHANGE>N</EXCHANGE><FEEELIG>Work in Progress</FEEELIG><FEEREGIME>*** LSTM tbc ***</FEEREGIME><FESTUMK>*** LSTM tbc ***</FESTUMK><FUNDCODE>*** LSTM tbc ***</FUNDCODE><FUNDCOMP>*** LSTM tbc ***</FUNDCOMP><FUNDLEV>20</FUNDLEV><LOCSDY>Z</LOCSDY><MODE>01</MODE><MSTUFEE>*** LSTM tbc ***</MSTUFEE><RCSTDNT>99</RCSTDNT><REDUCEDI>*** LSTM tbc ***</REDUCEDI><SPECFEE>0</SPECFEE><SPLENGTH>Work in Progress</SPLENGTH><SSN>*** LSTM tbc ***</SSN><STULOAD>Work in Progress</STULOAD><TYPEYR>Work in Progress</TYPEYR><UNITLGTH>Work in Progress</UNITLGTH><YEARPRG>Work in Progress</YEARPRG><YEARSTU>Work in Progress</YEARSTU>';
  sisAuditInstance.OUTPUT_SECTION__C = 'Instance';
  sisAuditInstance.AUDIT_EVENT__C = 'Registration';
  sisAuditInstance.Student__c = con.Id;
  sisAuditInstance.Student_Programme__c = sp.Id;
  INSERT sisAuditInstance;
  Test.startTest();
  XMLGenerationController xml = new XMLGenerationController();
  list < list < string >> studList = xml.getStudentDetails();
  Test.stopTest();
}

static testMethod void TestStudentXMLWithSOMOnly() {
  id recType = Schema.SObjectType.Programme_Version__c.getRecordTypeInfosByName().get('Versions').getRecordTypeId();

  Contact con = new Contact(LastName = 'test');
  INSERT con;
  Programme_Version__c pv = new Programme_Version__c(Name = 'testPV',Programme_Type__c = 'Professional Diploma');
  pv.Entry_Award_1__c = 'MSc';
  pv.RecordTypeId = recType;
  INSERT pv;

  Programme__c p = new Programme__c(Name = 'testProgramme',Academic_year__c = '15/16');
  p.programme_version__c = pv.Id;
  INSERT p;
  
  FilteredProgrammeIds__c fp = new FilteredProgrammeIds__c(Name = p.Id);
  insert fp;
  FilteredProgramTypes__c fpt = new FilteredProgramTypes__c(Name='Professional Diploma');
  insert fpt;   
  FilteredYear__c fy = new FilteredYear__c(Name='15/16');
  insert fy;  
  
  Student_Programme__c sp = new Student_Programme__c();
  sp.Name = 'testStudentProgramme';
  sp.Student__c = con.Id;
  sp.programme__C = p.Id;
  INSERT sp;

  SIS_Audit__c sisAudit = new SIS_Audit__c();
  sisAudit.AUDIT_BODY__C = 'test';
  sisAudit.AUDIT_PERIOD__C = 'H1516';
  sisAudit.AUDIT_OUTPUT__C = '<HUSID>*** LSTM tbc ***</HUSID><OWNSTU>00011727</OWNSTU><BIRTHDTE>2015-06-20</BIRTHDTE><DISABLE></DISABLE><ETHNIC></ETHNIC><FNAMES>Manu</FNAMES><NATION>AS</NATION><SEXID>1</SEXID><SURNAME>km</SURNAME><TTACCOM>*** LSTM tbc ***</TTACCOM><TTPCODE>6578393</TTPCODE><ULN>*** LSTM tbc ***</ULN>';
  sisAudit.OUTPUT_SECTION__C = 'Student';
  sisAudit.AUDIT_EVENT__C = 'Registration';
  sisAudit.Student__c = con.Id;
  sisAudit.Student_Programme__c = sp.Id;
  INSERT sisAudit;

  SIS_Audit__c sisAuditQOEntry = new SIS_Audit__c();
  sisAuditQOEntry.AUDIT_BODY__C = 'test';
  sisAuditQOEntry.AUDIT_PERIOD__C = 'H1516';
  sisAuditQOEntry.AUDIT_OUTPUT__C = '<QUALGRADE>Pass</QUALGRADE><QUALSBJ>C14</QUALSBJ><QUALSIT>W</QUALSIT><QUALTYPE>A</QUALTYPE><QUALYEAR>2010</QUALYEAR>';
  sisAuditQOEntry.OUTPUT_SECTION__C = 'Qualification on Entry';
  sisAuditQOEntry.AUDIT_EVENT__C = 'Registration';
  sisAuditQOEntry.Student__c = con.Id;
  INSERT sisAuditQOEntry;

  SIS_Audit__c sisAuditSOM = new SIS_Audit__c();
  sisAuditSOM.AUDIT_BODY__C = 'test';
  sisAuditSOM.AUDIT_PERIOD__C = 'H1516';
  sisAuditSOM.AUDIT_OUTPUT__C = '<MODID>DTM&H</MODID><MODOUT>6</MODOUT><MODSTAT>2</MODSTAT>';
  sisAuditSOM.OUTPUT_SECTION__C = 'Student On Module';
  sisAuditSOM.AUDIT_EVENT__C = 'Student Module';
  sisAuditSOM.Student__c = con.Id;
  sisAuditSOM.Student_Programme__c = sp.Id;
  INSERT sisAuditSOM;

  Test.startTest();
  XMLGenerationController xml = new XMLGenerationController();
  list < list < string >> studList = xml.getStudentDetails();
  Test.stopTest();
}

}