objects/FilteredProgrammeIds__c.object
<CustomObject><customSettingsType>List</customSettingsType><description>For internal use of XML Filter controller classes (do not modify)</description><enableFeeds>false</enableFeeds><label>FilteredProgrammeIds</label><visibility>Protected</visibility></CustomObject>

objects/FilteredProgramTypes__c.object
<CustomObject><customSettingsType>List</customSettingsType><description>For internal use of XML Filter controller classes (do not modify)</description><enableFeeds>false</enableFeeds><label>FilteredProgramTypes</label><visibility>Public</visibility></CustomObject>

objects/FilteredSpecialinclusions__c.object
<CustomObject><customSettingsType>List</customSettingsType><description>For internal use of XML Filter controller classes (do not modify)</description><enableFeeds>false</enableFeeds><label>FilteredSpecialinclusions</label><visibility>Public</visibility></CustomObject>

objects/FilteredYear__c.object
<CustomObject><customSettingsType>List</customSettingsType><enableFeeds>false</enableFeeds><label>FilteredYear</label><visibility>Public</visibility></CustomObject>

objects/Programme__c.object
<CustomObject><fields>
        <fullName>Academic_Year__c</fullName>
        <description>For Instance level records</description>
        <inlineHelpText>For reporting, use academic year for this Instance, not from the Version</inlineHelpText>
        <label>Academic Year</label>
        <picklist>
            <picklistValues>
                <fullName>14/15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15/16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16/17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17/18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18/19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19/20</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>HESA_Audit__c</fullName>
        <formula>Programme_Version__r.Master_Link__r.HESA_Audit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Set at Master Version level</inlineHelpText>
        <label>HESA Audit</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Type__c</fullName>
        <formula>Text ( Programme_Version__r.Programme_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Taken from Version level</inlineHelpText>
        <label>Type</label>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/SIS_Audit__c.object
<CustomObject><fields>
        <fullName>Special_Inclusion__c</fullName>
        <description>Used for none standard HESA audit records, such as credit bearing short course. Picklist used to allow for extensions if required.</description>
        <inlineHelpText>eg credit bearing Short Courses that need to be included in audit output</inlineHelpText>
        <label>Special Inclusion</label>
        <picklist>
            <picklistValues>
                <fullName>Credit Bearing Short Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intercalating Students</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Generic location for audit records such as for HESA</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>SIS Audit</label><nameField>
        <displayFormat>SA-{0000000}</displayFormat>
        <label>SIS Audit Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>SIS Audit</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/FilterSisAuditsForXMLcontroller.cls
public class FilterSisAuditsForXMLcontroller 
{
    Public String year{get;set;}
    Public List<String> programmeTypes{get;set;}
    Public List<String> specialinclusions{get;set;}
    Public List<Programme__c> programmes{get;set;}
    public map<String,Boolean> mpChckBxProgrammeType{get;set;}  
    public map<String,Boolean> mpChckBxspecialinclusions{get;set;}
    public map<Id,Boolean> mpChckBxProgramme{get;set;}  
    public List<SelectOption> options{get;set;}  
    
    public FilterSisAuditsForXMLcontroller()
    {
        programmeTypes = new List<String>();
        specialinclusions = new List<String>();
        programmes = new List<Programme__c>();   
        mpChckBxProgrammeType = new map<String,Boolean>();
        mpChckBxspecialinclusions = new map<String,Boolean>();
        mpChckBxProgramme = new map<Id,Boolean>();

        options = new List<SelectOption>();
        Schema.DescribeFieldResult fieldResult = Programme__c.Academic_Year__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        for( Schema.PicklistEntry f : ple)
        {
            if(f.getValue() != '14/15' && f.getValue() != '15/16' )
                options.add(new SelectOption(f.getLabel(), f.getValue()));
        }
        options.add(new SelectOption('15/16', '15/16'));

        Schema.DescribeFieldResult SIfieldResult = SIS_Audit__c.Special_Inclusion__c.getDescribe();
        List<Schema.PicklistEntry> SIple = SIfieldResult.getPicklistValues();
        
        for( Schema.PicklistEntry f : SIple)
        {
            specialinclusions.add(f.getValue());
        }       
        
        programmeTypes.add('MSc Programme');
        programmeTypes.add('Professional Diploma');
        programmeTypes.add('PGR');

        for(String pt : programmeTypes)
        {
            mpChckBxProgrammeType.put(pt,false);
        }
        
        for(String si : specialinclusions)
        {
            mpChckBxspecialinclusions.put(si,false);
        }   

    }
    
    public PageReference onSelect()
    {
        List<String> selectedPTS = new List<String>();

        for(String pt : mpChckBxProgrammeType.keyset() )
            if(mpChckBxProgrammeType.get(pt))
               selectedPTS.add(pt);
        
        programmes = [SELECT Id,Name FROM Programme__c WHERE HESA_Audit__c = true AND Type__c IN: selectedPTS AND Academic_Year__c =: year ]; 

        Set<Programme__c> tempSet = new Set<Programme__c>();
        for(Programme__c prog : programmes)
        {
            mpChckBxProgramme.put(prog.Id,false);
            tempSet.add(prog);
        }   
        programmes.clear();
        for(Programme__c prog : tempSet)
            programmes.add(prog);
        
        return null;                   
        
    }
    
        
    public pagereference saveMethod()
    {
        List<FilteredProgramTypes__c> csProgramTypes_old = FilteredProgramTypes__c.getAll().values();
        List<FilteredProgrammeIds__c> csPrograms_old = FilteredProgrammeIds__c.getAll().values(); 
        List<FilteredSpecialinclusions__c> csSpecialinclusions_old = FilteredSpecialinclusions__c.getAll().values();   
        List<FilteredYear__c> csyear_old = FilteredYear__c.getAll().values();   
        delete csProgramTypes_old;
        delete csPrograms_old;
        delete csSpecialinclusions_old;
        delete csyear_old;
            
        List<FilteredProgrammeIds__c> csPrograms = new List<FilteredProgrammeIds__c>();  
        List<FilteredProgramTypes__c> csProgramTypes = new List<FilteredProgramTypes__c>();  
        List<FilteredSpecialinclusions__c> csSpInclusions = new List<FilteredSpecialinclusions__c>();  

        FilteredYear__c fy = new FilteredYear__c();
        fy.name = year;
        System.debug('FY'+fy);
        insert fy;
        
        for(String pt : mpChckBxProgrammeType.keyset() )
        {
            if(mpChckBxProgrammeType.get(pt))
            {
                FilteredProgramTypes__c csProgramType = new FilteredProgramTypes__c();
                csProgramType.Name = pt;
                csProgramTypes.add(csProgramType);
                System.debug('csProgramTypes'+csProgramTypes);
            }
        }
        for(Id prog : mpChckBxProgramme.keyset() )
        {
            if(mpChckBxProgramme.get(prog))
            {
                FilteredProgrammeIds__c csProgram = new FilteredProgrammeIds__c();
                csProgram.Name = prog;
                csPrograms.add(csProgram);
                System.debug('csPrograms'+csPrograms);
            }
        } 
        
        for(String si : mpChckBxspecialinclusions.keyset() )
        {
            if(mpChckBxspecialinclusions.get(si))
            {
                FilteredSpecialinclusions__c csSpInclusion = new FilteredSpecialinclusions__c();
                csSpInclusion.Name = si;
                csSpInclusions.add(csSpInclusion);
                System.debug('csSpInclusions'+csSpInclusions);
            }
        }       
        insert csProgramTypes;
        insert csPrograms;     
        insert csSpInclusions;
    
        PageReference page = new PageReference('/apex/XMLgeneratorHelper');              
        page.setRedirect(false);        
        return page;

    }
}