objects/Learning_Outcome__c.object
<CustomObject><fields>
        <fullName>Learning_Outcome__c</fullName>
        <label>Learning Outcome</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>Outcome_Type__c</fullName>
        <label>Outcome Type</label>
        <picklist>
            <picklistValues>
                <fullName>A (Knowledge &amp; Understanding)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B (Cognitive Skills)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C (Practical/Professional Skills)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <label>Programme Version</label>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Learning Outcomes</relationshipLabel>
        <relationshipName>Specification_Outcomes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Learning Outcome</label><nameField>
        <displayFormat>LO-{000000}</displayFormat>
        <label>Outcome Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Learning Outcomes</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Module_Version__c.object
<CustomObject><fields>
        <fullName>Master_Link__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Link</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Record must be a master</errorMessage>
            <filterItems>
                <field>Module_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Master Version</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Module_Version__c</referenceTo>
        <relationshipLabel>Child Module Versions</relationshipLabel>
        <relationshipName>Child_Module_Versions</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module Version</label><nameField>
        <label>Module Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Module Versions</pluralLabel><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><recordTypes>
        <fullName>Master_Version</fullName>
        <active>true</active>
        <label>Master Version</label>
    </recordTypes><recordTypes>
        <fullName>Versions</fullName>
        <active>true</active>
        <label>Versions</label>
    </recordTypes></CustomObject>

objects/Programme_Aim__c.object
<CustomObject><fields>
        <fullName>Programme_Version__c</fullName>
        <label>Programme Version</label>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Aims</relationshipLabel>
        <relationshipName>Programme_Aims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Programme Aim</label><nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Aim Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Programme Aims</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Programme_Version__c.object
<CustomObject><fields>
        <fullName>Master_Link__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To allow two levels of versions - master or senior, and child versions. Will provide external systems with a persistent ID across all Programmes and Programme Versions of same group</description>
        <label>Master Link</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Record must be a master</errorMessage>
            <filterItems>
                <field>Programme_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Master Version</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Child Programme Versions</relationshipLabel>
        <relationshipName>Programme_Versions</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme Version</label><nameField>
        <label>Programme Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programme Versions</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel><recordTypes>
        <fullName>Master_Version</fullName>
        <active>true</active>
        <description>Most senior level, defines family of related versions and instances</description>
        <label>Master Version</label>
    </recordTypes><recordTypes>
        <fullName>Versions</fullName>
        <active>true</active>
        <description>Annual (or other) iterations per programme</description>
        <label>Versions</label>
    </recordTypes></CustomObject>

objects/Skills_Attributes__c.object
<CustomObject><fields>
        <fullName>Programme_Version__c</fullName>
        <label>Programme Version</label>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Skills &amp; Attributes</relationshipLabel>
        <relationshipName>Skills_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Skill &amp; Attribute</label><nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Skill Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Skills &amp; Attributes</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/TestProgrammeVersionTabsExt.cls
/**
 * 2014-03-02 : Test class for ProgrammeVersionTabsExt
 */
@isTest
private class TestProgrammeVersionTabsExt {
    final static String PROG_MASTER_NAME = 'Master_Version';
    final static String PROG_VERSION_NAME = 'Versions';
    
    static testMethod void testController() {
        //Set up test data
        Map<String, RecordType> progRTMap = new Map<String, RecordType>();
        Map<String, RecordType> moduleRTMap = new Map<String, RecordType>();
        for (RecordType r : [select r.Id, r.DeveloperName from RecordType r where r.SObjectType = 'Programme_Version__c' and r.IsActive = true]){
            progRTMap.put(r.DeveloperName, r);
        }
        for (RecordType r : [select r.Id, r.DeveloperName from RecordType r where r.SObjectType = 'Module_Version__c' and r.IsActive = true]){
            moduleRTMap.put(r.DeveloperName, r);
        }
        
        Programme_Version__c newProgMaster = new Programme_Version__c();
        newProgMaster.Name = 'Test PVM';
        newProgMaster.RecordTypeId = progRTMap.get(PROG_MASTER_NAME).Id;
        insert newProgMaster;
        
        Programme_Version__c newProgVersion = new Programme_Version__c();
        newProgVersion.Name = 'Test PV ';
        newProgVersion.RecordTypeId = progRTMap.get(PROG_VERSION_NAME).Id;
        newProgVersion.Master_Link__c = newProgMaster.Id;
        insert newProgVersion;

        //Insert relates list records
        List<Programme_Aim__c> programmeAims = new List<Programme_Aim__c>();
        List<Skills_Attributes__c> skillsAttributes = new List<Skills_Attributes__c>();
        List<Learning_Outcome__c> learningOutcomes = new List<Learning_Outcome__c>();

        Programme_Aim__c pa = new Programme_Aim__c();
        pa.Programme_Version__c = newProgVersion.Id;
        insert pa;

        Skills_Attributes__c sa = new Skills_Attributes__c();
        sa.Programme_Version__c = newProgVersion.Id;
        insert sa;

        Learning_Outcome__c lc = new Learning_Outcome__c();
        lc.Programme_Version__c = newProgVersion.Id;
        lc.Outcome_Type__c = 'A (Knowledge & Understanding)';
        insert lc;
        
        ApexPages.StandardController std = new ApexPages.StandardController(newProgVersion);
        
        test.startTest();
        
        PageReference pageRef = Page.ProgrammeVersionTabs;
        
        ProgrammeVersionTabsExt pvte = new ProgrammeVersionTabsExt(std);
        
        test.stopTest();
        
    }
    
}