objects/Learning_Outcome__c.object
<CustomObject><fields>
        <fullName>Learning_Outcome__c</fullName>
        <label>Learning Outcome</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <label>Programme Version</label>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Learning Outcomes</relationshipLabel>
        <relationshipName>Specification_Outcomes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Record_No__c</fullName>
        <description>Set by workflow</description>
        <inlineHelpText>Leave blank on record creation if automatic numbering is required (set by Workflow)</inlineHelpText>
        <label>No.</label>
        <length>5</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Learning Outcome</label><nameField>
        <displayFormat>LO-{000000}</displayFormat>
        <label>Outcome Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Learning Outcomes</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Programme_Aim__c.object
<CustomObject><fields>
        <fullName>Programme_Version__c</fullName>
        <label>Programme Version</label>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Aims</relationshipLabel>
        <relationshipName>Programme_Aims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Record_No__c</fullName>
        <description>Text and not number to be consistent with Outcome Record No which needs letter prefix; set by workflow</description>
        <inlineHelpText>Leave blank on record creation if automatic numbering is required (set by Workflow)</inlineHelpText>
        <label>No.</label>
        <length>5</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Programme Aim</label><nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Aim Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Programme Aims</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Programme_Version__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme Version</label><nameField>
        <label>Programme Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programme Versions</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Skills_Attributes__c.object
<CustomObject><fields>
        <fullName>Programme_Version__c</fullName>
        <label>Programme Version</label>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Skills &amp; Attributes</relationshipLabel>
        <relationshipName>Skills_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Record_No__c</fullName>
        <description>Text and not number to be consistent with Outcome Record No which needs letter prefix; set by workflow</description>
        <inlineHelpText>Leave blank on record creation if automatic numbering is required (set by Workflow)</inlineHelpText>
        <label>No.</label>
        <length>5</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Skill &amp; Attribute</label><nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Skill Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Skills &amp; Attributes</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/ProgrammeVersionTabsExt.cls
/*
*
* 2015-03-02 : SM : Controller extension for the ProgrammeVersionTabs VF Page
*
*/
public class ProgrammeVersionTabsExt {
    public List<Programme_Aim__c> aimList {get; set;}
    public List<Learning_Outcome__c> outcomeList {get; set;}
    public List<Skills_Attributes__c> skillsList {get; set;}

    public ProgrammeVersionTabsExt(ApexPages.StandardController std){
        Id progId = std.getId();
        
        String aimQuery = 'SELECT ';
        for(Schema.FieldSetMember f : SObjectType.Programme_Aim__c.FieldSets.Aims.getFields()) {
            aimQuery += f.getFieldPath() + ', ';
        }
        
        aimQuery += 'Id from Programme_Aim__c where Programme_Version__c = :progId ORDER BY Record_No__c ASC';
                
        aimList = Database.query(aimQuery);
        
        String outcomeQuery = 'SELECT ';
        
        for(Schema.FieldSetMember f : SObjectType.Learning_Outcome__c.FieldSets.Outcomes.getFields()) {
            outcomeQuery += f.getFieldPath() + ', ';
        }
        
        outcomeQuery += 'Id from Learning_Outcome__c where Programme_Version__c = :progId ORDER BY Record_No__c ASC';
                
        outcomeList = Database.query(outcomeQuery);
        
        String skillsQuery = 'SELECT ';
        
        for(Schema.FieldSetMember f : SObjectType.Skills_Attributes__c.FieldSets.Skills.getFields()) {
            skillsQuery += f.getFieldPath() + ', ';
        }
        
        skillsQuery += 'Id from Skills_Attributes__c where Programme_Version__c = :progId ORDER BY Record_No__c ASC';
                
        skillsList = Database.query(skillsQuery);
        
        
        
    }

}