objects/Learning_Outcome__c.object
<CustomObject><fields>
        <fullName>Learning_Outcome__c</fullName>
        <label>Learning Outcome</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>Outcome_Type__c</fullName>
        <label>Outcome Type</label>
        <picklist>
            <picklistValues>
                <fullName>A (Knowledge &amp; Understanding)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B (Cognitive Skills)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C (Practical/Professional Skills)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <label>Programme Version</label>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Learning Outcomes</relationshipLabel>
        <relationshipName>Specification_Outcomes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Learning Outcome</label><nameField>
        <displayFormat>LO-{000000}</displayFormat>
        <label>Outcome Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Learning Outcomes</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Module_Version__c.object
<CustomObject><fields>
        <fullName>Master_Link__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Link</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Record must be a master</errorMessage>
            <filterItems>
                <field>Module_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Master Version</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Module_Version__c</referenceTo>
        <relationshipLabel>Child Module Versions</relationshipLabel>
        <relationshipName>Child_Module_Versions</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module Version</label><nameField>
        <label>Module Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Module Versions</pluralLabel><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><recordTypes>
        <fullName>Master_Version</fullName>
        <active>true</active>
        <label>Master Version</label>
    </recordTypes><recordTypes>
        <fullName>Versions</fullName>
        <active>true</active>
        <label>Versions</label>
    </recordTypes></CustomObject>

objects/Programme_Aim__c.object
<CustomObject><fields>
        <fullName>Programme_Version__c</fullName>
        <label>Programme Version</label>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Aims</relationshipLabel>
        <relationshipName>Programme_Aims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Programme Aim</label><nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Aim Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Programme Aims</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Programme_Module_Version__c.object
<CustomObject><fields>
        <fullName>Module_Version__c</fullName>
        <inlineHelpText>To find correct Module Version type the first few character of Module Version title then click magnifying glass for available options</inlineHelpText>
        <label>Module Version</label>
        <referenceTo>Module_Version__c</referenceTo>
        <relationshipLabel>Programme Module Versions</relationshipLabel>
        <relationshipName>Instance_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <label>Programme Version</label>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Programme Module Versions</relationshipLabel>
        <relationshipName>Instance_Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Many-to-many object to allow one Module version to be a member of multiple Programme version</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Programme Module Version</label><nameField>
        <displayFormat>PMV-{00000000}</displayFormat>
        <label>Programme Module Version</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Programme Module Versions</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Programme_Version__c.object
<CustomObject><fields>
        <fullName>Master_Link__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To allow two levels of versions - master or senior, and child versions. Will provide external systems with a persistent ID across all Programmes and Programme Versions of same group</description>
        <label>Master Link</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Record must be a master</errorMessage>
            <filterItems>
                <field>Programme_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Master Version</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Child Programme Versions</relationshipLabel>
        <relationshipName>Programme_Versions</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme Version</label><nameField>
        <label>Programme Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programme Versions</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel><recordTypes>
        <fullName>Master_Version</fullName>
        <active>true</active>
        <description>Most senior level, defines family of related versions and instances</description>
        <label>Master Version</label>
    </recordTypes><recordTypes>
        <fullName>Versions</fullName>
        <active>true</active>
        <description>Annual (or other) iterations per programme</description>
        <label>Versions</label>
    </recordTypes></CustomObject>

objects/Skills_Attributes__c.object
<CustomObject><fields>
        <fullName>Programme_Version__c</fullName>
        <label>Programme Version</label>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Skills &amp; Attributes</relationshipLabel>
        <relationshipName>Skills_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Skill &amp; Attribute</label><nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Skill Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Skills &amp; Attributes</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/TestCloneProgrammeVersionController.cls
/**
 * 2014-05-22 : Test class for CloneProgrammeController
 */
@isTest
private class TestCloneProgrammeVersionController {
    final static String PROG_MASTER_NAME = 'Master_Version';
    final static String PROG_VERSION_NAME = 'Versions';
    final static String MODULE_MASTER_NAME = 'Master_Version';
    final static String MODULE_VERSION_NAME = 'Versions';

    static testMethod void testController() {
        //Set up test data
        Map<String, RecordType> progRTMap = new Map<String, RecordType>();
        Map<String, RecordType> moduleRTMap = new Map<String, RecordType>();
        for (RecordType r : [select r.Id, r.DeveloperName from RecordType r where r.SObjectType = 'Programme_Version__c' and r.IsActive = true]){
            progRTMap.put(r.DeveloperName, r);
        }
        for (RecordType r : [select r.Id, r.DeveloperName from RecordType r where r.SObjectType = 'Module_Version__c' and r.IsActive = true]){
            moduleRTMap.put(r.DeveloperName, r);
        }
        
        Programme_Version__c newProgMaster = new Programme_Version__c();
        newProgMaster.Name = 'Test PVM';
        newProgMaster.RecordTypeId = progRTMap.get(PROG_MASTER_NAME).Id;
        insert newProgMaster;
        
        Map<String, Module_Version__c> modMap = new Map<String, Module_Version__c>();
        for (integer i = 0 ; i < 4 ; i++){
        	Module_Version__c m = new Module_Version__c();
        	m.Name = 'Test MVM ' + i;
        	//m.Instance_Date__c = date.today();
            m.RecordTypeId = moduleRTMap.get(MODULE_MASTER_NAME).Id;
        	modMap.put(m.Name, m);
        }
        
        insert modMap.values();
        
        Programme_Version__c newProgVersion = new Programme_Version__c();
        newProgVersion.Name = 'Test PV ';
        newProgVersion.RecordTypeId = progRTMap.get(PROG_VERSION_NAME).Id;
        newProgVersion.Master_Link__c = newProgMaster.Id;
        insert newProgVersion;

        //Insert relates list records
        List<Programme_Aim__c> programmeAims = new List<Programme_Aim__c>();
        List<Skills_Attributes__c> skillsAttributes = new List<Skills_Attributes__c>();
        List<Learning_Outcome__c> learningOutcomes = new List<Learning_Outcome__c>();

        Programme_Aim__c pa = new Programme_Aim__c();
        pa.Programme_Version__c = newProgVersion.Id;
        insert pa;

        Skills_Attributes__c sa = new Skills_Attributes__c();
        sa.Programme_Version__c = newProgVersion.Id;
        insert sa;

        Learning_Outcome__c lc = new Learning_Outcome__c();
        lc.Programme_Version__c = newProgVersion.Id;
        lc.Outcome_Type__c = 'A (Knowledge & Understanding)';
        insert lc;

        Map<String, Module_Version__c> modMapVersions = new Map<String, Module_Version__c>();
        for (integer i = 0 ; i < 4 ; i++){
            Module_Version__c m = new Module_Version__c();
            m.Name = 'Test MV ' + i;
            //m.Instance_Date__c = date.today();
            m.RecordTypeId = moduleRTMap.get(MODULE_VERSION_NAME).Id;
            m.Master_Link__c = modMap.get('Test MVM ' + i).Id;
            modMapVersions.put(m.Name, m);
        }

        insert modMapVersions.values();

        List<Programme_Module_Version__c> newModVersionList = new List<Programme_Module_Version__c>();
        for (integer i = 0 ; i < 4 ; i++){
            Programme_Module_Version__c pmv = new Programme_Module_Version__c();
            pmv.Programme_Version__c = newProgVersion.Id;
            pmv.Module_Version__c = modMapVersions.get('Test MV ' + i).Id;
            newModVersionList.add(pmv);
        }
        
        insert newModVersionList;

        
        PageReference pageRef = Page.CloneProgrammeVersion;
        pageRef.getParameters().put('progId',newProgVersion.Id);
        test.setCurrentPage(pageRef);
        
        ApexPages.StandardController std = new ApexPages.StandardController(newProgVersion); 
        
        test.startTest();
        
        CloneProgrammeVersionController cpc = new CloneProgrammeVersionController(std);

        cpc.moduleWrapperList[0].isSelected = true;
        
        PageReference returnRef = cpc.cloneProgramme();
               
        test.stopTest();
    }
    
    static testMethod void testControllerWithFilter() {
         //Set up test data
        Map<String, RecordType> progRTMap = new Map<String, RecordType>();
        Map<String, RecordType> moduleRTMap = new Map<String, RecordType>();
        for (RecordType r : [select r.Id, r.DeveloperName from RecordType r where r.SObjectType = 'Programme_Version__c' and r.IsActive = true]){
            progRTMap.put(r.DeveloperName, r);
        }
        for (RecordType r : [select r.Id, r.DeveloperName from RecordType r where r.SObjectType = 'Module_Version__c' and r.IsActive = true]){
            moduleRTMap.put(r.DeveloperName, r);
        }
        
        Programme_Version__c newProgMaster = new Programme_Version__c();
        newProgMaster.Name = 'Test PVM';
        newProgMaster.RecordTypeId = progRTMap.get(PROG_MASTER_NAME).Id;
        insert newProgMaster;
        
        Map<String, Module_Version__c> modMap = new Map<String, Module_Version__c>();
        for (integer i = 0 ; i < 4 ; i++){
            Module_Version__c m = new Module_Version__c();
            m.Name = 'Test MVM ' + i;
            //m.Instance_Date__c = date.today();
            m.RecordTypeId = moduleRTMap.get(MODULE_MASTER_NAME).Id;
            modMap.put(m.Name, m);
        }
        
        insert modMap.values();
        
        Programme_Version__c newProgVersion = new Programme_Version__c();
        newProgVersion.Name = 'Test Programme Version ';
        newProgVersion.RecordTypeId = progRTMap.get(PROG_VERSION_NAME).Id;
        newProgVersion.Master_Link__c = newProgMaster.Id;
        insert newProgVersion;

        Map<String, Module_Version__c> modMapVersions = new Map<String, Module_Version__c>();
        for (integer i = 0 ; i < 4 ; i++){
            Module_Version__c m = new Module_Version__c();
            m.Name = 'Test MV ' + i;
            //m.Instance_Date__c = date.today();
            m.RecordTypeId = moduleRTMap.get(MODULE_VERSION_NAME).Id;
            m.Master_Link__c = modMap.get('Test MVM ' + i).Id;
            modMapVersions.put(m.Name, m);
        }

        insert modMapVersions.values();

        List<Programme_Module_Version__c> newModVersionList = new List<Programme_Module_Version__c>();
        for (integer i = 0 ; i < 4 ; i++){
            Programme_Module_Version__c pmv = new Programme_Module_Version__c();
            pmv.Programme_Version__c = newProgVersion.Id;
            pmv.Module_Version__c = modMapVersions.get('Test MV ' + i).Id;
            newModVersionList.add(pmv);
        }
        
        insert newModVersionList;
        
        PageReference pageRef = Page.CloneProgrammeVersion;
        pageRef.getParameters().put('progId',newProgVersion.Id);
        test.setCurrentPage(pageRef);
        
        ApexPages.StandardController std = new ApexPages.StandardController(newProgVersion);
        
        test.startTest();
        
        CloneProgrammeVersionController cpc = new CloneProgrammeVersionController(std);
        
        cpc.filterName = 'Test';
        
        PageReference returnRef = cpc.filterModules();
               
        test.stopTest();
        
    }
    
    
}