objects/Module__c.object
<CustomObject><fields>
        <fullName>Module_Code__c</fullName>
        <description>Course unique Code value</description>
        <label>Module Code</label>
        <length>64</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>VLE_ID__c</fullName>
        <description>Course offering ID at VLE side</description>
        <label>VLE ID</label>
        <length>32</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Instances of Modules</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module</label><nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Modules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/TestModuleServices.cls
@isTest
private class TestModuleServices
{
    static testMethod void testModuleServices() 
    {
        Map<Id,Module__c> oldMap = new Map<Id,Module__c>();
        List<Module__c> moduleList = new List<Module__c>();   
        Module__c module = new Module__c();
        module.Name = 'Test Module'; 
        module.Test_Class_Record__c = true;
        module.VLE_ID__c = '1234'; 
        module.Module_Code__c = 'Test Code';
        moduleList.add(module);
        insert moduleList;
        oldMap.put(module.Id,module);
        ModuleServices.findActiveModules(moduleList);      
        ModuleServices.findModulesSetAsInactive(moduleList,oldMap);  
    }
}