objects/Module__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Instance_Suffix__c</fullName>
        <label>Instance Suffix</label>
        <length>20</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Module_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Filter prevents attaching Master record for Module Versions to Module Instance</description>
        <label>Module Version</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Module_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Versions</value>
            </filterItems>
            <filterItems>
                <field>Module_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Pre-Approved</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Module_Version__c</referenceTo>
        <relationshipLabel>Module Instances</relationshipLabel>
        <relationshipName>Modules_Instances</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Instances of Modules</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module</label><nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Modules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Module_Version__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Master_Link__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Link</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Record must be a master</errorMessage>
            <filterItems>
                <field>Module_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Master Version</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Module_Version__c</referenceTo>
        <relationshipLabel>Child Module Versions</relationshipLabel>
        <relationshipName>Child_Module_Versions</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Version_Suffix__c</fullName>
        <label>Version Suffix</label>
        <length>20</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module Version</label><nameField>
        <label>Module Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Module Versions</pluralLabel><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><recordTypes>
        <fullName>Versions</fullName>
        <active>true</active>
        <label>Versions</label>
    </recordTypes></CustomObject>

objects/Programme__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used for lookup from Student processes</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Code__c</fullName>
        <formula>Programme_Version__r.Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Taken from Version level</inlineHelpText>
        <label>Code</label>
        <type>Text</type>
    </fields><fields>
        <fullName>End_Date__c</fullName>
        <description>Last Date module is valid</description>
        <label>End Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Home_EU_Fee__c</fullName>
        <inlineHelpText>Fee for UK and rest of EU students; if 'Fee TBC' is checked this amount is an estimate for reporting</inlineHelpText>
        <label>Home EU Fee</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Instance_Suffix__c</fullName>
        <label>Instance Suffix</label>
        <length>20</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Mode__c</fullName>
        <formula>Text(  Programme_Version__r.Mode__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Taken from Version level</inlineHelpText>
        <label>Mode</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme_Group__c</fullName>
        <formula>TEXT( Programme_Version__r.Programme_Group__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Taken from Version level</inlineHelpText>
        <label>Programme Group</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme_Type__c</fullName>
        <description>DO NOT USE, to be deleted</description>
        <label>X Programme Type</label>
        <picklist>
            <picklistValues>
                <fullName>MSc Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Diploma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSc Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Course</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme Version</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Programme_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Versions, Versions, Specification, Versions - Pre Approved, Specification Edit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Programme Instances</relationshipLabel>
        <relationshipName>Programmes_Instances</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme_Module__c.object
<CustomObject><fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To find correct Module type first the few character of Module title then click magnifying glass for available options</inlineHelpText>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Assigned Programmes</relationshipLabel>
        <relationshipName>Programme_Modules</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Programme_Type__c</fullName>
        <formula>Programme__r.Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Taken from Programme level</inlineHelpText>
        <label>Programme Type</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme__c</fullName>
        <description>Via Master-Detail relationship, no reparenting allowed</description>
        <label>Programme</label>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Assigned Modules</relationshipLabel>
        <relationshipName>Programme_Modules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Many to many object, to allow one Module (instance) to be a member of multiple Programmes (instances)</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Programme Module</label><nameField>
        <displayFormat>PMI-{00000000}</displayFormat>
        <label>Programme Module</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Programme Modules</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Programme_Module_Version__c.object
<CustomObject><fields>
        <fullName>Module_Version__c</fullName>
        <inlineHelpText>To find correct Module Version type the first few character of Module Version title then click magnifying glass for available options</inlineHelpText>
        <label>Module Version</label>
        <referenceTo>Module_Version__c</referenceTo>
        <relationshipLabel>Programme Module Versions</relationshipLabel>
        <relationshipName>Instance_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <label>Programme Version</label>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Programme Module Versions</relationshipLabel>
        <relationshipName>Instance_Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Many-to-many object to allow one Module version to be a member of multiple Programme version</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Programme Module Version</label><nameField>
        <displayFormat>PMV-{00000000}</displayFormat>
        <label>Programme Module Version</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Programme Module Versions</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Programme_Version__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Code__c</fullName>
        <inlineHelpText>Internal LSTM programme code</inlineHelpText>
        <label>Code</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Master_Link__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To allow two levels of versions - master or senior, and child versions. Will provide external systems with a persistent ID across all Programmes and Programme Versions of same group</description>
        <label>Master Link</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Record must be a master</errorMessage>
            <filterItems>
                <field>Programme_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Master Version</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Child Programme Versions</relationshipLabel>
        <relationshipName>Programme_Versions</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Mode__c</fullName>
        <label>Mode of Study</label>
        <picklist>
            <picklistValues>
                <fullName>FT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Programme_Group__c</fullName>
        <label>Programme Group</label>
        <picklist>
            <picklistValues>
                <fullName>Clinical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Humanitarian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Laboratory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maternal &amp; Child Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning, Management &amp; Personal Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Health &amp; Humanitarian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sexual &amp; Reproductive Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel Health Courses</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Programme_Type__c</fullName>
        <label>Programme Type</label>
        <picklist>
            <picklistValues>
                <fullName>MSc Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Diploma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Masters Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG Cert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Course</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Date of first Intake</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Version_Suffix__c</fullName>
        <description>To differentiate between Programme Versions, added to Master name</description>
        <label>Version Suffix</label>
        <length>20</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme Version</label><nameField>
        <label>Programme Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programme Versions</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel><recordTypes>
        <fullName>Versions</fullName>
        <active>true</active>
        <description>Annual (or other) iterations per programme</description>
        <label>Versions</label>
    </recordTypes></CustomObject>

classes/QuickCreateProgrammeCont.cls
/**
 * @author Mykola Senyk
 * @date 16/07/2014
 * @description Controller for QuickCreateProgramme page
 */
public with sharing class QuickCreateProgrammeCont {
    
    // inner fields
    private Programme_Version__c masterProgramme;
    private Programme_Version__c versionProgramme;
    @TestVisible
    private Programme__c programme;
    private Module_Version__c masterModule;
    private Module_Version__c versionModule;
    @TestVisible
    private Module__c module;
    private Programme_Module_Version__c pmv;
    Programme_Module__c pm;
    
    public QuickCreateProgrammeCont() {
        init();
    }
    
    public Programme__c prog { get; set; }
    public Programme_Version__c progVersion { get; set; }
    public Programme_Module__c progModule { get; set; }
    
    
    /**
     * To do initialization
     */
    private void init() {
        prog = new Programme__c();
        progVersion = new Programme_Version__c(Mode__c = ApplyServices.PV_MODE_FT);
        progModule = new Programme_Module__c();
    }
    
    /**
     * Create programme with versions
     */
    private void buildProgrammes() {
        masterProgramme = new Programme_Version__c(
            RecordTypeId = CommonUtils.findRecordTypeIdByDev('Programme_Version__c', ApplyServices.RT_MASTER_PV_DEVNAME),
            Name = prog.Name, Active__c = prog.Active__c, Programme_Type__c = progVersion.Programme_Type__c,
            Mode__c = progVersion.Mode__c, Code__c = progVersion.Code__c, Programme_Group__c = progVersion.Programme_Group__c
        );
        insert masterProgramme;
        
        versionProgramme = new Programme_Version__c(
            RecordTypeId = CommonUtils.findRecordTypeIdByDev('Programme_Version__c', ApplyServices.RT_VERSION_PV_DEVNAME),
            Master_Link__c = masterProgramme.Id,
            Name = prog.Name, Version_Suffix__c = prog.Instance_Suffix__c, Start_Date__c = prog.Start_Date__c, End_Date__c = prog.End_Date__c,
            Active__c = prog.Active__c, Programme_Type__c = progVersion.Programme_Type__c,
            Mode__c = progVersion.Mode__c, Code__c = progVersion.Code__c, Programme_Group__c = progVersion.Programme_Group__c
        );
        insert versionProgramme;
        
        programme = new Programme__c(
            Programme_Version__c = versionProgramme.Id,
            Name = prog.Name, Instance_Suffix__c = prog.Instance_Suffix__c, Start_Date__c = prog.Start_Date__c, End_Date__c = prog.End_Date__c,
            Active__c = prog.Active__c, Home_EU_Fee__c = prog.Home_EU_Fee__c, Overseas_Fee__c = prog.Overseas_Fee__c, Capacity__c = prog.Capacity__c
        );
        insert programme;
    }
    
    /**
     * Create module and versions
     */
    private void buildModules() {
        if ( progModule.Module__c != null ) {
            // use existing Module Reference
            module = [
                SELECT Id, Module_Version__r.Id, Module_Version__r.Master_Link__r.Id
                FROM Module__c
                WHERE Id = :progModule.Module__c
            ];
            versionModule = module.Module_Version__r;
            masterModule = versionModule.Master_Link__r;
        } else {
            // create new module and version
            masterModule = new Module_Version__c(
                RecordTypeId = CommonUtils.findRecordTypeIdByDev('Module_Version__c', ApplyServices.RT_MASTER_MV_DEVNAME),
                Name = prog.Name, Active__c = prog.Active__c
            );
            insert masterModule;
            
            versionModule = new Module_Version__c(
                RecordTypeId = CommonUtils.findRecordTypeIdByDev('Module_Version__c', ApplyServices.RT_VERSION_MV_DEVNAME),
                Master_Link__c = masterModule.Id,
                Name = prog.Name, Version_Suffix__c = prog.Instance_Suffix__c, Start_Date__c = prog.Start_Date__c, End_Date__c = prog.End_Date__c,
                Active__c = prog.Active__c
            );
            insert versionModule;
            
            module = new Module__c(
                Module_Version__c = versionModule.Id,
                Name = prog.Name, Instance_Suffix__c = prog.Instance_Suffix__c, // FIXME Start_Date__c = prog.Start_Date__c, End_Date__c = prog.End_Date__c,
                Active__c = prog.Active__c
            );
            insert module;
        }
    }
    
    /**
     * Create junction records between programme and module and related versions
     */
    private void buildJunctionRecords() {
        // join module version with programme version (RT Versions)
        pmv = new Programme_Module_Version__c(
            Programme_Version__c = versionProgramme.Id, Module_Version__c = versionModule.Id
        );
        insert pmv;
        
        // join module with programme
        pm = new Programme_Module__c(
            Programme__c = programme.Id, Module__c = module.Id
        );
        insert pm;
    }
    
    /**
     * Action for quick create set of records
     */
    public PageReference create() {
        // return link to just created programme
        buildProgrammes();
        buildModules();
        buildJunctionRecords();
        
        PageReference pr = new ApexPages.StandardController(programme).view();
        pr.setRedirect(true);
        return pr;
    }

}