objects/Module_Role__c.object
<CustomObject><fields>
        <fullName>Module_Role__c</fullName>
        <description>Defines role for Module Spec, and against Module Instance for VLE integration</description>
        <label>Module Role</label>
        <picklist>
            <picklistValues>
                <fullName>Module Convenor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Module Moderator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Examiner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Teacher</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Join object between Staff (Contacts) and Modules (both Instances and Version objects). Will allow definition of staff role on a module and be used in VLE integration to define extent of staff enrolment.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Module Role</label><nameField>
        <displayFormat>MR-{00000000}</displayFormat>
        <label>Module Role Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Module Roles</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Programme_Version__c.object
<CustomObject><fields>
        <fullName>Programme_Type__c</fullName>
        <label>Programme Type</label>
        <picklist>
            <picklistValues>
                <fullName>MSc Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Diploma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Masters Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG Cert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Course</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme Version</label><nameField>
        <label>Programme Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programme Versions</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/VLE__c.object
<CustomObject><customSettingsType>List</customSettingsType><description>Credentials for VLE external service</description><enableFeeds>false</enableFeeds><label>VLE parameters</label><visibility>Protected</visibility></CustomObject>

objects/VLE_Org_Wide_Units_And_Role_Assignments__c.object
<CustomObject><fields>
        <fullName>Available_for_Staff__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this Org Unit relates to STAFF Only. Either "Is Student" OR "Is Staff" should be selected</description>
        <inlineHelpText>Is this Org Unit relates to Staff Only. Either "Is Student" OR "Is Staff" should be selected</inlineHelpText>
        <label>Available for Staff</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Available_for_Student__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this Org Unit relates to Student Only.</description>
        <inlineHelpText>Is this Org Unit relates to Student Only.</inlineHelpText>
        <label>Available for Student</label>
        <type>Checkbox</type>
    </fields><customSettingsType>List</customSettingsType><enableFeeds>false</enableFeeds><label>VLE Org Wide Units And Role Assignments</label><visibility>Public</visibility></CustomObject>

objects/VLE_Program_Type_2_Role_VLE_ID_Mapping__c.object
<CustomObject><fields>
        <fullName>Programme_Type__c</fullName>
        <description>Programme Version's Programme Type, which defines what Role Student will be enrolled to VLE Courses</description>
        <inlineHelpText>Programme Version's Programme Type, which defines what Role Student will be enrolled to VLE Courses</inlineHelpText>
        <label>Programme Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields><customSettingsType>List</customSettingsType><enableFeeds>false</enableFeeds><label>VLE: Program Type to Role VLE ID Mapping</label><visibility>Protected</visibility></CustomObject>

objects/VLE_Roles__c.object
<CustomObject><fields>
        <fullName>Available_for_Staff__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available for Staff</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Available_for_Student__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available for Student</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Vle_Role_Id__c</fullName>
        <description>Role Id in Vle Environment</description>
        <inlineHelpText>Role Id in Vle Environment</inlineHelpText>
        <label>Vle Role Id</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields><customSettingsType>List</customSettingsType><enableFeeds>false</enableFeeds><label>VLE Roles</label><visibility>Public</visibility></CustomObject>

objects/VLE_Staff_Module_Roles_And_Vle_Role_Ids__c.object
<CustomObject><fields>
        <fullName>Module_Role__c</fullName>
        <label>Module Role</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields><customSettingsType>List</customSettingsType><enableFeeds>false</enableFeeds><label>VLE Staff Module Roles And Vle Role Ids</label><visibility>Public</visibility></CustomObject>

classes/ManageVleOrgWideUnitRolesController.cls
public class ManageVleOrgWideUnitRolesController {

    public ManageVleOrgWideUnitRolesController(){
        isValid = false;
        
        try{
            initAndValidate();
        } catch (Exception e){
            ApexPages.addMessage( new ApexPages.message( ApexPages.severity.INFO, e.getMessage() ) );
            return;
        }
        isValid = true;
    }
    
    public Boolean isValid {get;set;}
    
    public List<SelectOption> studentRoles { get; set; }
    public List<SelectOption> staffRoles { get; set; }

    public List<SelectOption> moduleRoles { get; set; }
    public List<SelectOption> programTypes { get; set; }

    public List<VLE_Program_Type_2_Role_VLE_ID_Mapping__c> studentProgramType2VleRoleId {get; set;}
    public List<VLE_Staff_Module_Roles_And_Vle_Role_Ids__c> staffModuleRole2VleRoleId {get; set;}   
    public List<VLE_Org_Wide_Units_And_Role_Assignments__c> staffOrgUnitsParameters {get; set;}
    
    public Vle__c vleParameters {get;set;}

    public PageReference saveMappings(){

        try {
        
            Set<String> duplicates = new Set<String>();
            for ( VLE_Program_Type_2_Role_VLE_ID_Mapping__c prop : studentProgramType2VleRoleId ){
                prop.Name = prop.Programme_Type__c;
                if (! duplicates.add( prop.Programme_Type__c ) ) {
                    ApexPages.addMessage( new ApexPages.message( ApexPages.severity.ERROR, 'Duplicate Programme Type' ) );
                    return null;
                }
            }
            upsert studentProgramType2VleRoleId;
            
            duplicates  = new Set<String>();
            for ( VLE_Staff_Module_Roles_And_Vle_Role_Ids__c prop : staffModuleRole2VleRoleId ){
                prop.Name = prop.Module_Role__c;
                if (! duplicates.add( prop.Module_Role__c) ) {
                    ApexPages.addMessage( new ApexPages.message( ApexPages.severity.ERROR, 'Duplicate Module Role' ) );
                    return null;
                }                
            }            
            upsert staffModuleRole2VleRoleId;

            upsert staffOrgUnitsParameters;
            
            update vleParameters;

        } catch ( Exception e ){
            ApexPages.addMessage( new ApexPages.message( ApexPages.severity.INFO, 'Something went wrong while saving ... ' + e.getMessage() ) );
            return null;
        }
        
        ApexPages.addMessage( new ApexPages.message( ApexPages.severity.CONFIRM, 'Saved succesfully' ) );
        return null;
    }

    public PageReference cancel(){
        return Page.VleAdmin;
    }

    public String objName {get;set;}
    public void addRecord( ){
        if ( objName == 'VLE_Program_Type_2_Role_VLE_ID_Mapping__c' ){
            studentProgramType2VleRoleId.add( new VLE_Program_Type_2_Role_VLE_ID_Mapping__c() );
        
        } else  if ( objName == 'VLE_Staff_Module_Roles_And_Vle_Role_Ids__c' ){
            staffModuleRole2VleRoleId.add( new VLE_Staff_Module_Roles_And_Vle_Role_Ids__c() );
        
        } else if ( objName == 'VLE_Org_Wide_Units_And_Role_Assignments__c' ){
            staffOrgUnitsParameters.add( new VLE_Org_Wide_Units_And_Role_Assignments__c() );
        }
    }

    public Integer indexToDelete {get;set;}
    
    public void deleteRowStaff(){
        VLE_Staff_Module_Roles_And_Vle_Role_Ids__c param = staffModuleRole2VleRoleId.get( indexToDelete  );
        if ( param.Id != null ){
            delete param;
        }
        staffModuleRole2VleRoleId.remove( indexToDelete   );
    }

    public void deleteRowStudent(){
        VLE_Program_Type_2_Role_VLE_ID_Mapping__c param = studentProgramType2VleRoleId.get( indexToDelete  );
        if ( param.Id != null ){
            delete param;
        }
        studentProgramType2VleRoleId.remove( indexToDelete   );
    }

    private void initAndValidate(){

        //INIT STUDENT ROLES
        studentRoles = new List<SelectOption>();
        for ( VLE_Roles__c role : VLE_Roles__c.getAll().values() ) {
            if ( role.Available_for_Student__c && role.Vle_Role_Id__c != null ){
                studentRoles.add( new SelectOption( role.Vle_Role_Id__c, role.Name + ' (' + role.Vle_Role_Id__c + ')' ) );
            }
        }
        if ( studentRoles.isEmpty() ){
            ApexPages.addMessage( new ApexPages.message( ApexPages.severity.INFO, ' Student Roles are not setup. Please go to Setup => Custom Settings => "VLE Roles"' ) );
        }

        //INIT STAFF ROLES SETTINTS
        staffRoles = new List<SelectOption>();
        for ( VLE_Roles__c role : VLE_Roles__c.getAll().values() ) {
            if ( role.Available_for_Staff__c && role.Vle_Role_Id__c != null ){
                staffRoles.add( new SelectOption( role.Vle_Role_Id__c, role.Name + ' (' + role.Vle_Role_Id__c + ')'  ) );
            }
        }
        if ( staffRoles.isEmpty() ){
            ApexPages.addMessage( new ApexPages.message( ApexPages.severity.INFO, ' Staff Roles are not setup. Please go to Setup => Custom Settings => "VLE Roles"' ) );
        }

        //INIT MODULE ROLES PICKLIST VALUES
        moduleRoles = new List<SelectOption>();
        for ( String picklistValue : getPicklistValues( Module_Role__c.Module_Role__c ) ){
            moduleRoles.add( new SelectOption( picklistValue, picklistValue ) );
        }

        //INIT PROGRAM TYPES PICKLIST VALUES
        programTypes = new List<SelectOption>();
        for ( String picklistValue : getPicklistValues( Programme_Version__c.Programme_Type__c ) ){
            programTypes.add( new SelectOption( picklistValue, picklistValue ) );
        }   
    
        //INIT SETTINGS FOR MAPPINGS
        studentProgramType2VleRoleId = VLE_Program_Type_2_Role_VLE_ID_Mapping__c.getAll().values();
        staffModuleRole2VleRoleId = VLE_Staff_Module_Roles_And_Vle_Role_Ids__c.getAll().values();
        
        staffOrgUnitsParameters = new List<VLE_Org_Wide_Units_And_Role_Assignments__c>();
        for ( VLE_Org_Wide_Units_And_Role_Assignments__c orgUnitParam : VLE_Org_Wide_Units_And_Role_Assignments__c.getAll().values() ){
            if ( orgUnitParam.Available_for_Staff__c ){
                staffOrgUnitsParameters.add( orgUnitParam );
            }
        }
        
        //INIT VLE PARAMETERS SETTINGS  
        vleParameters = Vle__c.getInstance(VleServices.CS_NAME);
        if ( vleParameters == null ){
            ApexPages.addMessage( new ApexPages.message( ApexPages.severity.INFO, 'Vle Parameters are not setup. Please go to Setup => Custom Settings => "VLE parameters". Create record with name "main"' ) );
            return;
        }        
        
    }

    private static List<String> getPicklistValues(Schema.sObjectField picklistFieldToken) {
        List<String> values = new List<String>();
        List<Schema.PicklistEntry> plEntries = picklistFieldToken.getDescribe().getPicklistValues();
        for (Schema.PicklistEntry item: plEntries) {
            values.add(item.getValue());
        }
        return values;
    }

}