objects/Module__c.object
<CustomObject><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Instances of Modules</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module</label><nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Modules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme__c.object
<CustomObject><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme_Module__c.object
<CustomObject><fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To find correct Module type first the few character of Module title then click magnifying glass for available options</inlineHelpText>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Assigned Programmes</relationshipLabel>
        <relationshipName>Programme_Modules</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Programme__c</fullName>
        <description>Via Master-Detail relationship, no reparenting allowed</description>
        <label>Programme</label>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Assigned Modules</relationshipLabel>
        <relationshipName>Programme_Modules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Many to many object, to allow one Module (instance) to be a member of multiple Programmes (instances)</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Programme Module</label><nameField>
        <displayFormat>PMI-{00000000}</displayFormat>
        <label>Programme Module</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Programme Modules</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/TestCloneUtilities.cls
/**
 * 2014-05-13 : CSL : Test class for CloneUtilities
 * This class contains unit tests for the CloneUtilities class
 *
 */
@isTest
private class TestCloneUtilities {

    static testMethod void testCloneProgramme() {
        //Set up test data
        Programme__c newProg = new Programme__c();
        newProg.Name = 'Test Programme';
        newProg.Test_Class_Record__c = true;
        insert newProg;
        
        Map<String, Module__c> modMap = new Map<String, Module__c>();
        for (integer i = 0 ; i < 4 ; i++){
            Module__c m = new Module__c();
            m.Name = 'Test Module ' + i;
            m.Test_Class_Record__c = true;           
            modMap.put(m.Name, m);
        }
        
        insert modMap.values();
        
        List<Programme_Module__c> newModList = new List<Programme_Module__c>();
        for (integer i = 0 ; i < 4 ; i++){
            Programme_Module__c pm = new Programme_Module__c();
            pm.Programme__c = newProg.Id;
            pm.Module__c = modMap.get('Test Module ' + i).Id;
            pm.Test_Class_Record__c = true;
            newModList.add(pm);
        }
        
        insert newModList;
        
        test.startTest();
        
        String cloneProgId = CloneUtilities.cloneProgramme(newProg.Id);
                
        system.assertNotEquals(null, cloneProgId);
        
        Programme__c cloneProg = [select p.Name from Programme__c p where p.Id = :cloneProgId];
        
        //system.assertEquals(newProg.Name + '_CLONE', cloneProg.Name);
        
        test.stopTest();
        
    }
    
    static testMethod void testCloneProgramme2() {
        //Set up test data
        Programme__c newProg = new Programme__c();
        newProg.Name = 'Test Programme';
        newProg.Test_Class_Record__c = true;
        insert newProg;
        
        Map<String, Module__c> modMap = new Map<String, Module__c>();
        for (integer i = 0 ; i < 4 ; i++){
            Module__c m = new Module__c();
            m.Name = 'Test Module ' + i;
            m.Test_Class_Record__c = true;           
            modMap.put(m.Name, m);
        }
        
        insert modMap.values();
        
        List<Programme_Module__c> newModList = new List<Programme_Module__c>();
        for (integer i = 0 ; i < 4 ; i++){
            Programme_Module__c pm = new Programme_Module__c();
            pm.Programme__c = newProg.Id;
            pm.Module__c = modMap.get('Test Module ' + i).Id;
            pm.Test_Class_Record__c = true;
            newModList.add(pm);
        }
        
        insert newModList;
        
        test.startTest();
        
        Test.setCurrentPageReference(new PageReference('Page.ProgrammeClone')); 
        System.currentPageReference().getParameters().put('id', newProg.Id);        
        ApexPages.StandardController ctlr = new ApexPages.StandardController(newProg);
        CloneUtilities obj = new CloneUtilities(ctlr);
        obj.cloneProgrammeVF(newProg.Id);
        
        test.stopTest();
        
    }    
}