objects/Module__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Instance_Suffix__c</fullName>
        <label>Instance Suffix</label>
        <length>20</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Instances of Modules</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module</label><nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Modules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used for lookup from Student processes</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Capacity__c</fullName>
        <description>Number of students that can be taken on this Programme</description>
        <label>Capacity</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Code__c</fullName>
        <formula>Programme_Version__r.Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Taken from Version level</inlineHelpText>
        <label>Code</label>
        <type>Text</type>
    </fields><fields>
        <fullName>End_Date__c</fullName>
        <description>Last Date module is valid</description>
        <label>End Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Home_EU_Fee__c</fullName>
        <inlineHelpText>Fee for UK and rest of EU students; if 'Fee TBC' is checked this amount is an estimate for reporting</inlineHelpText>
        <label>Home EU Fee</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Instance_Suffix__c</fullName>
        <label>Instance Suffix</label>
        <length>20</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Mode__c</fullName>
        <formula>Text(  Programme_Version__r.Mode__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Taken from Version level</inlineHelpText>
        <label>Mode</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Overseas_Fee__c</fullName>
        <inlineHelpText>Fees for students outside of EU; if 'Fee TBC' is checked this amount is an estimate for reporting</inlineHelpText>
        <label>Overseas Fee</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Programme_Group__c</fullName>
        <formula>TEXT( Programme_Version__r.Programme_Group__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Taken from Version level</inlineHelpText>
        <label>Programme Group</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme_Type__c</fullName>
        <description>DO NOT USE, to be deleted</description>
        <label>X Programme Type</label>
        <picklist>
            <picklistValues>
                <fullName>MSc Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Diploma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSc Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Course</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme Version</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Programme_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Versions, Versions, Specification, Versions - Pre Approved, Specification Edit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Programme Instances</relationshipLabel>
        <relationshipName>Programmes_Instances</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme_Module__c.object
<CustomObject><fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To find correct Module type first the few character of Module title then click magnifying glass for available options</inlineHelpText>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Assigned Programmes</relationshipLabel>
        <relationshipName>Programme_Modules</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Programme_Type__c</fullName>
        <formula>Programme__r.Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Taken from Programme level</inlineHelpText>
        <label>Programme Type</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme__c</fullName>
        <description>Via Master-Detail relationship, no reparenting allowed</description>
        <label>Programme</label>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Assigned Modules</relationshipLabel>
        <relationshipName>Programme_Modules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Many to many object, to allow one Module (instance) to be a member of multiple Programmes (instances)</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Programme Module</label><nameField>
        <displayFormat>PMI-{00000000}</displayFormat>
        <label>Programme Module</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Programme Modules</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Programme_Version__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Code__c</fullName>
        <inlineHelpText>Internal LSTM programme code</inlineHelpText>
        <label>Code</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Home_EU_Fee__c</fullName>
        <label>Home EU Fee</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Master_Link__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To allow two levels of versions - master or senior, and child versions. Will provide external systems with a persistent ID across all Programmes and Programme Versions of same group</description>
        <label>Master Link</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Record must be a master</errorMessage>
            <filterItems>
                <field>Programme_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Master Version</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Child Programme Versions</relationshipLabel>
        <relationshipName>Programme_Versions</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Mode__c</fullName>
        <label>Mode of Study</label>
        <picklist>
            <picklistValues>
                <fullName>FT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Overseas_Fee__c</fullName>
        <label>Overseas Fee</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Programme_Group__c</fullName>
        <label>Programme Group</label>
        <picklist>
            <picklistValues>
                <fullName>Clinical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Humanitarian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Laboratory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maternal &amp; Child Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning, Management &amp; Personal Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Health &amp; Humanitarian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sexual &amp; Reproductive Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel Health Courses</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Programme_Type__c</fullName>
        <label>Programme Type</label>
        <picklist>
            <picklistValues>
                <fullName>MSc Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Diploma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Masters Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG Cert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Course</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Date of first Intake</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Version_Suffix__c</fullName>
        <description>To differentiate between Programme Versions, added to Master name</description>
        <label>Version Suffix</label>
        <length>20</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme Version</label><nameField>
        <label>Programme Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programme Versions</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

classes/TestQuickCreateProgrammeCont.cls
/**
 * @author Mykola Senyk
 * @date 16/07/2014
 * @description Unit test for QuickCreateProgrammeCont class
 */
@isTest
private class TestQuickCreateProgrammeCont {
	
	static Programme__c findProgramme(Id progId) {
		return [
			SELECT Active__c, Capacity__c, End_Date__c, Home_EU_Fee__c, Instance_Suffix__c, Name, Overseas_Fee__c, Start_Date__c,
				Programme_Version__r.Name, Programme_Version__r.Programme_Group__c, Programme_Version__r.Programme_Type__c, Programme_Version__r.RecordType.DeveloperName, Programme_Version__r.Version_Suffix__c, 
				Programme_Version__r.Master_Link__r.Code__c, Programme_Version__r.Master_Link__r.Mode__c, Programme_Version__r.Master_Link__r.RecordType.DeveloperName
			FROM Programme__c
			WHERE Id = :progId
		];
	}
        
    static testMethod void testController() {
        QuickCreateProgrammeCont cont = new QuickCreateProgrammeCont();
        String testName = 'Test';
        Date startDate = Date.newInstance(2014, 6, 16);
        Date endDate = Date.newInstance(2014, 6, 27);
        String suffix = 'testSfx';
        Boolean isActive = true;
        String prType = ApplyServices.PT_SHORT_COURSE;
        String mode = ApplyServices.PV_MODE_FT;
        String code = 'TCD';
        
        // check full create cycle
        // mandatory fields
        cont.prog.Name = testName;
        cont.prog.Start_Date__c = startDate;
        cont.prog.End_Date__c = endDate;
        cont.prog.Instance_Suffix__c = suffix;
        cont.progVersion.Programme_Type__c = prType;
        // optional fields
        cont.prog.Active__c = isActive;
        cont.progVersion.Mode__c = mode;
        cont.progVersion.Code__c = code;
        PageReference pr = cont.create();
        System.assert(pr != null);
        System.assert(cont.programme.Id != null);
        System.assert(cont.module.Name.startsWith(testName));
        Programme__c p = findProgramme(cont.programme.Id);
        System.assert(p.Name.startsWith(testName));
        System.assertEquals(suffix, p.Instance_Suffix__c);
        System.assertEquals(startDate, p.Start_Date__c);
        System.assertEquals(endDate, p.End_Date__c);
        System.assertEquals(isActive, p.Active__c);
        System.assertEquals(prType, p.Programme_Version__r.Programme_Type__c);
        System.assertEquals(suffix, p.Programme_Version__r.Version_Suffix__c);        
        System.assertEquals(ApplyServices.RT_VERSION_PV_DEVNAME, p.Programme_Version__r.RecordType.DeveloperName);
        System.assertEquals(mode, p.Programme_Version__r.Master_Link__r.Mode__c);
        System.assertEquals(code, p.Programme_Version__r.Master_Link__r.Code__c);
        System.assertEquals(ApplyServices.RT_MASTER_PV_DEVNAME, p.Programme_Version__r.Master_Link__r.RecordType.DeveloperName);
        
        // check programme <-> module junction
        Programme_Module__c pm = [SELECT Module__c, Programme__c FROM Programme_Module__c WHERE Programme__c =: cont.programme.Id];
        System.assert(pm != null);
        
        // use Module Reference
        cont.progModule.Module__c = pm.Module__c;
        mode = ApplyServices.PV_MODE_FT;
        cont.progVersion.Mode__c = mode;
        pr = cont.create();
        System.assertEquals(pm.Module__c, cont.module.Id);
        p = findProgramme(cont.programme.Id);
        System.assertEquals(mode, p.Programme_Version__r.Master_Link__r.Mode__c);
    }
    
}