objects/Module_Role__c.object
<CustomObject><fields>
        <fullName>Module_Role__c</fullName>
        <description>Defines role for Module Spec, and against Module Instance for VLE integration</description>
        <label>Module Role</label>
        <picklist>
            <picklistValues>
                <fullName>Module Convenor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Module Moderator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Examiner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Teacher</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Join object between Staff (Contacts) and Modules (both Instances and Version objects). Will allow definition of staff role on a module and be used in VLE integration to define extent of staff enrolment.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Module Role</label><nameField>
        <displayFormat>MR-{00000000}</displayFormat>
        <label>Module Role Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Module Roles</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/VLE__c.object
<CustomObject><fields>
        <fullName>API_Host__c</fullName>
        <description>Domain name of API host</description>
        <label>API Host</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>App_ID__c</fullName>
        <description>App ID from desire2learn</description>
        <label>App ID</label>
        <length>22</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>App_Key__c</fullName>
        <description>App Key for desire2learn (secret)</description>
        <label>App Key</label>
        <length>22</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>User_ID__c</fullName>
        <description>User ID for API calls</description>
        <label>User ID</label>
        <length>22</length>
        <type>Text</type>
    </fields><fields>
        <fullName>User_Key__c</fullName>
        <description>Key for API user (secret)</description>
        <label>User Key</label>
        <length>22</length>
        <type>Text</type>
    </fields><customSettingsType>List</customSettingsType><description>Credentials for VLE external service</description><enableFeeds>false</enableFeeds><label>VLE parameters</label><visibility>Protected</visibility></CustomObject>

objects/VLE_Org_Wide_Units_And_Role_Assignments__c.object
<CustomObject><fields>
        <fullName>Available_for_Staff__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this Org Unit relates to STAFF Only. Either "Is Student" OR "Is Staff" should be selected</description>
        <inlineHelpText>Is this Org Unit relates to Staff Only. Either "Is Student" OR "Is Staff" should be selected</inlineHelpText>
        <label>Available for Staff</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Available_for_Student__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this Org Unit relates to Student Only.</description>
        <inlineHelpText>Is this Org Unit relates to Student Only.</inlineHelpText>
        <label>Available for Student</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Org_Unit_VLE_ID__c</fullName>
        <description>Organisation Wide Unit VLE ID</description>
        <inlineHelpText>Organisation Wide Unit VLE ID</inlineHelpText>
        <label>Org Unit VLE ID</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Staff_Role_VLE_ID__c</fullName>
        <label>Staff Role VLE ID</label>
        <length>10</length>
        <type>Text</type>
    </fields><customSettingsType>List</customSettingsType><enableFeeds>false</enableFeeds><label>VLE Org Wide Units And Role Assignments</label><visibility>Public</visibility></CustomObject>

objects/VLE_Program_Type_2_Role_VLE_ID_Mapping__c.object
<CustomObject><fields>
        <fullName>Programme_Type__c</fullName>
        <description>Programme Version's Programme Type, which defines what Role Student will be enrolled to VLE Courses</description>
        <inlineHelpText>Programme Version's Programme Type, which defines what Role Student will be enrolled to VLE Courses</inlineHelpText>
        <label>Programme Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields><fields>
        <fullName>Role_VLE_ID__c</fullName>
        <description>VLE ID of Role Student will be assigned to</description>
        <inlineHelpText>VLE ID of Role Student will be assigned to</inlineHelpText>
        <label>Role VLE ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields><customSettingsType>List</customSettingsType><enableFeeds>false</enableFeeds><label>VLE: Program Type to Role VLE ID Mapping</label><visibility>Protected</visibility></CustomObject>

objects/VLE_Staff_Module_Roles_And_Vle_Role_Ids__c.object
<CustomObject><fields>
        <fullName>Module_Role__c</fullName>
        <label>Module Role</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>Role_VLE_ID__c</fullName>
        <label>Role VLE ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields><customSettingsType>List</customSettingsType><enableFeeds>false</enableFeeds><label>VLE Staff Module Roles And Vle Role Ids</label><visibility>Public</visibility></CustomObject>

classes/VleServices.cls
/**
 * Service class for VLE integration
 */
public with sharing class VleServices {
    
    // Name of Custom Settings
    public static final String CS_NAME = 'main';
    
    // HTTP methods
    public static final String DELETE_METHOD =  'DELETE';
    public static final String GET_METHOD =     'GET';
    public static final String POST_METHOD =    'POST';
    public static final String PUT_METHOD =     'PUT';
    
    // Default callout timeout
    public static final Integer HTTP_TIMEOUT = 30000;
    
    // HTTP status codes
    public static final Integer OK_STATUS_CODE = 200;
    public static final Integer FORBIDDEN_STATUS_CODE = 403;
    public static final Integer NOT_FOUND_STATUS_CODE = 404;
    
    // API result constants
    public static final Integer RESULT_UNKNOWN = 0;
    public static final Integer RESULT_OKAY = 1;
    public static final Integer RESULT_INVALID_SIG = 2;
    public static final Integer RESULT_INVALID_TIMESTAMP = 3;
    public static final Integer RESULT_NO_PERMISSION = 4;

    // API auth interfaces
    public interface IAppContext {
        URL createWebUrlForAuthentication(URL resultUri);
        IUserContext createUserContext(String userId, String userKey);
        IUserContext createAnonymousUserContext();
    }
    
    public interface IUserContext {
        Long getServerSkewMillis();
        void setServerSkewMillis(Long millis);
        URL createAuthenticatedUri(String path, String httpMethod);
        Boolean calculateServerSkewFromResponse(String responseBody);
        Integer interpretResult(Integer resultCode, String responseBody);
    }
    
    /**
     * Custom Settings with VLE auth credentials
     */
    public static VLE__c credentials {
        get {
            if ( credentials == null ) {
                credentials = VLE__c.getInstance(CS_NAME);
            }
            return credentials; 
        }
        private set;
    }
    
    /**
     * Custom Settings with Student Role Assignments
     * Returns Programme Type 2 Role VLE ID
     */
    public static Map<String, Long> programType2StudentRoleVleId {
        get {
            if ( programType2StudentRoleVleId == null ){
                programType2StudentRoleVleId = new Map<String, Long>();
                
                for ( VLE_Program_Type_2_Role_VLE_ID_Mapping__c sett : VLE_Program_Type_2_Role_VLE_ID_Mapping__c.getall().values() ){
                    programType2StudentRoleVleId.put( sett.Programme_Type__c, Long.valueOf( sett.Role_VLE_ID__c ) );
                }  
            }
            return programType2StudentRoleVleId;
        }
        private set;
    }

    /**
     * Custom Settings with Staff Role Assignments
     * Returns Programme Type 2 Role VLE ID
     */
    public static Map<String, List<Long>> staffOrgUnitId2RoleVleId {
        get {
            if ( staffOrgUnitId2RoleVleId == null ){
                staffOrgUnitId2RoleVleId = new Map<String, List<Long>>();
                
                for ( VLE_Org_Wide_Units_And_Role_Assignments__c sett : VLE_Org_Wide_Units_And_Role_Assignments__c.getall().values() ){
                    if ( sett.Available_for_Staff__c && sett.Org_Unit_VLE_ID__c != null && sett.Staff_Role_VLE_ID__c != null ){
                        staffOrgUnitId2RoleVleId.put( sett.Org_Unit_VLE_ID__c, new List<Long> { Long.valueOf( sett.Staff_Role_VLE_ID__c ) } );
                    }
                }
            }
            return staffOrgUnitId2RoleVleId;
        }
        private set;
    }

    public static Set<Long> studentOrgUnitIds {
        get{
            if ( studentOrgUnitIds == null ){
                studentOrgUnitIds = new Set<Long>();
                
                for ( VLE_Org_Wide_Units_And_Role_Assignments__c sett : VLE_Org_Wide_Units_And_Role_Assignments__c.getall().values() ){
                    if ( sett.Available_for_Student__c && sett.Org_Unit_VLE_ID__c != null ) {
                        studentOrgUnitIds.add( Long.valueOf( sett.Org_Unit_VLE_ID__c ) );
                    }
                }               
            }
            return studentOrgUnitIds;
        }   
        private set;
    }

    //saff module role 2 list VLE role Ids
    public static Map<String, List<Long>> staffRoles {
        get {
            if ( staffRoles == null ) {
                staffRoles = new Map<String, List<Long>>();
                
                for ( VLE_Staff_Module_Roles_And_Vle_Role_Ids__c sett : VLE_Staff_Module_Roles_And_Vle_Role_Ids__c.getall().values() ) {
                    staffRoles.put( sett.Module_Role__c, new List<Long> { Long.valueOf( sett.Role_VLE_ID__c ) } );
                }
            }
            return staffRoles;
        }
        private set;
    }


    /**
     * Return AppContext instance
     */
    public static IAppContext appContextInstance() {
        return new VleAppContext(credentials.App_ID__c, credentials.App_Key__c, 'https://' + credentials.API_Host__c);
    }
    
    /**
     * Return UserContext instance
     */
    public static IUserContext userContextInstance() {
        return appContextInstance().createUserContext(credentials.User_Id__c, credentials.User_Key__c);
    }
    
    /**
     * Build encrypted digest of value with private key
     * @param secretKey Private key
     * @param saltValue Value for encryption
     * @return Encrypted digest
     */
    public static String buildBase64HashString(String secretKey, String saltValue) {
        String algorithmName = 'HmacSHA256';
        Blob hmacData = Crypto.generateMac(algorithmName, Blob.valueOf(saltValue), Blob.valueOf(secretKey));
        String base64Str = EncodingUtil.base64Encode(hmacData);
        // make hash to be URL safe
        String urlSafe = base64Str.replace('+', '-').replace('/', '_').replace('=', '');
        return urlSafe;
    }
    
    /**
     * Make HTTP(s) callout with User Context to VLE API
     * @param path Relative path for API
     * @param httpMethod Method of request e.g. GET or POST
     * @param userContext Instance of User Context
     * @param body String body of request
     * @return HttpResponse or exception (as a rule callout)
     */
    public static HttpResponse performHttpCall(String path, String httpMethod, IUserContext userContext, String body) {
        Http h = new Http();
        
        System.debug(LoggingLevel.ERROR, '@@@ HTTP(' + httpMethod + '), path=' + path);
        HttpRequest req = new HttpRequest();
        req.setTimeout(HTTP_TIMEOUT);
        req.setMethod(httpMethod);
        URL endpoint = userContext.createAuthenticatedUri(path, httpMethod);
        req.setEndpoint(endpoint.toExternalForm());
        System.debug(LoggingLevel.ERROR, '@@@ endpoint=' + endpoint.toExternalForm());
        if ( !String.isBlank(body) ) {
            System.debug(LoggingLevel.ERROR, '@@@ request body: ' + body);
            req.setBody(body);
        }
        
        HttpResponse res = h.send(req);
        System.debug(LoggingLevel.ERROR, '@@@ response body: ' + res.getBody());
        return res;
    }
    
    /**
     * Make HTTP callout without body.
     * See @method performHttpCall()
     */
    public static HttpResponse performHttpCall(String path, String httpMethod, IUserContext userContext) {
        return performHttpCall(path, httpMethod, userContext, null);
    }

    /**
     * Converts Date to String format UTC
     * @param instance of Date
     * @return String in UTC format.
     */
    public static String dateToUTCFormatString(Date d){
        String gmtFormatStr = 'yyyy-MM-dd\'T\'hh:mm:ss.000\'Z\'';
        DateTime dt = DateTime.newInstance(d.year(), d.month(), d.day());
        return dt.formatGmt(gmtFormatStr);
    }   
    
    /**
     * Converts module name to unique code
     * @param String name of Module
     * @return String unique code 
     */ 
    public static String moduleNameToCode (String name){
        return name.left(5) + System.now().format('dd-MM-yy_hh-mm-ss');
    }   

}