objects/Module__c.object
<CustomObject><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Instances of Modules</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module</label><nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Modules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme__c.object
<CustomObject><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme_Module__c.object
<CustomObject><fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To find correct Module type first the few character of Module title then click magnifying glass for available options</inlineHelpText>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Assigned Programmes</relationshipLabel>
        <relationshipName>Programme_Modules</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Programme__c</fullName>
        <description>Via Master-Detail relationship, no reparenting allowed</description>
        <label>Programme</label>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Assigned Modules</relationshipLabel>
        <relationshipName>Programme_Modules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Many to many object, to allow one Module (instance) to be a member of multiple Programmes (instances)</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Programme Module</label><nameField>
        <displayFormat>PMI-{00000000}</displayFormat>
        <label>Programme Module</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Programme Modules</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/TestCloneProgrammeController.cls
/**
 * 2014-05-22 : Test class for CloneProgrammeController
 */
@isTest
private class TestCloneProgrammeController {

    static testMethod void testController() {
        //Set up test data
        Programme__c newProg = new Programme__c();
        newProg.Name = 'Test Programme';
        newProg.Test_Class_Record__c = true;
        insert newProg;
        
        Map<String, Module__c> modMap = new Map<String, Module__c>();
        for (integer i = 0 ; i < 4 ; i++){
            Module__c m = new Module__c();
            m.Name = 'Test Module ' + i; 
            m.Test_Class_Record__c = true;         
            modMap.put(m.Name, m);
        }
        
        insert modMap.values();
        
        List<Programme_Module__c> newModList = new List<Programme_Module__c>();
        for (integer i = 0 ; i < 4 ; i++){
            Programme_Module__c pm = new Programme_Module__c();
            pm.Test_Class_Record__c = true;
            pm.Programme__c = newProg.Id;
            pm.Module__c = modMap.get('Test Module ' + i).Id;
            newModList.add(pm);
        }
        
        insert newModList;
        
        PageReference pageRef = Page.CloneProgramme;
        pageRef.getParameters().put('progId',newProg.Id);
        test.setCurrentPage(pageRef);
        
        ApexPages.StandardController std = new ApexPages.StandardController(newProg);
        
        test.startTest();
        
        CloneProgrammeController cpc = new CloneProgrammeController(std);
        cpc.moduleWrapperList[0].isSelected = true;
        
        PageReference returnRef = cpc.cloneProgramme();
               
        test.stopTest();
    }
    
    static testMethod void testControllerWithFilter() {
        //Set up test data
        Programme__c newProg = new Programme__c();
        newProg.Name = 'Test Programme';
        newProg.Test_Class_Record__c = true;
        
        insert newProg;
        
        Map<String, Module__c> modMap = new Map<String, Module__c>();
        for (integer i = 0 ; i < 4 ; i++){
            Module__c m = new Module__c();
            m.Name = 'Test Module ' + i; 
            m.Test_Class_Record__c = true;         
            modMap.put(m.Name, m);
        }
        
        insert modMap.values();
        
        List<Programme_Module__c> newModList = new List<Programme_Module__c>();
        for (integer i = 0 ; i < 4 ; i++){
            Programme_Module__c pm = new Programme_Module__c();
            pm.Programme__c = newProg.Id;
            pm.Test_Class_Record__c = true;
            pm.Module__c = modMap.get('Test Module ' + i).Id;
            newModList.add(pm);
        }
        
        insert newModList;
        
        PageReference pageRef = Page.CloneProgramme;
        pageRef.getParameters().put('progId',newProg.Id);
        test.setCurrentPage(pageRef);
        
        ApexPages.StandardController std = new ApexPages.StandardController(newProg);
        
        test.startTest();
        
        CloneProgrammeController cpc = new CloneProgrammeController(std);
        
        cpc.filterName = 'Test';
        
        PageReference returnRef = cpc.filterModules();
               
        test.stopTest();
    }
}