objects/Module__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Instances of Modules</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Module</label><nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Modules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used for lookup from Student processes</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme Version</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Programme_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Versions, Versions, Specification, Versions - Pre Approved, Specification Edit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Programme Instances</relationshipLabel>
        <relationshipName>Programmes_Instances</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme_Aim__c.object
<CustomObject><fields>
        <fullName>Programme_Version__c</fullName>
        <label>Programme Version</label>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Aims</relationshipLabel>
        <relationshipName>Programme_Aims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Programme Aim</label><nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Aim Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Programme Aims</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Programme_Module__c.object
<CustomObject><fields>
        <fullName>Member_Type__c</fullName>
        <inlineHelpText>Whether Module is Required, Optional or Alternative; Solus is used to denote where a Programme only had a single Module.</inlineHelpText>
        <label>Member Type</label>
        <picklist>
            <picklistValues>
                <fullName>Required</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Optional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specials</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To find correct Module type first the few character of Module title then click magnifying glass for available options</inlineHelpText>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Assigned Programmes</relationshipLabel>
        <relationshipName>Programme_Modules</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Programme__c</fullName>
        <description>Via Master-Detail relationship, no reparenting allowed</description>
        <label>Programme</label>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Assigned Modules</relationshipLabel>
        <relationshipName>Programme_Modules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Many to many object, to allow one Module (instance) to be a member of multiple Programmes (instances)</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Programme Module</label><nameField>
        <displayFormat>PMI-{00000000}</displayFormat>
        <label>Programme Module</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Programme Modules</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Programme_Version__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme Version</label><nameField>
        <label>Programme Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programme Versions</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

classes/ProgrammeVersionServices.cls
public with sharing class ProgrammeVersionServices {

    public static final String PT_MSC_PROGRAMME =           'MSc Programme';
    public static final String PT_PROFESSIONAL_DIPLOMA =    'Professional Diploma';
    public static final String PT_MASTERS_MODULE =          'Masters Module';
    public static final String PT_SHORT_COURSE =            'Short Course';
    public static final String PT_PGT =                     'PGT';
    public static final String PT_PGR =                     'PGR';

	public static final String PROGRAMME_AIMS_RLP_NAME = 'Programme_Aims';

	public static void createProgrameVersionContentAsXmlAttachment ( Set<Id> progVersionIds){

		Map<Id, SObjectXMLBuilder.SObjectXMLContext> progVersionId2Context = new Map<Id, SObjectXMLBuilder.SObjectXMLContext>();
		List<Attachment> attachsToCreate = new List<Attachment>();
		SObjectXMLBuilder xmlBuilder = new SObjectXMLBuilder(true);

		List<Programme_Version__c> programVersioms = findProgrammeVersionsWithLatestXmlContextAttachment( progVersionIds );
		
		//form SObjectXMLContext objects
		for (Programme_Version__c pv : programVersioms){
			SObjectXMLBuilder.SObjectXMLContext pvContext = 
				new SObjectXMLBuilder.SObjectXMLContext( Programme_Version__c.getSObjectType(), CommonUtils.deserializeUntyped(pv, getProgrammeVersionFieldNames()) );

			List<SObjectXMLBuilder.SObjectXMLContext> aimContexts = new List<SObjectXMLBuilder.SObjectXMLContext>();
			if (! pv.Programme_Aims__r.isEmpty() ){
				for (Programme_Aim__c aim : pv.Programme_Aims__r){
					aimContexts.add( new SObjectXMLBuilder.SObjectXMLContext( Programme_Aim__c.getSObjectType(), CommonUtils.deserializeUntyped(aim, getProgrammeAimFieldNames()) ) );
				}
				pvContext.addChildRelation(PROGRAMME_AIMS_RLP_NAME, aimContexts);
			}
			progVersionId2Context.put(pv.Id, pvContext);
		}

		//compare/generate attachments
		Map<Id, Blob> pvId2AttachBody = getPvId2AttachmentBody( programVersioms );

		for (Programme_Version__c pv : programVersioms){
			String newlyGeneratedXmlStr = xmlBuilder.getFullXml( progVersionId2Context.get(pv.Id) ).getXmlString();

			//if pv has no attachment (e.g. new record) or there were changes to pv agains data in attachment
			if ((pvId2AttachBody.containsKey(pv.Id) && pvId2AttachBody.get(pv.Id).toString() != newlyGeneratedXmlStr)
			|| ! pvId2AttachBody.containsKey(pv.Id)){				

				Attachment att = new Attachment(
					Name = AttachmentServices.XML_CONTEXT_ATTACHMENT_PREFIX + Programme_Version__c.getSObjectType() + '_' + System.now(),
					ParentId = pv.Id,
					Body = Blob.valueOf(newlyGeneratedXmlStr)
				);
				attachsToCreate.add(att);		
			}
		}

		if (! attachsToCreate.isEmpty() ){
			insert attachsToCreate;
		}
	}


    public static List<String> getProgrammeVersionFieldNames() {
     	return CommonUtils.getFieldNames( SObjectType.Programme_Version__c.FieldSets.Xml.getFields() );
    }

    //Specific Aims
    public static List<String> getProgrammeAimFieldNames() {
     	return CommonUtils.getFieldNames( SObjectType.Programme_Aim__c.FieldSets.Aims.getFields() );
    }  

/*
    public static void processDefaultModulesCreationForActivePv(List<Programme_Version__c> newList, Map<Id,Programme_Version__c> oldMap){
    	List<Programme_Version__c> pvListFiltered = findActiveProgrammeVersions(newList, oldMap);

    	if (pvListFiltered.isEmpty()){
    		return;
    	}

    	Map<Id, Set<Id>> programmeId2ModuleIds = new Map<Id, Set<Id>>();

    	for (Programme__c programme : findProgrammesWithModulesByProgVersionIdsAndModuleIds(pvListFiltered, VleSyncServices.defaultModulesIds) ){
    		programmeId2ModuleIds.put(programme.Id, new Set<Id>());
    		if (! programme.Programme_Modules__r.isEmpty()){
    			for (Programme_Module__c progModule : programme.Programme_Modules__r){
    				programmeId2ModuleIds.get(programme.Id).add(progModule.Module__c);
    			}
    		}
    	}

    	List<Programme_Module__c> progModulesToCreate = new List<Programme_Module__c>();

    	for (Id programId : programmeId2ModuleIds.keySet()){
    		Set<Id> moduleIdsToCreate = new Set<Id>(VleSyncServices.defaultModulesIds);
    		moduleIdsToCreate.removeAll( programmeId2ModuleIds.get(programId) );

    		for (Id moduleId : moduleIdsToCreate){
    			Programme_Module__c pm = new Programme_Module__c(
    				Member_Type__c = 'Required',
    				Programme__c = programId,
    				Module__c = moduleId
    			);
    			progModulesToCreate.add(pm);
    		}
    	}

    	if (! progModulesToCreate.isEmpty()){
    		insert progModulesToCreate;
    	}
    }
*/

    public static List<Programme_Version__c> findActiveProgrammeVersions(List<Programme_Version__c> newList, Map<Id,Programme_Version__c> oldMap){
    	List<Programme_Version__c> pvList = new List<Programme_Version__c>();
    	for (Programme_Version__c progVersion : newList){
    		if (progVersion.Active__c && ! oldMap.get(progVersion.Id).Active__c) {
    			pvList.add(progVersion);
    		}
    	}
    	return pvList;
    }


    private static List<Programme__c> findProgrammesWithModulesByProgVersionIdsAndModuleIds(List<Programme_Version__c> progVersions, Set<Id> moduleIds){
    	return  [SELECT Id, Programme_Version__c,
    				(SELECT Module__c
    			 	FROM Programme_Modules__r
    			 	WHERE Module__c IN : moduleIds)
    		 	FROM Programme__c
    		 	WHERE Programme_Version__c IN : progVersions];
    }


    @TestVisible
	private static List<Programme_Version__c> findProgrammeVersionsWithLatestXmlContextAttachment(Set<Id> progVersionIds){
		String queryStr = ''
			+ ' SELECT ' + String.join(getProgrammeVersionFieldNames(), ',')
			+ 		', (SELECT ' + String.join(getProgrammeAimFieldNames(), ',')
			+ 		'  FROM Programme_Aims__r)'
			+ 		', (SELECT Id, ParentId' 
			+ 		'  FROM Attachments'
			+ 		'  WHERE Name LIKE \'' + AttachmentServices.XML_CONTEXT_ATTACHMENT_PREFIX + '%\''			
			+ 		'  ORDER BY CreatedDate DESC'
			+ 		'  LIMIT 1)'			
			+ ' FROM Programme_Version__c'
			+ ' WHERE Id IN : progVersionIds';
		
		return Database.query( queryStr );
	}

	@TestVisible
	private static Map<Id, Blob> getPvId2AttachmentBody( List<Programme_Version__c> programmeVersions ){
		Set<Id> attIds = new Set<Id>();
		Map<Id, Blob> progId2AttachBody = new Map<Id, Blob>();

		for (Programme_Version__c pv : programmeVersions){
			if (! pv.Attachments.isEmpty() ){
				attIds.add( pv.Attachments.get(0).Id );
			}
		}

		if (! attIds.isEmpty()) {
			for (Attachment att : AttachmentServices.getAttachmentsWithBodyByIds(attIds)){
				progId2AttachBody.put(att.parentId, att.Body);
			}
		}
		return 	progId2AttachBody;
	} 



}