objects/Module_Role__c.object
<CustomObject><fields>
        <fullName>Module_Role__c</fullName>
        <description>Defines role for Module Spec, and against Module Instance for VLE integration</description>
        <label>Module Role</label>
        <picklist>
            <picklistValues>
                <fullName>Module Convenor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Module Moderator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Examiner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Teacher</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Join object between Staff (Contacts) and Modules (both Instances and Version objects). Will allow definition of staff role on a module and be used in VLE integration to define extent of staff enrolment.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Module Role</label><nameField>
        <displayFormat>MR-{00000000}</displayFormat>
        <label>Module Role Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Module Roles</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/VLE_Program_Type_2_Role_VLE_ID_Mapping__c.object
<CustomObject><fields>
        <fullName>Programme_Type__c</fullName>
        <description>Programme Version's Programme Type, which defines what Role Student will be enrolled to VLE Courses</description>
        <inlineHelpText>Programme Version's Programme Type, which defines what Role Student will be enrolled to VLE Courses</inlineHelpText>
        <label>Programme Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields><fields>
        <fullName>Role_VLE_ID__c</fullName>
        <description>VLE ID of Role Student will be assigned to</description>
        <inlineHelpText>VLE ID of Role Student will be assigned to</inlineHelpText>
        <label>Role VLE ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields><customSettingsType>List</customSettingsType><enableFeeds>false</enableFeeds><label>VLE: Program Type to Role VLE ID Mapping</label><visibility>Protected</visibility></CustomObject>

objects/VLE_Staff_Module_Roles_And_Vle_Role_Ids__c.object
<CustomObject><fields>
        <fullName>Module_Role__c</fullName>
        <label>Module Role</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>Role_VLE_ID__c</fullName>
        <label>Role VLE ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields><customSettingsType>List</customSettingsType><enableFeeds>false</enableFeeds><label>VLE Staff Module Roles And Vle Role Ids</label><visibility>Public</visibility></CustomObject>

classes/TestManageVleOrgWideUnitRolesController.cls
@IsTest
public class TestManageVleOrgWideUnitRolesController {
    
    static testMethod void studentRoleAssignment(){

        VLE_Program_Type_2_Role_VLE_ID_Mapping__c vlePT2Role = new VLE_Program_Type_2_Role_VLE_ID_Mapping__c();
        vlePT2Role.Name = 'testvlePT2';
        vlePT2Role.Programme_Type__c ='testProgrammeType';
        vlePT2Role.Role_VLE_ID__c = '100';
        INSERT vlePT2Role;
        ManageVleOrgWideUnitRolesController mVController = new ManageVleOrgWideUnitRolesController();
        mVController.objName = 'VLE_Program_Type_2_Role_VLE_ID_Mapping__c';
        mVController.addRecord();
        mVController.indexToDelete = 0;
        mVController.deleteRowStudent();
        //PageReference pRef = new PageReference();
        PageReference  pRef = mVController.saveMappings();
    }

    /*static testMethod void staffRoleAssignment(){
        VLE_Staff_Module_Roles_And_Vle_Role_Ids__c vleStaff = new VLE_Staff_Module_Roles_And_Vle_Role_Ids__c();
        vleStaff.Name = 'testvleStaff';
        vleStaff.Module_Role__c = 'mRole';
        vleStaff.Role_VLE_ID__c = '121';
        INSERT vleStaff;

        ManageVleOrgWideUnitRolesController mVController = new ManageVleOrgWideUnitRolesController();
        mVController.objName = 'VLE_Staff_Module_Roles_And_Vle_Role_Ids__c';
        mVController.addRecord();
        mVController.indexToDelete = 0;
        mVController.deleteRowStaff();
        //PageReference pRef = new PageReference();
        PageReference  pRef = mVController.saveMappings();   
    }*/

    
}