objects/Page_Copy__c.object
<CustomObject><fields>
        <fullName>Body_Copy__c</fullName>
        <inlineHelpText>This is the main page content to be displayed on the community page</inlineHelpText>
        <label>Body Copy</label>
        <length>32768</length>
        <type>Html</type>
    </fields><fields>
        <fullName>Copy_Location__c</fullName>
        <inlineHelpText>Defines where the copy will be used</inlineHelpText>
        <label>Copy Location</label>
        <picklist>
            <picklistValues>
                <fullName>Applicant Homepage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Offer page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmation of Place page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Homepage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Welcome</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submission Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Registration Terms Conditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Registration Data Protection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New User Information</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Page_Status__c</fullName>
        <label>Page Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For Sys Admin defined content, to be used in specific Visualforce pages, such as home pages in Community portals.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Read</externalSharingModel><label>Page Copy</label><nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Page Copy Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Page Copy</pluralLabel><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>Stage__c</fullName>
        <description>NOTE : This field drives the Student Programme flow - DO NOT change pick list values without discussion with the I.T / Dev Team</description>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Checked</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional</fullName>
                <color>#339999</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unconditional</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
                <color>#FF99FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Expected</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Registered</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
                <color>#419249</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#666666</color>
            </picklistValues>
            <picklistValues>
                <fullName>Offered</fullName>
                <color>#DDDDDD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/VLE__c.object
<CustomObject><fields>
        <fullName>API_Host__c</fullName>
        <description>Domain name of API host</description>
        <label>API Host</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>App_ID__c</fullName>
        <description>App ID from desire2learn</description>
        <label>App ID</label>
        <length>22</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>App_Key__c</fullName>
        <description>App Key for desire2learn (secret)</description>
        <label>App Key</label>
        <length>22</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>Default_Staff_Role_VLE_ID__c</fullName>
        <description>If Module Role has no matches for VLE Role Id - this value is used as default for Staff</description>
        <inlineHelpText>If Module Role has no matches for VLE Role Id - this value is used as default for Staff</inlineHelpText>
        <label>Default Staff Role VLE ID</label>
        <length>10</length>
        <type>Text</type>
    </fields><customSettingsType>List</customSettingsType><description>Credentials for VLE external service</description><enableFeeds>false</enableFeeds><label>VLE parameters</label><visibility>Protected</visibility></CustomObject>

classes/TestNewUserPageContExt.cls
/**
 * 2014-05-22 : Test class for NewUserPageContExt
 */
 @IsTest
public class TestNewUserPageContExt {
    
    @testSetup
    public static void setup() {
        VLE__c vle = new VLE__c();
        vle.Name = 'main';
        vle.Default_Staff_Role_VLE_ID__c = '102';
        vle.API_Host__c = '2lstmedtest.desire2learn.com';
        vle.App_ID__c = '2BqFg3qrSd26I';
        vle.App_Key__c = '2MWXZLyA2xo4I';
        insert vle;
    }
        
    static testMethod void testController() {
        ApplyTestingUtils.setupTestData();
        Student_Programme__c sp = ApplyTestingUtils.sp;
        Page_Copy__c pc = new Page_Copy__c();
        pc.Copy_Location__c = 'New User Information';
        pc.Page_Status__c = 'Active';
        pc.Body_Copy__c = 'Test Copy';
        insert pc;

        sp.Stage__c = ApplyServices.COURSE_SUBMITTED_STAGE_NAME;
        sp.Test_Class_Record__c = true;
        update sp;

        PageReference testPage = Page.LSTMUserPage;
        
         Test.setCurrentPageReference(new PageReference('Page.LSTMUserPage'));
        System.currentPageReference().getParameters().put('id', sp.Id);  
        //ApexPages.StandardController std = new ApexPages.StandardController(sp);

        test.startTest();
            NewUserPageContExt ctrl = new NewUserPageContExt();

            PageReference homePage = ctrl.gotoHomePage();
            PageReference checkHomePage = Page.StudentLandingPage;


            system.assertEquals(checkHomePage.getUrl(), homePage.getUrl());

            ctrl.confirmDetails();
            
        test.stopTest();




    }
}