objects/Page_Copy__c.object
<CustomObject><fields>
        <fullName>Body_Copy__c</fullName>
        <inlineHelpText>This is the main page content to be displayed on the community page</inlineHelpText>
        <label>Body Copy</label>
        <length>32768</length>
        <type>Html</type>
    </fields><fields>
        <fullName>Copy_Location__c</fullName>
        <inlineHelpText>Defines where the copy will be used</inlineHelpText>
        <label>Copy Location</label>
        <picklist>
            <picklistValues>
                <fullName>Applicant Homepage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Offer page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmation of Place page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Homepage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Welcome</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submission Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Registration Terms Conditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Registration Data Protection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New User Information</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Page_Status__c</fullName>
        <label>Page Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For Sys Admin defined content, to be used in specific Visualforce pages, such as home pages in Community portals.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Read</externalSharingModel><label>Page Copy</label><nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Page Copy Ref</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Page Copy</pluralLabel><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/CommunitiesSelfRegController.cls
/**
 * An apex page controller that supports self registration of users in communities that allow self registration
 */
/***** Modifications 
///done for  on A6 Persistent Application Links ,Display the data base on parameter received on applyWizard Page o=in student community on 14-06-2015 *****/
///Author MKM
/// <summary> Edited Returning Url by adding new Url parametr for passing programme id </summary>
/// <param name="pgmId">Used store selected programme id and send via Url</param>
public with sharing class CommunitiesSelfRegController {

    public String firstName {get; set;}
    public String lastName {get; set;}
    public String email {get; set;}
    public String pgmId {get;set;}
    public String url{get;set;}
    public String password {get; set {password = value == null ? value : value.trim(); } }
    public String confirmPassword {get; set { confirmPassword = value == null ? value : value.trim(); } }
    public String communityNickname {get; set { communityNickname = value == null ? value : value.trim(); } }
    //2014-08-13 : CSL : New code to retrieve Page Copy text, for the header text on the Self Registration page
    public Page_Copy__c selfRegPageCopy {get; set;}
    
    public CommunitiesSelfRegController() {
        pgmId = ApexPages.currentPage().getParameters().get('programmeid');   
        selfRegPageCopy = [select p.Body_Copy__c from Page_Copy__c p where p.Copy_Location__c = 'Self Registration' and Page_Status__c = 'Active' LIMIT 1];
    }
    
    private boolean isValidPassword() {
        return password == confirmPassword;
    }
    
    public PageReference cancel(){
        return new PageReference('/LSTMLogin?programmeid='+pgmId);
    }

    public PageReference registerUser() {    
           // it's okay if password is null - we'll send the user a random password in that case
        if (!isValidPassword()) {
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, Label.site.passwords_dont_match);
            ApexPages.addMessage(msg);
            return null;
        } 
       

        String profileId = '00e20000001V3BS'; // To be filled in by customer.
        String roleEnum = null; // To be filled in by customer.        
        String accountId = '00120000017HW56'; // To be filled in by customer.
                                     
        String userName = email;
        User u = new User();
        u.Username = userName;
        u.Email = email;
        u.FirstName = firstName;
        u.LastName = lastName;
        //2014-08-07 : CSL : New code to create CommunityNickname automatically
        //2014-12-16 : CSL : We are now setting the CommunityNickName to the Email address
        //communityNickname = lastName.substring(0,4) + (firstName == null ? '' : firstName.substring(0,1));
        //u.CommunityNickname = communityNickname;
        u.CommunityNickname = email;
        u.ProfileId = profileId;
        System.Debug('accountId'+ accountId);
         System.Debug('u'+ u);

        String userId = Site.createPortalUser(u, accountId, password);
        System.Debug('userId: '+userId);
      
        if (userId != null) { 
            if (password != null && password.length() > 1) {
               url = '/'+'ChooseProgramme?programmeid=' + pgmId ;
               return Site.login(userName, password, url);               
            }
            else {
                PageReference page = System.Page.CommunitiesSelfRegConfirm;
                page.getParameters().put('programmeid', pgmId);               
                page.setRedirect(true);
                return page;                
            }
        }
        return null;
    }
}