objects/Programme__c.object
<CustomObject><fields>
        <fullName>Code__c</fullName>
        <formula>Programme_Version__r.Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Taken from Version level</inlineHelpText>
        <label>Code</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme Version</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Programme_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Versions, Versions, Specification, Versions - Pre Approved, Specification Edit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Programme Instances</relationshipLabel>
        <relationshipName>Programmes_Instances</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme_Version__c.object
<CustomObject><fields>
        <fullName>Code__c</fullName>
        <inlineHelpText>Internal LSTM programme code</inlineHelpText>
        <label>Code</label>
        <length>10</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme Version</label><nameField>
        <label>Programme Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programme Versions</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Provision__c.object
<CustomObject><fields>
        <fullName>AD_Account_Created_Updated__c</fullName>
        <label>AD Account Created/Updated</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Expiry_Date__c</fullName>
        <inlineHelpText>Set by Workflow on creation. Can be manually amended.</inlineHelpText>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>8</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Student_Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Programme</label>
        <referenceTo>Student_Programme__c</referenceTo>
        <relationshipLabel>Provisions</relationshipLabel>
        <relationshipName>Student_Programme</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Student_Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student/Staff</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Provisions</relationshipLabel>
        <relationshipName>Provisions</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Provision</label><nameField>
        <label>Provision Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Provisions</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Programme must be active (i.e. most recent)</errorMessage>
            <filterItems>
                <field>Programme__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Student Programmes</relationshipLabel>
        <relationshipName>Students_on_Programme1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>password__c</fullName>
        <formula>Registration_Password__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>password</label>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/ProvisionTriggerMethodsTest.cls
@isTest(seeAlldata=true)
public class ProvisionTriggerMethodsTest{
        
    static final String PROGRAMME_NAME = 'Diploma in Tropical Nursing';  
    static final String PROGRAMME_VERSION = 'Programme_Version__c';
    static final String PROGRAMME_TYPE = ApplyServices.PT_PROFESSIONAL_DIPLOMA;    
  
    public static testMethod void insertProvision(){
        
        Id mvrtId = CommonUtils.findRecordTypeIdByDev(PROGRAMME_VERSION, ApplyServices.RT_MASTER_PV_DEVNAME);
        Programme_Version__c mv = VleTestingUtils.createMasterProgrammeVersion(PROGRAMME_NAME, mvrtId, PROGRAMME_TYPE, false);
        mv.Code__c = StudentProgrammeTriggerMethods.CODE_DTN;
        insert mv;

        Id rtId = CommonUtils.findRecordTypeIdByDev(PROGRAMME_VERSION, ApplyServices.RT_VERSION_PV_DEVNAME);
        Programme_Version__c pv = VleTestingUtils.createProgrammeVersion(PROGRAMME_NAME, rtId, PROGRAMME_TYPE, mv.Id, false);
        pv.Code__c = StudentProgrammeTriggerMethods.CODE_DTN;
        insert pv;
        
        Programme__c prog = VleTestingUtils.createProgramme(PROGRAMME_NAME, pv.Id, false);
        insert prog;
        Contact student = VleTestingUtils.CreateStudent(true);
        Student_Programme__c sp = VleTestingUtils.CreateStudentProgramme(prog.Id, student.Id, true);        
        
        Test.startTest();
        List<Provision__c> provisionList = new List<Provision__c>();
        for(integer i=0;i<10;i++)
        {
            Provision__c provision = new Provision__c();
            provision.Name = 'Test Provision' + string.ValueOf(i);
            provision.Student_Staff__c = student.Id;
            provision.Student_Programme__c = sp.Id;
            provision.AD_Account_Created_Updated__c='Yes';
            provision.Expiry_date__c=system.today()+1;
            provisionList.add(provision);
        }
        Provision__c Provision1 = new Provision__c();
        provision1.Name = 'Test Provision';
        provision1.Student_Staff__c = student.Id;
        provision1.Student_Programme__c = sp.Id;
        provision1.AD_Account_Created_Updated__c='No';
        provision1.Expiry_date__c=system.today()-1;
        provisionList.add(provision1);
        
            
        insert provisionList;
        Provision__c insertedProvision = [SELECT Password__c FROM Provision__c WHERE Id IN: provisionList LIMIT 1];
        system.debug('insertedProvision '+insertedProvision.Password__c );
        system.AssertEquals(insertedProvision.Password__c.length(),8);
        delete provisionList;
        undelete provisionList;
        Test.stopTest();
    }
}