objects/Programme__c.object
<CustomObject><fields>
        <fullName>Code__c</fullName>
        <formula>Programme_Version__r.Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Taken from Version level</inlineHelpText>
        <label>Code</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Programme_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme Version</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Programme_Version__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Versions, Versions, Specification, Versions - Pre Approved, Specification Edit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme_Version__c</referenceTo>
        <relationshipLabel>Programme Instances</relationshipLabel>
        <relationshipName>Programmes_Instances</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Programme_Version__c.object
<CustomObject><fields>
        <fullName>Code__c</fullName>
        <inlineHelpText>Internal LSTM programme code</inlineHelpText>
        <label>Code</label>
        <length>10</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme Version</label><nameField>
        <label>Programme Version Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programme Versions</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Programme must be active (i.e. most recent)</errorMessage>
            <filterItems>
                <field>Programme__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Student Programmes</relationshipLabel>
        <relationshipName>Students_on_Programme1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Stage__c</fullName>
        <description>NOTE : This field drives the Student Programme flow - DO NOT change pick list values without discussion with the I.T / Dev Team</description>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Checked</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional</fullName>
                <color>#339999</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unconditional</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
                <color>#FF99FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Expected</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Registered</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
                <color>#419249</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#666666</color>
            </picklistValues>
            <picklistValues>
                <fullName>Offered</fullName>
                <color>#DDDDDD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/PicklistBannerSPControllerTest.cls
@isTest
private class PicklistBannerSPControllerTest
{
    static Programme_Version__c pv{ get; set;}
    static Programme_Version__c mv { get; set; }
    
    static testMethod void PCtest() 
    {
        setupTestData();
        Programme__c prog = VleTestingUtils.createProgramme('Test Programme', pv.Id, false);
        insert prog;
        Contact student = VleTestingUtils.CreateStudent(true);
        Student_Programme__c sp = VleTestingUtils.CreateStudentProgramme(prog.Id, student.Id, true);
        sp.Stage__c = 'Stage2';
        update sp;
        
        PicklistBannerSPController.getCompletedStages(sp.Id);
        PicklistBannerSPController.getCurrentStage(sp.Id);
        PicklistBannerSPController.getFutureStages(sp.Id);
        PicklistBannerSPController.updateStage(sp.Id,'Stage4');
    }
    
    static void setupTestData() 
    {
        Id mvrtId = CommonUtils.findRecordTypeIdByDev('Programme_Version__c', ApplyServices.RT_MASTER_PV_DEVNAME);
        mv = VleTestingUtils.createMasterProgrammeVersion('Test Programme', mvrtId, ApplyServices.PT_PROFESSIONAL_DIPLOMA, false);
        mv.Code__c = StudentProgrammeTriggerMethods.CODE_DTN;
        insert mv;
    
        Id rtId = CommonUtils.findRecordTypeIdByDev('Programme_Version__c', ApplyServices.RT_VERSION_PV_DEVNAME);
        pv = VleTestingUtils.createProgrammeVersion('Test Programme', rtId, ApplyServices.PT_PROFESSIONAL_DIPLOMA, mv.Id, false);
        pv.Code__c = StudentProgrammeTriggerMethods.CODE_DTN;
        insert pv;        
    }            
}