objects/Programme__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Qualifications_Experience__c.object
<CustomObject><fields>
        <fullName>Contact__c</fullName>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Qualifications &amp; Experiences</relationshipLabel>
        <relationshipName>Qualifications_Experiences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Part of Application process</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Qualifications &amp; Experience</label><nameField>
        <displayFormat>QE-{0000000}</displayFormat>
        <label>Q&amp;E No</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Qualifications &amp; Experiences</pluralLabel><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ControlledByParent</sharingModel><recordTypes>
        <fullName>Experience</fullName>
        <active>true</active>
        <description>Select this type for Experience</description>
        <label>Experience</label>
    </recordTypes></CustomObject>

objects/References__c.object
<CustomObject><fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>References</relationshipLabel>
        <relationshipName>References</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Student_Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Programme</label>
        <referenceTo>Student_Programme__c</referenceTo>
        <relationshipLabel>References</relationshipLabel>
        <relationshipName>References</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Custom object to hold Reference information on applications</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Reference</label><nameField>
        <displayFormat>Reference-{00000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>References</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Programme must be active (i.e. most recent)</errorMessage>
            <filterItems>
                <field>Programme__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Student Programmes</relationshipLabel>
        <relationshipName>Students_on_Programme1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Stage__c</fullName>
        <description>NOTE : This field drives the Student Programme flow - DO NOT change pick list values without discussion with the I.T / Dev Team</description>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Checked</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional</fullName>
                <color>#339999</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unconditional</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
                <color>#FF99FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Expected</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Registered</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
                <color>#419249</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#666666</color>
            </picklistValues>
            <picklistValues>
                <fullName>Offered</fullName>
                <color>#DDDDDD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reverted from Master:Detail as per LSTM requirement</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Programmes</relationshipLabel>
        <relationshipName>Student_Programmes1</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/TestApplyServices.cls
/**
 * @author Mykola Senyk
 * @date 20/06/2014
 * @description Unit test for ApplyServices class
 */
@isTest
private class TestApplyServices {
    
    static void testGetIndividualAccount() {
        ApplyTestingUtils.setupTestData();
        Account testAccount = ApplyServices.getIndividualAccount();
        System.assertEquals(testAccount.Name, ApplyTestingUtils.INDIVIDUAL_ACCOUNT_NAME);
    }
    
    static testMethod void testBuildQualification() {
        ApplyTestingUtils.setupTestData();
        Qualifications_Experience__c qe = ApplyServices.buildQualification(ApplyTestingUtils.student.Id, ApplyTestingUtils.sp.Id, ApplyServices.RT_ACADEMIC_QE_DEVNAME);
        System.assert(qe.Id == null);       
        System.assertEquals(CommonUtils.findRecordTypeIdByDev('Qualifications_Experience__c', ApplyServices.RT_ACADEMIC_QE_DEVNAME), qe.RecordTypeId);
        System.assertEquals(ApplyTestingUtils.student.Id, qe.Contact__c);
        // add different experience
        qe = ApplyServices.buildQualification(ApplyTestingUtils.student.Id, ApplyTestingUtils.sp.Id, ApplyServices.RT_EXPERIENCE_QE_DEVNAME);
        System.assert(qe.Id == null);       
        System.assertEquals(CommonUtils.findRecordTypeIdByDev('Qualifications_Experience__c', ApplyServices.RT_EXPERIENCE_QE_DEVNAME), qe.RecordTypeId);
        System.assertEquals(ApplyTestingUtils.student.Id, qe.Contact__c);
    }
    
    static testMethod void testFindPersonalDetails() {
        ApplyTestingUtils.setupTestData();
        
        // find contact
        Contact cont = ApplyServices.findPersonalDetails(ApplyTestingUtils.student.Id);
        System.assert(cont != null);
        System.assertEquals(ApplyTestingUtils.student.Id, cont.Id);
        
        // unable to find contact after delete
        delete cont;
        try {
            ApplyServices.findPersonalDetails(ApplyTestingUtils.student.Id);
            System.assert(false);
        } catch (QueryException e) {
            System.assert(true);
        }
    }
    
    static testMethod void testFindRelatedQualifications() {
        ApplyTestingUtils.setupTestData();
        Id contactId = ApplyTestingUtils.student.Id;
        // all
        List<Qualifications_Experience__c> qeList = ApplyServices.findRelatedQualifications(contactId);
        System.assertEquals(ApplyTestingUtils.qualifications.size(), qeList.size());
        for (Qualifications_Experience__c qe: qeList) {
            System.assertEquals(contactId, qe.Contact__c);
           // System.assertEquals(ApplyTestingUtils.sp.Id, qe.Student_Programme__c);
        }
        
        // for given RT only
        Id langRtId = CommonUtils.findRecordTypeIdByDev('Qualifications_Experience__c', ApplyServices.RT_LANGUAGE_QE_DEVNAME);
        Set<Id> rtIds = new Set<Id>{ langRtId };
        qeList = ApplyServices.findRelatedQualifications(contactId, rtIds);
        System.assertEquals(1, qeList.size());
        Qualifications_Experience__c qe = qeList[0];
        System.assertEquals(contactId, qe.Contact__c);
        //System.assertEquals(ApplyTestingUtils.sp.Id, qe.Student_Programme__c);
        System.assertEquals(langRtId, qe.RecordTypeId);
    }
    
    static testMethod void testFindRelatedReferences() {
        ApplyTestingUtils.setupTestData();
        Id contactId = ApplyTestingUtils.student.Id;
        List<References__c> refList = ApplyServices.findRelatedReferences(contactId);
        System.assertEquals(1, refList.size());
        System.assertEquals(contactId, refList[0].Applicant__c);
       // System.assertEquals(ApplyTestingUtils.sp.Id, refList[0].Student_Programme__c);
    }
    
    static testMethod void testCreateCourseByProgrammeId() {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        Id progId;
        User commUser;
        System.runAs(thisUser) {
            ApplyTestingUtils.setupTestData();
            progId = ApplyTestingUtils.prog.Id;
            commUser = ApplyTestingUtils.createCommunityUser('Doe', 'dd@test.com', ApplyTestingUtils.CUSTOMER_COMMUNITY_PROFILE_NAME);  
        }
        Test.startTest();
        System.runAs(thisUser) {
            Student_Programme__c course = Applyservices.createCourseByProgrammeId(progId);
            System.assertEquals(progId, course.Programme__c);
            System.assertEquals(ApplyServices.COURSE_INIT_STAGE_NAME, course.Stage__c);
           // System.assertEquals(commUser.ContactId, course.Student__c);
        }
        Test.stopTest();
    }
    
    @isTest(seeAllData = true)
    static void testCreateCourseForSFByProgrammeId() {
        ApplyTestingUtils.setupTestData();
        Id progId = ApplyTestingUtils.prog.Id;
        Student_Programme__c course = Applyservices.createCourseByProgrammeId(progId);
        System.assertEquals(progId, course.Programme__c);
        System.assertEquals(ApplyServices.COURSE_INIT_STAGE_NAME, course.Stage__c);
    }
    
    static testMethod void testBuildNameOfApplication() {
        ApplyTestingUtils.setupTestData();
        Id progId = ApplyTestingUtils.prog.Id;
        String applicationName = ApplyServices.buildNameOfApplication(progId, ApplyTestingUtils.STUDENT_LAST_NAME);
        System.assertEquals(ApplyTestingUtils.STUDENT_LAST_NAME + ' - ' + ApplyTestingUtils.PROGRAMME_VERSION_CODE, applicationName);
    }

    static testMethod void testGetProgrammeType() {
        ApplyTestingUtils.setupTestData();
        String pType = ApplyServices.getProgrammeType(ApplyTestingUtils.sp.Id);
        System.assertEquals(ApplyTestingUtils.PROGRAMME_TYPE, pType);
    }
    
}