objects/Programme__c.object
<CustomObject><fields>
        <fullName>External_Form__c</fullName>
        <description>eg Form Assembly</description>
        <inlineHelpText>URL of external form creation service</inlineHelpText>
        <label>External Form</label>
        <type>Url</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Programme</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Programme must be active (i.e. most recent)</errorMessage>
            <filterItems>
                <field>Programme__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Programme__c</referenceTo>
        <relationshipLabel>Student Programmes</relationshipLabel>
        <relationshipName>Students_on_Programme1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reverted from Master:Detail as per LSTM requirement</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Programmes</relationshipLabel>
        <relationshipName>Student_Programmes1</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/ExternalFormController.cls
public class ExternalFormController{

    public HTTPResponse res {get; set;}
    public String resBody {get; set;}
    public String endpoint {get; set;}
    public Boolean hasAccess {get; set;}
    public String instanceName {get; set;}    

    public ExternalFormController() {
        PageReference pageRef = ApexPages.currentPage();

        HttpRequest req = new HttpRequest();
        req.setMethod('GET');

        if(pageRef.getParameters().get('tfa_next') == null){
            String spId = pageRef.getParameters().get('SPID');
            String studentId = pageRef.getParameters().get('StudentID');
            String formURL = [SELECT Programme__r.External_Form__c FROM Student_Programme__c WHERE Id=:spId].Programme__r.External_Form__c;
            instanceName = [SELECT Programme__r.Name FROM Student_Programme__c WHERE Id=:spId].Programme__r.Name;

            String studentId_sf;

            try{
                studentId_sf = [SELECT Student__c FROM Student_Programme__c WHERE Id =: spId].Student__c;
            }
            catch(Exception e){
                studentId_sf = null;
                hasAccess = false;
            }
            
            //formURL = formURL.replace('www.tfaforms', System.Label.FormAssemblyURL);
            endpoint = formURL + '?SPID=' + spId + '&StudentID=' + studentId;
            
            User usr = new User();
            usr = [SELECT Name, ContactId FROM User WHERE Id = : UserInfo.getUserId()];

            if(usr.ContactId == studentId  && studentId != null && studentId_sf == studentId) //&& lstm_no != null && lstm_no_sf == lstm_no)
                hasAccess = true;
            else
                hasAccess = false;                
        }
        else{
            endpoint = 'https://' + System.Label.FormAssemblyURL + '.com/rest' + pageRef.getParameters().get('tfa_next');
        }
        req.setEndpoint(endpoint);

        Http http = new Http();
        try {
            res = http.send(req);
            resBody = res.getBody();
        } 
        catch(System.CalloutException e) {
            System.debug(e);
        }
    }
}