objects/Programme__c.object
<CustomObject><fields>
        <fullName>Test_Class_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test Class Record</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Programme</label><nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/CustomLoginControllerTest.cls
@IsTest(seeAllData=true)
public class CustomLoginControllerTest{
    static testMethod void TestController() {
        Programme__c newProg = new Programme__c();

        newProg.Name = 'Test Programme';
        newProg.Test_Class_Record__c = true;
        
        insert newProg;
    
        Test.setCurrentPageReference(new PageReference('Page.LSTMLogin')); 
        System.currentPageReference().getParameters().put('programmeid', newProg.Id);
    
        CustomLoginController obj = new CustomLoginController(); 
        obj.login();
        obj.forwardToCustomAuthPage();
        
                
    }
}