objects/Qualifications_Experience__c.object
<CustomObject><fields>
        <fullName>Contact__c</fullName>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Qualifications &amp; Experiences</relationshipLabel>
        <relationshipName>Qualifications_Experiences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Narrative__c</fullName>
        <description>Removed reference to Language record type as no longer used</description>
        <formula>If (  LEN(  Text(Start_Date__c) &amp;  Name_of_College_University__c &amp;  Qualification__c &amp;  Employer__c &amp;  Position_Held__c ) &lt;= 3, 
   "No Details Provided",
   If ( RecordType.Name  = "Experience", 
      (  Position_Held__c &amp; " at " &amp;  Employer__c &amp; "; started " &amp; Text(Year ( Start_Date__c))), 
      (  Qualification__c &amp; ", " &amp; Left ( Subject__c ,20) &amp; " at " &amp;  Name_of_College_University__c &amp; "; awarded " &amp;  Class_Grade__c &amp; " in " &amp;  Text (Year (Date_of_Award__c)))
      )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is a custom generated field from applicants entries to other fields</inlineHelpText>
        <label>Narrative</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Order__c</fullName>
        <description>Used for inline VF component</description>
        <formula>IF ( RecordType.Name = "Academic", 1,
   If ( RecordType.Name = "Professional", 2,
      If ( RecordType.Name = "Experience", 3,
      4)
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Checked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Part of Application process</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Qualifications &amp; Experience</label><nameField>
        <displayFormat>QE-{0000000}</displayFormat>
        <label>Q&amp;E No</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Qualifications &amp; Experiences</pluralLabel><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reverted from Master:Detail as per LSTM requirement</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Programmes</relationshipLabel>
        <relationshipName>Student_Programmes1</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/QandERelatedlistControllerExt.cls
/* QandERelatedlistControllerExt  Created by Manu KM on 08-sep-2015*/
/// <summary>
// This Class consist of methods for showing Q and E fields as a related list on Student programme and pagination mehtods
/// </summary>
/// <param name="deleteRecordId "> Strores the Id of Q&E record to be deletds</param>
/// <param name="deleteRecord "> Returns the Id of deleting Q&E filed</param>
/// <param name="studentPgmId ">Stores the parent Student programme ID </param>
/// <param name="noOfRecords"> Stores totoal number of Q&E records present for pagination</param>
/// <param name="size "> Number of records showing</param>

public with sharing class QandERelatedlistControllerExt {
 public Id deleteRecordId {
        get;
        set;
    }
    public id deleteRecord {
        get;
        set;
    }
    public string studentPgmId {
        get;
        set;
    }
    Public Integer noOfRecords {
        get;
        set;
    }
    Public Integer size {
        get;
        set;
    }   
   //Queries all then Q&E fields Based on the criteria
    public ApexPages.StandardSetController setCon {
        get {
            if (setCon == null) {
                size = 5;
                studentPgmId = ApexPages.currentPage().getParameters().get('id');
                // string studentPgmId = 'a0B11000005Pcq7';
                Student_Programme__c sp = [Select Student__c from Student_Programme__c where id = : studentPgmId];
                string spStdntId = sp.Student__c;
                string queryString = 'Select Id,name,Narrative__c,LastModifiedDate,RecordType.Name,Status__c,Order__c  from Qualifications_Experience__c where Contact__c =: spStdntId ORDER BY Order__c ASC NULLS LAST ';
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator(queryString));
                setCon.setPageSize(size);
                noOfRecords = setCon.getResultSize();
            }
            return setCon;
        }
        set;
    }
   
    //method will find whter there is any next page to be showned for Q&E
    public Boolean hasNext {
        get {
            return setCon.getHasNext();
        }
        set;
    }
     //will find whter there is any previous page to be showned for Q&E
    public Boolean hasPrevious {
        get {
            return setCon.getHasPrevious();
        }
        set;
    }
    
    public Integer pageNumber {
        get {
            return setCon.getPageNumber();
        }
        set;
    }
     //Standared Controller
    public QandERelatedlistControllerExt(ApexPages.StandardController controller) {

    }
    public QandERelatedlistControllerExt(){
    }
    //Fteches all the Q&E records related to the parent Student programme
    public List < Qualifications_Experience__c > getQandE() {
        List < Qualifications_Experience__c > QEList = new List < Qualifications_Experience__c > ();
        for (Qualifications_Experience__c a: (List < Qualifications_Experience__c > ) setCon.getRecords())
            QEList.add(a);
        return QEList;

    }
     //Refreshes the pageblock manually or after every action
    public pageReference refresh() {
        setCon = null;
        getQandE();
        setCon.setPageNumber(1);
        return null;
    }
    //take to the first page of the pagination
    public void first() {
        setCon.first();
    }
    //take to the lastpage of the pagination
    public void last() {
        setCon.last();
    }
    //take to the previous page of the pagination
    public void previous() {
        setCon.previous();
    }
    //take to the next page of the pagination
    public void next() {
        setCon.next();
    }
    //Method will delete the selected Q&E record
    public void deleteRecord() {
        Qualifications_Experience__c deletingRecord = [select id from Qualifications_Experience__c where id = : deleteRecordId];
        delete deletingRecord;
        refresh();
        return;
    }
}