objects/Qualifications_Experience__c.object
<CustomObject><fields>
        <fullName>New_Upload__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New Upload</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Part of Application process</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Qualifications &amp; Experience</label><nameField>
        <displayFormat>QE-{0000000}</displayFormat>
        <label>Q&amp;E No</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Qualifications &amp; Experiences</pluralLabel><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>New_Upload__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New Upload</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/MultiAttachmentCont.cls
/**
 * @author Valentyn Bilenkyy
 * @date 19/06/2014
 * @description Controller class for MultiAttachment.component
 */
public class MultiAttachmentCont {
    public String attachmentParentId {get;set;}
    public String name {get;set;}
    public String attachmentDescription {get;set;}
    public Id attachmentIdToRemove {get;set;}
    public String errorMessage {get; private set;}
    public Boolean readOnlyModeVal {get; set;}
    
    public Attachment attachment {
        get {
            if(attachment == null)
                attachment = new Attachment();
            return attachment;
        }
        set;
    }
    
    public List<Attachment> recordAttachments {
        get {
            List<Attachment> recordAttachments = new List<Attachment>();
            if(String.isBlank(attachmentDescription))
                recordAttachments = CommonUtils.findAttachments(attachmentParentId);
            else 
                recordAttachments = CommonUtils.findAttachments(attachmentParentId, attachmentDescription);
            return recordAttachments;
        }
        private set;
    }
    
    public Boolean hasAttachments {
        get {
            return (recordAttachments.size()>0);
        }
        set;
    }

    public PageReference removeAttachment() {
        errorMessage = null;
        if(attachmentIdToRemove!=null) {
            try {
                Attachment a = [SELECT Id FROM Attachment WHERE Id=:attachmentIdToRemove];
                delete a;
            }
            catch (Exception e) {
                errorMessage = e.getMessage();
            }
        }
        attachmentIdToRemove = null;
        return null;
    }
    
    public PageReference upload() {
        errorMessage = null;
        attachment.OwnerId = UserInfo.getUserId();
        attachment.ParentId = attachmentParentId;
        attachment.IsPrivate = false;
        attachment.Description = attachmentDescription;
        System.debug('attachment.Description = '+attachment.Description);
        try {
            
            insert attachment;
            //Suyati Modified Start 26-04-2016
            /*if(attachment.Description == 'passport'){
                 Student_Programme__c sp = [SELECT Id,New_Upload__c FROM Student_Programme__c WHERE Id =: attachmentParentId ];
                 sp.New_Upload__c = true;
                 System.debug('before update');
                 UPDATE sp;
            
            }
            */
            Id attachmentIdentifier = Id.valueOf(attachmentParentId);
            System.debug(''+attachmentIdentifier.getSobjectType());
            if(string.valueOf(attachmentIdentifier.getSobjectType()) == 'Qualifications_Experience__c'){
                Qualifications_Experience__c qE = [SELECT Id,New_Upload__c FROM Qualifications_Experience__c WHERE Id =:attachmentIdentifier];
                qE.New_Upload__c = true;
                UPDATE qE;
                //Suyati Modified End 
            }
            
        }
        catch (Exception e) {
            errorMessage = e.getMessage();
        }
        finally {
            attachment = new Attachment();
        }
        return null;
    }
}