objects/References__c.object
<CustomObject><fields>
        <fullName>Referee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link to referee Contact record</inlineHelpText>
        <label>Referee</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>References (Referee)</relationshipLabel>
        <relationshipName>References1</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Custom object to hold Reference information on applications</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Reference</label><nameField>
        <displayFormat>Reference-{00000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>References</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/TestReferenceWrapper.cls
/**
 * @author Mykola Senyk
 * @date 20/06/2014
 * @description Unit test for ReferenceWrapper class
 */
@isTest
private class TestReferenceWrapper {
	
	static testMethod void testWrapper() {
		// empty reference
		References__c ref = new References__c();
		ReferenceWrapper wr = new ReferenceWrapper(ref);
		System.assert(wr.item.Id == null);
		System.assert(wr.referee.Id == null);
		System.assert(wr.empty);
		wr.referee.FirstName = 'John';
		System.assert(!wr.empty);
		
		// inserted reference
		ApplyTestingUtils.setupTestData();
		List<References__c> refList = ApplyServices.findRelatedReferences(ApplyTestingUtils.student.Id);
		System.assertEquals(1, refList.size());
		ref = refList[0];
		wr = new ReferenceWrapper(ref);
		System.assertEquals(ref.Id, wr.item.Id);
		System.assert(wr.referee.Id != null);
		System.assertEquals(ref.Referee__c, wr.referee.Id);
		System.assert(!wr.empty);
	}

}