objects/References__c.object
<CustomObject><fields>
        <fullName>Referee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link to referee Contact record</inlineHelpText>
        <label>Referee</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>References (Referee)</relationshipLabel>
        <relationshipName>References1</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Reference_Status__c</fullName>
        <label>Reference Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Student_Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Programme</label>
        <referenceTo>Student_Programme__c</referenceTo>
        <relationshipLabel>References</relationshipLabel>
        <relationshipName>References</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Custom object to hold Reference information on applications</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Reference</label><nameField>
        <displayFormat>Reference-{00000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>References</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Student_Programme__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/ReferenceUploadController.cls
/*
*
* 2014-07-16 : CSL : New class that looks after the ReferenceUpload VF Page
* enabling Referees to upload References (documents) against a Student Programme Application
*
*/
public class ReferenceUploadController {
    
    public final String STUDENT_PROG_PARAM_ID = 'spid';
    public final String REFERENCE_PARAM_ID = 'rid';
    public final String REFERENCE_STATUS_REPLIED = 'Replied';

    public Student_Programme__c sp {get; set;}
    public References__c reference {get; set;}
    public boolean showError {get; set;}
    public blob inputFile {get; set;}
    public String inFileName {set; get;}

    public ReferenceUploadController(){
        showError = false;
        Id spId = ApexPages.currentPage().getParameters().get(STUDENT_PROG_PARAM_ID);
        Id rId = ApexPages.currentPage().getParameters().get(REFERENCE_PARAM_ID);
        
        if (spId == null || rId == null){
            showError = true;
        }else {
            sp = [select s.Id, s.Name from Student_Programme__c s where s.Id = :spId LIMIT 1];
            reference = [select r.Id, r.Reference_Status__c, r.Referee__r.LastName from References__c r where r.Id = :rId LIMIT 1]; 
        }
            
        if (sp == null || reference == null){
            showError = true;
        }
        
        
    }
    
    public PageReference uploadAttachment(){
        PageReference pageRef;
        
        Attachment a = new Attachment();
        a.ParentId = reference.Id;
        //a.Name = sp.Name + '_REFERENCE ' + reference.Referee__r.LastName;
        a.Name = inFileName;
        //Need to populate the Body field
        a.Body = inputFile;
        
        insert a;
        
        reference.Reference_Status__c = REFERENCE_STATUS_REPLIED;
        
        update reference;
        
        pageRef = Page.ReferenceUploadThankyou;
        pageRef.setRedirect(true);
        
        return pageRef;
    }

}