objects/References__c.object
<CustomObject><fields>
        <fullName>Can_Request_Reference_from_Referee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Can Request Reference from Referee?</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>College_University_or_Employer__c</fullName>
        <label>College / University or Employer</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Referee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link to referee Contact record</inlineHelpText>
        <label>Referee</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>References (Referee)</relationshipLabel>
        <relationshipName>References1</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Custom object to hold Reference information on applications</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Reference</label><nameField>
        <displayFormat>Reference-{00000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>References</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/ReferenceWrapper.cls
/**
 * @author Mykola Senyk
 * @date 17/06/2014
 * @description Wrapper class for References__c
 */
public class ReferenceWrapper {
	
	// comma separeated field names of Contact & References__c
	public static final STRING CONTACT_FIELDS = 'Salutation,LastName,FirstName,Title,MailingStreet,MailingCity,MailingState,MailingPostalCode,MailingCountry,Phone';
	public static final String REFERENCE_FIELDS = 'College_University_or_Employer__c';
	
	public ReferenceWrapper(References__c record) {
		item = record;
		referee = ( item.Referee__r != null ) ? item.Referee__r : new Contact(); 
	}
	
	public References__c item { get; set; }
	
	public Contact referee { get; set; }
	
	/**
     * Index in parent list
     */
    public Integer index { get; set; }
    
    /**
     * Return true if all fields of wrapper are empty
     */
    public Boolean empty { get {
    	Boolean res = CommonUtils.allFieldsAreEmpty(referee, CONTACT_FIELDS) && CommonUtils.allFieldsAreEmpty(item, REFERENCE_FIELDS) && !item.Can_Request_Reference_from_Referee__c;
    	if ( res ) {
    		res = !CommonUtils.hasAttachment(item.Id);
    	}
    	return res;
    } }

}