objects/Research_Period__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Drives list view visibility</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Period_End_Date__c</fullName>
        <label>Period End Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Period_Number__c</fullName>
        <label>Period Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Period_Start_Date__c</fullName>
        <label>Period Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Previous_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Period</label>
        <referenceTo>Research_Period__c</referenceTo>
        <relationshipLabel>Next Period</relationshipLabel>
        <relationshipName>Research_Periods</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Required_Supervisory_Meetings__c</fullName>
        <description>Previously Required_Supervisions</description>
        <inlineHelpText>Number of required Supervisions in this Research Period</inlineHelpText>
        <label>Required Supervisory Meetings</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of Research Period</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Measures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Student_Programme__c</fullName>
        <label>Student Programme</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>You can only assign Research Periods to Student Programmes where Record Type = PGR Programme.</errorMessage>
            <filterItems>
                <field>Student_Programme__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>PGR Student</value>
            </filterItems>
            <filterItems>
                <field>Student_Programme__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>PGR Application</value>
            </filterItems>
            <infoMessage>Oops... the Student Programme you have selected is not a PGR Programme.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Student_Programme__c</referenceTo>
        <relationshipLabel>Research Periods</relationshipLabel>
        <relationshipName>Research_Periods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Research Period</label><nameField>
        <label>Research Period Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Research Periods</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>Mode_of_Study__c</fullName>
        <label>Mode of Study</label>
        <picklist>
            <picklistValues>
                <fullName>Full Time</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Part Time</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Programme_End_Date__c</fullName>
        <formula>Programme__r.End_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Taken from Programme (instance) level</inlineHelpText>
        <label>Programme End Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Programme_Length__c</fullName>
        <inlineHelpText>Length of Programme in Research Periods</inlineHelpText>
        <label>Programme Length (Periods)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Programme_Start_Date__c</fullName>
        <formula>Programme__r.Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Taken from Programme (instance) level</inlineHelpText>
        <label>Programme Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Stage__c</fullName>
        <description>NOTE : This field drives the Student Programme flow - DO NOT change pick list values without discussion with the I.T / Dev Team</description>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Checked</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional</fullName>
                <color>#339999</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unconditional</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
                <color>#FF99FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Expected</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Registered</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
                <color>#419249</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#666666</color>
            </picklistValues>
            <picklistValues>
                <fullName>Offered</fullName>
                <color>#DDDDDD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><recordTypes>
        <fullName>Checked</fullName>
        <active>true</active>
        <label>Checked</label>
    </recordTypes><recordTypes>
        <fullName>Registered</fullName>
        <active>true</active>
        <label>Non-MSc Registered</label>
    </recordTypes></CustomObject>

objects/Supervision__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <description>Taken from Status on Research Period. Returns TRUE for all Statuses except Completed</description>
        <formula>Research_Period__r.Active__c</formula>
        <inlineHelpText>Taken from Status on Research Period</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Primary_Supervisor__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Tick to denote Supervisor will provide primary supervision of student</inlineHelpText>
        <label>Primary Supervisor</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Research_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Research Period</label>
        <referenceTo>Research_Period__c</referenceTo>
        <relationshipLabel>Supervisors</relationshipLabel>
        <relationshipName>Supervisions</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <description>Status of Supervision record. Available values vary by record type.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed with caveats</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Student_Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Programme</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Oops... you can only associate Supervisors with Student Programmes where Record Type = PGR Programme</errorMessage>
            <filterItems>
                <field>Student_Programme__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>PGR Programme</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Student_Programme__c</referenceTo>
        <relationshipLabel>Supervisions</relationshipLabel>
        <relationshipName>Supervisors</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Supervisor_Weighting__c</fullName>
        <label>Supervisor Weighting</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields><fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The person you are trying to look up is not a registered supervisor or not a member of staff.</errorMessage>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Staff</value>
            </filterItems>
            <filterItems>
                <field>Contact.Registered_Supervisor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Find the name of the Supervisor.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Students Supervising</relationshipLabel>
        <relationshipName>Supervisions</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Join between staff and student programme for managing of PGR supervisions</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Supervision</label><nameField>
        <label>Supervision Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Supervisions</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/ResearchPeriodRecord.cls
/*
 * Created on : 13/06/2017
 * Suyati
 * Desc : Class will handle the Student Programme Visualforce page for 'Register PGR Student'
 * Suyati Modified : 22/06/2017
*/
public Without Sharing class ResearchPeriodRecord
{ 
    public string studentId;
    public Date dat {get;set;}
    public Date enddat {get;set;}
    public Integer num{get;set;}
    public Integer Snum{get;set;}
    public Boolean second{get;set;}
    public Boolean check{get;set;}
    public Student_Programme__c Student{get;set;}
    public List<Supervision__c> Supervision{get;set;}
    public List<wrapper> superList{get;set;}
    Research_Period__c Research;
    public List<Supervision__c > ListSupervisor;
    public boolean WeightingError{get;set;}
    Public Id periodId;
    PageReference pr;
    Map<Id, Supervision__c> SupervisionMap = new Map<Id, Supervision__c>();
    
    public ResearchPeriodRecord(ApexPages.StandardController controller)
    {
        decimal period=0;
        Id highestWeight;
        Integer sameWeight=0;
        WeightingError=false;
        Supervision = new List<Supervision__c>();
        superList=new List<wrapper>();
        second= false;
        check= true;
        Decimal weight=0;
        Decimal weightOld=0;
        ListSupervisor =new List<Supervision__c >();
        
        // Calculate period start date
        datetime myDate = date.today(); 
        String formatted1 = myDate.formatGMT('EEEEEEE');
        datetime nextmonth=mydate.addmonths(1);
        date firstDate = date.valueof(nextmonth).toStartOfMonth();
        
        dat = firstDate; //system.today(); 
        datetime endDate = firstDate.addYears(1)-1;
        enddat =  date.valueof(endDate);
        num =1;
        studentId= ApexPages.currentPage().getParameters().get('id');
        system.debug('student++++++++++++++++++++++++++++++++++'+studentId); 
        Student= [select id,Name,Mode_of_Study__c,Programme_Start_Date__c,Programme_End_Date__c,Programme_Length__c,Status__c,(Select id, Previous_Period__c,Period_Number__c from Research_Periods__r ) from  Student_Programme__c  where id =:studentId]; 
        for(Research_Period__c research : Student.Research_Periods__r)
        {
            if(research.Period_Number__c > period)
            {
                period=research.Period_Number__c;
                periodId =research.Id;
                system.debug('periodId'+periodId);                
            }
        }
        ListSupervisor = [select id,Name,Supervisor_Weighting__c,Primary_Supervisor__c,Supervisor__r.name from  Supervision__c where Student_Programme__c =:studentId and Research_Period__c=:periodId ];   
        
        for(Supervision__c superv: ListSupervisor)
        { 
            system.debug('superv'+superv.Supervisor_Weighting__c);
            if(superv.Supervisor_Weighting__c > weight)
            {  
                weight=superv.Supervisor_Weighting__c;                
                highestWeight=superv.Id;
            }
            if(superv.Supervisor_Weighting__c==weightOld)
            {
                sameWeight=sameWeight+1;
            }
            superList.add(new wrapper(superv.id,true,superv.Supervisor__r.name,superv.Supervisor_Weighting__c,superv.Primary_Supervisor__c));
            weightOld=superv.Supervisor_Weighting__c;
        }
        for(wrapper listElement: superList)
        {
            
            if(listElement.RecordId==highestWeight && sameWeight!=ListSupervisor.size()-1)
            {
                listElement.Primary=true;
            }
            else
            {
                listElement.Primary=false;
            }
        }
        
    }
    public PageReference UpdateData()
    {
        
        second= true;
        system.debug('number'+num);
        //count = count+1;
        String Periodname = Student.Name + 'Period';
        system.debug('studentId'+studentId);        
        system.debug('periodId'+periodId);
        Id devRecordTypeId = Schema.SObjectType.Research_Period__c.getRecordTypeInfosByName().get(Student.Mode_of_Study__c).getRecordTypeId();
        system.debug('devRecordTypeId '+devRecordTypeId );
        Research = new Research_Period__c(Name= Periodname ,Active__c=true, Student_Programme__c=studentId,Previous_Period__c=periodId, Period_Number__c=num, Period_Start_Date__c= dat ,Period_End_Date__c=enddat,Required_Supervisory_Meetings__c=Snum  );
        Research.RecordTypeId = devRecordTypeId;      
        insert Research;
        update Student;
        return null;
        
    }
    
    public PageReference SaveData()
    {
        set<Supervision__c> lstSupervisor=new set<Supervision__c>();
        List<Supervision__c > setSupervisor = new List<Supervision__c >();
        List<Supervision__c > listToUpdate = new List<Supervision__c >();
        List<Supervision__c > Li= new List<Supervision__c >();
        List<Supervision__c > DuplicateSupervisor= new List<Supervision__c >();
        set<Supervision__c> St=new set<Supervision__c>();
        decimal count=0;
        boolean save=true;
        decimal primaryWt;
        decimal weightValue=0;
        integer prim =0;
        system.debug('ListSupervisor%%%%%%%% '+ListSupervisor );
        for(wrapper a: superList )
        {
           if(a.Weight > weightValue && a.checked==true) 
           {
               weightValue =a.Weight;
           }
           if(a.Primary == true && a.checked==true)
           {
               primaryWt=a.Weight;               
           }
           if(a.Primary == true && a.checked!=true)
           {
               save=false;
               ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Info,'Primary Supervisor must be one of the selected Supervisors'));
           }
        }
        for(wrapper a: superList)
        {
            if(a.checked==true)
            {
                count=count+a.weight;              
                for(Supervision__c superv: ListSupervisor )
                {
                    if(a.RecordId==superv.id)
                    {  
                        if(a.Weight!=null && a.Weight==weightValue && primaryWt!=a.Weight && a.Primary!=true)
                        {                            
                            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Info,'The Primary Supervisor must have the highest supervision weighting'));
                            save=false;
                        }
                        else if(a.Weight!=null)
                        {
                            superv.Primary_Supervisor__c=a.Primary;
                        }
                        
                        superv.Supervisor_Weighting__c=a.Weight;
                        //superv.Research_Period__c=Research.id;
                    }                    
                    lstSupervisor.add(superv);  
                }
            }
        }
        for(Supervision__c newSupervision : lstSupervisor) {
            SupervisionMap.put(newSupervision.Id,newSupervision);
        }
        system.debug('lstSupervisorSize'+lstSupervisor.size());
        if(count!=100)
        {
            save=false;
            WeightingError=true;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Info,'Total weighting for all selected Supervisors must be 100%'));
        }
        else if(save==true)
        {  
            system.debug('SupervisionMap'+ SupervisionMap);
            Student.Stage__c='Registered';
            system.debug('+++++++++++++++++***'+Student.Stage__c);
            update Student;
            update SupervisionMap.values();
            System.debug('SupervisionMap'+SupervisionMap);
            String baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
            pr = new PageReference(baseUrl +'/'+ Research.id);
            pr.setRedirect(true);          
  
            
            for(wrapper a: superList)
            {      
                if(a.checked==true)
                {
                    for(Supervision__c supervision: ListSupervisor )
                    {
                        if(a.RecordId==supervision.id )
                        {
                            Supervision__c s = new Supervision__c ();
                            s.Name=supervision.Name;
                            s.Supervisor__c=supervision.Supervisor__c;
                            s.Supervisor_Weighting__c=supervision.Supervisor_Weighting__c;
                            s.Primary_Supervisor__c=supervision.Primary_Supervisor__c;                
                            s.Research_Period__c=Research.id;    
                            s.Student_Programme__c=Student.Id;
                            DuplicateSupervisor.add(s);
                        }
                    }
                }
            }
            insert DuplicateSupervisor;
            system.debug('listToUpdate'+listToUpdate);
            system.debug('DuplicateSupervisor'+DuplicateSupervisor);
        }
        return pr;
    }
    
    public PageReference Cancel()
    {
        String baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
        pr = new PageReference(baseUrl +'/'+ Student.id);
        //pr = new PageReference(Label.RedirectToResearch + Student.id);
        pr.setRedirect(true);
        return pr;
    }
    
    /* Wrapper for holding VF page data */
    public class wrapper
    {
        public Id RecordId{get;set;}
        public Boolean checked{get;set;}
        public string  Name{get;set;}
        public Boolean Primary{get;set;}  
        public decimal Weight{get;set;}    
        
        public wrapper(Id r,Boolean c,string n,decimal W,Boolean p)
        {
            RecordId=r;
            checked = c;
            Name = n;
            Weight=w;
            Primary = p;
        }    
    }
}