objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>Assigned_Supervisors__c</fullName>
        <description>Holds string of User IDs for assigned supervisors</description>
        <label>Assigned Supervisors</label>
        <type>TextArea</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Supervision__c.object
<CustomObject><fields>
        <fullName>Student_Programme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Programme</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Oops... you can only associate Supervisors with Student Programmes where Record Type = PGR Programme</errorMessage>
            <filterItems>
                <field>Student_Programme__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>PGR Programme</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Student_Programme__c</referenceTo>
        <relationshipLabel>Supervisions</relationshipLabel>
        <relationshipName>Supervisors</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The person you are trying to look up is not a registered supervisor or not a member of staff.</errorMessage>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Staff</value>
            </filterItems>
            <filterItems>
                <field>Contact.Registered_Supervisor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Find the name of the Supervisor.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Students Supervising</relationshipLabel>
        <relationshipName>Supervisions</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Join between staff and student programme for managing of PGR supervisions</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Supervision</label><nameField>
        <label>Supervision Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Supervisions</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/SupervisionTriggerMethods.cls
public class SupervisionTriggerMethods
{
    public static void addToTextArea(List<Supervision__c> supervisionList, List<id> studentproIds)
    {
        Map<Id,Set<Id>> SPsupervisorMap = new Map<Id,Set<Id>>();
        Map<Id,Id> contactUserMap = new Map<Id,Id>();   
        Set<Id> contactIDs= new Set<Id>();
        
        
        
        
        
        if ( !supervisionList.isEmpty() ) 
        {
            for(Supervision__c supervisions : supervisionList) 
            {
                if(SPsupervisorMap.containsKey(supervisions.Student_Programme__c))
                {
                    SPsupervisorMap.get(supervisions.Student_Programme__c).add(supervisions.Supervisor__c);
                    contactIDs.add(supervisions.Supervisor__c);
                }
                else
                { 
                    SPsupervisorMap.put(supervisions.Student_Programme__c, new Set<Id> {supervisions.Supervisor__c});                    
                    contactIDs.add(supervisions.Supervisor__c);
                }
            }
        }
        for(User u : [SELECT Id,ContactId FROM User WHERE ContactId IN: contactIDs])
        {
            contactUserMap.put(u.ContactId,u.Id);
        }           
        Set<String> spListToUpdate = new Set <String>();
       // spListToUpdate;
        List<Student_Programme__c> spListToUpdateLst = new List <Student_Programme__c>();
        for(Student_Programme__c sp : [SELECT Id,Assigned_Supervisors__c FROM Student_Programme__c WHERE ID IN: studentproIds])
        {
            
          // sp.Assigned_Supervisors__c='';
            String str2='';
            
            for(Id supervisorId : SPsupervisorMap.get(sp.Id))
            {   
                spListToUpdate.add(String.valueOf(contactUserMap.get(supervisorId)));
            }
            for(String str : spListToUpdate)
            {
                str2=str2+str+',';            	
                system.debug('str2'+str2);
            } 
            sp.Assigned_Supervisors__c=str2;
            spListToUpdateLst.add(sp);
        }
        update spListToUpdateLst;
    }
    
    public static void removeFromTextArea(List<Supervision__c> supervisionList)
    {
        Map<Id,List<Id>> SPsupervisorMap = new Map<Id,List<Id>>();
        Map<Id,Id> contactUserMap = new Map<Id,Id>();   
        Set<Id> contactIDs= new Set<Id>();
        
        if ( !supervisionList.isEmpty() ) 
        {
            for(Supervision__c supervisions : supervisionList) 
            {
                if(SPsupervisorMap.containsKey(supervisions.Student_Programme__c))
                {
                    SPsupervisorMap.get(supervisions.Student_Programme__c).add(supervisions.Supervisor__c);
                    contactIDs.add(supervisions.Supervisor__c);
                }
                else
                {
                    SPsupervisorMap.put(supervisions.Student_Programme__c , new List<Id> {supervisions.Supervisor__c});
                    contactIDs.add(supervisions.Supervisor__c);
                }
            }
        }
        
        for(User u : [SELECT Id,ContactId FROM User WHERE ContactId IN: contactIDs])
        {
            contactUserMap.put(u.ContactId,u.Id);
        }           
        
        List<Student_Programme__c> spListToUpdate = new List <Student_Programme__c>();
        for(Student_Programme__c sp : [SELECT Id,Assigned_Supervisors__c FROM Student_Programme__c WHERE ID IN: SPsupervisorMap.keyset()])
        {
            
            for(Id supervisorId : SPsupervisorMap.get(sp.Id))
            {
                if(contactUserMap.get(supervisorId)!=null)
                {
                    If(sp.Assigned_Supervisors__c.contains(',' + String.valueOf(contactUserMap.get(supervisorId))))
                    {
                        sp.Assigned_Supervisors__c = sp.Assigned_Supervisors__c.remove(',' + String.valueOf(contactUserMap.get(supervisorId)));             
                        spListToUpdate.add(sp); 
                    }
                    else if(sp.Assigned_Supervisors__c.contains(String.valueOf(contactUserMap.get(supervisorId)+ ',')))
                    {
                        sp.Assigned_Supervisors__c = sp.Assigned_Supervisors__c.remove(String.valueOf(contactUserMap.get(supervisorId)+ ','));              
                        spListToUpdate.add(sp); 
                    }
                    else
                    {
                        sp.Assigned_Supervisors__c = sp.Assigned_Supervisors__c.remove(String.valueOf(contactUserMap.get(supervisorId)));               
                        spListToUpdate.add(sp);
                    }
                }
            }
        }
        update spListToUpdate;        
    } 
    public static void blankTextArea(List<Student_Programme__c> str)
    {
        for (Student_Programme__c str1: str)
            str1.Assigned_Supervisors__c=null;
            update str;

        
    }
    
}