objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>Stage__c</fullName>
        <description>NOTE : This field drives the Student Programme flow - DO NOT change pick list values without discussion with the I.T / Dev Team</description>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Checked</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional</fullName>
                <color>#339999</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unconditional</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
                <color>#FF99FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Expected</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Registered</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
                <color>#419249</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#666666</color>
            </picklistValues>
            <picklistValues>
                <fullName>Offered</fullName>
                <color>#DDDDDD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/VFPicklistBannerSPController.cls
global with sharing class VFPicklistBannerSPController{

    public List<String> options{get; set;}
    public string opts {get; set;}

    public VFPicklistBannerSPController(ApexPages.StandardController controller) {
        Id spID = (Id)controller.getRecord().id;
        options = new List<String>();       
        List<String> options = PicklistDescriber.describe(spID, 'Stage__c');
        opts = JSON.serialize(options);       
    }
    
    @RemoteAction
    global static String doSubmitForm(String spId, String stage) {
        if(spId != null) {
            Student_Programme__c sp = [Select Id,Name,Stage__c FROM Student_Programme__c WHERE Id=:spId];
            if(sp != null) {
                sp.Stage__c = stage;
                update sp;
                return 'Success';
            } 
            else {
                return 'Student Programme could not be found';
            }
        } 
        else {
            return 'Student Programme Id was null';
        }
    }
}