objects/Student_Programme__c.object
<CustomObject><fields>
        <fullName>Stage__c</fullName>
        <description>NOTE : This field drives the Student Programme flow - DO NOT change pick list values without discussion with the I.T / Dev Team</description>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Checked</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional</fullName>
                <color>#339999</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unconditional</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
                <color>#FF99FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Expected</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Registered</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
                <color>#419249</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#666666</color>
            </picklistValues>
            <picklistValues>
                <fullName>Offered</fullName>
                <color>#DDDDDD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>For specific Programme that has been applied for or is being taken.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Programme</label><nameField>
        <label>Student Programme Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Student Programmes</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>true</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><recordTypes>
        <fullName>Completed</fullName>
        <active>true</active>
        <label>Completed</label>
    </recordTypes></CustomObject>

classes/PicklistBannerSPController.cls
public with sharing class PicklistBannerSPController{

    @AuraEnabled
    public static List<String> getCompletedStages(Id studenProgrammeId) {
        List<String> stageList = new List<String>();
        
        String currentStage = [SELECT Stage__c FROM Student_Programme__c WHERE Id =: studenProgrammeId].Stage__c;
    
        List<String> stages = PicklistDescriber.describe(studenProgrammeId, 'Stage__c');
    
        for(String stage : stages)
        {
            if(stage == currentStage)
                break;
            stageList.add(stage);               
        }
        system.debug('completed stages : ' + stageList);
        return stageList;
    }

    @AuraEnabled
    public static String getCurrentStage(Id studenProgrammeId) {
        
        String currentStage = [SELECT Stage__c FROM Student_Programme__c WHERE Id =: studenProgrammeId].Stage__c;
        system.debug('current Stage : ' + currentStage);                
        return currentStage;
    }
    
    @AuraEnabled
    public static List<String> getFutureStages(Id studenProgrammeId) {
        List<String> stageList = new List<String>();
        
        String currentStage = [SELECT Stage__c FROM Student_Programme__c WHERE Id =: studenProgrammeId].Stage__c;
        boolean flag = false;    
        List<String> stages = PicklistDescriber.describe(studenProgrammeId, 'Stage__c');
        
        for(String stage : stages)
        {
            if(stage == currentStage)
            {
                flag = true;
                continue;
            }    
            if(flag == true)
                stageList.add(stage);               
        }
        system.debug('Future stages : ' + stageList);        
        return stageList;
    }


    @AuraEnabled
    public static Student_Programme__c updateStage(Id studenProgrammeId,String stageName) {        
        Student_Programme__c sp = [SELECT Id,Stage__c FROM Student_Programme__c WHERE Id =: studenProgrammeId];
        sp.Stage__c = stageName;
        update sp;
        return sp;
    }    
    
}