objects/VLE_Action__c.object
<CustomObject><fields>
        <fullName>Status__c</fullName>
        <description>Status value means: New - for future, Delayed - wait for became Batch, Canceled - not actual in some reasons</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Batch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delayed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Object for perform complex action to VLE API</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>VLE Action</label><nameField>
        <label>VLE Action Name</label>
        <type>Text</type>
    </nameField><pluralLabel>VLE Actions</pluralLabel><sharingModel>Private</sharingModel></CustomObject>

classes/VleSyncBatch.cls
/**
 * Batch job for synchronizing action to VLE
 */
global class VleSyncBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {

	private String query = 'SELECT Id, Status__c FROM VLE_Action__c WHERE Status__c = \'' + VleSyncServices.ACTION_BATCH_STATUS + '\'';
	
	public Database.QueryLocator start(Database.BatchableContext BC){
		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext BC, List<VLE_Action__c> scope){
		VleSyncServices.syncActionBatch(scope[0].Id);
	}

	global void finish(Database.BatchableContext BC) {
		VleSyncServices.isBatchRunning = false;
	}
	
}