objects/VLE__c.object
<CustomObject><fields>
        <fullName>App_Key__c</fullName>
        <description>App Key for desire2learn (secret)</description>
        <label>App Key</label>
        <length>22</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>User_ID__c</fullName>
        <description>User ID for API calls</description>
        <label>User ID</label>
        <length>22</length>
        <type>Text</type>
    </fields><fields>
        <fullName>User_Key__c</fullName>
        <description>Key for API user (secret)</description>
        <label>User Key</label>
        <length>22</length>
        <type>Text</type>
    </fields><customSettingsType>List</customSettingsType><description>Credentials for VLE external service</description><enableFeeds>false</enableFeeds><label>VLE parameters</label><visibility>Protected</visibility></CustomObject>

classes/VleCallbackCont.cls
/**
 * Controller for VleCallback page
 */
public with sharing class VleCallbackCont {
	
	private static final String MSG_OK = 'Session for User context has been successfully updated!';
	private static final String MSG_ERROR = 'Signature doesn\'t match';
	
	public String tokenId { get; set; }
	public String tokenKey { get; set; }
	public String tokenSig { get; set; }
	
	public VleCallbackCont() {
		tokenId = ApexPages.currentPage().getParameters().get('x_a');
		tokenKey = ApexPages.currentPage().getParameters().get('x_b');
		tokenSig = ApexPages.currentPage().getParameters().get('x_c');
	}
	
	public void checkToken() {
		// check token's signature
		String value = tokenId + '&' + tokenKey;
		String verifiedSig = VleServices.buildBase64HashString(VleServices.credentials.App_Key__c, value);
		
		if ( verifiedSig.equals(tokenSig) ) {
			// update custom setting
			VLE__c cs = new VLE__c(Id = VleServices.credentials.Id, User_ID__c = tokenId, User_Key__c = tokenKey);
			update cs;
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, MSG_OK));
		} else {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, MSG_ERROR));
		}
	}

}